### ISSUE TITLE
Allow more granular operations for @exclude directive 

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#1000]
**Is your feature request related to a problem? Please describe.**

If you have a fair number of Types there can be hundres of generated queries and mutations. Not all of these are necessary and it creates a lot of clutter.

I wish to have the tools to reduce the number of generated queries and mutations to exactly what I need and wish to provide.

**Describe the solution you'd like**

1. First I'd like to have more granular control. Today we can specify operations `[CREATE, READ, UPDATE, DELETE]`. Extend these to allow for detailed configuration. _Example: `[READ]` would be an alias for the more granular `[READ_TYPE, READ_COUNT, READ_AGGREGATE]`. When necessary I can define the more narrow operations._

2. Next I'd also like for the inverse of `@exclude` by adding `@include`. I find it frustrating that I have to over and over perform the mental task of figuring out what is missing in the operations list to actually know what will be generated. _Example: `type Person @include(operations: [READ_COUNT, CREATE])`._ 

Above steps would allow me to declare what I want to be generated down to the level I want.

**Comment by darrellwarde** [comment]
Despite this being the original, #1672 has slightly more detail in it (including a workaround), so I will close this as a duplicate. Looking at this for the next major release!
