### ISSUE TITLE
Input validation for queries/mutations

### ISSUE THREAD

**Issue by steffiso** [neo4j/graphql#1002]
**Is your feature request related to a problem? Please describe.**
Let's assume the following GraphQL Typedefs
```
type Comment {
    id: ID!
    text: String!
    relatedPage: Page! @relationship(type:"${REL_TYPES.REPLY}", direction:IN)
    replyed: Comment @relationship(type:"${REL_TYPES.REPLY}", direction:OUT)
    created: String!
    createdBy: String!
  }

type Mutation {
    CreateComment(pageId: ID!, replyCommentId: ID, text: String!): Comment
        @cypher(statement:"<some complex cypher statement>")
}
```

If someone execute the CreateComment mutation, I would like to give user feedback, if input **pageId** doesn't exists yet. 

**Describe the solution you'd like**
```
const Page = ogm.model('Page');
const commentMutationResolver = {
  CreateComment: async (object, params, ctx, resolveInfo) => {
    const page = Page.find({
      where: {
         id: params.pageId
      }
    });
    if (!page) {
       throw new BadUserInputError('Page with input id doesn't exist in database');
    }
    // execute cypher directive defined in typeDefs
};
```

**Comment by darrellwarde** [comment]
Going to close this as this is quite possible in a number of ways - using the OGM as you described, or you could use something like `apoc.util.validate` within custom Cypher to rollback the transaction and throw an error if something you need doesn't exist.
