### ISSUE TITLE
OGM Generate creates required `rootValue` property for DELETE mehotd's arguments.

### ISSUE THREAD

**Issue by raibtoffoletto** [neo4j/graphql#1019]
**Describe the bug**
When automatic generating types from a schema OGM's `generate` create `delete` methods with a required `rootValue`.
In all other created methods this property is optional.

**To Reproduce**
 I followed steps found in the official documentation.

**Expected behavior**
Method creates a type like:

```typescript
  public delete(args: {
    where?: RecoveryCodeWhere;
    delete?: RecoveryCodeDeleteInput;
    context?: any;
    rootValue: any;
  }): Promise<{ nodesDeleted: number; relationshipsDeleted: number }>;
```

It should be:
```typescript
  public delete(args: {
    where?: RecoveryCodeWhere;
    delete?: RecoveryCodeDeleteInput;
    context?: any;
    rootValue?: any;
  }): Promise<{ nodesDeleted: number; relationshipsDeleted: number }>;
```

**System:**
* OS: `Ubuntu 20.04.3 LTS`
* Version: `@neo4j/graphql-ogm@2.5.8`
* Node.js: `v16.14.0`

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @raibtoffoletto! :pray: We will now prioritise the bug and address it appropriately.

**Comment by tbwiss** [comment]
For later reference, see this line in the [generate.ts](https://github.com/neo4j/graphql/blob/dev/packages/ogm/src/generate.ts#L187) file.
Pinging @danstarns to see if this is working as intended.

**Comment by raibtoffoletto** [comment]
Thanks @tbwiss for being on top this! Do you guys want a PR from me (I guess it's not necessary looks like a simple typo)?

**Comment by tbwiss** [comment]
Hi @raibtoffoletto! Thanks for raising this issue and your help. I would first like to check with Dan to see if this may actually be intended, if not we will fix it. Thanks again for your help!

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
