### ISSUE TITLE
Filtering by connections in where clauses cause server error when using interfaces

### ISSUE THREAD

**Issue by jnterry** [neo4j/graphql#1049]
**Describe the bug**
The top level where filters with a relationship connection causes a server error if the relation is to an interface.

**Type definitions**

```graphql
interface Media {
	id      : ID! @id
	title   : String!
	likedBy : [Person!] @relationship(type: "LIKES", direction: IN)
	similar : [Media!] @cypher(statement: """
		MATCH (this)<-[:LIKES]-(:Person)-[:LIKES]->(other:Media)
		RETURN COLLECT(other { .*, __resolveType: apoc.coll.subtract(labels(other), ['Meda'])[0] })
	""")
}

type Book implements Media @node(additionalLabels: ["Media"]) {
	id      : ID!
	title   : String!
	likedBy : [Person!]
	similar : [Media!]

	pageCount: Int!
}

type Film implements Media @node(additionalLabels: ["Media"]) {
	id      : ID!
	title   : String!
	likedBy : [Person!]
	similar : [Media!]

	runTime: Int!
}

type Person {
	name   : String
	likes  : [Media!] @relationship(type: "LIKES", direction: OUT)
}
```

(schema also used in bug report #887)

**To Reproduce**

Seed the database with the following data:

```graphql
createPeople(input: [{
    name: "Bob",
    likes: { create: [
        { node: {Book: { title: "Harry Potter",      pageCount: 300, }}},
        { node: {Book: { title: "Lord of the Rings", pageCount: 400, }}}
    ]}
}]) {
    info { nodesCreated }
}
```

Run the following query:
```graphql
query {
  people (where: {
    likesConnection_SOME: {
      node: { title: "Harry Potter" }
    }
  }) { name }
}
```

The following server error is returned: 
 > Cannot read properties of undefined (reading 'name')

Looking at the code, I think this is because there does not exist a 'Node' instance for the interface, and hence this line evaluates to undefined:

https://github.com/neo4j/graphql/blob/ee0df92352e5fb8f0727608260c4bb5db30d7145/packages/graphql/src/translate/where/create-where-and-params.ts#L184

Reading the `refNode.name` therefore crashes:
https://github.com/neo4j/graphql/blob/ee0df92352e5fb8f0727608260c4bb5db30d7145/packages/graphql/src/translate/where/create-where-and-params.ts#L189

**Expected behavior**
The query should run successfully.

**System (please complete the following information):**

* OS: Debian 11
* Version: Affects @neo4j/graphql@3.0.1 and 2.5.x
* Node.js version: 16

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jnterry. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by jnterry** [comment]
I have implemented a fix for this issue which I would appreciate feedbakc on before I proceed with it further:
https://github.com/neo4j/graphql/pull/1056

My idea is to create a new Interface class akin to Node and pass this down in the Context object. Extending on this approach may be useful in fixing various other issues with querying interfaces and in implementing feature requests such as https://github.com/neo4j/graphql/issues/146

**Comment by darrellwarde** [comment]
This all seems to work as expected now, so closing this! 🙂
