### ISSUE TITLE
How can I add a property to a new node when using onConnectOrCreate in Neo4j GraphQL?

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#1068]
I'm using Neo4j's GraphQL library, trying to use connectOrCreate for a new Image, which is defined like this:

```
type Image {
    id: ID! @id(autogenerate: true),
    url: String! @unique, 
    creator: User! @relationship(type: "CREATED_BY", direction: OUT),
}
```

And based on the documentation on the Neo4j website, I should be able to say if a node with the url field is not found, then create one and set some properties. Like this:

```
mutation NEW_POST {
  createPosts(input: { images: { 
    connectOrCreate: [{ 
      where: { node: { url: "https://picsum.photos/600" }}
      onCreate: { where: { node: { creator: { node: { id: "userId"}}}}},
    }]}}){
  posts {
    id
    }
  }
}
```

However, for the onCreate Field Input, my only options are `id` and `url`. Meaning, I can't actually add the creator property like I do here.

`"Field \"creator\" is not defined by type \"ImageOnCreateInput\".",`

Do you think this is intended, or any idea where I should look for guidance? 
I'm looking at this documentation: [https://neo4j.com/docs/graphql-manual/current/mutations/create/][1] which shows `onCreate: { node: { title: "Forrest Gump" } }` achieving what I hope to achieve.

[![enter image description here][2]][2]

  [1]: https://neo4j.com/docs/graphql-manual/current/mutations/create/
  [2]: https://i.stack.imgur.com/iuDhS.png

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @danielfein. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @danielfein! Thanks for reaching out!
If the node with the url `https://picsum.photos/600` does not exist, a new node node with the information provided in the `onCreate` part of the mutation will be created. This "onCreate" node (with `ImageOnCreateInput`) will automatically connect the node that is specified as the "anchor". See my comments in the slightly modified mutation that you provided:

```gql
mutation NEW_POST {
  createPosts(
    input: {
      id: "userId"     // Note this 'id' here. This is the 'anchor' node.
      images: {
        connectOrCreate: [
          {
            where: { node: { url: "https://picsum.photos/600" } }
            onCreate: { node: { name: "the name" } }       // If the node with "https://picsum.photos/600" does not exist, this will create a Post with "the name" and also connect it to the anchor node with id "userId".
          }
        ]
      }
    }
  ) {
    posts {
      id
    }
  }
}
```

You can experiment and play with the typeDefs and mutation provided in the documentation (https://neo4j.com/docs/graphql-manual/current/mutations/create/#_connectorcreate_relationships) to see how the `connectOrCreate` relationship mutation is operating.
Hope this information helps, otherwise feel free to reach out again!

**Comment by danielfein** [comment]
Can somebody please reopen this? Also here is the query in context:

<img width="318" alt="Screen Shot 2022-03-01 at 8 27 29 AM" src="https://user-images.githubusercontent.com/1616865/156177626-4b92cde9-d4bf-42c8-8949-5790565d8b0c.png">

**Comment by darrellwarde** [comment]
Hey @danielfein, nested operations are currently not supported by `connectOrCreate`, hence why you cannot specify the `creator` field in the `onCreate` object. Can you please raise a feature request for this if you would like to see it implemented? Thanks!

**Comment by danielfein** [comment]
Got it, cool that makes sense - thank you!

**Comment by mchaliadzinau** [comment]
IS there an option to do the same for relation?
