### ISSUE TITLE
Unable to generate neo4j schema when using relations to interfaces

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#1085]
**Describe the bug**
I wish to have types implement interfaces that encapsulates generic relations or something that is external, but that creates issues when generating the neo4j schema. I tried to reproduce this with a simple example below where I model addresses and organisation numbers (a national external identifer).

This gives me the following error when starting the server:
```
Error: Unknown type "WithOrganisationIdentifierOrgNrConnectionSort". Did you mean "WithOrganisationIdentifierOrgNrConnectionWhere", "WithOrganisationIdentifierOrgNrConnectFieldInput", "WithOrganisationIdentifierConnectInput", "WithOrganisationIdentifierDisconnectInput", or "WithOrganisationIdentifierOrgNrUpdateConnectionInput"?
```

**Type definitions**
```graphql
type Address {
    id: ID! @id
    locates: [WithAddress!]! @relationship(type: "ADDRESS", direction: OUT) 
  }

  type OrganisationNumber {
    value: String! @unique
    identifies: [WithOrganisationIdentifier!]! @relationship(type: "ORGNR", direction: OUT) 
  }

  interface WithAddress {
    address: Address! @relationship(type: "ADDRESS", direction: IN) 
  }

  interface WithOrganisationIdentifier {
    orgNr: OrganisationNumber! @relationship(type: "ORGNR", direction: IN) 
  }

  type Controller implements WithAddress & WithOrganisationIdentifier {
    name: String!
    address: Address! @relationship(type: "ADDRESS", direction: IN) 
    orgNr: OrganisationNumber! @relationship(type: "ORGNR", direction: IN) 
  }

  type Processor implements WithAddress & WithOrganisationIdentifier {
    name: String!
    address: Address! @relationship(type: "ADDRESS", direction: IN) 
    orgNr: OrganisationNumber! @relationship(type: "ORGNR", direction: IN) 
  }
```
**To Reproduce**

1. Run an example project for `neo4j/graphql` with the above graphql schema
2. Start the server
3. See error

**Expected behavior**
This should work and I would be able to query using the interface.

**Additional context**
Might be that I'm doing something illegal that the library cannot cope with. In that case it would be helpful to at least create a more helpful error message that detects this issue.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @magnusart 
Currently, multiple interfaces are not supported by the library. We have opened a feature request issue to keep track of this feature, as it has been requested a few times. I'll close this issue in favour of #1102 

Feel free to comment or discuss in #1102
