### ISSUE TITLE
Enum values not resolving correctly inside of relationships

### ISSUE THREAD

**Issue by stkterry** [neo4j/graphql#1091]
When creating enums and their corresponding resolvers and placing them inside of a relationship for a node, the return data
come back as the enum name, and not the resolver value.  However, relationship properties in the database are mutated and stored correctly, in their resolved values.

Simplified Type definitions to demonstrate (extra enum values removed for brevity)
```graphql

type Person {
  id: ID! @id
  name: String
  acne: [AcneSpot!]! @relationship(type: "BREAKOUTS", properties: "AcneProfile", direction: OUT)
}

type AcneSpot {
  location: String! @unique
  people: [Person!]!  @relationship(type: "BREAKOUTS", properties: "AcneProfile", direction: IN)
}

interface AcneProfile @relationshipProperties {
  severity: AcneSeverity!
  types: [AcneTypes]!
}

enum AcneSpots {
  FACE
}

enum AcneSeverity {
  MILD
}

enum AcneTypes {
  BLACK_HEADS
}

input UpdateAcne {
  email: String!
  locations: [AcneSpots!]!
  types: [AcneTypes!]!
  severity: AcneSeverity!
}

type Mutation {
  updateAcne(input: UpdateAcne!): Person!
    @cypher(statement: """
      MATCH (person:Person { email: $input.email })
      OPTIONAL MATCH (person)-[r:BREAKOUTS]->()
      DELETE r
      WITH person LIMIT 1
      OPTIONAL MATCH (acneSpots:AcneSpot) WHERE acneSpots.location IN $input.locations
      CREATE (person)-[newR:BREAKOUTS { types: $input.types, severity: $input.severity }]->(acneSpots)
      RETURN person
    """)
}

```

And the resolvers...
```ts
const AcneSpots = {
  FACE: "face",
}

const AcneSeverity = {
  MILD: "mild",
}

const AcneTypes = {
  BLACK_HEADS: "black heads",
}

export const resolvers  =  {
  AcneSpots,
  // AcneSpots relationship properties
  AcneSeverity,
  AcneTypes,
{

```

**To Reproduce**
Run a mutation or query on Person and request relationship data on the return

**Expected behavior**
ALL returned data should be resolved to the strings present in the resolvers, but those in the relationships do not.

**Screenshots**
![screen](https://user-images.githubusercontent.com/31839035/156854116-bcf4d3cc-ab50-44fc-b355-243f80e817d6.png)
![database](https://user-images.githubusercontent.com/31839035/156854509-c3c61ce0-2eee-4c63-aa80-7201ee0a1770.png)

**System (please complete the following information):**

* OS: [Ubuntu 21.10]
* Version: [@neo4j/graphql 3.0.1, apollo-server-koa 3.6.3, koa 2.13.4, graphql 16.3.0]
* Node.js version: [v17.5.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @stkterry. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
