### ISSUE TITLE
In v3, it seems no longer possible to create more than 1 node in a nested mutation, which was possible in v1.

### ISSUE THREAD

**Issue by cramatt** [neo4j/graphql#1098]
**Describe the regression**
In v3, it seems no longer possible to create more than 1 node in a nested mutation, which was possible in v1.

Given the following schema:

```graphql
# schema valid in v1 and v3
type Design {
  id: ID! @id(autogenerate: true)
  name: String
  test: [Test!]! @relationship(type: "HAS_TEST", direction: OUT)
}

type Test {
  id: ID! @id(autogenerate: true)
  design: Design @relationship(type: "HAS_TEST", direction: IN)
  name: String
}
```

In v1 you could write this mutation. Here we create 1 design node, and create 3 test nodes connected to it. This is possible because`create` accepts an array (I can't recall the exact behavior but I believe it accepted an array OR object).

```graphql
# mutation worked in v1
mutation {
  createDesigns(
    input: [
      { name: "design 1", 
        test: { 
            create: [
                { name: "Test 1" } 
                { name: "Test 2" } 
                { name: "Test 3" } 
            ]
        } 
      }
    ]
  ) {
    designs {
      name
      test {
        name
      }
    }
  }
}
```

However after upgrading to v3, and adjusting the mutation syntax it seems I can only create 1 test node.  Here is the sample mutation.  Its not valid if `create.node` is an array.

```graphql
# mutation required in v3
mutation {
  createDesigns(
    input: [
      { name: "design 1", 
        test: { 
            create: { 
                node: { name: "Test 1" } 
            } 
        } 
      }
    ]
  ) {
    designs {
      name
      test {
        name
      }
    }
  }
}
```

**Last working version**

Worked up to version: [e.g. @neo4j/graphql@1.x.x]

Stopped working in version: [e.g. @neo4j/graphql@3.x.x]

**Type definitions**
See above

**To Reproduce**

1. Run a server with the above schema
2. Attempt to execute the above mutations. See error and limitations.

**Expected behavior**
Expect that when creating a node multiple related nodes can be created in same mutation. 

**Screenshots**
n/a

**System (please complete the following information):**

-   Mac OS, Node 14.x 

**Additional context**
n/a

**Comment by darrellwarde** [comment]
Hey @cramatt, `create.node` shouldn't be an array, but `create` should be. So your first example would be the following in 3.0.0:

```gql
mutation {
  createDesigns(
    input: [
      { name: "design 1", 
        test: { 
            create: [
                { node: { name: "Test 1" } }
                { node: { name: "Test 2" } }
                { node: { name: "Test 3" } }
            ]
        } 
      }
    ]
  ) {
    designs {
      name
      test {
        name
      }
    }
  }
}
```

Let me know if this works for you!

**Comment by cramatt** [comment]
@darrellwarde thanks for the quick reply, your suggestion and example code worked perfect. 

Might I suggest adding this to the documentation on relationships, here: https://neo4j.com/docs/graphql-manual/current/type-definitions/relationships/

I just noticed the migration guide DOES contain the needed syntax, I must have glanced over it. I was also bouncing between the migration guide and the relationships docs page.
