### ISSUE TITLE
Filtering: WHERE type wont get autogenerated on custom scalars

### ISSUE THREAD

**Issue by mobsean** [neo4j/graphql#1100]
**Describe the bug**
This is probably heavily correlated to #915.
I´m still converting my old neo4j-graphql-js queries to V3.0.1 and I need the custom scalar UnsignedInt from 'graphql-scalars'.

**Type definitions**
```
type Material {
  Number: UnsignedInt! @unique
  Name: String!
}
```

**To Reproduce**

1. Run a server with the the typedef above

**Expected behavior**
The autogenerated MaterialWhere only generates _IN, _NOT_IN, etc. for the Name field.
This should also be the case for any custom scalars.

**Screenshots**
![image](https://user-images.githubusercontent.com/32038980/157212516-c14dda51-c6ec-4cbd-8d4c-e346ca5e0969.png)

**System:**

* OS: Windows
* Version: @neo4j/graphql@3.0.1
* Node.js version: 16.6.1

**Additional context**
Maybe this can be fixed with #915 all together.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mobsean. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @mobsean, this was just never implemented, so I have relabelled this as a feature request. Thanks!

**Comment by darrellwarde** [comment]
So here we should add:

- For a list field: `_NOT`, `_INCLUDES` and `_NOT_INCLUDES`
- For a singular field: `_NOT`, `_IN` and `_NOT_IN`
