### ISSUE TITLE
Documentation for bind in Authorization is missing CREATE

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#1106]
**Describe the bug**
In the list of available operations for bind is "CREATE" missing, while it is used in the example directly under it. CREATE also seems to be missing in the allow documentation. Also the navigation bar on the side in the docs seems broken for 3. level entries.

**To Reproduce**

Go to https://neo4j.com/docs/graphql-manual/current/auth/authorization/bind/

**Expected behavior**
Expected the Example to be one of the available operations.

Expected Side Navigation Bar to display "bind" etc more on the right, instead of left.

**Screenshots**
![image](https://user-images.githubusercontent.com/12431981/157446718-b9ecc694-0485-42e5-a9c0-4d4e4157eeb7.png)
![image](https://user-images.githubusercontent.com/12431981/157447718-c228b9bd-2006-4d84-862a-b0a486869efd.png)

**Comment by angrykoala** [comment]
Hi @eriklueth May I ask what browser and version do you use? To reproduce the problem with the side nav

**Comment by angrykoala** [comment]
Hi @eriklueth The sidebar problem is already fixed.

**Comment by eriklueth** [comment]
> Hi @eriklueth The sidebar problem is already fixed.

Awesome 🚀
