### ISSUE TITLE
connectOrCreate modify fields on where

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#1124]
**Describe the bug**
ConnectOrCreate has 2 fields: `where` and `onCreate`. In the cases where a field is sent on `where` but not `onCreate`, that field will be set due to the merge statement used. This is counterintuitive, as the `where` name does not convey modification.

**Type definitions**
```graphql
type Movie {
  title: String! @unique
  subtitle: String @unique
  actors: [${typeActor.name}!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor {
  name: String
  movies: [${typeMovie.name}!]! @relationship(type: "ACTED_IN", direction: OUT)
}

```

**To Reproduce**
```graphql
mutation {
  createActors(
      input: [{
      name: "Tom Hanks"
      movies: {
        connectOrCreate: {
        where: { node: { subtitle: "my-subtitle" } }
        onCreate: { node: { title: "my-title"} }
        }
      }
    }]
  ) {
  actors {
    name,
      movies {
      id
      title
      subtitle
    }
  }
  }
}
```

**Expected behavior**
If a movie is created, it should have the title `"my-title"` but not subtitle.

Currently, both `my-title` and `my-subtitle` are added on creation

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @angrykoala! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
