### ISSUE TITLE
Nested `connectOrCreate` inside of `create` statement loses track of top most node in query

### ISSUE THREAD

**Issue by Tenrys** [neo4j/graphql#1127]
**Describe the bug**
When using `connectOrCreate` inside of a `create` statement for a relationship when using a `createNodes` mutation, the resulting Cypher is forgetting about `this0`, which results in the main node that was being created having no relationships, and instead a 'dead' node being the target. It works with when using `create` inside of `create`.

**Type definitions**
```gql
type TestCustomer {
  uuid: ID! @id
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])

  address: TestAddress! @relationship(type: "TEST_HAS_ADDRESS", direction: OUT)
}

type TestAddress {
  uuid: ID! @id
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])

  postalCode: TestPostalCode! @relationship(type: "TEST_HAS_POSTAL_CODE", direction: OUT)
}

type TestPostalCode {
  number: String! @unique
}
```

**To Reproduce**

1. Run a server with these type definitions
2. Execute the following Mutation...
```gql
mutation CreateTestCustomers($input: [TestCustomerCreateInput!]!) {
  createTestCustomers(input: $input) {
    testCustomers {
      uuid
    }
  }
}
```

Variables:

```gql
{
  "input": [
    {
      "address": {
        "create": {
          "node": {
            "postalCode": {
              "connectOrCreate": {
                "where": {
                  "node": {
                    "number": "00001"
                  }
                },
                "onCreate": {
                  "node": {
                    "number": "00001"
                  }
                }
              }
            }
          }
        }
      }
    }
  ]
}
```
3. The server will respond with something like this, because it's returning the 'dead' node:
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field TestCustomer.uuid.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "createTestCustomers",
        "testCustomers",
        0,
        "uuid"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}
```

**Expected behavior**
The resulting graph should look like:
```
TestCustomer -> TestAddress -> TestPostalCode
```
and not 
```
TestCustomer 
... 
(empty node) -> TestAddress -> TestPostalCode
```

**Screenshots**
Actual behavior:
![firefox_MmzMhp6Bye](https://user-images.githubusercontent.com/3979239/158214746-73a97a4c-8cac-4438-aeb6-c150bd4efbef.png)

Expected behavior:
![firefox_wc3KiNufHQ](https://user-images.githubusercontent.com/3979239/158214815-bf0ec626-887a-46ed-b096-2d41f9b1b942.png)

Example of differing Cypher:
![Code_LWHHYHbO7y](https://user-images.githubusercontent.com/3979239/158214857-3f11182c-5c21-4415-a129-4976185a44b4.png)

As you can see, the left query's `WITH` statement is missing a reference to `this0`.

**System (please complete the following information):**

* OS: Linux
* Version: @neo4j/graphql@3.0.1 with Neo4j 4.4.4, APOC 4.4.0.2
* Node.js version: v16.14.0

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Tenrys! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
