### ISSUE TITLE
Generate function on OGM fails when type begins with multiple uppercase letters 

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#1130]
**Describe the bug**

If you try and use the generate function from the OGM when you have a type that starts with multiple capital letters -- e.g., `SICIndustry` -- it will fail with the error `Cannot read property "split" of undefined`.  If you change the typeDefinition name to `SicIndustry`, there is no error.

**Types**

```graphql

type Company {
  name: String!
  industries: [SICIndustry!]! @relationship(type: "CONDUCTS_BUSINESS_IN", direction: OUT)
}

# <-- Changing the name to "SicIndustry" works
type SICIndustry {
  code: ID! @id(autogenerate: false)
  title: String!
  companies: [Company!]! @relationship(type: "CONDUCTS_BUSINESS_IN", direction: IN)
}

```

The debug trace points to the `createLines` function called by `createAggregationInput` function in the [generate.ts](https://github.com/neo4j/graphql/blob/dev/packages/ogm/src/generate.ts) file. 

**Screenshots**

Output from the error (I run generate as an api route I can call in nextjs during dev):

![image](https://user-images.githubusercontent.com/1900476/158323581-129ef82e-cca3-4828-bfad-68d540a75dbd.png)

**System (please complete the following information):**

* OS: macOs
* Version: 3.0.1
* Node.js version: lts/fermium

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @litewarp. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @litewarp! :pray: We will now prioritise the bug and address it appropriately.
