### ISSUE TITLE
Issues with aliases on connectOrCreate v2

### ISSUE THREAD

**Issue by tbwiss** [neo4j/graphql#1131]
**Describe the bug**
The issue reported in https://github.com/neo4j/graphql/issues/976 has been fixed but now apparently another issue surfaced.

**Type definitions**
Use on empty database
```graphql
type BibliographicReference @node(additionalLabels: ["Resource"]){
    iri: ID! @unique @alias(property: "uri")
    prefLabel: [String]
    isInPublication: [Concept!]! @relationship(type: "isInPublication", direction: OUT)
}

type Concept @node(additionalLabels: ["Resource"]){
    iri: ID! @unique @alias(property: "uri")
    prefLabel: [String]!
}
```

**To Reproduce**
1. Execute the following mutation:

```gql
mutation {
  createBibliographicReferences(
    input: {
      iri: "urn:myiri2"
      prefLabel: "initial label"
      isInPublication: {
        create: { node: { iri: "new-e", prefLabel: "stuff" } }
      }
    }
  ) {
    bibliographicReferences {
      iri
      prefLabel
      isInPublication {
        iri
        prefLabel
      }
    }
  }
}
```
2. Execute the following mutation:
```gql
mutation {
  deleteConcepts(where: { iri: "new-e" }) {
    nodesDeleted
  }

  updateBibliographicReferences(
    where: { iri: "urn:myiri2" }
    update: {
     prefLabel: "Updated Label:My BRS with Resource"
     isInPublication: [
        {
          connectOrCreate: {
            where: { node: { iri: "new-g" } }
            onCreate: { node: { iri: "new-g", prefLabel: "pub" } }
          }
        }
        {
          connectOrCreate: {
            where: { node: { iri: "new-f" } }
            onCreate: { node: { iri: "new-f", prefLabel: "pub" } }
          }
        }
      ]
    }
  ) {
    bibliographicReferences {
      iri
      prefLabel
      isInPublication(where: { iri_IN: ["new-f", "new-e"] }) {
        iri
        prefLabel
      }
    }
  }
}
```

3. Now check the result of the following Cypher query (the node contains both the property `iri` and the proeprty `uri`):

```cypher
match (n:Resource) where n.uri="new-f" return n
```

The customer expectation is to only have the aliased property created on the node (`uri`), but in this case as you can see from the result of step 4 both `uri` and `iri` are available.

**System (please complete the following information):**

* Neo4j Version: 4.4.x
* neo4j/graphql: 3.0.1
* Reproduced locally: yes

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @tbwiss. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @tbwiss! :pray: We will now prioritise the bug and address it appropriately.
