### ISSUE TITLE
Execution of multiple mutations in one transaction

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#1133]
**Is your feature request related to a problem? Please describe.**
I would like to run several mutations in a row. If a mutation fails or an inconsistent state is reached, I want to undo all mutations.

**Describe the solution you'd like**
For such cases, database-level transactions can be used. It would be nice to be able to manage transactions yourself via the GraphQL-API.

I don't know if this is easily possible.

**Comment by darrellwarde** [comment]
#953 is currently being worked on which will allow for an existing session or transaction in via the context. Whilst this won't directly resolve this feature request, it could certainly be used to achieve this goal!

**Comment by angrykoala** [comment]
Hi @AccsoSG 
We will close this issue in favour of #464 that will be solved in PR #953 as it will solve this problem.

**Comment by AccsoSG** [comment]
@angrykoala @darrellwarde is there any example on how to run multiple mutations over one transaction?
