### ISSUE TITLE
Invalid type declaration in OGM.d.ts

### ISSUE THREAD

**Issue by bloomdido** [neo4j/graphql#1136]
**Describe the bug**
The `OGM.d.ts` file located in the current npm package of `@neo4j/graphql-ogm` is invalid. 

**To Reproduce**

1. Install the package in a TypeScript project using `npm i @neo4j/graphql-ogm`
2. Add `import {OGM} from '@neo4j/graphql-ogm` to a TS file in the project
3. Build the project using `ts-node`

* OS: All
* Version: @neo4j/graphql-ogm@3.0.1

**Additional context**
When trying to build, the following error occurs:
```
node_modules/@neo4j/graphql-ogm/dist/classes/OGM.d.ts:13:25 - error TS2307: Cannot find module '../graphql/src/classes/Node' or its corresponding type declarations.

13     get nodes(): import("../graphql/src/classes/Node").default[];
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@neo4j/graphql-ogm/dist/classes/OGM.d.ts:13
```

This is the contents of the `node_modules/@neo4j/graphql-ogm/dist/classes/OGM.d.ts` file from the npm package:
```ts
import { Neo4jGraphQLConstructor } from "@neo4j/graphql";
import { GraphQLSchema } from "graphql";
import Model from "./Model";
export declare type OGMConstructor = Neo4jGraphQLConstructor;
declare class OGM<ModelMap = {}> {
    checkNeo4jCompat: () => Promise<void>;
    private models;
    private neoSchema;
    private _schema?;
    private initializer?;
    constructor(input: OGMConstructor);
    get schema(): GraphQLSchema;
    get nodes(): import("../graphql/src/classes/Node").default[];
    init(): Promise<void>;
    model<M extends T extends keyof ModelMap ? ModelMap[T] : Model, T extends keyof ModelMap | string = string>(name: T): M;
    private initModel;
    private createInitializer;
}
export default OGM;
//# sourceMappingURL=OGM.d.ts.map
```

I believe the problem stems from the following line:
https://github.com/neo4j/graphql/blob/6900e295b20e371fe23e860de7bbe4a239ce21f9/packages/ogm/src/classes/OGM.ts#L64

The return type for this function is not being explicitly declared. It should be `Node[]`, which TS seems to be inferring from the return value. However, when generating the .d.ts file, it seems as if TS doesn't know how to reference the type, so it's inserting `import("../graphql/src/classes/Node").default[]` as the return type.

I believe it can be fixed by explicitly declaring the return type for the function. Something like:
```ts
import {Node} from '@neo4j/graphql/src/classes';
.
.
.
    public get nodes(): Node[] {
        try {
            return this.neoSchema.nodes;
        } catch {
            throw new Error("You must await `.init()` before accessing `nodes`");
        }
    }
```

A workaround for this issue is to enable the following setting in your tsconfig.json file:

https://www.typescriptlang.org/tsconfig#skipLibCheck

This will prevent TS from type-checking the library (and all other libraries) when importing. This is not ideal.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @bloomdido. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by stkterry** [comment]
This has been plaguing me for a couple weeks now.
I can confirm setting _skipLibCheck_ to false in **_tsconfig.json_** does mask the issue until the bug is fixed.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @bloomdido! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
This should now be fixed in 3.0.2, @bloomdido @stkterry can you confirm?

**Comment by bloomdido** [comment]
All looks good here.

**Comment by stkterry** [comment]
Works a treat.  Thanks for the fix!
