### ISSUE TITLE
Missing scalar timestamps fields in  *OnCreateInput input type

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#1182]
Given the following schema ([from the tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/connect-or-create-id.test.ts#L412-L423))

```graphql
type Post {
    id: ID! @id(autogenerate: false)
    content: String!
    creator: User! @relationship(type: "HAS_POST", direction: IN)
    createdAt: DateTime!
}
type User {
    id: ID! @id(autogenerate: true)
    name: String!
    posts: [Post!]! @relationship(type: "HAS_POST", direction: OUT)
}
```

The following type is generated:

```graphql
input PostOnCreateInput {
  content: String!
  id: ID!
}
```

I would expect the type `PostOnCreateInput` to contain the field `createdAt`, since this field is no auto generated field:

```graphql
input PostOnCreateInput {
  content: String!
  createdAt: DateTime!
  id: ID!
}
```

***Additional Info***

this is because of this filter: 

https://github.com/neo4j/graphql/blob/c60707d702daf3196a0bceba66969a05c9fe5427/packages/graphql/src/schema/to-compose.ts#L86-L89

which was introduced via #1073

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
