### ISSUE TITLE
Do not create empty input type for onCreate-fields

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#1184]
Given the schema from test [rfc-003](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/rfcs/rfc-003.test.ts#L97-L112):

```graphql
interface SourceInterface {
  targets: [Target!]! @relationship(type: "HAS_TARGET", direction: OUT)
  target1: Target! @relationship(type: "HAS_TARGET", direction: OUT)
  target2: Target @relationship(type: "HAS_TARGET", direction: OUT)
}

type Source implements SourceInterface {
  id: ID @id
  targets: [Target!]!
  target1: Target!
  target2: Target
}

type Target {
  id: ID @id
}
```

The following types are generated beside others:

```graphql
input SourceInterfaceTarget1ConnectOrCreateFieldInput {
  onCreate: SourceInterfaceTarget1ConnectOrCreateFieldInputOnCreate!
  where: TargetConnectOrCreateWhere!
}

input SourceInterfaceTarget1ConnectOrCreateFieldInputOnCreate {
  node: TargetOnCreateInput!
}

input SourceInterfaceTarget2ConnectOrCreateFieldInput {
  onCreate: SourceInterfaceTarget2ConnectOrCreateFieldInputOnCreate!
  where: TargetConnectOrCreateWhere!
}

input SourceInterfaceTarget2ConnectOrCreateFieldInputOnCreate {
  node: TargetOnCreateInput!
}

input SourceInterfaceTargetsConnectOrCreateFieldInput {
  onCreate: SourceInterfaceTargetsConnectOrCreateFieldInputOnCreate!
  where: TargetConnectOrCreateWhere!
}

input SourceInterfaceTargetsConnectOrCreateFieldInputOnCreate {
  node: TargetOnCreateInput!
}

input TargetOnCreateInput {
  "Appears because this input type would be empty otherwise because this type is composed of just generated and/or relationship properties. See https://neo4j.com/docs/graphql-manual/current/troubleshooting/faqs/"
  _emptyInput: Boolean
}
```

The `onCreate` of the types `SourceInterfaceTarget1ConnectOrCreateFieldInput` and `SourceInterfaceTarget2ConnectOrCreateFieldInput` can be removed, since there is nothing the user can input and the node gets created either way (b/c its a connection).

If the `onCreate` fields gets removed, also these types are no longer required:

* SourceInterfaceTarget2ConnectOrCreateFieldInputOnCreate
* SourceInterfaceTargetsConnectOrCreateFieldInputOnCreate
* TargetOnCreateInput

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
This is fixed

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
