### ISSUE TITLE
Wrong param for fulltext queries

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#1188]
given the schema ([taken from the tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/tck/tck-test-files/fulltext/score.test.ts#L27-L29)):

```graphql
type Movie @fulltext(indexes: [{name: "MovieTitle", fields: ["title"]}]) {
  title: String
}
```

and the query

```graphql
{
  movies(
    fulltext: {MovieTitle: {phrase: "something AND something", score_EQUAL: 1}}
  ) {
    title
  }
}
```

The library is currently generating the following cypher:

```cypher
CALL db.index.fulltext.queryNodes(
    "MovieTitle",
    $this_fulltext_MovieTitle_phrase
) YIELD node as this, score as score
WHERE score = this_fulltext_MovieTitle_score_EQUAL
RETURN this { .title } as this
```

The `this_fulltext_MovieTitle_score_EQUAL` should be a parameter (prefixed with `$`)

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
