### ISSUE TITLE
Missing label check for fulltext search

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#1189]
Given the schema ([taken from the tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/tck/tck-test-files/fulltext/match.test.ts#L31-L33)):

```graphql
type Movie @fulltext(indexes: [{name: "MovieTitle", fields: ["title"]}]) {
  title: String
}
```

and the request

```graphql
{
  movies(
    fulltext: {MovieTitle: {phrase: "something AND something"}}
    where: {title: "some-title"}
  ) {
    title
  }
}
```

the following cypher is generated:

```cypher
CALL db.index.fulltext.queryNodes(
    "MovieTitle",
    $this_fulltext_MovieTitle_phrase
) YIELD node as this, score as score
WHERE this.title = $this_title
RETURN this { .title } as this
```

I would expect  a label check, like in the [additional label tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/tck/tck-test-files/fulltext/node-labels.test.ts#L106):

```cypher
CALL db.index.fulltext.queryNodes(
    "MovieTitle",
    $this_fulltext_MovieTitle_phrase
) YIELD node as this, score as score
WHERE \\"Movie\\" IN labels(this)  AND this.title = $this_title
RETURN this { .title } as this
```

Additional Information:

* The index may contain other nodes not matching the ones queried
* The check for `additionalLabels` should be removed
https://github.com/neo4j/graphql/blob/f079969bcd5976cd4e92ae23d628e7136f234980/packages/graphql/src/translate/translate-top-level-match.ts#L65-L69

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
