### ISSUE TITLE
Unable to use netlify lambda function with @neo4j/graphql v3

### ISSUE THREAD

**Issue by jaedag** [neo4j/graphql#1225]
**Describe the bug**
Unable to use netlify lambda function with @neo4j/graph3.0.3 with the asynchronous schema generation.

**To Reproduce**
Deploy a lambda function with @neo4j/graphql 3.0.3

**Expected behavior**
Expected the lambda function to be invoked. 

**Code Sample**

This is what my code looks like.
```js
// This module can be used to serve the GraphQL endpoint
// as a lambda function

const { ApolloServer } = require('apollo-server-lambda')
const { Neo4jGraphQL } = require('@neo4j/graphql')
const { Neo4jGraphQLAuthJWTPlugin } = require('@neo4j/graphql-plugin-auth')
const neo4j = require('neo4j-driver')

// This module is copied during the build step
// Be sure to run `npm run build`
const { typeDefs } = require('./schema/graphql-schema')
const { resolvers } = require('../../resolvers/resolvers.js')
const { serviceResolvers } = require('../../resolvers/service-resolvers')
const { arrivalsResolvers } = require('../../resolvers/arrivals-resolvers')

const driver = neo4j.driver(
  process.env.NEO4J_URI || 'bolt://localhost:7687',
  neo4j.auth.basic(
    process.env.NEO4J_USER || 'neo4j',
    process.env.NEO4J_PASSWORD || 'neo4j'
  )
)

const neoSchema = new Neo4jGraphQL({
  typeDefs,
  resolvers: { ...resolvers, ...serviceResolvers, ...arrivalsResolvers },
  driver,
  plugins: {
    auth: new Neo4jGraphQLAuthJWTPlugin({
      secret: process.env.JWT_SECRET.replace(/\\n/gm, '\n'),
      rolesPath: 'https://flcadmin\\.netlify\\.app/roles',
    }),
  },
})

const startServer = async () => {
  const schema = await neoSchema.getSchema()

  const server = new ApolloServer({
    context: ({ event }) => ({ req: event }),
    introspection: true,
    schema,
  })

  return server
}
const server = startServer()
const apolloHandler = server.createHandler()

export const handler = (event, context, ...args) => {
  return apolloHandler(
    {
      ...event,
      requestContext: context,
    },
    context,
    ...args
  )
}

```

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@3.0.3
* Node.js version: v16.13.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jaedag. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
> ```js
> const startServer = async () => {
>   const schema = await neoSchema.getSchema()
> 
>   const server = new ApolloServer({
>     context: ({ event }) => ({ req: event }),
>     introspection: true,
>     schema,
>   })
> 
>   return server
> }
> const server = startServer()
> const apolloHandler = server.createHandler()
> ```

Hey @jaedag, this isn't a problem with the library. In this portion of your code block above, you are assigning a promise of an Apollo Server to the `server` variable and then trying to call `createHandler` on the promise - that is why this code won't be working.

Your handler really needs to be async: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html#nodejs-handler-async

**Comment by flieks** [comment]
Hi, 

i am having the same problem with NextJS. I want to use it directly from getStaticProps but in order to do so i need a module that exports the schema and the ApolloServer

![image](https://user-images.githubusercontent.com/5032389/172849319-0ad1351b-503c-4231-85bd-ca56c6b79082.png)
