### ISSUE TITLE
Time field does not accept times formatted as HH:MM 

### ISSUE THREAD

**Issue by megatrond** [neo4j/graphql#1234]
**Describe the bug**
When using a time field, and passing a string in the format `HH:MM`, the validation fails with the message

```
Variable "$input" got invalid value "17:15" at "input[44].period.create.node.begin"; Expected type "Time". Value must be formatted as Time: 17:15
```

**To Reproduce**

1. Pass a time in the format `HH:MM` to a `Time` field in a mutation
2. Get error

**Expected behavior**
According to the specification at https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-specify-time this should be allowed

**System (please complete the following information):**

* OS: macOS
* Version: 3.0.3
* Node.js version: 16.3.0

**Additional context**
Changing the value of the `RFC_3339_REGEX` variable in `@neo4j/graphql/dist/schema/scalars/Time.js:27` to:

```
^(?<hour>[01]\d|2[0-3]):(?<minute>[0-5]\d)(:(?<second>[0-5]\d))?(\.(?<fraction>\d{1}(?:\d{0,8})))?((?:[Zz])|((?<offsetDirection>[-|+])(?<offsetHour>[01]\d|2[0-3]):(?<offsetMinute>[0-5]\d)))?$
```

seems to fix the issue, but this has not been tested other than to see that `HH:MM` formatted times are matched

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @megatrond. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by angrykoala** [comment]
The aforementioned regexp, while accepting `HH:MM`, also accepts invalid formats, such as `20:10.555`.

Instead, this regex will be used:
```js
/^(?<hour>[01]\d|2[0-3]):(?<minute>[0-5]\d)(:(?<second>[0-5]\d)(\.(?<fraction>\d{1}(?:\d{0,8})))?((?:[Zz])|((?<offsetDirection>[-|+])(?<offsetHour>[01]\d|2[0-3]):(?<offsetMinute>[0-5]\d)))?)?$/
```
