### ISSUE TITLE
Sort, first, and after arguments not correctly applied to root-level connection fields

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#1273]
**Describe the bug**

The sort, limit, and offset strings for top-level-connections get applied on the returned connection -- i.e. the object `{totalCount, edges}` and not the edges themselves. So the sort, offset, and limit arguments do nothing.

Also, the root-connection resolver uses the resolveTree args which don't get translated correctly when passed to the `createConnectionWithEdgeProperties` function. So 

These are probably oversights on my part while drafting the root-level connections PR, but I think things also changed slightly from the fix for #591.  I've fixed these and will be issuing a PR shortly.

To reproduce, run a query on a top level connection with first and sort arguments: 

**TypeDefs**

```graphql

type Movie {
  id: ID! @id
  title: String!
}

```

Create 20 movies, then run:

**Query**

```graphql

query {
  moviesConnection(first: 10, sort: [{title: ASC}]) {
    totalCount
    edges {
      node {
        title
      }
    }
    pageInfo {
      # <-- This will be false even though the totalCount returns 20 and the first argument is 10
      hasNextPage
    }
  }
}
```

**Cypher**

```
MATCH (this:Movie)
WITH COLLECT({ node: this { .title } }) as edges
RETURN { edges: edges, totalCount: size(edges) } as this
# <------- these arguments need to be applied before returning the connection
ORDER BY this.title ASC
LIMIT $this_limit
```

* OS: macOs
* Version: 3.1.0
* Node.js version: 14*

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @litewarp. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @litewarp! :pray: We will now prioritise the bug and address it appropriately.
