### ISSUE TITLE
connectOrCreate not utilizing the value from 'where' in 'onCreate'

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#1276]
**Describe the bug**
With previous versions, if you use connectOrCreate, the `where` statement would look for a node via a property. If not found, that property would be implicitly added to the `onCreate`. This just broke recently.

What was this:
```
 imagesConnectData.push({ 
        where: { node: { url: imageUrl }},
        onCreate: { node: { creator_id: userId }},
      })
```

Now only works like this:
```
 imagesConnectData.push({ 
        where: { node: { url: imageUrl }},
        onCreate: { node: { creator_id: userId, url: imageUrl }},
      })
```

Any idea?

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @danielfein. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @danielfein! Thanks for reaching out!
With `This just broke recently` do you mean it broke in version 3.1.0 but was still working in 3.0.4? That should help us to narrow it down.
