### ISSUE TITLE
Leaky aggregate counts (related to aliased fields I think)

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#1320]
**Describe the bug**
When aliasing an aggregate multiple times in the same query, using different filters in each, the results leak between properties

**Type definitions**
Relevant bit of a much larger schema:

```graphql
type Risk {
    code: String!
    ownedBy: Team @relationship(type: "OWNS_RISK", direction: IN)
    mitigationState: [MitigationState] 
}

type Team {
    code: String!
    ownsRisks: [Risk!]! @relationship(type: "OWNS_RISK", direction: OUT)
}

enum MitigationState {
  Deferred
  Identified
  Accepted
  Complete
}

```

**To Reproduce**

1. Run a @neo4j/graphql server augmenting the schema above
2. Create a Team record and relationships pointing at a number of Risks with either Complete or Accepted states
3. Then run the following Query...

```
query getStuff($code: String!) {
  greenStat: teams(where: { code: $code }) {
    amberRisks: ownsRisksAggregate(
      where: { mitigationState_IN: [Accepted, Complete] }
    ) {
      count
    }
  }
  
  amberStat: teams(where: { code: $code }) {
    amberRisks: ownsRisksAggregate(
      where: { mitigationState_IN: [Deferred, Identified] }
    ) {
      count
    }
  }

  stats: teams(where: { code: $code }) {
    amberRisks: ownsRisksAggregate(
      where: { mitigationState_IN: [Deferred, Identified] }
    ) {
      count
    }

    greenRisks: ownsRisksAggregate(
      where: { mitigationState_IN: [Accepted, Complete] }
    ) {
      count
    }
  }
}
```

**Expected behavior**
The counts for amber stats should all be zero, but when run within the same subquery where green stats are fetched simultaneously, the value is the same as green stats

**Screenshots**
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/447559/165582639-a05cb5c8-b5e2-40df-a9b7-b27ccad4e159.png">

**System (please complete the following information):**

* OS: Linux (Ubuntu I think, whatever the heroku-18 stack is)
* Version: 3.1.0
* Node.js version:  14.x

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @wheresrhys. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @wheresrhys! :pray: We will now prioritise the bug and address it appropriately.

**Comment by tbwiss** [comment]
For reference, I also managed to reproduce it with this query:

```
query {
  greenStat: teams(where: { code: "XXXXXXX" }) {
    amberRisks: ownsRisksAggregate(
      where: { mitigationState_INCLUDES: Accepted }
    ) {
      count
    }
  }
  
  amberStat: teams(where: { code: "XXXXXXX" }) {
    amberRisks: ownsRisksAggregate(
      where: { mitigationState_INCLUDES: Identified }
    ) {
      count
    }
  }

  stats: teams(where: { code: "XXXXXXX" }) {
    amberRisks: ownsRisksAggregate(
      where: { mitigationState_INCLUDES: Deferred }
    ) {
      count
    }

    amberRisks2: ownsRisksAggregate(
      where: { mitigationState_INCLUDES: Identified }
    ) {
      count
    }

    greenRisks: ownsRisksAggregate(
      where: { mitigationState_INCLUDES: Complete }
    ) {
      count
    }

    greenRisks2: ownsRisksAggregate(
      where: { mitigationState_INCLUDES: Accepted }
    ) {
      count
    }
  }
}
```
