### ISSUE TITLE
Use `import type` in generated OGM types for SelectionSetNode, DocumentNode

### ISSUE THREAD

**Issue by dennisjlee** [neo4j/graphql#1323]
**Describe the bug**

When using the [OGM code generation feature](https://neo4j.com/docs/graphql-manual/current/ogm/type-generation/), this line gets generated in the code:

```
import { SelectionSetNode, DocumentNode } from "graphql";
```

My project's tsconfig.json has `importsNotUsedAsValues` set to `error`, which results in this error on that line:
```
TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
```

**Type definitions**
N/A

**To Reproduce**

1. Follow the example for type generation from https://neo4j.com/docs/graphql-manual/current/ogm/type-generation/
2. Run `npx tsc index.ts --noEmit --importsNotUsedAsValues error`
3. See error

**Expected behavior**
The code should be generated with `import type` to avoid this error. I think this is safe to do even if users are not using `importsNotUsedAsValues=error`.

**Screenshots**
N/A

**System (please complete the following information):**

* OS: Windows 11
* Version: @neo4j/graphql@3.1.0, @neo4j/graphql-ogm@3.1.0
* Node.js version: 16.14.0

**Additional context**
N/A

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @dennisjlee. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @dennisjlee! :pray: We will now prioritise the bug and address it appropriately.
