### ISSUE TITLE
Please create a CHANGELOG for releases

### ISSUE THREAD

**Issue by bloomdido** [neo4j/graphql#1332]
I know this was discussed on Discord a good while back, but since we're on the third major version release of the library and releases have become more stable and less frequent, can you please add a CHANGELOG to track changes between releases. It is a major bummer to have to manually diff commit histories to try to figure out what has changed from version to version. A listing of changes (possibly broken up into features & bugfixes, and especially identifying breaking changes) would be a major timesaver when trying to update to a new version in our projects.

Thanks!

- Chris

**Comment by angrykoala** [comment]
Hi Chris
We keep a changelog in [releases](https://github.com/neo4j/graphql/releases) section.
Is there anything else you need from the changelog?

**Comment by bloomdido** [comment]
I hadn't realized that was there!
