### ISSUE TITLE
Sort Broken on Cypher Field When Querying Root Connections

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#1364]
**Describe the bug**

Sort no longer works with connections when using a cypher field since the projection happens *after* the sort is applied.  I'll work on a fix at some point.

Given the schema: 

```graphql
type Organization {
  id: ID! @id
  fundraises: [Opportunity!]! @relationship(type: "IS_COMPANY_IN", direction: OUT)
  roundsRaised: Int! @cypher(statement: """
  MATCH (this)-[:IS_COMPANY_IN]->(opp:Opportunity)
  RETURN count(opp)
  """)
}

type Opportunity {
  id: ID! @id
  investedCompanies: [Organization!]! @relationship(type: "IS_COMPANY_IN", direction: IN)
}
```

Run the following query:

```graphql

query MyQuery($sort: [OrganizationSort], $where: OrganizationWhere!) {
  organizationsConnection(
    first: 20
    sort: [{ roundsRaised: DESC }]
  ) {
    edges {
      cursor
      node {
        id
        roundsRaised
      }
    }
  }
}

```

And it will produce cypher like the following from an actual query I ran:

```
CALL {
MATCH (this:Organization)
WITH COLLECT(this) as edges
WITH edges, size(edges) as totalCount
UNWIND edges as this
RETURN this, totalCount
# <--- Sort happens here
ORDER BY this.roundsRaised DESC
LIMIT $this_limit
}
# <--- But projection happens here
WITH COLLECT({ node: this { .name, roundsRaised:  apoc.cypher.runFirstColumn("MATCH (this)-[:IS_COMPANY_IN]->(opp:Opportunity)
RETURN count(opp)", {this: this, auth: $auth}, false) } }) as edges, totalCount
RETURN { edges: edges, totalCount: totalCount } as this
```

Result is that sort is broken.

* OS: Mac
* Version: 3.1.0
* Node.js version: 14.x

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @litewarp. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @litewarp! Thanks for raising this bug!
I wasn't quite able to reproduce the cypher above. I probably missed something somewhere.
Just for reference:
```graphql
query MyQuery {
  organizationsConnection(
    first: 20
    sort: [{ roundsRaised: DESC }]
  ) {
    edges {
      cursor
      node {
        id
        roundsRaised
      }
    }
  }
}
```
produces:
```cypher
MATCH (this:Organization)
WITH COLLECT({ node: this { .id, roundsRaised:  apoc.cypher.runFirstColumn("MATCH (this)-[:IS_COMPANY_IN]->(opp:Opportunity)
RETURN count(opp)", {this: this, auth: $auth}, false) } }) as edges
RETURN { edges: edges, totalCount: size(edges) } as this
ORDER BY this.roundsRaised DESC
LIMIT $this_limit
```
Do I miss some variables/parameters for the query?

**Comment by litewarp** [comment]
@tbwiss what version are you using? There was a PR that got merged into master where the root connection cypher is wrapped in a subquery call which I don't see.

**Comment by tbwiss** [comment]
@litewarp Sry this one is on me! I was testing it on the wrong branch.. I can confirm your bug (and the produced cypher).

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @litewarp! :pray: We will now prioritise the bug and address it appropriately.

**Comment by litewarp** [comment]
@tbwiss no worries! Btw, I think I may have a fix somewhat shortly. 

We should also get @darrellwarde's input as he had a PR (can't find it now) that dealt with a similar issue and changed some of the translate-read.ts logic. He may want to batch this fix with that work.
