### ISSUE TITLE
@Callback is called on an update even though the UPDATE operation is not set.

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#1414]
**Describe the bug**
As described in the title

**Type definitions**

````gql
interface Product {
    id: ID! @callback(operations: [CREATE], name: "nanoid")
    productTitle: String!
    releatsTo: [Product!]!
}

type Series implements Product {
    id: ID!
    productTitle: String!

    seasons: [Season!]!
}

type Season implements Product {
    id: ID!
    productTitle: String!

    seasonNumber: Int
    episodes: [ProgrammeItem!]!
}

type ProgrammeItem implements Product {
    id: ID!
    productTitle: String!

    episodeNumber: Int
}
````

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...

Create Node:
````gql
mutation {
  createProgrammeItems(input: {
    productTitle: "TestPI"
  }) {
    programmeItems {
      id
      productTitle
    }
  }
}
````
Result:
````json
{
  "data": {
    "createProgrammeItems": {
      "programmeItems": [
        {
          "id": "7DQE-3UL3-WD8X",
          "productTitle": "TestPI"
        }
      ]
    }
  }
}
````

Update Node:
````gql
mutation {
  updateProgrammeItems(where: {id: "7DQE-3UL3-WD8X"}, update: {productTitle: "TestPI2"}) {
    programmeItems {
      id
      productTitle
    }
  }
}
````

Result:
````json
{
  "data": {
    "updateProgrammeItems": {
      "programmeItems": [
        {
          "id": "33ST-IEFB-8BQM",
          "productTitle": "TestPI2"
        }
      ]
    }
  }
}
````

As you can see, the callback "nanoid" is also called for an update. A new ID has been generated.

**Expected behavior**
The callback should not be called for an update if this has not been configured.

**Additional context**

https://www.npmjs.com/package/nanoid

````javascript
const { customAlphabet } = require("nanoid");

...

const nanoIdSize = 12;
const nanoIdAlphabet = "123456789ABCDEFGHIJKLMNPQRSTUVWXYZ";

function generateNanoId() {
    const nanoIdCallback = customAlphabet(nanoIdAlphabet, nanoIdSize);
    const nanoId = nanoIdCallback();
    const formattedNanoId = nanoId.substring(0, 4) + "-" + nanoId.substring(4, 8) + "-" + nanoId.substring(8, 12)
    return formattedNanoId;
}

...

const neoSchema = new Neo4jGraphQL({ 
    typeDefs, 
    driver,
    config: {
        callbacks: {
          nanoid: generateNanoId,
        },
    },
});

...

````

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.
