### ISSUE TITLE
Auth Working is not as per the documentation

### ISSUE THREAD

**Issue by iamsanaur** [neo4j/graphql#1419]
The documentation says 

```js
import { Neo4jGraphQL } from "@neo4j/graphql";
import { Neo4jGraphQLAuthJWTPlugin } from "@neo4j/graphql-plugin-auth";

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    plugins: {
        auth: new Neo4jGraphQLAuthJWTPlugin({
            secret: "super-secret"
        })
    }
});
```

However the actual procedure is 

```js
const neoSchema = new Neo4jGraphQL({
  typeDefs,
  driver,

  config: {
    jwt: {
      secret: process.env.JWT_SECRET,
    },
  },
})
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @iamsanaur. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @iamsanaur! Thanks for reaching out!
Could you point to where exactly in the documentation this is? Is it on the [Auth - Setup](https://neo4j.com/docs/graphql-manual/current/auth/setup/) page?
Thank you!

**Comment by iamsanaur** [comment]
Yes it is placed in the documentation 

https://neo4j.com/docs/graphql-manual/current/auth/setup/#auth-setup-passing-in

import { Neo4jGraphQL } from "@neo4j/graphql";
import { Neo4jGraphQLAuthJWTPlugin } from "@neo4j/graphql-plugin-auth";

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    plugins: {
        auth: new Neo4jGraphQLAuthJWTPlugin({
            secret: "super-secret"
        })
    }
});
However in the neo4j package inside auth it clearly shows we need config property to get hold of JWT verification,

<img width="1080" alt="Screen Shot 2022-05-13 at 2 10 22 PM" src="https://user-images.githubusercontent.com/3446273/168245760-a6cddbff-2f75-4414-9944-7a5c5e53f96b.png">

**Comment by tbwiss** [comment]
You can see an example on how it works here in this [integration test](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/integration/aggregations/top-level/auth.int.test.ts#L66-L86).

As a first step, the schema is created just like described in the [docs](https://neo4j.com/docs/graphql-manual/current/auth/setup/#_configuration).
To then pass the JWT token, described [here in the docs](https://neo4j.com/docs/graphql-manual/current/auth/setup/#auth-setup-passing-in), use a HTTP header. A header can be added in for instance the Apollo studio editor. See this [link](https://www.apollographql.com/docs/studio/explorer/connecting-authenticating/) for more information.
The integration test file above does this step of passing a "header" with the JWT token (a Bearer token) in code [here](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/integration/aggregations/top-level/auth.int.test.ts#L85). You will not need to do that if you use the Apollo server respectively the Apollo studio, it's just for clarification.

Does this help?

**Comment by darrellwarde** [comment]
@iamsanaur, what version of the library are you using?

**Comment by iamsanaur** [comment]
> You can see an example on how it works here in this [integration test](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/integration/aggregations/top-level/auth.int.test.ts#L66-L86).
> 
> 
> 
> As a first step, the schema is created just like described in the [docs](https://neo4j.com/docs/graphql-manual/current/auth/setup/#_configuration).
> 
> To then pass the JWT token, described [here in the docs](https://neo4j.com/docs/graphql-manual/current/auth/setup/#auth-setup-passing-in), use a HTTP header. A header can be added in for instance the Apollo studio editor. See this [link](https://www.apollographql.com/docs/studio/explorer/connecting-authenticating/) for more information.
> 
> The integration test file above does this step of passing a "header" with the JWT token (a Bearer token) in code [here](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/integration/aggregations/top-level/auth.int.test.ts#L85). You will not need to do that if you use the Apollo server respectively the Apollo studio, it's just for clarification.
> 
> 
> 
> Does this help?
> 
> 

I can get this but the documentation is still not apt. Documentation is something that should match.

**Comment by iamsanaur** [comment]
> @iamsanaur, what version of the library are you using? 

3.2.0

**Comment by darrellwarde** [comment]
The documentation does indeed match the current requirements for enabling auth. You can see on [this page](https://neo4j.com/docs/graphql-manual/current/auth/setup/#_configuration) that auth is enabled by passing in a plugin, much like it is done in the integration test referenced above.

The `get-jwt.js` file which you referenced in [your comment above](https://github.com/neo4j/graphql/issues/1419#issuecomment-1125802312) does not exist in the current release, which leads me to believe that you are potentially looking at an old version of the library.

Closing this as we have no way to reproduce, and we have hundreds of tests validating that the functionality works and also matches the documentation.
