### ISSUE TITLE
Mutation on Interface fail to keep one to one constraint

### ISSUE THREAD

**Issue by AnsonHwang86** [neo4j/graphql#1430]
**Describe the bug**
Mutation on Interface fail to keep one to one constraint

**Type definitions**
```
type ABCE{
  id:ID @id
  name: String
  interface: InterfaceMom @relationship(type:"HAS_INTERFACE", direction:OUT)
}

interface InterfaceMom {
  id:ID @id
  name:String
}

type ChildOne implements InterfaceMom {
  id:ID @id
  name:String
  feathur: String
}

type ChildTwo implements InterfaceMom {
  id:ID @id
  name:String
  sth: String
}
```
**To Reproduce**

1. Run a server with the following code...

2. Execute the following Mutation...

```
mutation createAbces{
	createAbces(input:[
		{
			
			interface:{
				
				create:{
					node:{
						ChildOne:{
							name:"childone name"
						}
						ChildTwo:{
							name:"childtwo name"
						}
					}
				}
			}
		}
	]){
		abces{
			id
			name
			interface{
				id
				name
				__typename
			}
		}
	}
}
```
3. Then run the following Query...

```
{
	"data": {
		"abces": [
			{
				"id": "23a9cdc4-bf9c-46bf-a51d-343d9c7ef3ab",
				"name": null,
				"interface": {
					"id": "2c50f399-1660-4d2d-83c9-f266bd1a0a5f",
					"name": "childone name1",
					"__typename": "ChildOne"
				}
			},
			{
				"id": "23a9cdc4-bf9c-46bf-a51d-343d9c7ef3ab",
				"name": null,
				"interface": {
					"id": "05ced8da-14c9-4639-8be9-062734c262d8",
					"name": "childtwo name1",
					"__typename": "ChildTwo"
				}
			}
		]
	}
}
```

The return data contain two ABCE nodes with same ID. 

**Expected behavior**
It should throw an error, beacause the relationship between ABCE and InterfaceMom is one to one as in scheme.

If I continue to operate update mutation as following

```
mutation ddfs{
	updateAbces(where:{	id:"23a9cdc4-bf9c-46bf-a51d-343d9c7ef3ab"}
		create:{
			interface:{
				node:{ChildOne:{
					name:"childone name2"
				}}
			}
		}
	){
		abces{
			id
			interface{
				id
				name
				__typename
			}
		}
	}
}
```

It will add a new ABCE node with same id("23a9cdc4-bf9c-46bf-a51d-343d9c7ef3ab") alone with new created ChildOne node instead of just create ChildOne node(not create ABCE node).

**System (please complete the following information):**

* OS: [ Windows 10 pro]
* Version: [e.g. @neo4j/graphql@3.2.0]
* Node.js version: [e.g. 16.13.0]

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AnsonHwang86. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @AnsonHwang86! Thanks for reaching out!
I was running your provided queries. If I use Neo4j Browser to check what is stored in the database after I executed `mutation ddfs` (the last provided query) then I see the following:

<img width="534" alt="Skärmavbild 2022-05-16 kl  15 21 44" src="https://user-images.githubusercontent.com/8817964/168602179-e8ed5be1-2716-4eca-9ddb-1e11b275cd72.png">

There is only one `ABCE` node. No additional one got added.
Is that what you expected?

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AnsonHwang86! :pray: We will now prioritise the bug and address it appropriately.

**Comment by AnsonHwang86** [comment]
> Hi @AnsonHwang86! Thanks for reaching out! I was running your provided queries. If I use Neo4j Browser to check what is stored in the database after I executed `mutation ddfs` (the last provided query) then I see the following:
> 
> <img alt="Skärmavbild 2022-05-16 kl 15 21 44" width="534" src="https://user-images.githubusercontent.com/8817964/168602179-e8ed5be1-2716-4eca-9ddb-1e11b275cd72.png">
> 
> There is only one `ABCE` node. No additional one got added. Is that what you expected?

Yes, but `ABCE` should have one relationship(type:HAS_INTERFACE) with InterfaceMom . Becuase the relationship between is one to one as description in schema.
