### ISSUE TITLE
Proposal: add support for relation filters _some, _none, _single and _every

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#144]
In the [java version](https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/main/kotlin/org/neo4j/graphql/Predicates.kt#L198-L209) we currently support the relation filters `_some`, `_none`, `_single` and `_every`

As stated by @danstarns in slack:

> Good point - `_single` and `_some` are missing. We removed `_none` because its the same as:
> ```graphql
> {
>   User(filter: { posts_not: { id: 1 } }) {
>     id
>   }
> }
> ```
> And `_every` is the same as:
> ```graphql
> {
>   User(filter: { posts: { id: 1 } }) {
>     id
>   }
> }
> ```

---

I would suggest to distinguish between `n..1` and `n..m` relations:

### Filter for `n..m`-relations

I realized that users may use the `_every` but expecting it to act like the `_some` filter:
```graphql
{
  User(filter: { posts: { id: 1 } }) {
    id
  }
}
```

That's why I would vote for make all 4 filters explicit:

- `_every`: Filters only those `${type.name}` for which all `${field.name}`-relationships matches this filter
- `_some`: Filters only those `${type.name}` for which at least one `${field.name}`-relationship matches this filter
- `_single`: Filters only those `${type.name}` for which exactly one `${field.name}`-relationship matches this filter
- `_none`: Filters only those `${type.name}` for which none of the `${field.name}`-relationships matches this filter

and remove `<field>_not` and `<field>` for `n..m` relations!
**It's much clearer to the user what he can expect as result, especially with the given description on each field.**

### Filter for `n..1`-relations

The filter above does not make sense for `n..1` relations, so I would keep the current API with `<field>_not` and `<field>` for these types of relations.

**Comment by wheresrhys** [comment]
@darrellwarde is there any decision on whether these will be added, and if so what the timeline is likely to be.

I _think_ it's the only blocker we have to migrating from neo4j-graphql-js

**Comment by darrellwarde** [comment]
No decision yet (there hasn't really been a _massive_ call for it), but it will certainly be compelling if this is one of the last remaining blockers to migration.

Another one of the reasons we haven't gone ahead with this is because we believe that despite some of these absent filters, there are alternative ways of achieving the same outcomes using the already implemented filters.

Could you possibly give some examples of where you are blocked @wheresrhys? We can either help find some alternative filters, or it will help feed into the planning for this work. Thanks! 🙂

**Comment by wheresrhys** [comment]
A typical use case for us is to build a report (and there are many many different instances of this pattern in use by us - I'll just share one example)

```
{
  Teams(filter: {delivers_some: {lifecycleStage_not: Decommissioned}}) {
    code
    delivers(filter: {lifecycleStage_not: Decommissioned}) {
      code
    }
  }
}
```

This query means 'For every team that has some active systems, display its active systems'. Without `_some` we are forced into showing this for all teams.

So I guess the use case in the abstract is 'Enable filtering a list to display only those items that are related to at least some data of interest'.

**Comment by wheresrhys** [comment]
Another use case, our incidents are logged against systems, delivered by teams, which live within groups. If we want a report of incidents for the group we query:

```
{
  Incidents(filter: {systems_some: {deliveredBy: {group: {code: "my-group"}}}}) { severity ... }
}
```

If our model specified that the incident to system relationship was many to one we wouldn't need `_some`, but we designed the model to be a truer picture of reality (sometimes incidents have a wider blast radius than a single system). It feels suboptimal that, without `_some` being supported, this reasonable modelling decision puts us in a position where the querying possibilities are much reduced compared to if we modelled as many to one.

**Comment by dmoree** [comment]
@wheresrhys I've run into similar issues with the limitations of current relationship filters. I've created #796 to try to address this and I think that this test reproduces your use case:
https://github.com/dmoree/graphql/blob/feature/additional-relationship-filters/packages/graphql/tests/integration/advanced-filtering.int.test.ts#L1842-L1851

**Comment by wheresrhys** [comment]
Thanks @dmoree 🙌

**Comment by darrellwarde** [comment]
That's brilliant @dmoree, we'll move over to the PR to work with you there but broadly we support this change!

**Comment by Andy2003** [comment]
Hi @darrellwarde, as i just noticed, in js there is still no distinction between `0..1` and `0..n` relations regarding the filter. Is there a plan to address this topic in the future?

**Comment by darrellwarde** [comment]
Hey @Andy2003, there is a distinction here! For example:

```gql
type Movie {
  title: String!
  actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
  director: Person! @relationship(type: "DIRECTED", direction: IN)
}
```

`actors` will have the "full suite" of filters (`ANY`, `ALL`, etc.), whilst `director` will only have `director` and `director_NOT`.
