### ISSUE TITLE
Auth pre-flight

### ISSUE THREAD

**Issue by udaykor** [neo4j/graphql#1443]
**Describe the bug**
GraphQL Authentication/Authorisation works when there is data. For Nodes that do not exist an empty array is returned. This can be best examined on an empty Neo4j instance.

**Type definitions**
```
type User @auth(rules: [{operations: [READ], isAuthenticated: true}]) {
  userId: ID!
}
```

**To Reproduce**
1. Create empty database.
2. Create GraphQL Server with JWT Auth or JWKS (Choice does not matter).
3. Query for data
```
query x {
 users {
   userId
 }
} 
```

1. Run a server with the following code...
5. Execute the following Mutation...
6. Then run the following Query...
7. See error

**Expected behavior**
Authentication Error or Authorisation error must show up. This does happen but only when there is data. If this 

**Screenshots**

**System (please complete the following information):**

* OS: macOS
* Version: 
```
"@neo4j/graphql": "^3.2.2",
"@neo4j/graphql-ogm": "^3.2.2",
"@neo4j/graphql-plugin-auth": "^1.0.0",
```
* Node.js version: [16.15.0]

**Additional context**
If this is expected behaviour when node of types not present, Please close the issue.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @udaykor. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @udaykor, this is something we're aware of, and was originally reported way back in #195. We want to look at auth holistically soon, and this will be included when we get around to that. Going to close this as a duplicate in the meantime.
