### ISSUE TITLE
Proposal: deep sorting

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#145]
As explained in https://github.com/neo4j-graphql/neo4j-graphql-java/issues/64 I would suggest to change the way sorting is defined.

> Given the Schema:
> 
> ```graphql
> type Movie {
>   title: String
>   publishedBy: Publisher @relation(name: "PUBLISHED_BY", direction: OUT)
> }
> 
> type Publisher {
>   name: ID!
> }
> ```
> 
> The augmentation would be:
> 
> ```graphql
> type Query {
>   movie(sort: [_MovieSorting!]): [Movie!]!
> }
> enum SortDirection{
>   asc,
>   desc,
> }
> 
> input _MovieSorting {
>   title: SortDirection
>   publishedBy: [_PublisherSorting!]
> }
> 
> input _PublisherSorting {
>   name: SortDirection
> }
> ```
> 
> So a user can get all movies ordered by `Publisher.name` and `title` by calling
> 
> ```graphql
> query {
>   movie(sort: [{publishedBy: [{name: desc}]}, {title: asc}]) {
>     title
>   }
> }
> ```
>  which results in this query
> 
> ```cypher
> MATCH (m:Movie)
> WITH m
>   ORDER BY head([(m)-[:PUBLISHED_BY]->(p:Publisher) | p.name]) DESC, m.name ASC
> RETURN m{.title}
> ```
> 
> This sorting should be possible for all 1..1 relations.

**Comment by rcbevans** [comment]
Hey @darrellwarde, any update on this?

I have many examples of places where I need to be able to sort results based on connected edges, for example, sort posts by the number of comments, or sort author by most recent post.  

I attempted to work around the issue by adding a virtual field backed by a cypher query to return the result to sort on, hoping the GraphQL library would generate an order by augmentation for the property, but it seems it doesn't for fields backed by Cypher.

In some cases I'm able to mitigate by denormalizing the data and storing the count on the node as well, but this opens the opportunity for the property to be wrong which isn't great.

**Comment by morningcloud** [comment]
Following this issue for updates after posting to the discord channel. Looking forward to when this feature will be addressed.

**Comment by morningcloud** [comment]
Hi @darrellwarde, are the sorting-related features abandoned or is there any plan to proceed with the Pagination and Sorting 2.0 milestone?

Hi @rcbevans, I am interested to know if you managed to apply some reasonable alternative approaches to support the use case you mentioned for sorting

**Comment by darrellwarde** [comment]
Definitely not abandoned, just a lot more to do first (`updateOrCreate`, root-level Interface and Union queries, etc.). And we're also more likely to implement sorting by aggregations first, as that has more utility than this. So don't expect anything too soon on this!

**Comment by MichaelCDormann** [comment]
Hi @darrellwarde, just wondering if this is still not abandoned. This would be a great feature to be able to use. 

Currently if I need sorting on related node properties I have to give up on pagination, get all results, and sort on the client side. Curious if anyone has any better solutions.

**Comment by saurav213** [comment]
Hi @darrellwarde 
Just wanted to know if this feature is still being developed?

We have a use case where we have to sort based on the properties of nested node in rich relationship.
It would be great if we have this feature.
Thanks

**Comment by darrellwarde** [comment]
Given that we are removing support for 1:1 relationships in Version 7 and that is the only type of relationship field you could feasibly sort by, this feature request is being closed.

**Comment by helorem** [comment]
Hi @darrellwarde 

I do not understand your last comment.

The example is a n:1 relationship, not a 1:1. A movie has one publisher but a publisher has many movies.

In that case, how can I sort movies by publisher name ?

Is a rewriting needed for the example ? In that case can you show it because I did not found any guidelines to solve this issue.

Thanks
