### ISSUE TITLE
Unions / Interfaces at top level

### ISSUE THREAD

**Issue by smkhalsa** [neo4j/graphql#146]
As [mentioned](https://github.com/neo4j/graphql-tracker-temp/blob/master/introduction.md#top-level-unions), unions no longer work at the top level, and interfaces no longer work at the top level or on relationships.

This is a major issue for me, and I hope that we can find a way to maintain this functionality in the new library. I'd like to highlight several use cases that are relevant to me:

## 1. Unions for Search

Search is the canonical example for unions, and it's not clear how we can replicate this behavior without them.

```graphql
union SearchResult =
    Album
  | Song
  | Artist
  | UserPlaylist
  | FeaturedPlaylist
  | Podcast

type Query {
  Search(string: String!): [SearchResult!]!
    @cypher(
      statement: """
      CALL db.index.fulltext.queryNodes('names', $string+'~') YIELD node, score
      RETURN node
      """
    )
}
```

## 2. Interfaces on Relationships for Activity Feed

Assuming the below schema excerpt, we may want to query for all of a user's activity, ordered by `createdAt` time

```graphql
interface Activity {
  id: ID!
  createdAt: _Neo4jDateTime!
  user: User! @relation(name: "BY_USER", direction: "OUT")
}

type AudioListen implements Activity {
  id: ID!
  createdAt: _Neo4jDateTime!
  user: User! @relation(name: "BY_USER", direction: "OUT")
  audio: Audio! @relation(name: "AUDIO_LISTENED", direction: "OUT")
}

type VideoView implements Activity {
  id: ID!
  createdAt: _Neo4jDateTime!
  user: User! @relation(name: "BY_USER", direction: "OUT")
  video: Video! @relation(name: "VIDEO_VIEWED", direction: "OUT")
}

type User {
  id: ID!
  name: String
  createdAt: _Neo4jDateTime
  activity: [Activity!]! 
    @cypher(
      statement: """
        // get all activity, sorted by createdAt field
      """
    )
}
```

## 3. Top-Level Interface to Query Across Related Types

Assuming the below schema excerpt, we may wish to query across all `Audio` types.

```graphql
interface Audio {
  id: ID!
  name: String!
  url: String!
  listens: [AudioListen!]! @relation(name: "AUDIO_LISTENED", direction: "IN")
}

type Song implements Audio {
  id: ID!
  name: String!
  url: String!
  artists: [Artist!]! @relation(name: "BY_ARTIST", direction: "OUT")
  albums: [Album!]! @relation(name: "HAS_SONG", direction: "IN")
  listens: [AudioListen!]! @relation(name: "AUDIO_LISTENED", direction: "IN")
}

type Podcast implements Audio {
  id: ID!
  name: String!
  url: String!
  host: User!
  listens: [AudioListen!]! @relation(name: "AUDIO_LISTENED", direction: "IN")
}
```

Each of these works fine with the existing `neo4j-graphql-js` package. I would advocate strongly for ensuring that these and similar use cases can be easily implemented with the new package.

**Comment by smkhalsa** [comment]
@danstarns Any update on this? I see that v1.0 is now live, and this is one of the few issues preventing me from migrating from the old lib.

**Comment by danstarns** [comment]
Hi @smkhalsa. Still no change, sorry to hear it's blocking your migration.

**Comment by smkhalsa** [comment]
@danstarns is this actively being worked on? Can you give an estimated timeline?

**Comment by danstarns** [comment]
@smkhalsa We are not actively working on this, it's being put aside until we come to a solution for relationship properties and relay, as we think there is going to be overlap with interfaces.

**Comment by Pitchlab** [comment]
@danstarns you stated "As it stands, on fields, you can use Unions" -- can you please point to a working example of such a union on a field? Then at least there is a way to work around this issue.

**Comment by danstarns** [comment]
> @danstarns you stated "As it stands, on fields, you can use Unions" -- can you please point to a working example of such a union on a field? Then at least there is a way to work around this issue.

Hi. Specifically, you can use Unions on a `@relationship` field. There is an example here https://neo4j.com/docs/graphql-manual/current/type-definitions/unions-and-interfaces/. Sorry, there is not a solution and we realise the need for the requested. Once relationship properties are in we can dive deeper into this.

**Comment by MarcH1000** [comment]
Hi,
 I have a use case where it’s practical to group classes/nodes into a super-class or even within a hierarchical tree. However, I have seen that multiple labels are not recommended for such relationships and even « is-a » relationship with caution (https://community.neo4j.com/t/graph-modeling-labels/27690 ). 
The author prefers unions (https://neo4j.com/docs/graphql-manual/current/type-definitions/unions-and-interfaces/ ), which is also advised by Danstarns in the current thread. But you don’t always remember all members of a union. According to what I see in this last post, there was no attribute inheritance in the former « Interface » anyway. 
Danstarns also suggests to use the @cypher directive. Could you please point to an example ? 
Besides, in a webinar dedicated to data science this afternoon, I saw a « part-of-group » relationship. Could it better fit than the former options ? More over, there are classification algorithms in GDS. How does Neo4J handle the resulting classes ?

**Comment by smkhalsa** [comment]
> Sorry, there is not a solution and we realise the need for the requested. Once relationship properties are in we can dive deeper into this.

@danstarns Now that relationship properties have shipped (awesome work!) in v2, can you provide any update on interfaces on using interfaces at top level / in relationships?

**Comment by darrellwarde** [comment]
Hey @smkhalsa, we're about to shape up the work for some or all of:

- Top-level unions
- Top-level interfaces
- Relationship interface fields

Unlikely we'll start work on all of these straight away, so we're going to have to make a judgement call on what's going to be most valuable at this stage. 🙂

**Comment by smkhalsa** [comment]
@darrellwarde that's great news 🎉. Thank you!

My vote would be to start with relationship interface fields.

**Comment by dmoree** [comment]
@darrellwarde If you’re looking for community feedback on this I would vote along with @smkhalsa for relationship interface fields

**Comment by darrellwarde** [comment]
100% keen for community feedback on this - I encourage all to voice their opinion!

**Comment by adley-kim** [comment]
@darrellwarde any updates on the status of top-level unions/interfaces? They feel necessary for returning search results that span multiple node types. I'm eager to migrate away from neo4j-graphql-js, but I don't think I'll be able to until they're supported.

**Comment by danstarns** [comment]
Field level interfaces have been released in 2.4.0 and are available on npm. Top-level is something we are still planning and shaping.

**Comment by nelsonpecora** [comment]
Hey folks! I was wondering if there's been any update on top-level interfaces? We've got a few use cases that I can't figure out good workarounds to, and it would be super helpful if we had autogenerated queries and mutations for them. For example, given this schema:

```graphql
interface Content {
  id: ID!
  name: String @ignore
}

type Image implements Content {
  id: ID!
  name: String @ignore(dependsOn: ["altText"])
  url: String
  altText: String
}

type Post implements Content {
  id: ID!
  name: String @ignore(dependsOn: ["title"])
  text: String
  title: String
}
```

Currently, there are no queries or mutations that are generated for them, so we'd have to query or mutate `Image` or `Post` records separately. This requires quite a bit of application code, especially once you have more than 3 or 4 different types of `Content`. I looked into writing my own queries using `@cypher` and calling the `OGM` directly, and both have downsides.

* `@cypher` - like others have mentioned, these are hardcoded queries, so we wouldn't be able to handle different selection sets in different requests. We could try and fetch _everything_, but our data model has many-to-many `Content` relations that might have arbitrary depth, and I'm not sure how to handle that with this approach (plus, even if it's possible, that's a whole lot of data on every request, especially if the actual selection set ends up being small)
* `OGM` - we can't call `ogm.model()` on interfaces (which makes sense, I think), but that means doing a query against every possible `Content` type. Even so, you can pass a request's selection set into an OGM model's `.find()` method, until you try to fetch a field with `@ignore(dependsOn)` or `@cypher` in the schema, which throws an error (I think because OGM doesn't know about all of the stuff `@neo4j/graphql` knows about)

**Comment by dmoree** [comment]
@nelsonpecora I saw your comment and looked at it again. I didn't look at it for too long, but the initial work is here:
https://github.com/neo4j/graphql/compare/dev...dmoree:feature/top-level-union-interface

Those are minimal changes to get queries working where full text in unions can be used on those that have them, but quickly you'll realize that interfaces are treated differently. They are only relevant if they are used in a `@relationship`. Maybe I'm missing something, but you can take a look.

Also, how would you envision mutations working? Queries I think can be readily done if things were reworked, interfaces in particular.

**Comment by bjoernpy** [comment]
Any updates or workaround for top-level interface queries?

**Comment by ZhongYic00** [comment]
Any updates for top-level interface queries? I see multiple branches industriously developed by @a-alle and some PRs merged, such as #4061.
Would it be released soon? 🥰🥰

**Comment by darrellwarde** [comment]
As you've seen, feature development is well underway! They are currently hidden under an `experimental` flag that we've introduced, so not ready for production use yet, but you can play around with them if you like! Feedback is appreciated.

**Comment by mc-luisg** [comment]
Hi 🐱 
Im currently looking into this but I noticed that the experimental is no longer supported. Is there any update or release for this?

**Comment by darrellwarde** [comment]
Sorry for the radio silence here! @ZhongYic00, @mc-luisg, as I hope you may have noticed by now, top-level queries for interfaces have been available for some time now by default in the Neo4j GraphQL Library. We are not going to implement top-level queries for unions as we feel these have no utility (the union members can just be queried individually given there is no shared fields, etc.), so closing this issue as complete!
