### ISSUE TITLE
Dependency conflict between @neo4j/graphql and graphql-parse-resolve-info

### ISSUE THREAD

**Issue by NilsMoller** [neo4j/graphql#1467]
**Describe the bug**
`@neo4j/graphql` has a `peerDependency` on `"graphql": "^16.0.0"`  
`@neo4j/graphql` has a `dependency` on `"graphql-parse-resolve-info": "^4.12.0"`  
`graphql-parse-resolve-info` has a `peerDependency` on `"graphql": ">=0.9 <0.14 || ^14.0.2 || ^15.4.0"`  
  
This means the package can not be installed.

**To Reproduce**
1. Create a new Node project: `npm init --yes`
2. Install @neo4j/graphql: `npm install @neo4j/graphql`
3. See errors

**Expected behavior**
All dependencies can work with each other, making the package usable.

**System (please complete the following information):**

* OS: Windows 10 Pro
* Version: @neo4j/graphql@3.2.3
* Node.js version: 16.14.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @NilsMoller. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Are you sure that the dependency doesn't work at all @NilsMoller? We're aware of this, but it should just be a warning and be 100% compatible.

**Comment by darrellwarde** [comment]
We run all of our test framework against both 15 and 16, so we have quite high confidence! I'll close this for now.
