### ISSUE TITLE
how about Recurse Query

### ISSUE THREAD

**Issue by AnsonHwang86** [neo4j/graphql#1491]
**Is your feature request related to a problem? Please describe.**
how about recurse Query

**Describe the solution you'd like**
Say I have schema
```
Type Category{
  id: ID @id
  parentCategory: Category (type:"xxx", direction:OUT)
  childCategory: Category (type:"mmm", direction: OUT)
}
```

**Describe alternatives you've considered**
There is maybe serveral lever of Category, such as 3lever: Appliances -> Dishwashers -> Countertop Dishwashers.
something we maybe have 4lever or 5. 
If there is some directive support Recurse Query it would fine.

so we can query all the parentCategory and childCategory in one Query in any deep of lever.

**Additional context**

**Comment by darrellwarde** [comment]
I think the ask here is essentially variable length relationship matching, which is covered in quite an old issue #596. So will close this one as a duplicate.
