### ISSUE TITLE
Performance: Aggregate{count} results in database contention

### ISSUE THREAD

**Issue by tbwiss** [neo4j/graphql#1505]
**Describe the bug**

Performance issue.
This was raised in a Trello card with the title: "Aggregate{count} results in database contention".

**Type definitions**
```graphql
type Pose {
        name: String
        published: [PublishInfo!]! @relationship(type: "WAS_PUBLISHED", direction: OUT)
}

type PublishInfo {
        name: String
}
```
**To Reproduce**

Execute this query:
```
query {
  poses {
    publishedAggregate {
      count
    }
  }
}
```
This results in the following cypher:
```cypher
MATCH (this:Pose)
RETURN this { publishedAggregate: { count: head(apoc.cypher.runFirstColumn("MATCH (this)-[r:WAS_PUBLISHED]->(n:PublishInfo)      RETURN COUNT(n)", { this: this })) } } as this
```

That results in the query log showing the inner cypher statement being run hundreds of times simultaneously and causing contention on the Aura database.

Reason:
`apoc.cypher.runFirstColumn` executes in its own context/subquery. Therefore if the database contains hundreds of `Pose` nodes it will execute `apoc.cypher.runFirstColumn("MATCH (this)-[r:WAS_PUBLISHED]->(n:PublishInfo) RETURN COUNT(n)", { this: this }` as many times as there are `Pose` nodes in the database, given the structure of the provided GraphQL query.

Improvement suggestion:
The suggestion is that it could be changed to an actual [subquery](https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/) or use something like `size((this)-[:WAS_PUBLISHED]->())`.

**Additional context**
This was raised in a Trello card with the title: "Aggregate{count} results in database contention".

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @tbwiss! :pray: We will now prioritise the bug and address it appropriately.

**Comment by process0** [comment]
Maybe related. I am experiencing very slow aggregate counts as well using a similar graphql query structure.

**Comment by process0** [comment]
Any update on this @darrellwarde ? The aggregate queries generated take a significant amount of time (30+ seconds)  to run with the generated cypher.  The custom cypher code I write as an alternative is 500ms. I would prefer not to have to write every aggregate query as a custom cypher field.

**Comment by darrellwarde** [comment]
Hey @process0, this is being worked on as we speak, and assuming no unexpected problems, a fix should be released within a couple of weeks!

**Comment by process0** [comment]
Thanks for the update! I'm happy to test

**Comment by darrellwarde** [comment]
Hey @process0, 3.6.1 should be working a lot better in this case, please do give it a try!
