### ISSUE TITLE
Toolbox: Mixed secure configuration error even when secure connection box is unchecked 

### ISSUE THREAD

**Issue by johnymontana** [neo4j/graphql#1526]
**Describe the bug**
When using the `neo4j+s` protocol in a database connection string and unchecking the "Secure Connection" button, the error message "Encryption/trust can only be configured either through URL or config, not both".

**To Reproduce**

Open GraphQL Toolbox
Use the`neo4j+s://` protocol in the connection string.
Uncheck "Secure Connection"

**Expected behavior**
Since the "Secure Connection" button is unchecked, the `neo4j+s://` protocol should be able to be used.

**Screenshots**

<img width="606" alt="Screen Shot 2022-06-05 at 6 05 58 PM" src="https://user-images.githubusercontent.com/1222454/172074621-37a441fd-60f3-4bff-b007-1d35292a2f53.png">

**Additional context**
The default Aura connection string uses `neo4j+s` when copied from the Aura console app so this will impact any users copy/pasting from Aura. I would suggest removing the "Secure Connection" box and just allowing the user to configure a secure connection through the connection string protocol, or perhaps inspecting the connection string and disabling the toggle when the user enters `neo4j+s` protocol.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @johnymontana. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @johnymontana! :pray: We will now prioritise the bug and address it appropriately.
