### ISSUE TITLE
Relay Ids not translating properly when underlying field is an integer

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#1560]
**Describe the bug**

If using the relay generated `id` in a `where` argument, and the underlying id field is an integer, the db does not find the node. This is likely due to the id being translated as a string rather an integer. 

```graphql
type Organization {
  dbId: Int! @id(autogenerate: false, global:true) @alias(property: "id")
  name: String!
}


# create an entry 

mutation {
  createOrganizations(input: [{ dbId: 12345, name: "test" }]) {
    organizations {
       # <----- make sure and request the relay id in the response
       id
       dbId
       name
     }
  }
}

# then query for the organization using the return relayId

query Organizations {
  organizations(where: { node: { id:  "id-from-above" } }) {
     id
     dbId
     name
  }
}

```

**Screenshots**

The resulting cypher renders the param as a string rather an integer, so the lookup fails. Screenshot is an example from a project -- the "affinityId" is an Int field (like the dbId above)

![image](https://user-images.githubusercontent.com/1900476/173209592-dc2fa630-57f6-4d07-9deb-09dce8b12e73.png)

**System (please complete the following information):**

* OS: mac
* Version:  3.3.0
* Node.js version:  lts/fermium

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @litewarp. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @litewarp! :pray: We will now prioritise the bug and address it appropriately.

**Comment by litewarp** [comment]
@darrellwarde heya, just wanted to point out that I submitted a PR to fix this in case you didn't see it above ☝🏾

**Comment by darrellwarde** [comment]
As always, thanks for the fix @litewarp, we're tentatively aiming for a release tomorrow!
