### ISSUE TITLE
It's possible to alias to the same name as an existing field in relationship properties

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#1575]
**Describe the bug**

It's possible to alias to the same name as an existing field

**Type definitions**

The following should really throw an error. 

```graphql
type Foo {
  point: Point
  geo_point: Point @alias(property: "point")
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @darrellwarde. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.

**Comment by a-alle** [comment]
Node properties fixed in https://github.com/neo4j/graphql/pull/2200.
Relationship properties still TODO.

**Comment by angrykoala** [comment]
This has already been fixed, some tests confirming this behaviour in #5794
