### ISSUE TITLE
Query as an @auth option

### ISSUE THREAD

**Issue by tlester** [neo4j/graphql#159]
**Is your feature request related to a problem? Please describe.**
As a developer, I need to have a flexible option validate date as a condition for authenticity.

**Describe the solution you'd like**
I would like to have an option to have a rule called "query" who's value is a graphql query.  The query is evaluated just as any other query as a condition.  If the condition is true, then the operation is authenticated.   

```gql
@auth(rules: [{                         // Authenticated
    operations: [CREATE],
    isAuthenticated: true,
    query: {
        match: "bob",
        gql:  `users(where: {name: "bob"}) { name }`
    }
}]) 

@auth(rules: [{                         // NOT Authenticated
    operations: [CREATE],
    isAuthenticated: true,
    query: {
        match: "allen",
        gql:  `users(where: {name: "bob"}) { name }`
    }
}])

const myAuthQuery = gql`
    users(where: {
        name: "bob"
    }) {
        name
    }
`

@auth(rules: [{                         // Authenticated
    operations: [CREATE],
    isAuthenticated: true,
    query: {
        match: "bob",
        gql: myAuthQuery 
    }
}])

@auth(rules: [{                         // Authenticated
    operations: [CREATE],
    isAuthenticated: true,
    query: {
        match: "bob",
        cypher: "MATCH (u:User {name: "bob"}) return u.name"
    }
}])


@auth(rules: [{                         // NOT Authenticated
    operations: [CREATE],
    isAuthenticated: true,
    query: {
        match: "allen",
        cypher: "MATCH (u:User {name: "bob"}) return u.name"
    }
}])
```

**Describe alternatives you've considered**
I have implemented on the client by calling similar queries as validation, but that still potentially leave the endpoint compromised, or I have to limit application functionality.

**Additional context**
Nope... just the code example above.   PS... this is a direct functionality lift of another graphq DB's graphql solution.

**Comment by danstarns** [comment]
Hey @tlester thanks for subbmitng your idea! Im struggling to get the concept do you have any more examples or info ? Given the below: 

```graphql

type User {
  name: String
}

extend type User @auth(rules: [{ 
    operations: [CREATE],
    isAuthenticated: true,
    query: {
        match: "allen",
        gql:  `users(where: {name: "bob"}) { name }`
    }
}])
```

Then someone performs a `CREATE` operation: 

```
mutation {
  createUsers(input: [{ name: "SOME NAME" }]) {
    users {
      name
    }
  }
}
```

Where and how does the below `query` bit get incorporated with this mutation? 

```
query: {
        match: "allen",
        gql:  `users(where: {name: "bob"}) { name }`
    }
```

**Comment by darrellwarde** [comment]
> I need to have a flexible option validate date as a condition for authenticity.

I find myself especially intrigued by this use case, an example of how and where you might use this could really provide some clarity here.

**Comment by bloomdido** [comment]
@tlester Would my suggested feature #163 satisfy your needs? The `@cypher` directive can already handle parameters, and you'd have full access to the power of Cypher (not just GraphQL) in determining the conditions for your validation.

**Comment by jacob-buscher** [comment]
> > I need to have a flexible option validate date as a condition for authenticity.
> 
> I find myself especially intrigued by this use case, an example of how and where you might use this could really provide some clarity here.

@darrellwarde 

This would be especially useful in places where you need tenant based auth, if you have numerous "organizations" and "suborganizations" and you want to have [RBAC](https://neo4j.com/docs/graphql-manual/current/auth/authorization/roles/#_rbac) style roles 

Something like `${teamId}:admin`, `${teamId}:owner`, `${teamId}:guest` where `teamId` is populated from based on the query.

I'm having a hard time using the `@auth` directive to make tenant based roles and permissions. I believe this is possible with `allow` but my rules are looking way more complex than I think they should.

I go into a bit of detail about [my use case](https://github.com/neo4j/graphql/issues/163#issuecomment-873151656) in #163

**Comment by darrellwarde** [comment]
This is not something we're ever going to do - auth is a big enough beast as it is and is overdue a much needed refactor, but GraphQL within a directive definitely won't be a part of it - far too meta!! 😆 In the interest in making _some_ progress on the feature backlog, closing this one.
