### ISSUE TITLE
Field must be included in selection set when sorting in a nested selection

### ISSUE THREAD

**Issue by johnymontana** [neo4j/graphql#160]
**Describe the bug**

When sorting a nested selection the ordering is not applied if the field used for ordering is not included in the selection set. Sorting works as expected when the field is included in the selection set.

**Type definitions**

This [Codesandbox](https://codesandbox.io/s/priceless-pasteur-d92b3) can be used to demonstrate the issue.

**To Reproduce**

This query (note that `year` is not included in the `acted_in` selection set:

```GraphQL
{
  movies(where: { title_CONTAINS: "Matrix Reloaded, The" }) {
    title
    actors(options: { limit: 1 }) {
      name
      acted_in(options: { limit: 3, sort: { year: DESC } }) {
        title
      }
    }
  }
}
```

produces this result:

```json
{
  "data": {
    "movies": [
      {
        "title": "Matrix Reloaded, The",
        "actors": [
          {
            "name": "Keanu Reeves",
            "acted_in": [
              {
                "title": "Matrix Reloaded, The"
              },
              {
                "title": "Side by Side"
              },
              {
                "title": "Matrix Revolutions, The"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

however, when `year` is included in the selection set:

```GraphQL
{
  movies(where: { title_CONTAINS: "Matrix Reloaded, The" }) {
    title
    actors(options: { limit: 1 }) {
      name
      acted_in(options: { limit: 3, sort: { year: DESC } }) {
        title
        year
      }
    }
  }
}
```

then ordering of the `acted_in` array is properly sorted in the result:

```json
{
  "data": {
    "movies": [
      {
        "title": "Matrix Reloaded, The",
        "actors": [
          {
            "name": "Keanu Reeves",
            "acted_in": [
              {
                "title": "The Neon Demon",
                "year": 2016
              },
              {
                "title": "John Wick",
                "year": 2014
              },
              {
                "title": "47 Ronin",
                "year": 2013
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Expected behavior**

I expect ordering to be applied to the nested field even if the field used to order is not included in the selection set.

**System (please complete the following information):**

-   Version:  @neo4j/graphql@1.0.0-beta.2

**Comment by danstarns** [comment]
@johnymontana Thanks for the clarity and steps to reproduce I can produce this locally also.

**Comment by danstarns** [comment]
Digging deeper - If we take the query that's failing: 

```graphql
{
  movies(where: { title_CONTAINS: "Matrix Reloaded, The" }) {
    title
    actors(options: { limit: 1 }) {
      name
      acted_in(options: { limit: 3, sort: { year: DESC } }) {
        title
      }
    }
  }
}
```

The cypher produced is: 

```cypher
MATCH (this:Movie)
WHERE this.title CONTAINS $this_title_CONTAINS

RETURN this {
  .title, 
  actors: [ (this)<-[:ACTED_IN]-(this_actors:Actor) | this_actors { 
      .name, 
      acted_in: apoc.coll.sortMulti([ (this_actors)-[:ACTED_IN]->(this_actors_acted_in:Movie) | this_actors_acted_in { .title } ], ['year'])[..3] 
  } ][..1] 
} AS this
```
Looking at what `neo4j-graphql-js` does... We should still project the property so it can be sorted on:


```diff
MATCH (this:Movie)
WHERE this.title CONTAINS $this_title_CONTAINS

RETURN this {
  .title, 
  actors: [ (this)<-[:ACTED_IN]-(this_actors:Actor) | this_actors { 
      .name, 
-     acted_in: apoc.coll.sortMulti([ (this_actors)-[:ACTED_IN]->(this_actors_acted_in:Movie) | this_actors_acted_in { .title } ], ['year']),
+     acted_in: apoc.coll.sortMulti([ (this_actors)-[:ACTED_IN]->(this_actors_acted_in:Movie) | this_actors_acted_in { .title, .year } ], ['year'])
[..3] 
  } ][..1] 
} AS this
```

 This does mean that on particular usages, such as this issue raised, we are selecting a field that is not asked for and relying on the GraphQL runtime to filter out that field.

**Comment by johnymontana** [comment]
Right, it's an unfortunate consequence of using `apoc.coll.sortMulti` as a post-processing step of the pattern comprehension. If the Cypher pattern comprehension supported ordering then the additional field wouldn't need to be selected and the database would just take care of it. There's an outstanding card to add this functionality [here](https://trello.com/c/hPw7MesW/295-improvement-request-allow-distinct-limit-order-by-and-skip-in-pattern-comprehensions), perhaps worth pinging with this example as another use case where it would make sense to add to Cypher?
