### ISSUE TITLE
Relationships with a cardinality of [1-n]

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#1624]
**Is your feature request related to a problem? Please describe.**
It is currently possible to define relationships with the following cardinalities using the relationship directive:

````gql
type Movie {
  genre: Genre @relationship(type: "HAS_GENRE", direction: OUT) #Cardinality: [0-1]
  genre: Genre! @relationship(type: "HAS_GENRE", direction: OUT) #Cardinality: [1-1]
  genres: [Genre!]! @relationship(type: "HAS_GENRE", direction: OUT) #Cardinality: [0-n]
  #How do we create a cardinality of [1-n]?
}
````

**Describe the solution you'd like**
We need a way to create relationships with a cardinality of [1-n].
For example, we want to create objects of type Movie and Genre. A movie can have multiple genres and should have at least one genre.

**Additional context**
It might be interesting if you can create any cardinalities such as [2-2] -> A movie should have exactly two genres.

**Comment by darrellwarde** [comment]
Our general attitude towards relationship cardinality enforcement is to only support constraints supported by the Neo4j database itself. The Cypher for the existing checks we do is horrendous and we don't to build upon this any more. Closing, but hopefully we can support native database features in the future.
