### ISSUE TITLE
Sub-graph data isolation for multi-tenancy support 

### ISSUE THREAD

**Issue by aurlien** [neo4j/graphql#168]
**Is your feature request related to a problem? Please describe.**
I would like a way to support data isolation across multiple projects in a single database. My concrete use case is to be able to support multiple "tenants" with their own schemas on a single Neo4j Aura instance. 

**Describe the solution you'd like**
In `neo4j-graphql-js` there is the [`@additionalLabels`](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization/#additionallabels) directive, which adds the option to inject extra labels on both queries and mutations. Using this I can add a `tenant-id` as an additional label, which gives me the data isolation I need. 

**Describe alternatives you've considered**
 1. Data isolation using [multiple databases](https://neo4j.com/developer/manage-multiple-databases/)
 This is an option that is (mostly) supported in the `neo4j-graphql-js` library. However, Neo4j aura does not support this 
 feature. We have also experienced performance issues with this approach when using a large number of databases.
 
 2. Data isolation using multiple neo4j aura instances
 This solution is not practically possible today, as there is no way to programmatically manage neo4j aura instances. It will also introduce a lot of extra overhead to have to manage all the instances, and it increases the cost significantly.

**Comment by danstarns** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Pitch] Additional Labels](https://trello.com/c/ygNrBdnT/12-pitch-additional-labels)

**Comment by bauerflo77** [comment]
We also need the  @additionalLabels functionality again (or something with the same features) to divide sub-graphs.

**Comment by oskarhane** [comment]
> We also need the @additionalLabels functionality again (or something with the same features) to divide sub-graphs.

This has been merged and will be in the next release: https://github.com/neo4j/graphql/pull/475
