### ISSUE TITLE
Wrong output for aggregations using connection fields

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#1685]
**Describe the bug**
Wrong output for aggregations using connection fields.

**Type definitions**
```graphql
interface Production {
  id: ID
  title: String
}

type Movie implements Production {
  id: ID
  title: String
  actorCount: Int
  genres: [Genre!]! @relationship(type: "HAS_GENRE", direction: OUT)
}

type Genre {
  name: String
  movies: [Production!]! @relationship(type: "HAS_GENRE", direction: IN)
}
```
**To Reproduce**

With the following dataset:
```
 CREATE (c:Movie { id: "1", title: "Matrix" })-[:HAS_GENRE]->(:Genre { id: "10", name: "Sci-fi" })
 CREATE (c)-[:HAS_GENRE]->(g2:Genre { id: "11", name: "Action" })
 CREATE (h:Movie { id: "2", title: "The Hobbit" })-[:HAS_GENRE]->(g3:Genre { id: "12", name: "Fantasy" })
```

Trying to find all the genres related to movies with also "Action" as a genre, with the following query:
```graphql
query Genres{
  genres {
    moviesConnection(where: {
    "node": {
      "_on": {
        "Movie": {
          "genresConnection_SOME": {
            "node": {
              "name": "Action"
            }
          }
        }
      }
    }
  }) {
      totalCount
    }
    name
  }
}
```

it obtains the following result:

```graphql
{
  "data": {
    "genres": [
      {
        "moviesConnection": {
          "totalCount": 1
        },
        "name": "Sci-fi"
      },
      {
        "moviesConnection": {
          "totalCount": 1
        },
        "name": "Action"
      },
      {
        "moviesConnection": {
          "totalCount": 1
        },
        "name": "Fantasy"
      }
    ]
  }
}
```

**Expected behavior**
As the genre "Fantasy" in the dataset does not have any movies related with the "Action" genre I expect the following output:
```graphql
{
  "data": {
    "genres": [
      {
        "moviesConnection": {
          "totalCount": 1
        },
        "name": "Sci-fi"
      },
      {
        "moviesConnection": {
          "totalCount": 1
        },
        "name": "Action"
      },
      {
        "moviesConnection": {
          "totalCount": 0
        },
        "name": "Fantasy"
      }
    ]
  }
}
```

**System (please complete the following information):**

* OS: [e.g. macOS]
* Version: [e.g. @neo4j/graphql@3.5.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
Added tests that cover this issue in the PR #1692 .

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
