### ISSUE TITLE
Simple connection query with `totalCount` fails.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#1686]
**Describe the bug**
Simple connection query with `totalCount` fails.

**Type definitions**
```graphql
interface Production {
    id: ID
    title: String
}
type Movie implements Production {
    id: ID
    title: String
    actorCount: Int
    genres: [Genre!]! @relationship(type: "HAS_GENRE", direction: OUT)
}

type Genre {
  name: String
  movies: [Production!]! @relationship(type: "HAS_GENRE", direction: IN)
}
```

**Dataset**
```
 CREATE (c:Movie { id: "1", title: "Matrix" })-[:HAS_GENRE]->(:Genre { id: "10", name: "Sci-fi" })
 CREATE (c)-[:HAS_GENRE]->(g2:Genre { id: "11", name: "Action" })
 CREATE (h:Movie { id: "2", title: "The Hobbit" })-[:HAS_GENRE]->(g3:Genre { id: "12", name: "Fantasy" })
```

**To Reproduce**
Querying the movieConnection and select only the `totalCount` fails.
```graphql
query MoviesConnection {
  moviesConnection {
    totalCount
  }
}
```

**Expected behavior**
Should returns the correct `totalCount` also if no other properties are returned.

**System (please complete the following information):**

* OS: [e.g. macOS]
* Version: [e.g. @neo4j/graphql@3.5.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
Added tests that cover this issue in the PR #1692 .

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
