### ISSUE TITLE
Filtering using connection fields could fails.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#1687]
**Describe the bug**
Filtering using connection fields could fails.

**Type definitions**
```graphql
interface Production {
    id: ID
    title: String
}
type Movie implements Production {
    id: ID
    title: String
    actorCount: Int
    genres: [Genre!]! @relationship(type: "HAS_GENRE", direction: OUT)
}

type Genre {
  name: String
  movies: [Production!]! @relationship(type: "HAS_GENRE", direction: IN)
}
```

**Dataset**
```
 CREATE (c:Movie { id: "1", title: "Matrix" })-[:HAS_GENRE]->(:Genre { id: "10", name: "Sci-fi" })
 CREATE (c)-[:HAS_GENRE]->(g2:Genre { id: "11", name: "Action" })
 CREATE (h:Movie { id: "2", title: "The Hobbit" })-[:HAS_GENRE]->(g3:Genre { id: "12", name: "Fantasy" })
```

**To Reproduce**
Trying to query all the genres related to the movie "The Matrix", using connection fields, fails:
```graphql
query Genres {
  genres(where: {
    moviesConnection_ALL: {
      node: {
        _on: {
          Movie: {
            title: "The Matrix"
          }
        }
      }
    }
  }) {
    name
  }
}
```

**Expected behavior**
Should return all the genres connected to the movie "The Matrix".

**System (please complete the following information):**

* OS: [e.g. macOS]
* Version: [e.g. @neo4j/graphql@3.5.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
Added tests that cover this issue in the PR #1692 .
