### ISSUE TITLE
InterfaceConnection not working when interface property is in query

### ISSUE THREAD

**Issue by bjoernpy** [neo4j/graphql#1690]
**Describe the bug**
If one has a type with an interface as property and queries the type, the interfaceConnection does not work when the interface itself is also inside the query.

**Type definitions**
```
type User {
  username: String!
  posts: [Post!]! @relationship(type: "HAS_POST", direction: OUT)
}

interface Post {
  title: String!
  author: User! @relationship(type: "HAS_POST", direction: IN)
}

type Query {
  // Works
  users(where: $where) {
    username
    postsConnection {
      totalCount
    }
  }

  // Does not work
  users(where: $where) {
    username
    postsConnection {
      totalCount
    }
    posts {
      title
    }
}
```

**To Reproduce**

1. Have a graphQL definition with an interface as property.
2. Execute a query with the interface property and the interfaceConnection property.
3. Error: "message": "Variable `postsConnection` not defined (line 51, column 26 (offset: 2448))\n\"RETURN this { .username, postsConnection, posts: posts } as this\"\n                          ^".

**Expected behavior**
The posts and the postsConnection property should be resolved.

**System (please complete the following information):**

* OS: WSL Ubuntu
* Version: @neo4j/graphql@3.5.0
* Node.js version: 16.14.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @bjoernpy. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by litewarp** [comment]
Is there a reason you need to query both the interface AND the interface connection? The connection should return all the information of the interface type plus the connection information. 

Just trying to think through a use case for this.

**Comment by litewarp** [comment]
So a "connection" will contain both the totalCount and the actual data (the "edges"). So for a connection you can query like below and then paginate using the cursor information (a la [Relay](https://www.apollographql.com/blog/graphql/explaining-graphql-connections/))

```graphql
query {
  users(where: $where) {
    postsConnection {
      totalCount
      edges {
        cursor
        node {
          title
        }
     }
  }
}
```

If you wanted to use the limit/offset pagination on the regular posts field and not the connection, you should query the postsAggregate field to get the count like below:

```graphql
query {
  users(where: $where) {
   posts {
      title
    }
    postsAggregate {
      count
    }
  }
}
```

**Comment by bjoernpy** [comment]
Thank you for all the information. The later example does not work because there is not postsAggreagate Field generated. I split the queries into two parts and resolve all the information about the user and the amount of posts. Then I paginate through the posts with a different query. The amount of implementations of the interface is resolved with the implementaitonAggregate and a where clause. Is there a nicer way to do this? Here is my final solution. Thank you for your help. Will close the isssue after this.

```
query {
  users(where: ...) {
    username
    postsConnection {
      totalCount
    }
  }
  articlesAggregate(where: ...) {
    count
  }
  linksAggregate(where: ...) {
    count
  }
}
```
