### ISSUE TITLE
OGM Auto Generated TypeScript 

### ISSUE THREAD

**Issue by danstarns** [neo4j/graphql#174]
**Is your feature request related to a problem? Please describe.**
As a user of the OGM, I would like to see autogenerated typescript types. Currently, I have to use generics and cross-check with the GraphQL API. 

**Describe the solution you'd like**
A script I can call to produce typings for the OGM. 

**Additional context**
Please express interest in this issue so we can gauge demand.

**Comment by TreeMan360** [comment]
I would definitely benefit from this feature. Thumbs up from me 👍
