### ISSUE TITLE
Leading . character is causing zero results for a full-text query

### ISSUE THREAD

**Issue by CraigDeverall** [neo4j/graphql#1744]
Sending a string with a leading . character is returning zero results for a full-text query. 
It returns the expected results if the . character is not leading in the string.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @CraigDeverall. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @CraigDeverall, thanks for reaching out!
Would you be able to provide some more information and details? For instance the type definitions you used and how you used the full-text directive as well as the GraphQL query you applied?
Thank you!

**Comment by CraigDeverall** [comment]
**GraphQL Schema**
`type User @fulltext(indexes: [{ name: "UserName", fields: ["name"] }]) {
  id: ID! @unique
  name: String!
}
`

**Database Data**
`UNWIND ['.Net', '.Potatoe', 'Nanny'] as x
CREATE (n:User) set n.name = x set n.id = apoc.create.uuid()
return n`

**GraphQL Query:**

`query Users($fulltext: UserFulltext) {
  users(fulltext: $fulltext) {
    id
    name
  }
}`

**Variables**
`{
  "fulltext": {
    "UserName": {
      "phrase": ".Ne*"
    }
  }
}`


> You will see that .Net is not returned when I expected it should. If you remove the "." it returns as expected.

**Comment by tbwiss** [comment]
Thanks for the updates @CraigDeverall. Sorry for the delay here.
Are you required to use the wildcard search (`*`)? Would you also be able to use a fuzzy search (`~`)?
Background: The [fulltext index of Neo4j ](https://neo4j.com/docs/cypher-manual/current/indexes-for-full-text-search/#administration-indexes-fulltext-search-drop) uses Apache Lucene under the hood. Apache Lucene has multiple [term modifiers](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), using the fuzzy search (f.e. `.Ne~`) it returns the `.Net` node as you would expect. Would this help in your specific case?

**Comment by CraigDeverall** [comment]
Thanks for the tip @tbwiss. I think my best work around or perhaps a better solution for my use case is to use regex rather than fulltext. The index is just for fullNames. I had the requirement to search by any word of the name. Fulltext with wild card gave me that functionality but I think I can achieve the same with regex. Fuzzy search is perhaps better suited to larger blocks of text? While results were found the ordering was not what I was aiming for for this use case.
