### ISSUE TITLE
Issue with nested delete operation relying on connectionAggregate count

### ISSUE THREAD

**Issue by teenkevo** [neo4j/graphql#1751]
**Describe the bug**

Let's say 
1. I have an application database which has multiple organizations. 
2. Each organization has its own admins. 
3. An admin can belong to multiple organizations as shown in the figure below.  

![image](https://user-images.githubusercontent.com/46814008/175792832-0371817b-e476-4524-94e4-448200df2d6c.png)

While deleting an organization, I would like to delete the organization together with its administrators as long as they don't participate in any other organization. 

In the mutation below, I try to delete the organization Google together with its admin(un named node). The other admins connected to Google (Mugukey and Mugumya) should not be deleted but only disconnected from Google. 

**Type definitions**

```graphql
type Organization {
    organizationId: ID! @id
    title: String
    createdAt: DateTime!
    admins: [Admin!]! @relationship(type: "HAS_ADMINISTRATOR", direction: OUT)
}

type Admin {
    adminId: ID! @id
    createdAt: DateTime!
    isSuperAdmin: Boolean
}
```

**To Reproduce**
Exexute this mutation

_Mutation_
```graphql
mutation DeleteOrganizations($where: OrganizationWhere, $delete: OrganizationDeleteInput) {
  deleteOrganizations(where: $where, delete: $delete) {
    nodesDeleted
    relationshipsDeleted
  }
}
```
_Variables_
```graphql
{
  "where": {
    "title": "Google"
  },
  "delete": {
    "admins": [
      {
        "where": {
          "node": {
            "organizationsAggregate": {
              "count": 1
            }
          }
        }
      }
    ]
  }
}
```
Upon running the operation above only the organization node Google gets deleted, and 3 relationships (1 from each of the admins)

**Expected behavior**
Deletion of the organization Google, deletion of the unnamed admin node attached to it, and deletion of the 3 relationships(1 from each of the attached admins).

**System**

* OS: [ Windows]
* Version: [@neo4j/graphql@^3.3.0]
* Node.js version: [v14.17.4]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @teenkevo. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @teenkevo! :pray: We will now prioritise the bug and address it appropriately.

**Comment by mjfwebb** [comment]
With the given type definitions and mutation we are generating incorrect Cypher.

_types_
```gql
typeDefs = gql`
    type Organization {
        organizationId: ID! @id
        title: String
        createdAt: DateTime!
        admins: [Admin!]! @relationship(type: "HAS_ADMINISTRATOR", direction: OUT)
    }

    type Admin {
        adminId: ID! @id
        createdAt: DateTime!
        isSuperAdmin: Boolean
        organizations: [Organization!]! @relationship(type: "HAS_ADMINISTRATOR", direction: IN)
    }
`;
```

_mutation_
```gql
const query = gql`
    mutation DeleteOrganizations($where: OrganizationWhere, $delete: OrganizationDeleteInput) {
        deleteOrganizations(where: $where, delete: $delete) {
            nodesDeleted
            relationshipsDeleted
        }
    }
`;
```

_variables_
```ts
const variableValues = {
    where: {
        title: "Google",
    },
    delete: {
        admins: [
            {
                where: {
                    node: {
                        organizationsAggregate: {
                            count: 1,
                        },
                    },
                },
            },
        ],
    },
};
```

Current Cypher:
```cypher
            "MATCH (this:\`Organization\`)
            WHERE this.title = $param0
            WITH this
            OPTIONAL MATCH (this)-[this_admins0_relationship:HAS_ADMINISTRATOR]->(this_admins0:Admin)
            WHERE EXISTS { (this_admins0)<-[:HAS_ADMINISTRATOR]-(this_admins0_organizations:Organization) WHERE this_admins0_organizations.count = $this_deleteOrganizations.args.delete.admins[0].where.node.organizations.count }
            WITH this, collect(DISTINCT this_admins0) as this_admins0_to_delete
            FOREACH(x IN this_admins0_to_delete | DETACH DELETE x)
            DETACH DELETE this"
```

Instead, we should be generating Cypher like this:
```cypher
            "MATCH (this:\`Organization\`)
            WHERE this.title = $param0
            WITH this
            OPTIONAL MATCH (this)-[this_admins0_relationship:HAS_ADMINISTRATOR]->(this_admins0:Admin)
            WHERE apoc.cypher.runFirstColumn(\\" MATCH (this_admins0)<-[aggr_edge:HAS_ADMINISTRATOR]-(aggr_node:Organization)
            RETURN count(aggr_node) = $aggr_count
            \\", { this_admins0: this_admins0, aggr_count: $this_deleteOrganizations.args.delete.admins[0].where.node.organizationsAggregate.count }, false )
            WITH this, collect(DISTINCT this_admins0) as this_admins0_to_delete
            FOREACH(x IN this_admins0_to_delete | DETACH DELETE x)
            DETACH DELETE this"
```

Notes:

- The `WHERE EXISTS` is replaced by a `WHERE apoc.cyphyer.runFirstColumn`
- `$this_deleteOrganizations.args.delete.admins[0].where.node.organizations.count` is corrected to `$this_deleteOrganizations.args.delete.admins[0].where.node.organizationsAggregate.count`

**Comment by mjfwebb** [comment]
A failing tck test has been created https://github.com/mjfwebb/graphql/tree/1751

**Comment by angrykoala** [comment]
Confirmed to still be happening on 3.6.1
