### ISSUE TITLE
connectOrCreate does not automatically generate properties that have a @callback directive

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#1756]
**Describe the bug**
In the onCreate block of connectOrCreate, parameters are expected that should actually be generated via the callback directive.

**Type definitions**
````gql
interface INode {
  id: ID! @callback(operations: [CREATE], name: "nanoid")
}

type Product implements INode {
  id: ID!
  name: String!
  genre: [Genre!]! @relationship(type: "HAS_GENRE", direction: OUT)
}

type Genre implements INode {
  id: ID!
  value: String! @unique
}
````

**To Reproduce**
1. Execute the following Mutation...
````gql
mutation {
  createProducts(input: {
    name: "TestProduct",
    genre: {
      connectOrCreate: [
        {
          where: {
            node: {
              value: "Action"
            }
          },
          onCreate: {
            node: {
              value: "Action"
            }
          }
      	}
      ]
    }
  }) {
    products {
      id
      name
      genre {
        id
        value
      }
    }
  }
}
````

3. See error
````
Field \"GenreOnCreateInput.id\" of required type \"ID!\" was not provided.
````
**Expected behavior**
For example, if I use the id directive instead of the callback directive, it works fine. The input GenreOnCreateInput should be generated exactly the same as when using the id directive.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.
