### ISSUE TITLE
Default / coalesce directives are not supported with lists of enums

### ISSUE THREAD

**Issue by Tenrys** [neo4j/graphql#1761]
**Describe the bug**
An error is thrown when trying to default a non-nullable list of non-nullable enums to an empty list.
Defaulting to a list with values also does not work.

**Type definitions**
```graphql
enum MyEnum {
	FOO
	BAR
}

type MyType {
	enumList: [MyEnum!]! @default(value: [])
}
```

**Expected behavior**
I expect to be able to just be able to default my list of enums to an empty one if the field unspecified while creating an item.

**Screenshots**
![image](https://user-images.githubusercontent.com/3979239/179211078-cecd55ed-5b63-4ea1-839f-7129cc1573cf.png)

**System (please complete the following information):**

* OS: Windows 11 21H2 (OS Build 22000.739)
* Version: @neo4j/graphql@3.5.1
* Node.js version: v16.13.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Tenrys. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Tenrys! :pray: We will now prioritise the bug and address it appropriately.
