### ISSUE TITLE
An `EXISTS` clause is used in a `RETURN` clause where it is not valid

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#1779]
**Describe the bug**
An `EXISTS` clause is used in a `RETURN` clause where it is not valid.

**Type definitions**

```gql
type Person {
    name: String
    age: Int
    attends: [School!]! @relationship(type: "attends", direction: OUT)
}

type School {
    name: String
    students: [Person!]! @relationship(type: "attends", direction: IN)
}
```

**To Reproduce**

1. Execute the following query:

```gql
{
  people{
    name
    attends(where: {students_ALL: {age_GT: 23}}){
      name
    }
  }
}
```

2. See the error `The EXISTS subclause is not valid inside a WITH or RETURN clause.`

**Expected behavior**

No error to be thrown.

**System (please complete the following information):**

* Version: `@neo4j/graphql@3.5.0`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @darrellwarde. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
