### ISSUE TITLE
Subscriptions and Relationship property

### ISSUE THREAD

**Issue by fab679** [neo4j/graphql#179]
I'm working on a project with a team that want to utilize Graphql with neo4j. I think this library is nice but i would like to request the subscriptions and Relationship properties as they will be crucial in the project.

**Comment by manonthemat** [comment]
I concur, subscriptions would be a great feature to be supported and certainly mandatory in some projects.

**Comment by AdrienLemaire** [comment]
Following this issue so I can know when to migrate from neo4j-graphql-js to this lib (we're already using subscriptions).

**Comment by danstarns** [comment]
Thanks to all for raising this. I have made two new issues to track the progress of each graphql subscriptions and relationship properties individually. On the two topics; relationship properties are pitched work and we are scheming for it to be in our next dev phase and for subscriptions... they will need more work and attention thus we are not going to consider them till further down the line.
