### ISSUE TITLE
assertSchema & seachSchema

### ISSUE THREAD

**Issue by Jason-zyshen** [neo4j/graphql#182]
Hey guys, while I am really excited about this new release, I find that there are a few powerful features I really enjoy in the previous `neo4j-graphql.js` library are missing in this release. I personally use `assertSchema` and `seachSchema` a lot, so I wonder if there would be a further update so that I can keep my use of `@index` `@unique` `@search` in my graphql schema.

**Comment by danstarns** [comment]
Hey @Jason-zyshen. Thanks for raising this! We realise that not supporting index, unique and search is a frustration for some and we are planning and shaping how they will fit into this implementation.

**Comment by manonthemat** [comment]
I'm also looking into migrating a project which is currently using the neo4j-graphql-js package.
For that project, we use `assertSchema` in our init function and it's crucial for us to have confidence at the time of schema/data migration.

**Comment by darrellwarde** [comment]
`@unique` and `@fulltext` supported, just missing "normal" indexes which will be covered in #1312.
