### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/graphql#183]
**Is your feature request related to a problem? Please describe.**
GraphQL support for Neo4j Fabric mode.

**Describe the solution you'd like**
It would be great to see an example with this package demonstrating Fabric support.

**Describe alternatives you've considered**
As I know previous effors on neo4j-graphql-js didn't support Fabric mode.

**Comment by redbar0n** [comment]
does it support Fabric today? I couldn't find any documentation on it anywhere...

**Comment by danstarns** [comment]
> does it support Fabric today? I couldn't find any documentation on it anywhere...

Hey, still no support for Fabric.

**Comment by darrellwarde** [comment]
I'm going to close this feature request today. There's not enough information for us to go on in the description, and Fabric support isn't on our roadmap. We believe that GraphQL Federation is an alternative, GraphQL native way of working with Fabric federated databases, and this is a route that we're going to explore first.
