### ISSUE TITLE
Full filtering support for the `@auth` directive

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#1871]
**Is your feature request related to a problem? Please describe.**

This will act as a "mega feature request" to capture the variety of requests for full filtering support in the `@auth` directive, including:

- #163
- #518
- #631
- #1105
- #1095
- #2811
- #3111

Whilst they all seem like quite different feature requests, they all fall under the same underlying issue - the translation code for `@auth` filtering is totally different to that which is used for generating filters generally. The solution here is to have unified filtering for both `@auth` and standard filtering.

Any feature requests relating to this will be closed in favour of this, to aid in us capturing the full requirements for an evolution of the `@auth` directive.

**Comment by imkleats** [comment]
Checking in on the status of this and whether you can provide any more concrete release timelines. Specifically having the capabilities encompassed by #1105 is essential for our production deployments using this library. Thanks!
