### ISSUE TITLE
@auth directive and combining where with roles

### ISSUE THREAD

**Issue by pandemosth** [neo4j/graphql#1889]
**Describe the bug**
Combining a where rule with a roles rule behaves like an AND instead of an OR if the where rule does not specify a role. This is the same issue as #634 so may be a regression or it might be that the proposed fix for #490 was a slightly different case where roles are specified in each rule.

**Type definitions**
```graphql
type Person {
  id: ID @id
  name: String
  email: String
  roles: [String]
}

type Document {
  id: ID @id
  title: String
  owner: Person @relationship(type: "OWN", direction: IN)
}

extend type Document @auth(rules: [{
  where: { owner: { id: "$jwt.sub" }}
}, {
  roles: ["admin"]
}])
```

**To Reproduce**
```graphql
query Documents($options: DocumentOptions) {
  documents(options: $options) {
    title
  }
}
```
Running this query for a non-admin user raises a Forbidden error.

**Expected behavior**
The logic of this rule combination should be that a non-admin user (with any other role, or no roles specified in their JWT) can query for their own documents.

**Screenshots**
n/a

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@3.6.2
* Node.js version: 14.7.0

**Additional context**
I think the problematic clause in the generated cypher is this:

`CALL apoc.util.validate(NOT (any(r IN ["admin"] WHERE any(rr IN $auth.roles WHERE r = rr))), "@neo4j/graphql/FORBIDDEN", [0])`

Shouldn't there be an OR condition here?

Note. I've also tried expressing the rule as a single OR statement as per the alternative form shown in the documentation and the behaviour is the same.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @pandemosth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @pandemosth! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment]
Hi @pandemosth 
Just as you mention, the problem here is that roles are not specified in each rule, at the moment, this falls right into a redesign on how the auth works to fix these inconsistencies, the only workaround I can think of while we work on that would be to use a different role for the first case (as you mentioned on the previous bug)

I'll let you know if we can find a better alternative in the meantime as we work on the auth improvements

**Comment by darrellwarde** [comment]
> Any update on this? It's quite a problematic error, and the alternative suggested doesn't work when combining with `allowUnauthenticated` since the `jwt` is not defined and therefore so is `roles`. EDIT: my bug is a "sub-bug" of this, so I created a separate issue: #2548

Hey @dominusmi, we're currently doing a complete redesign of authorization, and this issue has been included as one of the issues which must be satisfied by the redesign. We'll be implementing it in the coming months - there are some big changes!

**Comment by darrellwarde** [comment]
Hey everyone! In 3.23.0, we released our new authorization features which will replace `@auth` in version 4.0.0. We would encourage you to [migrate](https://neo4j.com/docs/graphql-manual/current/guides/v4-migration/authorization/) as soon as possible so we can get your valuable feedback and you can enjoy all of the new features!

This feature is now supported, with the following changes to the original type definitions:

```gql
type JWT @jwt {
  roles: [String!]!
}

type Person {
  id: ID @id
  name: String
  email: String
  roles: [String]
}

type Document {
  id: ID @id
  title: String
  owner: Person @relationship(type: "OWN", direction: IN)
}

extend type Document
  @authorization(
    filter: [
      { where: { node: { owner: { id: "$jwt.sub" } } } }
      { where: { jwt: { roles_INCLUDES: "admin" } } }
    ]
  )
```

We'd appreciate any feedback you have to give! Thanks!
