### ISSUE TITLE
Sum aggregate on where unexpected behaviour

### ISSUE THREAD

**Issue by Hellenic** [neo4j/graphql#1933]
**Describe the bug**
When using sum aggregate on where filter, I would expect it to filter based on the same values returned by the same sum aggregate. Currently this does not seem to be the case, and behaviour is similar to the term used without `_SUM`

**Type definitions**
Below truncated version of relevant types

```gql
type Employee {
  employeeId: ID! @id(autogenerate: false)
  firstName: String! @readonly
  lastName: String @readonly
  projects: [Project!]!
    @relationship(
      type: "PARTICIPATES"
      direction: OUT
      properties: "EmployeeParticipationProperties"
    )
}

interface EmployeeParticipationProperties @relationshipProperties {
  allocation: Float
}

type Project {
  projectId: ID! @id(autogenerate: false)
  name: String! @readonly
  description: String
  employees: [Employee!]!
    @relationship(
      type: "PARTICIPATES"
      direction: IN
      properties: "EmployeeParticipationProperties"
    )
  }
```

**To Reproduce**
See expected behaviour and the screenshots below. 

**Expected behavior**
I would expect the screenshot with `allocation_SUM_LTE: 25` to have returned nothing, as sum for each project allocation is over 25 (either 40 or 60 in the screenshot). `allocation_LTE: 25` works correctly.

By copy-pasting the generated cypher queries to Neo4j Browser I got the same results, so I'd guess the generated cypher is incorrect.

**Screenshots**

`allocation_LTE: 25`
![allocation_LTE](https://user-images.githubusercontent.com/1734471/185398187-2c1d5d34-087e-4109-85ab-f2ab5a51d44b.png)
Above screenshot generated this Cypher:
```
Cypher:
MATCH (this:`Employee`)
WHERE apoc.cypher.runFirstColumn(" MATCH (this)-[aggr_edge:PARTICIPATES]->(aggr_node:Project)
RETURN aggr_edge.allocation <= $aggr_edge_allocation_LTE
", { this: this, aggr_edge_allocation_LTE: $aggr_edge_allocation_LTE }, false )
RETURN this { .employeeId, .firstName, .lastName, projectsAggregate: { count: size([(this)-[this_projectsAggregate_this1:PARTICIPATES]->(this_projectsAggregate_this0:`Project`) | this_projectsAggregate_this0]), edge: { allocation: head(apoc.cypher.runFirstColumn("MATCH (this)-[r:PARTICIPATES]->(n:Project)    
        RETURN {min: min(r.allocation), max: max(r.allocation), average: avg(r.allocation), sum: sum(r.allocation)}", { this: this })) } } } as this
Params:
{
  "aggr_edge_allocation_LTE": 25
}
```

`allocation_SUM_LTE: 25`
![allocation_SUM_LTE](https://user-images.githubusercontent.com/1734471/185398203-693de92c-e006-4aa2-8b7b-c0653bb5956a.png)
Above screenshot generated this Cypher:
```
Cypher:
MATCH (this:`Employee`)
WHERE apoc.cypher.runFirstColumn(" MATCH (this)-[aggr_edge:PARTICIPATES]->(aggr_node:Project)
WITH aggr_node, aggr_edge, sum(aggr_edge.allocation) AS aggr_edge_allocation_SUM_LTE_SUM
RETURN aggr_edge_allocation_SUM_LTE_SUM <= toFloat($aggr_edge_allocation_SUM_LTE)
", { this: this, aggr_edge_allocation_SUM_LTE: $aggr_edge_allocation_SUM_LTE }, false )
RETURN this { .employeeId, .firstName, .lastName, projectsAggregate: { count: size([(this)-[this_projectsAggregate_this1:PARTICIPATES]->(this_projectsAggregate_this0:`Project`) | this_projectsAggregate_this0]), edge: { allocation: head(apoc.cypher.runFirstColumn("MATCH (this)-[r:PARTICIPATES]->(n:Project)    
        RETURN {min: min(r.allocation), max: max(r.allocation), average: avg(r.allocation), sum: sum(r.allocation)}", { this: this })) } } } as this
Params:
{
  "aggr_edge_allocation_SUM_LTE": 25
}
```

**System (please complete the following information):**

* OS: Ubuntu 22.04.1 LTS (5.15.0-46-generic)
* Version: `"@neo4j/graphql": "^3.6.2"`
* Node.js version: `14.20`
* Neo4j Aura pro

PS. Thank you for the great library! Great to get such a good amount of features out-of-the-box.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Hellenic. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @Hellenic, thanks for reporting this bug!
I reproduced it with this test data:
```
CREATE (e1:Employee { employeeId: "3331", firstName: "Emp1", lastName: "EmpLast1" })
CREATE (e2:Employee { employeeId: "3332", firstName: "Emp2", lastName: "EmpLast2" })
CREATE (p1:Project { id: "2221", name: "Test_proj" })
CREATE (p2:Project { id: "2222", name: "Test_proj2" })
CREATE (e1)-[:PARTICIPATES { allocation: 20.0 }]->(p1)
CREATE (e1)-[:PARTICIPATES { allocation: 40.0 }]->(p2)
CREATE (e2)-[:PARTICIPATES { allocation: 30.0 }]->(p1)
CREATE (e2)-[:PARTICIPATES { allocation: 20.0 }]->(p2)
```

Re-posting the query for the `SUM_LTE` as well for easy copy&pasting:

```
Query:
query Query($where: EmployeeWhere) {
  employees(where: $where) {
    employeeId
    firstName
    lastName
    projectsAggregate {
      count
      edge {
        allocation {
          max
          min
          average
          sum
        }
      }
    }
  }
}
Variables:
{
  "where": {
    "projectsAggregate": {
      "edge": {
        "allocation_SUM_LTE": 25
      }
    }
  }
}
```

**Comment by darrellwarde** [comment]
We want to run some checks to see whether the generated Cypher here is different following some work to reduce our reliance on `apoc.cypher.runFirstColumn`. I wouldn't expect any work on this problem this week, however, we will revisit next week.

**Comment by Hellenic** [comment]
Thank you for looking into it! No worries, sounds great :)

**Comment by angrykoala** [comment]
The cypher examples in this issue are still relevant and will probably not change until we tackle aggregation's `runFirstColumn`
