### ISSUE TITLE
auth/roles integration tests fail if run against an empty database

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#195]
**Describe the bug**
The following tests in `packages/graphql/tests/integration/auth/roles.int.test.ts` fail if they are run against an empty database:

- auth/is-authenticated › read › should throw if not authenticated type definition
- auth/roles › read › should throw if missing role on type definition
- auth/roles › update › should throw if missing role on type definition (only if run in isolation)
- auth/roles › delete › should throw if missing role on type definition (only if run in isolation)

This bug, and the fact that the behaviour varies based on whether the tests are run in isolation, suggests that individual tests are relying on data produced by other tests to pass.

More worryingly, it seems that if there are no records for a type labelled with an `@auth` directive, it seems that the library will allow unauthenticated/unauthorized users to figure out the fact that there is no data. Not a massive breach, but they shouldn't even be able to do that.

**To Reproduce**
Steps to reproduce the the top two failures:

1. Empty your database: `MATCH (n) DETACH DELETE n`
2. Run the offending integration tests: `yarn test:int`
3. See error

Steps to reproduce the the bottom two failures:

1. Empty your database: `MATCH (n) DETACH DELETE n`
2. Run the offending integration tests: `yarn test:int -t "should throw if missing role on type definition"`
3. See error

**Expected behavior**
Tests to pass, `@auth` directive to block unauthenticated/unauthorized users from seeing if there is no data for a certain type.

**System**

-   OS: macOS
-   Version: master
-   Node.js version: 14.16.0

**Comment by darrellwarde** [comment]
Just spent a short amount of time looking at this.

One approach you can take is just by adding `OPTIONAL` to the first `MATCH`, but this will cause further issues downstream.

Another, and I think better, approach we could take is by splitting out the `isAuthenticated` and `roles` checks, performing them _before_ the first match.

So for `isAuthenticated` you would have something like:

```cypher
CALL apoc.util.validate(NOT(apoc.util.validatePredicate(NOT($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])
MATCH (this:Product)
RETURN this { .id } as this
```

This would have the added benefit of slightly better performance from bailing out early in this instances.

**Comment by danstarns** [comment]
> Just spent a short amount of time looking at this.
> 
> One approach you can take is just by adding `OPTIONAL` to the first `MATCH`, but this will cause further issues downstream.
> 
> Another, and I think better, approach we could take is by splitting out the `isAuthenticated` and `roles` checks, performing them _before_ the first match.
> 
> So for `isAuthenticated` you would have something like:
> 
> ```
> CALL apoc.util.validate(NOT(apoc.util.validatePredicate(NOT($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])
> MATCH (this:Product)
> RETURN this { .id } as this
> ```
> 
> This would have the added benefit of slightly better performance from bailing out early in this instances.

Looking back at this, I don't think we need to do the `isAuthenticated` check in the database at all... For the roles, we still need to continue to do the check after we match as with the example below, where would you put the `OR` ?

```gql
type User {
    id: ID
    name: String
}

extend type User @auth(rules: [{ OR: [{ allow: { id: "$jwt.sub" } }, { roles: ["admin"] }] }])
```

**Comment by darrellwarde** [comment]
Solved with the `@authentication` directive.
