### ISSUE TITLE
Extend the @cypher directive with statements for create/update/delete mutations to be able to mutate properties which are resolved by a @cypher directive

### ISSUE THREAD

**Issue by andreloeffelmann** [neo4j/graphql#1962]
**Is your feature request related to a problem? Please describe.**
We have type properties that are not related to a node property in neo4j but rather are "auto-generated" via a `@cypher` directive.
But: this works for queries only - not for mutations.
We need to run custom cypher statements for create/update/delete mutations on these properties.

**Describe the solution you'd like**
Since the `@cypher` query already has the `statement` field, add new fields for the several mutation types, e.g. `createStatement`, `updateStatement`, `deleteStatement`.
These statements should be executed whenever a mutation with a related property is received. This execution should be run in the same transaction as the actual mutation itself!
It would be ok to allow this for primitive types only.
If a `@cypher` directive has a `createStatement`, inject this field into the create mutation. Otherwise, discard it (as it is already done today).
If a `@cypher` directive has a `updateStatement`, inject this field into the update mutation. Otherwise, discard it (as it is already done today).
If a `@cypher` directive has a `deleteStatement`, inject this field into the delete mutation. Otherwise, discard it (as it is already done today).

**Describe alternatives you've considered**
We "solved" this problem with a workaround by creating custom mutation types for these properties. But this is not really convenient since it breaks the API design for the whole type handling. If there are properties on a specific type, it should be possible to mutate them whether they are resolved by a cypher directive or not. The client / API consumer must not know about how a property is resolved internally - in return he should not have to mutate such properties by using custom mutations which do not relate to the type mutation directly.

**Additional context**
Our use case: we have a type property `isInternal: Boolean` which is resolved by a `@cypher` directive. It returns `true` if the node has a specific label, `false` otherwise.
We need to add/remove this node label depending on this property. So if a mutation is received having `isInternal` set to `false`, we need to remove the node label. If a mutation is received having `isInternal` set to `true`, we need to add the node label. 
This seems not be solvable with the current possibilities of the graphql-neo4j API.

**Comment by darrellwarde** [comment]
Hey @andreloeffelmann, you're right, this kind of behaviour isn't currently easily achievable, or possible at all.

We have been thinking about functionality similar to this for some time now, but in a slightly different way to how you've described it. Instead of bundling this under `@cypher` which is all about _resolving_ fields, introducing a concept of "Cypher hooks" which allow the execution of custom Cypher before and after Queries and Mutations.

This is not something we can work on right away, but following a discussion with the team this morning, we might start thinking about the design work for this piece soon, into which we will factor in the use case you have described. 

Thanks for raising this!

**Comment by darrellwarde** [comment]
We will eventually provide a mechanism for this via the Cypher hooks feature I mentioned above. I have created a new (if empty) issue #2265 in which we will add more details for in near time.
