### ISSUE TITLE
@cypher directives in where clauses

### ISSUE THREAD

**Issue by Tanner-Scadden** [neo4j/graphql#1997]
**Is your feature request related to a problem? Please describe.**
Would be awesome to be able to filter results by values that have a @cypher directive! Would help with filtering by values such as ages calculated on date of birth values.

**Describe the solution you'd like**
To include the @cypher directive values in the autogenerated where clauses. I don't imagine this would be too hard since the library adds these values to the sort by options.

**Describe alternatives you've considered**
N/A

**Additional context**
Example:
```gql
type User {
  id: String! @id 
  birthday: Date!
  age: Int!  @cypher(
        statement: """
        MATCH (this)
        return duration.inMonths(date(this.birthday), date()).years
        """
      )
}

query Users {
  users(where: { age_GT: 60 }) {
    id
  }
}
```

**Comment by MacondoExpress** [comment]
Hi, @Tanner-Scadden thanks for the request!
We are doing some investigation around this particular request that you can find here https://github.com/neo4j/graphql/pull/2029.
I've added the duplicate flag as this request seems to me very similar to the https://github.com/neo4j/graphql/issues/554.

**Comment by Tanner-Scadden** [comment]
@MacondoExpress thanks for the update! Yes, I didn't see that request before. We can close out that one and I'll follow the other thread.
