### ISSUE TITLE
Fulltext-Index for properties of type "ID"

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#2080]
**Is your feature request related to a problem? Please describe.**
I want to define a fulltext index on several properties. One of its properties is of type ID. The following exception is thrown when starting the server:
````
Error: Node 'ProgrammeItem' @fulltext index contains invalid index 'ProgrammeItemSearchIndex' cannot use find String field 'id'
````

**Describe the solution you'd like**
When creating a fulltext index, handle properties of type ID the same as properties of type String.

**Additional context**
````gql
type ProgrammeItem {
  id: ID!
  name: String!
  productTitle: String!
  originalTitle: String
  workingTitle: String!
}

extend type ProgrammeItem
  @fulltext(
    indexes: [
      {
        name: "ProgrammeItemSearchIndex"
        fields: ["id", "name", "productTitle", "originalTitle", "workingTitle"]
      }
    ]
  )
````

**Comment by darrellwarde** [comment]
Sure, great spot, implemented in #2081! 🙂
