### ISSUE TITLE
Can't use @neo4j/graphql-ogm with esmodules

### ISSUE THREAD

**Issue by rmacy** [neo4j/graphql#210]
**Describe the bug**
Cannot import `@neo4j/graphql-ogm` using ES modules.

**To Reproduce**
1. Install graphql-ogm package
2. Attempt to import OGM using es module syntax
3. Experience error

**Expected behavior**

Imports work with commonjs and esmodules like `grapqhl` package.

**Additional context**

Can https://github.com/neo4j/graphql/blob/master/packages/ogm/package.json#L16 change to match `graphql` package?

**Comment by darrellwarde** [comment]
PR opened, thanks for raising. 🙂
