### ISSUE TITLE
Automatic Cloud GraphQL Hosting - Schema in Database

### ISSUE THREAD

**Issue by jdgamble555** [neo4j/graphql#2109]
It would be nice if the neo4j GraphQL Library was already hosted in the Cloud so that we didn't have to mess with our own hosting.  It can also be difficult to host a server with Web Socket support (if you want to use subscriptions for example) when most of the available hosting don't allow it.  They usually use lambdas or functions with cold start where web sockets are not available.  Hosting also requires you to know more about server technologies, which is why many people want to use neo4j Aura in the first place.

My proposal:

1. Move the Schema to the database.  If the schema is saved to the database itself, there would be no need to deal with your own GraphQL server.  This is how Dgraph does it.  You basically could use a command line (with Auth) to update your schema remotely.  That way you don't have to mess with any of the GraphQL core functionality, which is reinventing the wheel.
2. Offer a one click deployment version for those who want to use the GraphQL functionality.  Obviously they would pay for it separately, instead of having to deal with their own middleware hosting.

I believe having to self-host your own GraphQL server is a huge deterrence for new users wanting to adopt neo4j.  A lot of new databases provide this out-of-the-box  (8base, Dgraph, Hasura, Supabase, FaunaDB, etc).

I think this would be an extremely important financial decision for neo4j, and could bring a lot more adoption over time.  It would also bring more competition with relational cloud hosted databases.

J

**Comment by jdgamble555** [comment]
Hi @darrellwarde - I don't have any expectations, I just personally don't use neo4j for the moment because I don't want to host my own GraphQL server (Vercel, for example, won't support web sockets anyway).  

It would just be nice if this was done for us.  Dgraph is a perfect example to copy their formula on hosting.

I am happy to answer any questions you may have.

Thanks,

J

**Comment by LackOfMorals** [comment]
This is under active development and we're starting to look for people to take part in our first early access preview.  If this is of interest to you, you can register here: https://forms.gle/gr8n8sx8S8yXFZzj8
