### ISSUE TITLE
Allow optional autogeneration of mutations for fields with an @timestamp directive

### ISSUE THREAD

**Issue by james-m-hall** [neo4j/graphql#2135]
**Is your feature request related to a problem? Please describe.**
I'm currently dealing with an issue where I have a `DateTime` field where I would like the initial value to be set automatically e.g. ` @timestamp(operations: [CREATE])` but then have the option to manually update the value via the usual auto generated resolvers.

**Describe the solution you'd like**
I think one way of accomplishing this would be to have the signature of the `@timestamp` directive update to look something like the following
```
directive @timestamp(
    """Which events to generate timestamps on. Defaults to both create and update."""
    operations: [TimestampOperation!]! = [CREATE, UPDATE]
    """Whether to auto generate mutation resolvers for the field. Defaults to false"""
    generateResolvers: Boolean
) on FIELD_DEFINITION
```

**Describe alternatives you've considered**
I've looked into the following alternative methods of doing this

- apoc triggers - these aren't supported on Aura
- The `@callback` directive - this isn't supported on `DateTime` fields

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @james-m-hall. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
I can't believe I've only just realised this now, but this is almost certainly a bug. A timestamp for creates should be updatable, and a timestamp for updates should be create-able, and it seems like this isn't the case for either at the moment. My apologies that we didn't spot this earlier!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @james-m-hall! :pray: We will now prioritise the bug and address it appropriately.
