### ISSUE TITLE
Sort priority is not maintained between edge and node sort fields

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#2147]
**Describe the bug**
The following 2 queries, return connection nested fields, ordered by both, edge and node fields, but the order is not being affected in the resulting cypher:

```graphql
query MoviesSortedByRelationship {
  movies {
    actorsConnection(sort: [{edge: {year: DESC}}, {node: {name: ASC}}]) {
      edges {
        year
        node {
          name
        }
      }
    }
  }
}
```

```graphql
query MoviesSortedByRelationship {
  movies {
    actorsConnection(sort: [{node: {name: ASC}},{edge: {year: DESC}}]) {
      edges {
        year
        node {
          name
        }
      }
    }
  }
}
```

However, both queries yield the same following Cypher:
```cypher
MATCH (this:`Movie`)
CALL {
    WITH this
    MATCH (this)<-[this_connection_actorsConnectionthis0:ACTED_IN]-(this_Person:`Person`)
    WITH this_connection_actorsConnectionthis0, this_Person
    ORDER BY this_connection_actorsConnectionthis0.year DESC, this_Person.name ASC
    WITH { year: this_connection_actorsConnectionthis0.year, node: { name: this_Person.name } } AS edge
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    UNWIND edges AS edge
    WITH edge, totalCount
    ORDER BY edge.year DESC, edge.node.name ASC
    WITH collect(edge) AS edges, totalCount
    RETURN { edges: edges, totalCount: totalCount } AS actorsConnection
}
RETURN this { actorsConnection: actorsConnection } as this
```

**Expected result**
The `ORDER BY` priority should be maintained as defined in the `sort` input field

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @angrykoala! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
