### ISSUE TITLE
Cannot create custom scalars

### ISSUE THREAD

**Issue by Temmermans** [neo4j/graphql#2178]
**Describe the bug**
When trying to create custom scalars (as defined [here](https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/#importing-a-third-party-custom-scalar)), I get the following error:

![image](https://user-images.githubusercontent.com/14975555/193872394-20324cec-028c-483a-8bd9-fafd68b2a6ba.png)

I might be missing something stupid but I cannot get it to work.

**Type definitions**
In the typedefinitions, I define the scalar like so (abbreviated for clarity):
```js
const sharedTypedefs = `
scalar Date
...
`
export { sharedTypedefs }
```

In the resolvers I define the date like so:
```js
export const sharedResolvers = {
  Date: dateScalar,
  ...
}
```

The Date scalar itself is this file (just copied from the tutorial of Apollo):
```js
const { GraphQLScalarType, Kind } = require('graphql')

export const dateScalar = new GraphQLScalarType({
  name: 'Date',

  description: 'Date custom scalar type',

  serialize(value) {
    return value.getTime() // Convert outgoing Date to integer for JSON
  },

  parseValue(value) {
    return new Date(value) // Convert incoming integer to Date
  },

  parseLiteral(ast) {
    if (ast.kind === Kind.INT) {
      return new Date(parseInt(ast.value, 10)) // Convert hard-coded AST string to integer and then to Date
    }

    return null // Invalid hard-coded value (not an integer)
  }
})
```

**To Reproduce**

1. Run a server with the above typedefs and resolvers.
```js
import { Neo4jGraphQL } from '@neo4j/graphql'
import { OGM } from '@neo4j/graphql-ogm'
import { UserInputError } from 'apollo-server-express'
import neo4j from 'neo4j-driver'
import { resolvers, typeDefs } from './src/app'

const stringifiedTypeDefs = typeDefs.join('')

export const objectGraphMapper = new OGM({
  typeDefs: stringifiedTypeDefs,
  config: { enableRegex: true }
})

export const neoSchema = new Neo4jGraphQL({
  typeDefs: stringifiedTypeDefs,
  resolvers,
  config: { enableRegex: true, skipValidateTypeDefs: true }
})
```

**Expected behavior**
We should be able to create our own custom scalars

**System (please complete the following information):**

* OS: [macOS]
* Version: [@neo4j/graphql@3.9.0]
* Node.js version: [e.g. 14.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Temmermans. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Temmermans** [comment]
Great! Let me know if I can be of assistance :)

**Comment by Liam-Doodson** [comment]
Hi @Temmermans, we've reserved the type name `Date` and this is what is causing your issue. Please try using a different name for your custom scalar.

Apologies for the inconvenience!

**Comment by Temmermans** [comment]
I'm not sure that is the issue, I renamed it to Test and I still get the same error:
![afbeelding](https://user-images.githubusercontent.com/14975555/194512978-39863c9c-ee2e-4d5f-ba3d-bd63bbead9af.png)

Seems like something else is wrong. Can you share the code sample that works on your side?

**Comment by Liam-Doodson** [comment]
This is the code that I used to test this:

```ts
const dateScalarResolver = new GraphQLScalarType({
  name: "CustomDateScalar",
  description: "Date custom scalar type",
  serialize(value) {
    return "serialised"
  },
  parseValue(value) {
    return "val"
  },
  parseLiteral(ast) {
    return "literal"
  }
})

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("username", "password")
);

const typeDefs = gql`
    scalar CustomDateScalar

    type Material {
        name: String
        date: CustomDateScalar
    }
`;

const resolvers = {
  CustomDateScalar: dateScalarResolver
};

const neoSchema = new Neo4jGraphQL({
  typeDefs,
  driver,
  resolvers,
});

neoSchema.getSchema().then((schema) => {
    const server = new ApolloServer({
        schema
    });
    server.listen().then(({ url }) => {
        console.log(`🚀 Server ready at ${url}`);
    });
});
```

Note that the name assigned to the `GraphQLScalarType` is the same as the name of the custom scalar in my type definitions (i.e. both are `CustomDateScalar`). If these do not match I see the same error as you.

**Comment by Temmermans** [comment]
Sadly still the same issue, I guess I'm doing something else wrong than.. I'll try to troubleshoot a bit more but I'm not sure what the problem is.

**Comment by lewisparma** [comment]
@Temmermans did you manage to resolve this issue? I get the same error when trying to add custom scalars

**Comment by lewisparma** [comment]
Update: I get the error only if the scalar is not used by another type (pb get's filtered out from the schema in that case)
