### ISSUE TITLE
deprecated directive does not take effect together with relationship directive.

### ISSUE THREAD

**Issue by SvenAnton** [neo4j/graphql#2187]
**Describe the bug**
`@deprecated` directive does not take effect together with `@relationship` directive.

Initially I thought that this should not actually work, because `@relationship` creates new objects. But in Community Discord channel `graphql` I was informed that `@deprecated` directive should be carried along and therefore relationships should be deprecated as well. If not, it should be considered as a bug.

**Example type definition**
Note: Just to test it out, I added deprecated directive to the field `title` as well and it works fine.

```graphql
type Movie {
    title: String @deprecated(reason: "Do not use")
    year: Int
    imdbRating: Float
    genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT) @deprecated(reason: "Do not use")
}

type Genre {
    name: String
    movies: [Movie!]! @relationship(type: "IN_GENRE", direction: IN)
}
```

**To Reproduce**

1. Create a file `app.js` with following code:
```javascript
const { Neo4jGraphQL } = require("@neo4j/graphql");
const neo4j = require("neo4j-driver");
const { ApolloServer } = require("apollo-server");

const typeDefs = `
    type Movie {
        title: String @deprecated(reason: "Do not use")
        year: Int
        imdbRating: Float
        genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT) @deprecated(reason: "Do not use")
    }

    type Genre {
        name: String
        movies: [Movie!]! @relationship(type: "IN_GENRE", direction: IN)
    }
`;

const driver = neo4j.driver(
  "bolt://localhost:7687",
  neo4j.auth.basic("neo4j", "letmein")
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

async function main() {
  const schema = await neoSchema.getSchema();

  const server = new ApolloServer({
    schema,
    context: ({ req }) => ({ req }),
  });

  await server.listen(4000);

  console.log("Online");
}

main();
```

2. Install dependecies
```bash
npm install @neo4j/graphql
```
```bash
npm install graphql neo4j-driver
```
```bash
npm install apollo-server 
```
4. Run the application
```bash
node app.js
```
6. Open the query editor in Apollo Studio
 - http://localhost:4000/graphql
 - In the page, if asked, click to be directed to Apollo Studio
8. Use this example query:
```graphql
query Query {
  movies {
    title
    genres {
      name
    }
  }
}
```

**Expected behavior**
In the Apollo Studio query editor (look at the screenshot), you see that `title` is underlined and when you hover over it, it says `The field Movie.title is deprecated. Do not use`

The relationship `genres` should be deprecated exactly in a same way, because the same deprecated directive was added to `genres` relationship as well right after `@relationship` directive.

**Screenshots**
![Screenshot 2022-10-06 at 9 56 06 AM](https://user-images.githubusercontent.com/42271351/194234723-b1ab59cb-e010-4569-ab58-05cc503a4a07.png)

**System (please complete the following information):**

* OS: macOS, Linux (Debian)
* * Node.js version: 18.9.0
* Package versions: 
```json
{
  "dependencies": {
    "@neo4j/graphql": "^3.9.0",
    "apollo-server": "^3.10.2",
    "graphql": "^16.6.0",
    "neo4j-driver": "^5.0.1"
  }
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @SvenAnton. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @SvenAnton! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
Hey @SvenAnton, this should be an easy enough fix but we have our hands slightly full with a number of more breaking bugs right now. We're going to review over the next couple of weeks to get this done. Sorry for the inconvenience! 🙏
