### ISSUE TITLE
`@cypher` directive seems to force query to omit results with missing fields

### ISSUE THREAD

**Issue by Tenrys** [neo4j/graphql#2189]
**Describe the bug**
If you try to query an optional field with a `@cypher` directive, you will only get back nodes that contain the field as a result.

**Type definitions**
```graphql
type Test_Item {
  uuid: ID! @id
  int: Int
  str: String
  bool: Boolean
  
  feedback: Test_Feedback @relationship(type: "TEST_RELATIONSHIP", direction: IN)
  feedbackCypher: Test_Feedback @cypher(statement: """
    OPTIONAL MATCH (this)<-[:TEST_RELATIONSHIP]-(t:Test_Feedback)
    RETURN t
    LIMIT 1
  """)
}
type Test_Feedback {
  uuid: ID! @id
  int: Int
  str: String
  bool: Boolean
  
  item: Test_Item @relationship(type: "TEST_RELATIONSHIP", direction: OUT)
}
```

**To Reproduce**

1. Run a server with the following code...

```graphql
type Test_Item {
  uuid: ID! @id
  int: Int
  str: String
  bool: Boolean
  
  feedback: Test_Feedback @relationship(type: "TEST_RELATIONSHIP", direction: IN)
  feedbackCypher: Test_Feedback @cypher(statement: """
    OPTIONAL MATCH (this)<-[:TEST_RELATIONSHIP]-(t:Test_Feedback)
    RETURN t
    LIMIT 1
  """)
}
type Test_Feedback {
  uuid: ID! @id
  int: Int
  str: String
  bool: Boolean
  
  item: Test_Item @relationship(type: "TEST_RELATIONSHIP", direction: OUT)
}
```

2. Execute the following Mutation...

```graphql
mutation CreateTestItems($input: [Test_ItemCreateInput!]!) {
  createTestItems(input: $input) {
    info {
      relationshipsCreated
      nodesCreated
    }
  }
}
```

Variables:

```json
{
  "input": [
    {
      "feedback": {
        "create": {
          "node": {
            "str": "hi there",
          }
        }
      },
      "int": 1,
      "str": "one",
      "bool": false
    },
    {
      "int": 2,
      "str": "two",
      "bool": true
    }
  ]
}
```

3. Then run the following Query...

```graphql
query FeedbackCypher {
  testItems {
    bool
    int
    str
    uuid
    feedbackCypher {
      bool
      str
      int
      uuid
    }
    feedback {
      uuid
      int
      str
      bool
    }
  }
}
```

4. Notice how you only get back the node that has a `Test_Feedback` connected to it. If you remove the `feedbackCypher` field from your query, you will get both.

**Expected behavior**
The field should just return `null` instead of excluding the entire record from the list of results.

**System (please complete the following information):**

* OS: Manjaro Linux 22.0.0 "Sikaris"
* Version: @neo4j/graphql@3.9.0
* Node.js version: v16.16.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Tenrys. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by rydamckinney** [comment]
Also seeing this same exact issue on my side w/ v3.9

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Tenrys! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
This is a great spot, thanks for the report @Tenrys and thanks for echoing @rydamckinney. We've been making a bunch of changes and improvements (they are improvements, I promise) to the Cypher which we generate lately, and it sounds like maybe something got caught in the crossfire here. We'll take a look, but in the meantime, I would advise rolling back to 3.8.0 as I don't believe this is a problem on that release. Apologies for the inconvenience!

**Comment by darrellwarde** [comment]
A different reproduction purely with a single Mutation below.

The following Mutation returns _zero_ `testItems`:

```gql
mutation CreateTestItems {
  createTestItems(
    input: [
      {
        feedback: { create: { node: { str: "hi there" } } }
        int: 1
        str: "one"
        bool: false
      }
      { int: 2, str: "two", bool: true }
    ]
  ) {
    info {
      relationshipsCreated
      nodesCreated
    }
    testItems {
      bool
      int
      str
      uuid
      feedbackCypher {
        bool
        str
        int
        uuid
      }
      feedback {
        uuid
        int
        str
        bool
      }
    }
  }
}
```

The following Mutation returns both as expected:

```gql
mutation CreateTestItems {
  createTestItems(
    input: [
      {
        feedback: { create: { node: { str: "hi there" } } }
        int: 1
        str: "one"
        bool: false
      }
      { int: 2, str: "two", bool: true }
    ]
  ) {
    info {
      relationshipsCreated
      nodesCreated
    }
    testItems {
      bool
      int
      str
      uuid
      feedback {
        uuid
        int
        str
        bool
      }
    }
  }
}
```

**Comment by darrellwarde** [comment]
I have added integration tests for reproduction to the attached development branch.

**Comment by angrykoala** [comment]
Hi @Tenrys @rydamckinney thanks for the report, as @darrellwarde mentioned, this is a bug introduced during our last refactor into custom cypher in 3.9.0, it should be fixed in the next release
