### ISSUE TITLE
`First` on connection field not taken into account when connected type uses the `@queryOptions` directive

### ISSUE THREAD

**Issue by a-alle** [neo4j/graphql#2195]
**Describe the bug**
Given the following type definitions:
```gql
typeDefs = gql`
            type Movie @queryOptions(limit: { default: 3, max: 5 }) {
                id: ID!
                actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
            }

            type Person **@queryOptions(limit: { default: 2 })** { 
                id: ID!
            }
        `;
```
Then the following query:
```gql
const query = gql`
                query {
                    movies {
                        id
                        **actorsConnection(first: 4)** {
                            edges {
                                node {
                                    id
                                }
                            }
                        }
                    }
                }
            `;
```
Is expected to override the `default` limit of 2 with 4 (coming from the `first` argument).

However, currently the `first` argument is being ignored and the `default` limit option is used, such that 2 actors are being returned. 

**Expected behavior**
`first` argument should override the `default` limit, but still honour the `max` limit imposed using `@queryOptions` directive.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @a-alle. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @a-alle! :pray: We will now prioritise the bug and address it appropriately.

**Comment by a-alle** [comment]
Completed in https://github.com/neo4j/graphql/pull/2180
