### ISSUE TITLE
Neo4j-graphql-java translator issue

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [neo4j/graphql#223]
HI all i am trying translate graphql query to cypher for normal string the translated query is working fine when i am trying to filter with DateTime the translated query seems to be wrong..
I have added Schema and Translated cypher query pls help me on this

my graph ql Schema

type Person{
	confirmedtime: DateTime
	healthstatus: String
	name: String
}
graphQl Query

query{  Person(confirmedtime:{year:2021,month:5}){   healthstatus  name}}

This query works well in graphql-js but not in java

Translated Cypher

[Cypher(query=MATCH (person:Person)
WHERE person.confirmedtime = $personConfirmedtime
RETURN person {
	.healthstatus,
	.name
} AS Person, params={personConfirmedtime={year=2021, month=5}}, type=[Person], variable=Person)]

When I run this query and params in neo4j-java driver it throws error
org.neo4j.driver.exceptions.ClientException: Property values can only be of primitive types or arrays thereof

Spring boot code

URL url = Resources.getResource("schema.graphqls");

		String sdl = Resources.toString(url, Charsets.UTF_8);

		GraphQLSchema graphQLSchema = SchemaBuilder.buildSchema(sdl);
		Translator trans = new Translator(graphQLSchema);
		List<Cypher> cypher = trans.translate(query);

for the above code Except Spatial and temporal filter all other filters like String int it gives correct response
Please help me on this...If needed Additional details let me know
Thanks !!

**Comment by darrellwarde** [comment]
Hi @NAVEENKUMARSKPN, this repo is for the new JavaScript library. You'll need to raise this issue over in https://github.com/neo4j-graphql/neo4j-graphql-java.
