### ISSUE TITLE
Incorrect nodes created in nested update operation with interfaces

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#2269]
**Describe the bug**
Given the following type definitions:

```graphql
    type Movie {
        title: String!
        reviewers: [Reviewer!]! @relationship(type: "REVIEWED", properties: "Review", direction: IN)
    }

    interface Review @relationshipProperties {
        score: Int!
    }

    type Person implements Reviewer {
        name: String!
        reputation: Int!
        id: Int @unique
        reviewerId: Int @unique
    }

    type Influencer implements Reviewer {
        reputation: Int!
        url: String!
        reviewerId: Int
    }

    interface Reviewer {
        reputation: Int!
        reviewerId: Int
    }
```

With the following database setup:
```
CREATE(:Movie {title: "John Wick"})
```

And the following mutation:
```graphql
mutation UpdateMovies {
  updateMovies(
    where: { title: "John Wick" }
    update: {
      reviewers: [
        {
          create: [
            {
              edge: { score: 10 }
              node: { Person: { reputation: 100, name: "Ana" } }
            }
          ]
        }
      ]
    }
  ) {
    movies {
      title
    }
  }
}
```

The expected behaviour is for a new node `Person` with the name `Ana` to be created and connected to the movie with the `REVIEWED` type in the relationship.

Currently, 2 new unnamed nodes are created, with the label `Movie`, connected to the movie.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @angrykoala! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
