### ISSUE TITLE
Cannot use autogenerated types in schema for custom resolvers in 3.11.1

### ISSUE THREAD

**Issue by killmenot** [neo4j/graphql#2325]
**Describe the bug**
Hi,

After migration my project from 2.x to 3.11.1 I faced with the same problem during the validation
```
Error: Unknown type "SortDirection". Did you mean "__Directive"?
```

**To Reproduce**
https://github.com/killmenot/neo4j-custom-resolver-problem

**Expected behavior**
Should not have validation error

**Screenshots**

**System (please complete the following information):**

* OS: macOS
* Version: 3.11.1
* Node.js version: 14.20.1

**Additional context**
Only passing
```js
config: {
   skipValidateTypeDefs: true,
},
```
to both OGM and Neo4jGraphQL helped me but probably it's just a temporary hack
<img width="1044" alt="Screenshot 2022-10-28 at 14 15 34" src="https://user-images.githubusercontent.com/119337/198574718-4f03de72-30bf-43bf-8e81-8df068f16ae6.png">

Related ticket: https://github.com/neo4j/graphql/issues/442

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @killmenot! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
