### ISSUE TITLE
Nextjs 13 and the recommended implementation causing a memory leak

### ISSUE THREAD

**Issue by tbwiss** [neo4j/graphql#2356]
**Describe the bug**
Raised by [Discord community](https://discord.com/channels/787399249741479977/818578492723036210/1037407490658291723).
When using Nextjs 13 and the recommended implementation it causes a memory leak in development on code change causing it to crash after a few code changes (~5).

Setup according to the [next.js getting started](https://neo4j.com/docs/graphql-manual/current/guides/frameworks/nextjs/) guide.

**To Reproduce**

1. Run the next.js server with `yarn dev`
2. Send queries (between 5-10) to this endpoint `http://localhost:3000/api/graphql`

After 5-10 queries you will get: 
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.
...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

One can disable the warning with `require('events').EventEmitter.defaultMaxListeners = 15;` but that does not really solve the underlying issue.

**Expected behavior**
No memory leak

**System (please complete the following information):**

* Version: [e.g. @neo4j/graphql@3.12.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @tbwiss. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @tbwiss! :pray: We will now prioritise the bug and address it appropriately.

**Comment by cramatt** [comment]
Following - I'm seeing this error due to a different use case... maybe related. I'm creating 20+ instances of new ApolloSchema and subscription plugin.

**Comment by tbwiss** [comment]
Hi @cramatt!
If you think it's related would you be able to share a minimal example?
Thanks
