### ISSUE TITLE
ogm model functions' `fulltext` arg not working

### ISSUE THREAD

**Issue by pathologyenigma** [neo4j/graphql#2357]
**Describe the bug**
model.find and model.aggregate functions' fulltext arg not working whatever the input is

**Type definitions**

```graphql
// model definition
type Enterprise @node @fulltext(indexes: [{name: "search_by_name_tags_profile_or_extra_attributes", fields:["full_name", "tags"]}]){
        id: ID! @id
        full_name: String!
        tags: String
    }
```

**To Reproduce**
```javascript
// query

let list = await Enterprise.find({
        where,
        // not working without this
        //args: {
        //     fulltext: search_keyword ? {
        //         search_by_name_tags_profile_or_extra_attributes: { phrase: search_keyword }
        //     } : undefined
        // },
        fulltext: {
            search_by_name_tags_profile_or_extra_attributes: { phrase: search_keyword }
        },
        options: {
        offset: page ? page * pageSize : 0,
        limit: pageSize
    }
})
// aggregate
let count = (await Enterprise.aggregate({
    aggregate: {
        count: true
    },
    fulltext:  {
        search_by_name_tags_profile_or_extra_attributes: { phrase: search_keyword }
    },
    where,
})).count
// get this data(the only data in the database) whatever the search_keyword is
{
  "data": {
    "get_enterprise_list": {
      "count": 1,
      "list": [
        {
          "id": "30f18955-0b7d-48a1-a3e8-17b050397de8",
          "full_name": "aaaa",
          "tags": null
        }
      ]
    }
  }
}
```
**Expected behavior**
search result is empty when I input "123456" 

**Screenshots**

**System (please complete the following information):**

* OS: Windows
* Version: @neo4j/graphql-ogm@3.12.0
* Node.js version: 16.11.1

**Additional context**
the problem will fix for find function if I put the whole fulltext object inside args
I checked the code maybe fulltext arg is ignored [here](https://github.com/neo4j/graphql/blob/dev/packages/ogm/src/classes/Model.ts#L138)  and [here](https://github.com/neo4j/graphql/blob/dev/packages/ogm/src/classes/Model.ts#L423)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @pathologyenigma. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @pathologyenigma! :pray: We will now prioritise the bug and address it appropriately.
