### ISSUE TITLE
<type>OnCreateInput is missing `@relationship` fields that are present on <type>CreateInput

### ISSUE THREAD

**Issue by nettrino** [neo4j/graphql#2377]
**Describe the bug**
When using `connectOrCreate`, it should be possible to create a node as you would normally using a `create` mutation, however it seems that this is not possible. In particular, in case of connections of a node to itself, it is not possible to recursively allow relationships to be created using `connectOrCreate`, whereas it is possible to do so using `create`

**Type definitions**
Given the following definitions

```
  interface ResourceEntity {
    id: ID! @id(autogenerate: false)
    name: String
    """Allowed resource types (enums) """
    type: ResourceType!
    """
    Globally tracked tags for this resource (enum)
    """
    tags: [Tag!]
    properties: [Property!]
  }

  type Resource implements ResourceEntity {
    id: ID! @id(autogenerate: false)
    name: String
    type: ResourceType!
    externalIds: [ID!]
    """
    Globally tracked tags for this resource
    """
    tags: [Tag!]
    properties: [Property!]
    """
    Resources encapsulating the given resource (e.g., a github org contains a repo)
    """
    containedBy: [Resource!]! @relationship(type: "CONTAINS", direction: IN)
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [UPDATE])
  }
```

the inputs auto-generated are as follows:

```
input ResourceCreateInput {
  id: ID!
  name: String
  externalIds: [ID!]
  properties: [Property!]
  type: ResourceType!
  tags: [Tag!]
  containedBy: ResourceContainedByFieldInput
}
...
input ResourceOnCreateInput {
  id: ID!
  name: String
  externalIds: [ID!]
  properties: [Property!]
}
```

**Expected behavior**
I would expect `ResourceOnCreateInput` to be the same as  `ResourceCreateInput`. Instead, any attributes defined in the interface are not available on the `ResourceOnCreateInput`

* OS: macOS X, neo4j: 5.1
* Version: @neo4j/graphql@3.10.1
* Node.js version: v18.11.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @nettrino. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by nettrino** [comment]
I figured out that adding `properties: "ResourceEntity"` in the `@relationship` and then adding `@relationshipProperties` in the interface does add some missing fields, however it is still somewhat hazy  to me how `edge` & `node` are _supposed_ to be getting used. Moreover, if I change `containedBy: [Resource!]! @relationship(type: "CONTAINS", direction: IN)` to `containedBy: [ResourceEntity!]! @relationship(type: "CONTAINS", direction: IN)` I cannot get `connectOrCreate` directives at all, which is what I am mainly interested in, in terms of functionality. 

As a summary, probably the above is not a bug but leaving this open so that someone more knowledgeable can comment and we can have some reference in case anyone runs into the same issue

**Comment by darrellwarde** [comment]
> it is not possible to recursively allow relationships to be created using `connectOrCreate`, whereas it is possible to do so using `create`

We are aware of this - this is more of a feature request than a bug report, and it is on our roadmap.

> """Allowed resource types (enums) """
>     type: ResourceType!
>     """
>     Globally tracked tags for this resource (enum)
>     """
>     tags: [Tag!]
>     properties: [Property!]

But if these are indeed all enums, it looks like enums may have been missed from the `connectOrCreate` input types, we can take a look!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @nettrino! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
