### ISSUE TITLE
@customResolvers directive breaks integration with NestJS and other GraphQL Frameworks

### ISSUE THREAD

**Issue by rydamckinney** [neo4j/graphql#2394]
**Describe the regression**

The `@customResolvers` directive which replaces the previous `@computed` directive critically breaks our usage of this library in conjunction with `NestJS` GraphQL. 

Previously, if no custom resolver was provided to the Neo4jGraphQL (or OGM) constructor, the schema generation would not fail. This is important to us because we first generate the schema via `@neo4j/graphql` before passing the generated schema to NestJS. 

Then custom resolvers for mutations, queries, and field-level resolvers are implemented in the NestJS-style of Dependency-Injection containers. This is mission critical for a complex service like ours. 

Previously, we built out a `@neo4j/graphql`-only service, but this presented limitations in complexity due to the way that resolvers must be passed at schema-construction time. Very happy with our workflow of `neo4j -> generated schema -> nestjs + custom resolvers implementation` 

**Last working version**
Still works, but will be broken in 4.0 as the `@computed` directive is deprecated

**To Reproduce**

1. Define custom field-level resolvers in the schema-definition `.graphql` files
2. Do *not* pass the resolver at Neo4jGraphQL construction time
3. Schema generation fails

**Expected behavior**

**Requesting a `config.x` flag that can be passed in the `Neo4jGraphQLConstructor` to disable the enforcement of the presenec of custom resolvers**. 

This would enable this library to operate alongside NestJS and other graphql frameworks.

**Comment by darrellwarde** [comment]
Thanks for the report and thanks for trying out the new features, we appreciate the feedback! For now, roll back to `@computed`, we'll fix this before we deprecate that. 🙂
