### ISSUE TITLE
Support connectOrCreate  where non-unique fields

### ISSUE THREAD

**Issue by cramatt** [neo4j/graphql#2412]
**Is your feature request related to a problem? Please describe.**
`connectOrCreate`  currently only support `where` lookup on `unique` fields but this is less than useful and seems like an artificial limitation (or please elaborate if I'm incorrect). Even in the docs the example is not stellar, take this example:

```graphql
mutation {
  createActors(input: {
    name: "Tom Hanks",
    movies: {
      connectOrCreate: {
        where: { node: { id: "1234" } }
        onCreate: { node: { title: "Forrest Gump" } }
      }
    }
  }) {
    info {
      nodesCreated
    }
  }
}
```

How does an API users know the ID for Forrest Gump? Wouldn't it be more likely they would want this: 

```graphql
connectOrCreate: {
  where: { node: { title: "Forrest Gump" } }
  onCreate: { node: { title: "Forrest Gump" } }
}
```

**Describe the solution you'd like**
I would like to see `connectOrCreate` support `where` with any node properties, not just unique. 

**Describe alternatives you've considered**
Working within the current implementation.

**Additional context**
None

**Comment by darrellwarde** [comment]
Hey @cramatt, it's not artificial at all, it's based on https://neo4j.com/docs/cypher-manual/current/clauses/merge/#query-merge-using-unique-constraints to prevent the matching of multiple nodes, which would result in errors.

However, we are going to continue work on `connectOrCreate` and perhaps even remove `MERGE` as the underlying implementation, so we will leave this open to keep it in mind. Thanks!

**Comment by darrellwarde** [comment]
The plan is to remove `connectOrCreate` in Version 7 to give us a clean API and allow us to make changes such as these in the future without causing breaking changes. Will close this for now, because it has been noted for the next implementation.
