### ISSUE TITLE
Introspect schema using neo4j ogm java annotation

### ISSUE THREAD

**Issue by Hashdhi** [neo4j/graphql#2436]
We are using neo4j enterprise 5.1.0 . application built using java and neo4j-ogm-3.2.38 
we have java data model annotated with ogm annotation @Node /@Relationship 

 wanted to use neo4j/graphql  .

npm package, @neo4j/introspector generates GraphQL type definitions from an existing database

 is there any option of creating GraphQL type definitions from java data model annotated with ogm annotation @Node /@Relationship?

**Comment by tbwiss** [comment]
Hi @Hashdhi! 
Unfortunately, there is no way to do that in the `@neo4j/graphql` library and unlikely to be added in the future. You may want to head over to the [neo4j-graphql-java](https://github.com/neo4j-graphql/neo4j-graphql-java) lib and check/ask there.
