### ISSUE TITLE
composite type map not supported

### ISSUE THREAD

**Issue by Hashdhi** [neo4j/graphql#2463]
our Application based on java and uses neo4j 5.2.0 .
using neo-ogm 3.2.38 to interact with neo4j .

it supports Map data type 
<
@Properties
 private Map<String, String> charValueCompositeObject;
>
sample node
{
  "identity": 118,
  "labels": [
    "Example"
  ],
  "properties": {
"createdDate": "2022-11-24 07:37:51",
"createdUserId": "Example",
"charValueCompositeObject.FromAccessShared": "No",
"lastModifiedDate": "2022-11-24 07:37:51",
"lastModifiedUserId": "Example",
"charValueCompositeObject.Contention": "Premium",
"id": "ETHC12510389:OrdersAttribute : 34e1d7bb-8fe8-4797-8100-baecfc5f980c",
"charValueCompositeObject.AssociatedService": "Fibre",
"charName": "test",
"version": 0,
"charValueCompositeObject.SharedAccessAEnd": "ETHA12232797"
  }
}
charValueCompositeObject.key : value is stored . Both key and value are dynamic .

  there are many places in the app object model have defined  Map data type
 we are not able to define this type in neo4j graphql schema .
 we need this for mutation and query both . 
 Could you please help

**Comment by a-alle** [comment]
Hi Hashdhi,
We do not support Map field values, you would need to model the Map as a normal type in the schema. Or maybe you could create a [Custom Scalar type](https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/) for it if your use case allows it.

**Comment by Hashdhi** [comment]
Thanks
