### ISSUE TITLE
Cursor based pagination returning same items several times when sorting

### ISSUE THREAD

**Issue by sylv1b** [neo4j/graphql#2466]
I use cursor based pagination. When i want to sort some items are returned twice when moving cursor (endCursor  from previous response becomes "after" for the next query. The total number of returned items when reaching the end is the correct number of unique items that should be returned. Some are missing, some are double (or more).

* OS: MacOs
* Version: @neo4j/graphql@3.12.2
* Node.js version: 16.4.2

**Type definition**
```graphql
type Photography {
        photoId: ID @id
        key: String @unique(constraintName: "unique_photo_key")
        location: Point
        createdAt: DateTime! @timestamp(operations: [CREATE])
        updatedAt: DateTime! @timestamp(operations: [UPDATE])
        createdFrom: String
        user: User! @relationship(type: "PHOTOGRAPHIED", direction: IN)
        album: [PhotoAlbum!]!
            @relationship(type: "CONTAINS_PHOTOGRAPHY", direction: IN)
        tags: [Tag!]! @relationship(type: "HAS_TAG", direction: OUT)
        resizedUrl: String
        originalSizeUrl: String
        metadata: Metadata @relationship(type: "HAS_METADATA", direction: OUT)
        camera: Camera
            @relationship(
                type: "TAKEN_WITH_CAMERA"
                properties: "SerialNumber"
                direction: OUT
            )
        lens: Lens
            @relationship(
                type: "TAKEN_WITH_LENS"
                properties: "SerialNumber"
                direction: OUT
            )
    }

    extend type Photography
        @auth(
            rules: [
                {
                    operations: [CREATE, UPDATE, DELETE]
                    bind: { user: { userId: "$jwt.sub" } }
                }
            ]
        )
```

**Custom resolver**
```js
export const createResolvers = (ogm: any) => {
return {
...
 Photography: {
            resizedUrl: async ({ key }: any) => {
                const fileType = key.split(".")[1].toLowerCase();
                return await getImageUri(key, fileType !== "heic");
            },
            originalSizeUrl: async ({ key }: any) => {
                return await getImageUri(key, false);
            },
        },
...
}
```

**Query**
```graphql
fragment CorePhoto on Photography {
  key
  photoId
  resizedUrl
  createdAt
  location {
    longitude
    latitude
  }
}

fragment PhotoMetadata on Photography {
  metadata {
    apertureValue
    artist
    copyright
    exposureTime
    flash
    focalLength
    iso
    shutterSpeedValue
    software
    subjectDistance
    createDate
  }
}


query PhotographiesConnection(
  $photographiesConnectionWhere: PhotographyWhere
  $photographiesConnectionSort: [PhotographySort]
  $photographiesConnectionFirst: Int
  $photographiesConnectionAfter: String
) {
  photographiesConnection(
    where: $photographiesConnectionWhere
    sort: $photographiesConnectionSort
    first: $photographiesConnectionFirst
    after: $photographiesConnectionAfter
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...CorePhoto
        ...PhotoMetadata
        lens {
          make
          model
          id
        }
        camera {
          make
          model
          id
        }
      }
    }
  }
}

{
  "photographiesConnectionWhere": {
    "user": {
      "userId": "----"
    }
  },
  "photographiesConnectionSort": [
    {
      "createdAt": "DESC"
    }
  ],
  "photographiesConnectionFirst": 20,
  "photographiesConnectionAfter": "YXJyYXljb25uZWN0aW9uOjExOQ=="
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @sylv1b. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @sylv1b 
To help us replicate this problem, could you provide a small sample of data that replicates this issue?

**Comment by sylv1b** [comment]
> Hi @sylv1b To help us replicate this problem, could you provide a small sample of data that replicates this issue?

I just sent you an email :-)

**Comment by sylv1b** [comment]
Hi, 

 

Sorry for the late reply. Here is a dump of my Aura instance.

 

Sylvain Brochard

+46 (0)72  853 63 13

***@***.***  

 

De : angrykoala ***@***.***>
Répondre à : neo4j/graphql ***@***.***>
Date : jeudi 8 décembre 2022 à 12:06
À : neo4j/graphql ***@***.***>
Cc : Sylvain Brochard ***@***.***>, Mention ***@***.***>
Objet : Re: [neo4j/graphql] Cursor based pagination returning same items several times when sorting (Issue #2466)

 

Hi @sylv1b
Ideally, just a few Cypher queries create a small data sample that replicates the problem
e.g.

CREATE(:Photograph {key: "my-key"})
...
as it will let us confirm the problem and test that it is fixed.

**Comment by sylv1b** [comment]
Not an issue.
