### ISSUE TITLE
OGM, Alias on relationships throws error "Cannot return null for non-nullable field "

### ISSUE THREAD

**Issue by mikaelmattsson** [neo4j/graphql#2471]
**Describe the bug**
Any query where you use an alias on the relationship fails.

It throws an error like "Cannot return null for non-nullable field Movie.actors."

**To Reproduce**

```graphql
type Movie {
  name: String!

  actors: [Actor!]!
  @relationship(type: "ACTS_IN", direction: IN)
}
```

```graphql
query Movies {
  movies {
    name
    females: actors(where: {gender: "female"}) {
      name
    }
    males: actors(where: {gender: "male"}) {
      name
    }
  }
}

```

Tested on version 3.6.3 and 3.12.2

it works fine on top level queries. Just not on relationships.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mikaelmattsson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @mikaelmattsson, I haven't been able to reproduce this problem locally.

I also note that the type definitions in your example are incomplete as they do not include the `Actor` type.

Please can you provide a more complete example that I can use to reproduce this problem?

For reference, here are the type definitions and query I used to try to reproduce this:

Type definitions:
```graphql
type Movie {
    title: String!
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Person {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

Query:
```graphql
query Movies {
  movies {
    title
    myAlias: actors {
      name
    }
  }
}
```

**Comment by mjfwebb** [comment]
Closing this as it can't be reproduced. Please reopen if you can provide new information.

**Comment by mikaelmattsson** [comment]
This seems to happen on any field at any level, even simple strings.
Upgraded now to 3.14.2 but it is still an issue.
If there are no movies then it works.

The strange thing is that this works
```graphql
query Movies {
  movies {
   title
    t: title
  }
}
```

**Comment by mikaelmattsson** [comment]
I can confirm that it seems to be using the the “original field” when assigning the value for the alias.
```graphql
query Movies {
  movies {
    title
    actors(where: { name_CONTAINS: "a" }) {
      name
    }
    
    # this will only contain actors with a in their name, even tough it should contain all actors.
    myAlias: actors {
      name
    }
  }
}
```
