### ISSUE TITLE
Support _NOT_MATCHES filter (or equivalent at root level of queries)

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#2509]
**Is your feature request related to a problem? Please describe.**
Often writing a positive lookup regex is easier, more comprehensible and more performant than a negative lookup. When filtering on nested objects it's possible to effectively do a NOT_MATCHES query by nesting filters:

```
where: {
    deliveredBy_NOT: { email_MATCHES: "blah"}
}
```
It'd be nice to be able to do similar at the root level of the filter.

**Describe the solution you'd like**
Either of the following
- A `...NOT_MATCHES` filter
- A `NOT` 'operator' that - similar to `AND` and `OR` - can be used to construct a complex Boolean logic filter

**Comment by darrellwarde** [comment]
Indeed, a `NOT` operator is what we're going for, and we will be removing all of the `*_NOT_*` filters (such as `_NOT_CONTAINS`) in the next major release.

**Comment by wheresrhys** [comment]
Great news. Will you be adding the NOT operator in a minor release first so
that migrations are easier?

**Comment by darrellwarde** [comment]
Hey @wheresrhys, apologies, missed this comment! Hopefully that you've seen that this has indeed been added as a minor change. Enjoy!
