### ISSUE TITLE
Allow User to Pass in Decoded JWT to Context

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#252]
**Is your feature request related to a problem? Please describe.**
The current auth JWT functionality does not permit manual verification of tokens through third-party apps or using an RSA key. This makes it impossible to use with Firebase Auth, or any endpoint using a JWKS authentication schema (e.g., Auth0, Azure AD/B2C) since there is no simple secret to pass into the neo4j JWT config. 

**Describe the solution you'd like**
The ability to manually set the JWT claims in the context, either by overriding the JWT object or with a flag that indicates a second location for the JWT object.

**Describe alternatives you've considered**
The current workaround is to have the backend re-encode the already-decoded JWT with a secret that's then passed to the neo4j JWT config. It introduces two extra steps in front of the auth functionality for every request, one to reencode the token and the neo4j library's decoding of that token so it is not ideal. 

**Additional context**
Last communication from @darrellwarde in Discord:

> So the reason this didn't work for you is because of https://github.com/neo4j/graphql/blob/master/packages/graphql/src/classes/Neo4jGraphQL.ts#L120

> Because of that reassignment, anything you pass into the context yourself will get overridden if a JWT can't be found...

> There's obviously some use cases we haven't catered for here, which is to be expected as auth is a deep and complex subject area! I think the conclusion you've collectively come to, of setting the Authorization header, is the best you're going to get at the moment.

I'm not sure there's a security benefit here to keeping JWT's locked to only those than can decode simple secrets. Third-party libraries like Firebase Auth or the JWKS scheme use rotating keys and tokens which are far more preferable than a single secret. Plus people are already working around it by decoding these objects and then re-encoding them.

**Comment by tlester** [comment]
This is an important RFE.   Everything is great if you are paying for Auth0, fails, when you need to decode your own.

**Comment by jacob-buscher** [comment]
@litewarp 

I'm currently making firebase auth work by setting JWT to no verify and then verifying the token in the context function with the firebase admin library.

Not sure if that helps or not, here's my implementation:
```typescript
const neoSchema = new Neo4jGraphQL({
  typeDefs,
  driver,
  config: {
    jwt: {
      noVerify: true,
    } as any,
  },
});

const getAuth = async (req) => {
  const authHeader = req.headers.authorization;
  if (!authHeader) {
    return null;
  }
  const idToken = authHeader ? authHeader.split("Bearer ")[1] : req.body.token;
  return idToken && auth.verifyIdToken(idToken).catch(() => null);
};

const server = new ApolloServer({
  schema: neoSchema.schema,
  context: async ({ req }) => {
    const token = await getAuth(req);

    if (!token) {
      throw new AuthenticationError("Authentication required.");
    }

    return {
      req,
    };
  },
});
```

**Comment by litewarp** [comment]
@jacob-buscher Thanks. Yeah, that method works if you want to do a simple auth/non-auth check, but if you're trying to do field-level auth or use roles, you need to pass in the JWT. So you'd have to do something like this [gist](https://gist.github.com/litewarp/abdcfc991fa652605ab220b4dcbef01c)

**Comment by darrellwarde** [comment]
PR #303 is open to allow users to pass in decoded JWTs, just needs a little more testing and documentation but should be merged and released soon. 🙂
