### ISSUE TITLE
[Feature] Prevent generation of toxic CYPHER queries

### ISSUE THREAD

**Issue by jasperblues** [neo4j/graphql#2558]
## Problem 

A common problem with OGM tools (and thus generated GraphQL) is in managing performance with regards to generated queries. To ensure that the productivity boost of using an OGM layer (implicitly or directly) doesn't become a cost later, provide tooling to prevent the generation of toxic queries. 

It is possible to request a fragment that looks benevolent at face-value which nonetheless generates a toxic mega query consisting of over 10,000 lines of generated CYPHER. 

The generated query will be untenable and, when run, can bring down a whole production cluster. 

## Proposed Solution

Provide some parameters that would prevent such queries from running. 

I think it would be possible to analyze the generated CYPHER for red-flags in a sophisticated way, however suggest the starting simple, with something like: 

```
cypher.max.lines=1000 # Do not allow generated CYPHER of more than 1000 lines to run. 
cypher.warn.lines=500 # Issue a warning if generated CYPHER will result in a query longer than 500 lines
```

**Describe alternatives you've considered**
Suggest the above could be runtime errors, however another options is to provide a tool to use the OGM and schema to generate all queries in advance so that they can be sanity checked. 

It would then be possible to try out alternatives and re-run the tool. 

**Additional context**

**Comment by jasperblues** [comment]
Thanks @mjfwebb !

I can't share the _exact_ schema, as I don't have ability to disclose that on this particular commercial project. However here is a slightly obfuscated version: 

```graphql
fragment BaseEntityCore on BaseEntity {
  __typename
  sourceFile {
    __typename
    ...CloudFileSm
  }
  ...BaseEntitySm
  ... on TextEntity {
    __typename
    text
    textLower
  }
  ... on URLEntity {
    __typename
    url
  }
}

fragment BaseEntityFile on BaseEntity {
  __typename
  sourceFile {
    __typename
    ...CloudFileSm
  }
  ...BaseEntitySm
}

fragment BaseEntitySm on BaseEntity {
  __typename
  createdAt
  initiator {
    __typename
    uid
  }
  entityStatus
  entityType
  inSpaceID
  lastModified
  name
  nodeLabels
  scopedTo {
    __typename
    uid
  }
  uid
}

fragment CloudFileSm on CloudFile {
  __typename
  accessibleURL
  cloudURI
  fileSizeMb
  mimeType
  owner {
    __typename
    uid
  }
  sourceFor {
    __typename
    entityType
    uid
  }
  uid
  uploadedAt
}

fragment PayloadCore on Payload {
  __typename
  initiator {
    __typename
    ...UserIdentitySm
  }
  Payloads {
    __typename
    uid
  }
  parent {
    __typename
    entityStatus
    entityType
    uid
  }
  parentPayload {
    __typename
    contentTxt
    uid
  }
  events {
    __typename
    ...EventSm
  }
  readBySelf
  refsOutConnection {
    __typename
    edges {
      __typename
      isOriginalSource
      node {
        __typename
        ...BaseEntityCore
      }
      textRefStartIdx
      textRefType
    }
  }
  seenByConnection {
    __typename
    edges {
      __typename
      node {
        __typename
        uid
        username
      }
      seenAt
    }
  }
  initiator {
    __typename
    ...UserIdentitySm
  }
  sentIn {
    __typename
    imageURL
    name
    spaceType
    uid
  }
  ...PayloadSm
}

fragment PayloadSm on Payload {
  __typename
  contentRaw
  contentTxt
  createdAt
  initiator {
    __typename
    uid
  }
  deliveryStatus
  editedAt
  entityStatus
  isDeleted
  lastModified
  readBySelf
  threadID
  uid
}

fragment LinkedPayload on Payload {
  __typename
  Payloads {
    __typename
    ...PayloadCore
  }
  parent {
    __typename
    ...BaseEntityFile
  }
  parentPayload {
    __typename
    ...PayloadCore
  }
  ...PayloadCore
}

fragment EventMinimal on Event {
  __typename
  createdAt
  deletedForEntityID
  lastModified
  reaction
  reactor {
    __typename
    uid
  }
  uid
}

fragment EventSm on Event {
  __typename
  toEntityConnection {
    __typename
    edges {
      __typename
      node {
        __typename
        uid
      }
    }
  }
  ...EventMinimal
}

fragment UserIdentitySm on UserIdentity {
  __typename
  createdAt
  identity_type
  lastModified
  presenceStatus
  uid
  username
}
```

When we query for this: 

```graphql
query PayloadRelatedPayloads($where: PayloadWhere) {
  Payloads(where: $where) {
    __typename
    ...LinkedPayload
  }
}
```

. . . it produces over 10,000 lines of CYPHER (should be easy to repro) and kills even a quite beefy server with just instance of this query. We need to support hundreds of concurrent users per second, so are avoiding the use of the above, for the meantime. 

We suspect the polymorphic types may be one of the main contributing factors to the blow-out. 

This is just one example, there have been other occasions where something can seem reasonable at face value, but maps to an unworkable amount of CYPHER, hence the reason for a generic feature to catch that preemptively. 

Our development values are "communication" , "simplicity", "fast feedback", "courage" and "respect" - this type of feature aligns with the fast/useful/early feedback value.

**Comment by mjfwebb** [comment]
This sounds like an ideal use case for some GraphQL middleware to limit the complexity or depth of a query. For example, https://github.com/Escape-Technologies/graphql-armor can help introduce some sensible limits.

**Comment by jasperblues** [comment]
@mjfwebb thank you for the recommendation. I will look into this option.

**Comment by mjfwebb** [comment]
Great, closing this now then.
