### ISSUE TITLE
Custom resolver for [...] has not been provided

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#2560]
**Describe the bug**
I was migrating from the compute directive to the new customResolver directive and encountered a bug.
In the constructor of Neo4jGraphQL you can pass either an IResolver object or an array of IResolver objects for the resolvers.
We've spread our resolvers across multiple files, so we're passing in an array of resolvers. But when we do it this way, we get the error message that the resolver doesn't exist for the field with the customResolver directive. If I pass all resolvers as one object it works fine.

**Type definitions**
````typescript
const typeDefs = `
    type User {
        firstName: String!
        lastName: String!
        fullName: String! @customResolver(requires: ["firstName", "lastName"])
    }
`;

const resolvers = [
  { 
      User: {
          fullName(source) {
              return `${source.firstName} ${source.lastName}`;
          },
      },
  }
]; 

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    resolvers,
});
````

**System (please complete the following information):**
* Version: @neo4j/graphql@3.13.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
