### ISSUE TITLE
UNION query on explicit node label 

### ISSUE THREAD

**Issue by Hashdhi** [neo4j/graphql#2565]
interface Production {
    title: String!
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Movie implements Production {
    title: String!
    actors: [Actor!]!
    runtime: Int!
}

type Series implements Production {
    title: String!
    actors: [Actor!]!
    episodes: Int!
}

interface ActedIn @relationshipProperties {
    role: String!
}

type Actor {
    name: String!
    actedIn: [Production!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

Actor actedIn could be of type Movie/Series
When we query on explicit node label "Movie"
Query : 
query GetProductionsStartingWithThe {
    actors {
        name
        actedIn{
            title
            ... **on Movie** {
                runtime
            }
           
        }
    }
}

Cypher:
```
MATCH (this:`Actor`)

WITH *
CALL {
WITH *
CALL {
    WITH this
    MATCH (this)-[this0:ACTED_IN]->(this_Movie:`Movie`)

    RETURN { __resolveType: "Movie", runtime: this_Movie.runtime, title: this_Movie.title } AS this_actedIn
    **UNION**
    WITH this
    MATCH (this)-[this1:ACTED_IN]->(this_Series:`Series`)

    RETURN { __resolveType: "Series", title: this_Series.title } AS this_actedIn
}
RETURN collect(this_actedIn) AS this_actedIn
}
RETURN this { .name, actedIn: this_actedIn } AS this
```

1. Why generated cypher has UNION ?
2. How do we get only Movies of the actor actedIn?

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Hashdhi. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Hashdhi. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
