### ISSUE TITLE
Sorting by multiple fields fails if any field is `@cypher`

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#2577]
**Describe the bug**
When sorting by multiple fields, in some cases the generated cypher is invalid

**Type definitions**
```graphql
    type Movie{
        id: ID!
        title: String!
        oneActorName: String @cypher(statement: "MATCH (this)<-[:ACTED_IN]-(a:Person) RETURN a.name")
    }
```

**To Reproduce**
The following query: 
```graphql
query SortWithTopLevelCypher_only {
    movies(options: { limit: 5, sort: { title: ASC, oneActorName: DESC } }) {
        title
        oneActorName
    }
}
```
Fails with the error:
```
Neo4jError: Variable `this_oneActorName` not defined (line 7, column 42 (offset: 122))
"ORDER BY this.title ASC, this_oneActorName DESC"
```

The generated Cypher: 
```cypher
MATCH (this:`Movie`)

WITH *
ORDER BY this.title ASC, this_oneActorName DESC
LIMIT $param0
CALL {
    WITH this
    UNWIND apoc.cypher.runFirstColumnSingle("MATCH (this)<-[:ACTED_IN]-(a:Person) RETURN a.name", { this: this, auth: $auth }) AS this_oneActorName
    RETURN head(collect(this_oneActorName)) AS this_oneActorName
}
RETURN this { .title, oneActorName: this_oneActorName } AS this
```

**System (please complete the following information):**

* Version: @neo4j/graphql@3.14.0
* Neo4j 5.1.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
This only happens when the sorting fields are in a single object (`{field1: ASC, field2: DESC}`) and not with the recommended use case of the fields in separate objects: `[{field1: ASC}, {field2: DESC}]`
