### ISSUE TITLE
New @cypher argument columnName, break some query.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#2581]
**Describe the bug**
New @cypher argument columnName, break some query.

**Type definitions**
```graphql
type Author {
    name: String
    mostRecentBook: Book
        @cypher(statement: "MATCH (this)-[:AUTHORED_BOOK]->(b:Book) RETURN b AS result ORDER BY b.year DESC LIMIT 1", columnName: "result")
    mostRecentBooks: [Book!]
        @cypher(statement: "MATCH (this)-[:AUTHORED_BOOK]->(b:Book) RETURN b AS result ORDER BY b.year DESC LIMIT 5", columnName: "result")
    lastPublishedYear: Int
        @cypher(statement: "MATCH (this)-[:AUTHORED_BOOK]->(b:Book) RETURN b.year AS result ORDER BY b.year DESC LIMIT 1", columnName: "result")
    books: [Book!]! @relationship(type: "AUTHORED_BOOK", direction: OUT)
}

type Book {
    name: String!
    year: Int
    refID: ID @id
    soldCopies: Int @cypher(statement: "OPTIONAL MATCH(sales:Sales) WHERE this.refID = sales.refID WITH count(sales) as result RETURN result as result", columnName: "result")
    authors: [Author!]! @relationship(type: "AUTHORED_BOOK", direction: IN)
}

type Sales {
    price: Int
    refID: ID
}
```

**To Reproduce**
```graphql
query {
  authors {
    name
    mostRecentBook {
      name
      year
      soldCopies
    }
  }
}
```

**Expected behavior**
Return the correct number of copies sold.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
