### ISSUE TITLE
node directive label text is not working

### ISSUE THREAD

**Issue by Hashdhi** [neo4j/graphql#2614]
```
interface Production {
    title: String!
    actors: [Actor!]!
}

type Movie implements Production @node(label:"Film"){
    title: String!
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
    runtime: Int!
}

type Series implements Production {
    title: String!
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
    episodes: Int!
}

interface ActedIn @relationshipProperties {
    role: String!
}

type Actor {
    name: String!
    actedIn: [Production!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

```

```
query GetProductionsMovie {
 actors {
   actedIn (where: { _on: { Movie: {} } }){
      title
   }
 } 
}
```
**Generated Cyper :**
Cypher:
```
MATCH (this:`Actor`)

WITH *
CALL {
WITH *
CALL {
    WITH this
    MATCH (this)-[this0:ACTED_IN]->**_(this_Movie:`Movie`)_**

    RETURN { __resolveType: "Movie", title: this_Movie.title } AS this_actedIn
}
RETURN collect(this_actedIn) AS this_actedIn
}
RETURN this { actedIn: this_actedIn } AS this
```

Why Film label is not used here ? i.e this_Movie:`Film`

**Comment by tbwiss** [comment]
Hi @Hashdhi,
thanks for reaching out!
I think you discovered a bug here. Will update the labels.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Hashdhi! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Hashdhi. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
