### ISSUE TITLE
aggregate node selection causes error

### ISSUE THREAD

**Issue by bpurtz** [neo4j/graphql#2652]
**Describe the bug**
When you query the node field within an aggregate query, getting a syntax error:

```"message":"Variable `this_reviewsAggregate_var2` already declared in outer scope```

**Type definitions**
This is happening whenever you have a relationship, and then try to aggregate that relationship to get information. In my case, I had this type:

```gql
type Location @auth(rules: [{ isAuthenticated: true }]) {
    id: ID!
    name: String!
    name_lc: String!
    description: String!
    point: Point!
    placeId: String
    createdAt: DateTime!

    reviews: [LocationReview!]! @relationship(type: "HAS_REVIEW", direction: OUT)
}
```

**To Reproduce**

1: Create a schema with 2 types. One type should reference the other type as a field, such as reviews being referenced by the Location in the above example. 
2: Use apollo to query the relationship field aggregate, and try to query the node:

```gql
query ReviewsAggregate {
  locations {
    reviewsAggregate {
      count
      node {
        rating {
          average
        }
      }
    }
  }
}
```

By trying to query the node, it will throw the error.

**Expected behavior**
I expect no error to happen

**Screenshots**

**System (please complete the following information):**

* OS: M1 Macbook pro
* Version: @neo4j/graphql@3.14.1
* Node.js version: [e.g. 14.16.0]

**Additional context**

I have downgraded to @neo4j/graphql@3.12.2 and this error does not occur

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @bpurtz. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @bpurtz. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @bpurtz, just to ensure we have all the information we need to troubleshoot this, could you please provide your full type definitions?

I haven't been able to reproduce this currently.

**Comment by bpurtz** [comment]
@mjfwebb Thank you for the response :) I have gutted my typedefs in a branch to get a minimal reproducible example, and I will attach. I will also attach my package.json so you can see the current versions of dependencies. Let me know if you need any additional information. If you are unable to reproduce, could you drop your typedefs as well as your package.json that you're using to try to reproduce? Maybe it's a version of a dependency. Here is the full stack trace as well:
ERROR:
throw new Error(`Provided incorrect InputType: ${(0, misc_2.inspect)(typeDef)}`);
Error: TypeError[LocationSubscriptionWhere.point_IN]: Provided incorrect InputType: "[Point]"
    at TypeMapper.convertInputTypeDefinition (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/TypeMapper.js:335:23)
    at TypeMapper.convertInputFieldConfig (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/TypeMapper.js:387:36)
    at InputTypeComposer.setField (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/InputTypeComposer.js:127:46)
    at /Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/InputTypeComposer.js:133:18
    at Array.forEach (<anonymous>)
    at InputTypeComposer.addFields (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/InputTypeComposer.js:132:32)
    at Function.createTemp (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/InputTypeComposer.js:97:21)
    at Function.create (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/InputTypeComposer.js:59:26)
    at SchemaComposer.createInputTC (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/graphql-compose/lib/SchemaComposer.js:305:54)
    at generateSubscriptionWhereType (/Users/benjaminpurtzer/Documents/PetSocial/api/node_modules/@neo4j/graphql/dist/schema/subscriptions/generate-subscription-where-type.js:33:27)

TYPE DEFS:
/* eslint-disable @typescript-eslint/no-var-requires */
const { gql } = require("apollo-server");

const typeDefs = gql`
  type Location @auth(rules: [{ isAuthenticated: true }]) {
    id: ID!
    name: String!
    name_lc: String!
    description: String!
    point: Point!
    placeId: String
    createdAt: DateTime!

    reviews: [LocationReview!]!
      @relationship(type: "HAS_REVIEW", direction: OUT)
  }

  type LocationReview @auth(rules: [{ isAuthenticated: true }]) {
    id: ID!
    title: String!
    title_lc: String!
    review: String!
    rating: Int!
    createdAt: DateTime!

    location: Location @relationship(type: "HAS_REVIEW", direction: IN)
  }
`;

exports.typeDefs = typeDefs;


PACKAGE JSON DEPENDENCIES
"dependencies": {
    "@aws-crypto/sha256-browser": "^2.0.2",
    "@aws-sdk/client-s3": "^3.204.0",
    "@aws-sdk/hash-node": "^3.226.0",
    "@aws-sdk/protocol-http": "^3.226.0",
    "@aws-sdk/s3-request-presigner": "^3.231.0",
    "@aws-sdk/url-parser": "^3.226.0",
    "@aws-sdk/util-format-url": "^3.226.0",
    "@neo4j/graphql": "^3.13.1",
    "@neo4j/graphql-plugin-auth": "^1.1.1",
    "@neo4j/graphql-plugin-subscriptions-amqp": "^1.0.0",
    "apollo-server": "^3.6.2",
    "apollo-server-express": "^3.10.3",
    "aws-sdk": "^2.1261.0",
    "bcrypt": "^5.1.0",
    "body-parser": "^1.20.1",
    "cors": "^2.8.5",
    "dotenv": "^16.0.0",
    "eslint": "^8.25.0",
    "express": "^4.18.2",
    "express-http-proxy": "^1.6.3",
    "google-auth-library": "^8.7.0",
    "graphql": "^16.0.0",
    "graphql-ws": "^5.11.2",
    "http": "^0.0.1-security",
    "jsonwebtoken": "^8.5.1",
    "multer": "^1.4.5-lts.1",
    "multer-s3": "^3.0.1",
    "neo4j-driver": "^4.4.1",
    "uuid": "^9.0.0",
    "ws": "^8.11.0"
  },

**Comment by bpurtz** [comment]
I tried attaching files, but got an error saying it did not accept the file types. Here are the typedefs without the extension
[typedefs.txt](https://github.com/neo4j/graphql/files/10333917/typedefs.txt)
[package.json.txt](https://github.com/neo4j/graphql/files/10333919/package.json.txt)

**Comment by bpurtz** [comment]
@mjfwebb Thank you for the quick response :) I accidentally responded to with the wrong ticket in mind, so here is try 2 lol

I tore down my typedefs to the minimal reproducible example and will attach. I will also attach my package.json. Let me know if you need any additional information, and thank you for your time! Very much appreciated.

It does not let me attach .js or .json, so I added .txt to both to allow me to upload.

[package.json.txt](https://github.com/neo4j/graphql/files/10333935/package.json.txt)
[typedefs.js.txt](https://github.com/neo4j/graphql/files/10333936/typedefs.js.txt)

**Comment by mjfwebb** [comment]
Thanks @bpurtz! With those type definitions I've been able to reproduce it locally. For our information:

This is occurring on @neo4j/graphql 3.14.1 (latest version as of this writing).

Query:
```
query ReviewsAggregate {
  locations {
    reviewsAggregate {
      count
      node {
        rating {
          average
        }
      }
    }
  }
}
```

Type definitions:
```gql
export const typeDefs = gql`
    type Location @auth(rules: [{ isAuthenticated: true }]) {
        id: ID!
        name: String!
        name_lc: String!
        description: String!
        point: Point!
        placeId: String
        createdAt: DateTime!

        reviews: [LocationReview!]! @relationship(type: "HAS_REVIEW", direction: OUT)
    }

    type LocationReview @auth(rules: [{ isAuthenticated: true }]) {
        id: ID!
        title: String!
        title_lc: String!
        review: String!
        rating: Int!
        createdAt: DateTime!
    }
`;
```

Debug output:
```
Cypher:
MATCH (this:`Location`)
WHERE apoc.util.validatePredicate(NOT (apoc.util.validatePredicate(NOT ($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])

CALL {
    WITH this
    MATCH (this)-[this_reviewsAggregate_this0:HAS_REVIEW]->(this_reviewsAggregate_this1:`LocationReview`)
    WHERE apoc.util.validatePredicate(NOT (apoc.util.validatePredicate(NOT ($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])
    RETURN count(this) AS this_reviewsAggregate_var2
}

CALL {
    WITH this
    MATCH (this)-[this_reviewsAggregate_this0:HAS_REVIEW]->(this_reviewsAggregate_this1:`LocationReview`)
    WHERE apoc.util.validatePredicate(NOT (apoc.util.validatePredicate(NOT ($auth.isAuthenticated = true), "@neo4j/graphql/UNAUTHENTICATED", [0])), "@neo4j/graphql/FORBIDDEN", [0])
    RETURN { min: min(this_reviewsAggregate_this1.rating), max: max(this_reviewsAggregate_this1.rating), average: avg(this_reviewsAggregate_this1.rating), sum: sum(this_reviewsAggregate_this1.rating) }  AS this_reviewsAggregate_var2
}
RETURN this { reviewsAggregate: { count: this_reviewsAggregate_var2, node: { rating: this_reviewsAggregate_var2 } } } AS this
Params:
{
  "auth": {
    "isAuthenticated": false,
    "roles": []
  }
} +1s
  @neo4j/graphql:execute Neo4jError: Variable `this_reviewsAggregate_var2` already declared in outer scope (line 15, column 207 (offset: 1080))
"    RETURN { min: min(this_reviewsAggregate_this1.rating), max: max(this_reviewsAggregate_this1.rating), average: avg(this_reviewsAggregate_this1.rating), sum: sum(this_reviewsAggregate_this1.rating) }  AS this_reviewsAggregate_var2"
                                                                                                                                                                                                               ^

    at captureStacktrace (../graphql/node_modules/neo4j-driver-core/lib/result.js:611:17)
    at new Result (../graphql/node_modules/neo4j-driver-core/lib/result.js:105:23)
    at newCompletedResult (../graphql/node_modules/neo4j-driver-core/lib/transaction.js:502:12)
    at Object.run (../graphql/node_modules/neo4j-driver-core/lib/transaction.js:334:20)
    at TransactionPromise.Transaction.run (../graphql/node_modules/neo4j-driver-core/lib/transaction.js:175:34)
    at Executor.transactionRun (../graphql/packages/graphql/src/classes/Executor.ts:222:28)
    at ../graphql/packages/graphql/src/classes/Executor.ts:204:25
    at TransactionExecutor._safeExecuteTransactionWork (../graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:141:26)
    at TransactionExecutor.<anonymous> (../graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:128:46)
    at step (../graphql/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:52:23) {
  constructor: [Function],
  code: 'Neo.ClientError.Statement.SyntaxError',
  retriable: false
} +11ms
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @bpurtz! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by bpurtz** [comment]
I very much appreciate your swift action and prioritization! :)
