### ISSUE TITLE
Subscriptions with Point type throw error during schema augmentation

### ISSUE THREAD

**Issue by bpurtz** [neo4j/graphql#2653]
**Describe the bug**
If you use a point field, and then try to generate subscriptions from your schema, an error is thrown regarding an incorrect type.

**Type definitions**
This is a simple type def that would throw this error:

```gql
type Location {
    id: ID!
    name: String!
    name_lc: String!
    description: String!
    point: Point!
}
```

**To Reproduce**

1. Create simple schema with a point field within the type definition
2. Add in subscriptions via Neo4jGraphQLSubscriptionsSingleInstancePlugin (The same problem occurs with Neo4jGraphQLSubscriptionsAMQPPlugin)
3. Try to run the program, and it will throw an error similar to:
```Error: TypeError[LocationSubscriptionWhere.point_IN]: Provided incorrect InputType: "[Point]"```

**Expected behavior**
It should not throw error

**Screenshots**

**System (please complete the following information):**

* OS: M1 mac
* Version: @neo4j/graphql@3.14.1
* Node.js version: 16.13.1

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @bpurtz. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @bpurtz! :pray: We will now prioritise the bug and address it appropriately.

**Comment by bpurtz** [comment]
Thank you for your work on this issue!
