### ISSUE TITLE
[regression] Alias is not evaluated for aggregation queries

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2656]
given

```graphql
type User {
    name: String!
}
type Post {
    content: String!
    likes: [User!]! @relationship(type: "LIKES", direction: IN, properties: "Likes")
}
interface Likes {
    someString: String
    someStringAlias: String @alias(property: "_someStringAlias")
}
```

the query

```graphql
{
    posts(where: { likesAggregate: { edge: { someStringAlias_EQUAL: "10" } } }) {
        content
    }
}
```

generates:

```cypher
MATCH (this:Post)
CALL {
	WITH this
	MATCH (this1:User)-[this0:LIKES]->(this)
	RETURN any(var2 IN collect(this0.someStringAlias) WHERE var2 = $param0) AS var3
}
WITH *
WHERE var3 = true
RETURN this {
	.content
} AS this
```

expected usage of db property `_someStringAlias` instead of `someStringAlias`

```cypher
MATCH (this:Post)
CALL {
	WITH this
	MATCH (this1:User)-[this0:LIKES]->(this)
	RETURN any(var2 IN collect(this0._someStringAlias) WHERE var2 = $param0) AS var3
}
WITH *
WHERE var3 = true
RETURN this {
	.content
} AS this
```

The corresponding test case: 

https://github.com/neo4j/graphql/blob/3a47b5b90ececd965d0ec7613adb9f64d53b2828/packages/graphql/tests/tck/aggregations/where/edge/string.test.ts#L86-L117

was updated by https://github.com/neo4j/graphql/commit/0be20dd3f27678f6025214bf28e40920383151cf#diff-ed73cf61db37db9eb82b7115b5b5f9c83384cd6985681644d0aa771ba2d9ba1cR103-R109

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
