### ISSUE TITLE
Augmented Where-Input-Type is missing string comparison fields

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2657]
given

```graphql
type Movie {
  title: String
}
```

is creating the input type:

```graphql
input MovieWhere {
  AND: [MovieWhere!]
  OR: [MovieWhere!]
  title: String
  title_CONTAINS: String
  title_ENDS_WITH: String
  title_IN: [String]
  title_NOT: String
  title_NOT_CONTAINS: String
  title_NOT_ENDS_WITH: String
  title_NOT_IN: [String]
  title_NOT_STARTS_WITH: String
  title_STARTS_WITH: String
}
```

expected the input type to contain additional fields for comparing strings:

```graphql
input MovieWhere {
  AND: [MovieWhere!]
  OR: [MovieWhere!]
  title: String
  title_CONTAINS: String
  title_ENDS_WITH: String
  title_GT: String
  title_GTE: String
  title_IN: [String]
  title_LT: String
  title_LTE: String
  title_NOT: String
  title_NOT_CONTAINS: String
  title_NOT_ENDS_WITH: String
  title_NOT_IN: [String]
  title_NOT_STARTS_WITH: String
  title_STARTS_WITH: String
}
```

the cypher generation for comparing strings is already implemented but not reflected in the augmented schema:

https://github.com/neo4j/graphql/blob/3a47b5b90ececd965d0ec7613adb9f64d53b2828/packages/graphql/tests/tck/advanced-filtering.test.ts#L410-L434

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @Andy2003, whilst we were asked for these filters and did implement them, we put them behind a feature flag because, honestly, we think comparing strings in this manner is pretty messy. So if you look in that test file, you'll see the following in the setup:

```ts
        neoSchema = new Neo4jGraphQL({
            typeDefs,
            config: {
                enableRegex: true,
            },
            features: {
                filters: {
                    String: {
                        LT: true,
                        GT: true,
                        LTE: true,
                        GTE: true,
                    },
                },
            },
            plugins: {
                auth: new Neo4jGraphQLAuthJWTPlugin({
                    secret: "secret",
                }),
            },
        });
```
