### ISSUE TITLE
Inconsistent aggregation for Strings

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2661]
given

```graphql
type User {
    someFloat: Float
    name: String
}
type Post {
    content: String!
    likes: [User!]! @relationship(type: "LIKES", direction: IN)
}
```

The following `PostLikesNodeAggregationWhereInput` input type is generated:

```graphql
input PostLikesNodeAggregationWhereInput {
  AND: [PostLikesNodeAggregationWhereInput!]
  OR: [PostLikesNodeAggregationWhereInput!]
  name_AVERAGE_EQUAL: Float
  name_AVERAGE_GT: Float
  name_AVERAGE_GTE: Float
  name_AVERAGE_LT: Float
  name_AVERAGE_LTE: Float
  name_EQUAL: String
  name_GT: Int
  name_GTE: Int
  name_LONGEST_EQUAL: Int
  name_LONGEST_GT: Int
  name_LONGEST_GTE: Int
  name_LONGEST_LT: Int
  name_LONGEST_LTE: Int
  name_LT: Int
  name_LTE: Int
  name_SHORTEST_EQUAL: Int
  name_SHORTEST_GT: Int
  name_SHORTEST_GTE: Int
  name_SHORTEST_LT: Int
  name_SHORTEST_LTE: Int
  someFloat_AVERAGE_EQUAL: Float
  someFloat_AVERAGE_GT: Float
  someFloat_AVERAGE_GTE: Float
  someFloat_AVERAGE_LT: Float
  someFloat_AVERAGE_LTE: Float
  someFloat_EQUAL: Float
  someFloat_GT: Float
  someFloat_GTE: Float
  someFloat_LT: Float
  someFloat_LTE: Float
  someFloat_MAX_EQUAL: Float
  someFloat_MAX_GT: Float
  someFloat_MAX_GTE: Float
  someFloat_MAX_LT: Float
  someFloat_MAX_LTE: Float
  someFloat_MIN_EQUAL: Float
  someFloat_MIN_GT: Float
  someFloat_MIN_GTE: Float
  someFloat_MIN_LT: Float
  someFloat_MIN_LTE: Float
  someFloat_SUM_EQUAL: Float
  someFloat_SUM_GT: Float
  someFloat_SUM_GTE: Float
  someFloat_SUM_LT: Float
  someFloat_SUM_LTE: Float
}
```

I would expect the following fields to be of type `String`:

```
  name_GT: String
  name_GTE: String
  name_LT: String
  name_LTE: String
```

so they are handled the same way as `name_EQUAL`.

To aggregate by string length, the additional fields:

```
  name_SIZE_EQUAL: Int
  name_SIZE_GT: Int
  name_SIZE_GTE: Int
  name_SIZE_LT: Int
  name_SIZE_LTE: Int
```

can be introduced.

### Background

```graphql
{
    posts(where: { likesAggregate: { node: { someFloat_GT: 10 } } }) {
        content
    }
}
```

is generating 

```cypher
MATCH (this:`Post`)
CALL {
    WITH this
    MATCH (this1:\`User\`)-[this0:LIKES]->(this:`Post`)
    RETURN any(var2 IN collect(this1.someFloat) WHERE var2 > $param0) AS var3
}
WITH *
WHERE var3 = true
RETURN this { .content } AS this
```

where

```graphql
{
    posts(where: { likesAggregate: { node: { name_GT: 10 } } }) {
        content
    }
}
```

is generating 

```cypher
MATCH (this:`Post`)
CALL {
    WITH this
    MATCH (this1:\`User\`)-[this0:LIKES]->(this:`Post`)
    RETURN any(var2 IN collect(size(this1.name)) WHERE var2 > $param0) AS var3
}
WITH *
WHERE var3 = true
RETURN this { .content } AS this
```

So for all primitive types except `String` the `_LT` (and all other comparisons) are comparing the concrete value, but for strings it compares the length instead of the content.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Andy2003** [comment]
The `AVERAGE_*` fields for strings are also misleading. I would suggest to rename them to `AVERAGE_SIZE_*`.

**Comment by Andy2003** [comment]
Perhaps `*_LENGTH_*` would be even better than `*_SIZE_*`:

eg:

```
  name_LENGTH_EQUAL: Int
  name_LENGTH_GT: Int
  name_LENGTH_GTE: Int
  name_LENGTH_LT: Int
  name_LENGTH_LTE: Int
```

and 

```
  name_AVERAGE_LENGTH_EQUAL: Float
  name_AVERAGE_LENGTH_GT: Float
  name_AVERAGE_LENGTH_GTE: Float
  name_AVERAGE_LENGTH_LT: Float
  name_AVERAGE_LENGTH_LTE: Float
```

**Comment by darrellwarde** [comment]
I've relabelled this as a feature request - I think this has highlighted some changes we need to make to the API here, which we will be looking at making in our next major release. Thanks!

**Comment by Andy2003** [comment]
Would it be possible to define the necessary API adjustments in time, so that I can already work with it on the Java side?

**Comment by darrellwarde** [comment]
Sure, I'll try to remember to post the proposed changes here! 🙂

**Comment by MacondoExpress** [comment]
Hi @Andy2003, 
you're right about these inconsistencies, and I agree that adding the suffix `_LENGTH` would make the API more clear, although I wanted to point out that the operators:
  - name_EQUAL: String
  - name_GT: Int
  - name_GTE: Int
  - name_LT: Int
  - name_LTE: Int
  - someFloat_EQUAL: Float
  - someFloat_GT: Float
  - someFloat_GTE: Float
  - someFloat_LT: Float
  - someFloat_LTE: Float

Are not aggregation operations, and they do not belong here at all, in fact, you can achieve the following:

```graphql
query Query {
  posts(where: {
    likesAggregate: {
      node: {
        someFloat_GT: 2
      }
    }
  }) {
    content
  }
}
```
with:

```graphql
query Posts {
  posts(where: {
    likes_SOME: {
      someFloat_GT: 2
    }
  }) {
    content
  }
}
```
I would suggest that moving forward, in the next versions of the library, these operators will be removed from the aggregation filters and added as you suggest the suffix `_LENGTH` for aggregations of string fields!
