### ISSUE TITLE
Different behaviour for String-`AVERAGE_*` fields for norde and edge

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2662]
For the node `RETURN avg(size(this1.name)) = $param0 AS var2 `  is generated:

https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/tests/tck/aggregations/where/node/string.test.ts#L619-L650

vs

For the edge `RETURN avg(this0.someString) = $param0 AS var2 `  is generated:

https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/tests/tck/aggregations/where/edge/string.test.ts#L623-L654

See also : 

- https://github.com/neo4j/graphql/issues/2661#issuecomment-1369673043

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Andy2003** [comment]
This bug also applies for `LONGEST_*`- and  `SHORTEST_*`-fields

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
