### ISSUE TITLE
[regression] source node is counted instead of relations in aggregation query

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2665]
The generated cypher in this test looks wrong:

https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations.test.ts#L51-L79

The count should be done on the relation instead of the source node, like:

```cypher
MATCH (this:`Movie`)
CALL {
    WITH this
    MATCH (this_actorsAggregate_this1:`Actor`)-[this_actorsAggregate_this0:ACTED_IN]->(this)
    RETURN count(this_actorsAggregate_this0) AS this_actorsAggregate_var2
}
RETURN this { .title, actorsAggregate: { count: this_actorsAggregate_var2 } } AS this
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
