### ISSUE TITLE
Support Passing a Factory Method for the Driver

### ISSUE THREAD

**Issue by zprobst** [neo4j/graphql#2667]
**Is your feature request related to a problem? Please describe.**

We are working on enabling password rotation for the service user our API uses to access the database. The password rotation happens in an automated fashion and the password itself is stored in a secret store. There is no mechanism(that I can see) to reconfigure the driver if it receives an authentication error. 

**Describe the solution you'd like**
Instead of relying on the user to restart the service, it would be better if the neo4j graphql library supported taking a factory to get a driver that is called initially and after it gets an authentication exception from the database. If the query still fails after that, then it would be safe to return the error. Something like this:

```js
const getDriver = () => { 
    const password = "password" // get from secret store here 
    return neo4j.driver(
        "bolt://localhost:7687",
        neo4j.auth.basic("neo4j", password)
    );
}

const neoSchema = new Neo4jGraphQL({ typeDefs, getDriver });
```

**Describe alternatives you've considered**
A simple work around is to implement some process that restarts the service, gathering the credentials again. However that requires a more complex coupling between password rotation and the service itself.

**Comment by darrellwarde** [comment]
Hey @zprobst, I'm afraid this isn't a feature we plan to implement, it is _super_ specific to your particular use case which we have never seen anything remotely similar to before. If I was you, I would also look into whether you can use some logic when populating the context to "test" a driver before injecting into the `executionContext` field of the context, and fetch the new credentials if the test fails.

**Comment by zprobst** [comment]
Hi @darrellwarde. Thanks for replying.  I'll look into what you are saying with `executionContext` as a possible solution. I think what you are suggesting to do something like this:

```js
const server = new ApolloServer({
    schema,
    context: ({ req }) => {
       // check the driver and pass down a "good one" here. 
       return { req, executionContext: driver }
   }
});
```

However, I hope you'll be willing to reconsider in the future. I don't think password rotation is _super_ specific to anything. It's a fairly common practice in my opinion.
