### ISSUE TITLE
[regression] Alias is not resolved for edge aggregation

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2669]
This test is wrong:

https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts#L90-L121

expected db property `screentime` to be used.

This is caused by passing the node instead of the properties here:

https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/src/translate/field-aggregations/create-field-aggregation.ts#L131-L137

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
