### ISSUE TITLE
When using type with only 1 field which is @cypher directive, Apollo server fails 

### ISSUE THREAD

**Issue by cramatt** [neo4j/graphql#269]
**Describe the bug**
Consider the following schema. Notice the Voltage type has a single field, which uses the `@cypher` directive. 

```graphql
type Voltage {
  value: Float
  units: String
}

type HighVoltage {
  value: Boolean
    @cypher(
      statement: """
      MATCH (this)<-[:HAS_PROPERTY]-(c)-[:HAS_PROPERTY]->(v:Voltage)
      RETURN
      CASE
        WHEN v.value >= 1000  THEN true
        ELSE false
      END AS result
      """
    )
}

union PropertyTypes = Voltage | HighVoltage

type Motor {
  name: String
  voltage: VoltageTypes @relationship(type: "HAS_PROPERTY", direction: OUT)
}
```

When used with Apollo server in the GRANDStack starter project, the following error is thrown:

```
/Site/node_modules/graphql/type/validate.js:69
    throw new Error(errors.map(function (error) {
    ^
Error: Input Object type HighVoltageCreateInput must define one or more fields.
Input Object type HighVoltageUpdateInput must define one or more fields.
    at assertValidSchema (/Site/node_modules/graphql/type/validate.js:69:11)
    at assertValidExecutionArguments (/Site/node_modules/graphql/execution/execute.js:150:35)
    at executeImpl (/Site/node_modules/graphql/execution/execute.js:98:3)
    at Object.execute (/Site/node_modules/graphql/execution/execute.js:60:63)
    at Object.generateSchemaHash (/Site/api/node_modules/apollo-server-core/src/utils/schemaHash.ts:12:18)
    at ApolloServer.generateSchemaDerivedData (/Site/api/node_modules/apollo-server-core/src/ApolloServer.ts:822:24)
    at new ApolloServerBase (/Site/api/node_modules/apollo-server-core/src/ApolloServer.ts:421:33)
    at new ApolloServer (/Site/api/node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
    at Object.<anonymous> (/Site/api/src/index.js:111:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
```

To fix the issue one must add a second trivial field to the HighVoltage type. This is an OK workaround but not ideal.

**Type definitions**

See above

**To Reproduce**

1. Create a new GRANDStack starter project. 
2. Modify the schema to include the above
3. See the error

**Expected behavior**
I would expect the above type definition to work without needing an additional trivial field. GraphQL requires 1 or more fields are defined. 1 field is defined which is valid. Using the @cypher directive with it should not throw the above error. 

**Screenshots**

None

**System (please complete the following information):**

-   OS: [e.g. macOS]
-   Version: [e.g. @neo4j/graphql@1.0.0]
-   Node.js version: [14.17.0]

**Additional context**

None

**Comment by darrellwarde** [comment]
This has been a problem since day one, and something we're definitely aware of, but Mutation input makes this a tricky one!

For instance, take the `createHighVoltage` Mutation which would be generated, what would this look like?

```graphql
input CreateHighVoltageInput {
  ????????????????
}

type Mutation {
  createHighVoltages(input: [CreateHighVoltageInput!]!): CreateHighVoltageMutationResponse!
}
```

Given there is nothing to go in the `CreateHighVoltageInput`, that would mean our `createHighVoltages` Mutation would no longer work. The only way this could work is if we were to start introducing Mutations for single nodes, and we could have a `createHighVoltage` Mutation with no input, but this is a complete change to the way in which we generate our schema.

**Comment by danstarns** [comment]
> This has been a problem since day one, and something we're definitely aware of, but Mutation input makes this a tricky one!
> 
> For instance, take the `createHighVoltage` Mutation which would be generated, what would this look like?
> 
> ```graphql
> input CreateHighVoltageInput {
>   ????????????????
> }
> 
> type Mutation {
>   createHighVoltages(input: [CreateHighVoltageInput!]!): CreateHighVoltageMutationResponse!
> }
> ```
> 
> Given there is nothing to go in the `CreateHighVoltageInput`, that would mean our `createHighVoltages` Mutation would no longer work. The only way this could work is if we were to start introducing Mutations for single nodes, and we could have a `createHighVoltage` Mutation with no input, but this is a complete change to the way in which we generate our schema.

I agree with what Darrel said here. This is a tricky one and not much we can do about it. Your best option would be to add an arbitrary field to the type and don't use it. You could lock this field down with auth so no one can use it.

**Comment by danstarns** [comment]
I'm going to close this because there isn't much we can do about it 🤔
