### ISSUE TITLE
Aggregation: wrong cypher to compare durations

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2697]
Direct comparison of duration is not supported and so, the cypher queries generated by these tests are wrong:

* https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/tests/tck/aggregations/where/edge/duration.test.ts
* https://github.com/neo4j/graphql/blob/0d571437d2bf24790fa718ffdd81071d20cf49c5/packages/graphql/tests/tck/aggregations/where/node/duration.test.ts

Example:

```cypher
MATCH (this:`Post`)
            CALL {
                WITH this
                MATCH (this1:`User`)-[this0:LIKES]->(this:`Post`)
                RETURN any(var2 IN collect(this0.someDuration) WHERE var2 >= $param0) AS var3
            }
            WITH *
            WHERE var3 = true
            RETURN this { .content } AS this
```

should be

```cypher
MATCH (this:`Post`)
            CALL {
                WITH this
                MATCH (this1:`User`)-[this0:LIKES]->(this:`Post`)
                RETURN any(var2 IN collect(this0.someDuration) WHERE datetime() + var2 >= datetime() + $param0) AS var3
            }
            WITH *
            WHERE var3 = true
            RETURN this { .content } AS this
```

Background:

> The behavior you describe is intended and documented:
> https://neo4j.com/docs/cypher-manual/current/syntax/operators/#cypher-ordering
> 
> > [Duration](https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-durations) values cannot be compared, since the length of a day, month or year is not known without knowing which day, month or year it is. Since Duration values are not comparable, the result of applying a comparison operator between two Duration values is null.
> 
> If you want to compare duration values, you first need to add them to a common date/datetime like this:
> 
> ```
> RETURN date() + duration("P1D") <=  date() + duration("P1Y")
> ```
> 
> Alternatively, if you know that your durations only use the same [component groups](https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-accessing-components-durations), you can compare those:
> 
> ```
> RETURN duration("P1D").days <=  duration("P365D").days
> ```
 _Originally posted by @sherfert in https://github.com/neo4j/neo4j/issues/13019#issuecomment-1375340256_

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Another great spot! As already discussed, we will soon be doing a big review of the aggregation types, and I feel like these are some of the fields which are up for removal (they're essentially just filters!).

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
