### ISSUE TITLE
Aggregations filters produce invalid cypher when inside a relationship filter

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#2708]
**Describe the bug**
Aggregations filters produce invalid cypher when inside a relationship filter. This issue seems very similar to #2670, just in a different place.

**Type definitions**
```gql
type Movie {
  title: String!
  actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor {
  name: String!
  movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

**To Reproduce**

1. Execute the following Query:

```gql
{
  movies(where: {actors: { moviesAggregate: { count_GT: 10}  } }) {
    title
  }
}
```

2. See the following error:

```Variable `var1` not defined```

This is because the following cypher is produced:

```
MATCH (this:`Movie`)
WHERE EXISTS {
    MATCH (this0:`Actor`)-[:ACTED_IN]->(this)
    WHERE var1 = true
}


RETURN this { .title } AS this
```

**Expected behavior**
No error

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@3.14.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.
