### ISSUE TITLE
Check for at least one occurrence when filtering by connection_ALL 

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#2713]
do we need to check for at least one occurrence as well?

```cypher
MATCH (this:`Movie`)
CALL {
    WITH this
    MATCH (this)-[this0:IN_GENRE]->(this1:`Genre`)
    WHERE NOT (this1.name = $param0)
    RETURN count(this0) AS var2
}
CALL {
    WITH this
    MATCH (this)-[this0:IN_GENRE]->(this1:`Genre`)
    WHERE this1.name = $param0
    RETURN count(this0) AS var3
}
WITH *
WHERE var2 = 0 and var3  > 0
RETURN this { .actorCount } AS this"
```

_Originally posted by @Andy2003 in https://github.com/neo4j/graphql/pull/2679#discussion_r1066730856_

**Comment by Liam-Doodson** [comment]
For more context this would mean that results are not returned for the following typedefs/query:

```gql
type Movie {
    _id: ID
    id: ID
    title: String
    actorCount: Int
    budget: BigInt
    genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT)
}
type Genre {
    name: String
    movies: [Movie!]! @relationship(type: "IN_GENRE", direction: IN)
}
```

```gql
{
    movies(where: { genresConnection_ALL: { node: { name: "some genre" } } }) {
        actorCount
    }
}
```

Movies are not returned when there are no connected genres.

This seems to be the behaviour for the equivalent filter on relationships.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
