### ISSUE TITLE
Nested query using @cypher directives return wrong results

### ISSUE THREAD

**Issue by tranphong1991** [neo4j/graphql#273]
**Describe the bug**
Currently, I encounter a bug when I try to migrate from neo4j-graphql-js. The @cypher directives does not work when I return a certain type and go deep into another nested level

**Type definitions**
```
type Product {
	id: ID!
	description: String
	name: String
	price: Float!
	lots: [Lot] @relationship(type: "ASSIGNED_TO", direction: IN)
}

type Lot {
	id: String!
	lotNumber: String!
	status: String
	stock: Float
	expiredDate: Float
}

type Query {
	getProductbyCypher: Product
	@cypher(
		statement: """
		MATCH (product:Product {id:"gmPBv5AkXNPhIeUKjkmf"})
		RETURN product
		"""
	)
}
```

**To Reproduce**
1. I run the autogenerate query on Product in which I want to return Lot which work well.

```
{
  products(where:{id:"gmPBv5AkXNPhIeUKjkmf"}) {
    id
    name
    lots {
        id
    }
  }
}
```
Response

```
{
    "data": {
        "products": [
            {
                "id": "gmPBv5AkXNPhIeUKjkmf",
                "name": "test lot",
                "lots": [
                    {
                        "id": "uRxc9KwCl9bJQr9GFb9i"
                    }
                ]
            }
        ]
    }
}
```

2. I tried this with @cypher directive query, it should return the same thing for `lots`, however it return null.

```
{
  getProductbyCypher {
    id
    name
    lots {
        id
    }
  }
}
```

Response

```
{
    "data": {
        "getProductbyCypher": {
            "id": "gmPBv5AkXNPhIeUKjkmf",
            "name": "test lot",
            "lots": null
        }
    }
}
```
This is the reproduce for every case with @cypher directives. 

**Expected behavior**
Lots should show some results

**Screenshots**
![Screen Shot 2021-06-19 at 11 02 49 PM](https://user-images.githubusercontent.com/26109589/122648239-7bd4d000-d152-11eb-964f-5ce90915d577.png)

**System (please complete the following information):**

-   OS: [macOS]
-   Version: [@neo4j/graphql@1.0.1, 2.0.0-alpha.2]
-   Node.js version: [e.g. 12.13.0]

**Additional context**
This stop me to migrate from neo4j-gaphql-js

**Comment by dmoree** [comment]
This is a known issue #227 regarding the `cypher` directive and nested relationships. There is an open PR #251 regarding a fix.

**Comment by danstarns** [comment]
@tranphong1991 Thank you for raising this. Going to close in favour of the issue @dmoree linked. Cheers.
