### ISSUE TITLE
@neo4j/graphql server setup not working with the latest @apollo/server v4

### ISSUE THREAD

**Issue by rohit-uf** [neo4j/graphql#2739]
**Describe the bug**
I am following [this](https://neo4j.com/docs/graphql-manual/current/getting-started/) tutorial. But instead of `apollo-server` package, I tried the latest version of apollo server (v4) i.e. `@apollo/server` and I am getting the following error
```sh
Error: Type Query must define one or more fields.
    at assertValidSchema (D:\work\buildux\experiments\neo4j-tutorial\graphql-neo4j\node_modules\graphql\type\validate.js:59:11)
    at Function.generateSchemaDerivedData (D:\work\buildux\experiments\neo4j-tutorial\graphql-neo4j\node_modules\@apollo\server\dist\cjs\ApolloServer.js:332:41)   
    at new SchemaManager (D:\work\buildux\experiments\neo4j-tutorial\graphql-neo4j\node_modules\@apollo\server\dist\cjs\utils\schemaManager.js:21:44)
    at new ApolloServer (D:\work\buildux\experiments\neo4j-tutorial\graphql-neo4j\node_modules\@apollo\server\dist\cjs\ApolloServer.js:96:36)
    at D:\work\buildux\experiments\neo4j-tutorial\graphql-neo4j\server.js:19:20
```
 
**Type definitions**
```gql
type Movie{
  title: String
  actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor{
  name: String,
  movies: [Movie!]! @relationship(type: "ACTED_IN", direction : OUT)
}
```

**To Reproduce**

1. Create a basic node project
2. Follow [this](https://neo4j.com/docs/graphql-manual/current/getting-started/) tutorial, and instead of `apollo-server`, install the `@apollo/server` dependency
3. Run the main file

**Expected behavior**
I expected that the GraphQL Server will be available after following the tutorial

**Screenshots**
![image](https://user-images.githubusercontent.com/103091956/212648050-934871d9-d6c5-49bd-b0f9-601f0cb8e0f7.png)

**System (please complete the following information):**

* OS: Windows 11
* Version:
  * `@neo4j/graphql`  : 3.14.2
  * `@apollo/server` : 4.3.0

* Node.js version: 16.13.1

**Additional context**

<details>
<summary>Here is my main JS file</summary>

```js

const { ApolloServer } = require('@apollo/server')
const { startStandaloneServer }  = require('@apollo/server/standalone');    // Creates express app and installs apolloserver as middleware
const fs = require('fs');
const { Neo4jGraphQL } = require('@neo4j/graphql');
const {printType} = require('graphql');
const neo4j = require('neo4j-driver');

const gql_schema = fs.readFileSync('./schema.gql', {encoding: 'utf-8', flag: 'r'});

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("neo4j", "pass")
);

const neoSchema = new Neo4jGraphQL({gql_schema, driver});

neoSchema.getSchema().then((schema)=>{

    const server = new ApolloServer({
        typeDefs: schema,
    });

    startStandaloneServer(server, {
        listen: {port: 3000}
    }).then(url=>{
        console.log(url);
    }).catch(err=>{
        console.log(1);
        console.log(err);
    });

}).catch(err=>{
    console.log(err);
});
```
</details>

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @rohit-uf. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
You have at least one typo in your code, you need to ensure the `typeDefs` key is provided to our library:

> ```js
> const neoSchema = new Neo4jGraphQL({ typeDefs: gql_schema, driver });
> ```

Other than that, make sure you're using GraphQL 16 - I've seen the error you're encountering when using GraphQL 15.

**Comment by rohit-uf** [comment]
I am using GraphQL 16.6.0.

Your solution worked like a charm @darrellwarde. Basic JS parameter passing that I messed 😓 

Thanks 👍
