### ISSUE TITLE
Using patterns for labels

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#2765]
In Neo4j 5, [patterns for labels](https://neo4j.com/docs/cypher-manual/current/syntax/patterns/#cypher-pattern-label) were introduced. These can be used to achieve some behaviours, such as creating fields that resolve to multiple relationships as in [this](https://discord.com/channels/787399249741479977/1065322751725936670) discord conversation.

This behaviour is currently not officially supported in the library and will break some features such as mutations, as patterns are not expected in the label name. We could either add some support, provide alternatives or document these

**Comment by MacondoExpress** [comment]
I'm curious about the implication of the usage of these, in my opinion, it could lead to unexpected results.
Potentially, we could validate the user input to raise an error during the startup.

**Comment by darrellwarde** [comment]
We will be introducing further automatic escaping in the next major release, and this will be tested.
