### ISSUE TITLE
Firebase JWT tokens not working with Neo4jGraphQLAuthJWTPlugin

### ISSUE THREAD

**Issue by yaakovyitzchak** [neo4j/graphql#2781]
B"H
**Describe the bug**
Trying to follow the steps to mak ea basic isAuthenticated check with a firebase JWT token, its always unauthetnicated

```
#graphql    

    type Why  {
        name: String @auth(rules:[
                {
                    isAuthenticated: true
                }
        ])
    }

```

**To Reproduce**
Here is the entire code:
`//B"H

var schema = `#graphql
    type Query {
        hi: String 
    }

    type Why  {
        name: String @auth(rules:[
                {
                    isAuthenticated: true
                }
        ])
    }

`

var http = require("http")
var neoGr = require("@neo4j/graphql")
var apollo = require("@apollo/server")
var exp4 = require("@apollo/server/express4")

var neoDriver = require("neo4j-driver")

var secret = require("../credentials/m.json")
var pk = require("./publicKey.json")
var key = pk.key;

var neoAuth = require("@neo4j/graphql-plugin-auth")

var cors = require("cors")
var bodyp = require("body-parser")
var ex = require("express")

var dr = neoDriver.driver(
    "",
    neoDriver.auth.basic(
        "neo4j",
        "password"
    )
)

var neoSchema = new neoGr.Neo4jGraphQL({
    typeDefs: schema,
    resolvers:{},
    driver: dr,
    plugins: {
        auth: new neoAuth
        .Neo4jGraphQLAuthJWTPlugin({
            secret: key
        })
    }
})

neoSchema.getSchema()
.then(sch=>{
    var app = ex()
    var httpServer = http.createServer(app)

    var server = new apollo.ApolloServer({
        schema: sch,
        context: async ({req}) => {
            console.log("a!")
            return ({req})
        }
    })
    
    server.start().then(() => {
        
        
        app.use(
            "/awtsmoos",
            cors(),
            bodyp.json(),
            exp4.expressMiddleware(
                server, {
                    context: async ({req}) => {
                        console.log("a!",req.auth)
                        return ({req});
                    }
                }
            )
        )
        httpServer.listen(8080,() => {
            console.log("Started!")
        })
        
    })
    
})
`

the "credentials/m.json" is a service key taken from firebase settings. at first for the "secret" I was using secret.private_key, then I tried using the PUBLIC key derived based on the instructions here https://firebase.google.com/docs/auth/admin/verify-id-tokens#:~:text=Grab%20the%20public%20key%20from,to%20refresh%20the%20public%20keys. with the same result. Both ways are not working

Access the query with a basic firebase JWT token, like:
Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQwNTU5YzU5MDgzZDc3YWI2NDUxOThiNTIxZmM4ZmVmZmVlZmJkNjIiLCJ0eXAiOiJKV1QifQ.eyJpZCI6IjMyZDg5OTZkLTQwNzctNDQxMC1hYzFjLWE0ZmY4MWFmMTQwYSIsInJvbGVzIjpbIkFETUlOIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9tYXRjaG1ha2VyLWFwcC1mYzQzZSIsImF1ZCI6Im1hdGNobWFrZXItYXBwLWZjNDNlIiwiYXV0aF90aW1lIjoxNjc0NjI1NTk1LCJ1c2VyX2lkIjoiaWM1QUNRSm04QlpvOGdSVjRHT1d2VzJvU3pmMiIsInN1YiI6ImljNUFDUUptOEJabzhnUlY0R09Xdlcyb1N6ZjIiLCJpYXQiOjE2NzQ2MjU1OTUsImV4cCI6MTY3NDYyOTE5NSwiZW1haWwiOiJhc2Q1QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhc2Q1QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.S_c8ws8hdb4mQyTpZZIqjg8WFyiMp87plk7erkPVvvn7XHFM8-EwNEE_eDEWhT-YrgP-NPryrP7Gp2U9hzXpB0fRXP5IpOnKuzHCR0m79vXIOKBvCE5S7BHYReg1TqPTan_Lpj6OQ0kVWqrxkLvgiIBPXTJ3DKJwAC9xj_3N8TbJpU7KEnNbXED-GMGlATcupAf2eIquKWp-9oolusqHjq1YiovvuRZpTV6Kec4Pewd9YD2rUjauFElv1Db8d4EOpmYnfst4WqkgDaNH9Wn3oxDVrgaTFSG5OGmj5SztWxqKMHA0kF-Fa-ACjqlQBKEfyvp5dhxJV_BSIPLu_V1OZA

(it expired, but not sure if that matters here)

then try a standard mutation, the above code should NOT work (say "unauthetnicated"):

`
mutation ch {
  createWhies(input: [
    {
      name: "Hi"
    }
  ]) {
    whies {
      name
    }
  }
}`

this is tested to work with OTHER Jwt tokens, but regarding firebase, I'm not sure what to put for the secret, other than either the private key or the public key?
**Expected behavior**
It should allow me to get the 

**Screenshots**

![Screenshot from 2023-01-25 02-20-05](https://user-images.githubusercontent.com/46662394/214503396-b6639438-fde5-49b5-9259-6f3bf0607c31.png)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @yaakovyitzchak. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @yaakovyitzchak. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @yaakovyitzchak 
This seems to be a problem integrating Firebase.

As you mentioned, your case is working with other JWT tokens and doesn't seem to be a problem with the library itself so not really anything we can do about this here, unless we can find a reproducible case of a bug with the library.
Please make sure you follow any documentation provided by Firebase on how to integrate their authentication with 3rd party libraries and that both the secret and expiration are valid. You may find helpful https://jwt.io/ to test your tokens independently from our library

**Comment by yaakovyitzchak** [comment]
BH

Hi

We're your able to reproduce the bug using a firebase token? In other words
were you able to verify the firebase token using your library?

**Comment by angrykoala** [comment]
Hi @yaakovyitzchak 
As mentioned before, unless a reproducible token with a valid secret is provided, debugging a full integration is difficult, please provide an example token and secret that is not working for you so it can be reproduced under the same conditions.

Please, make sure that token and secret are examples, and not production tokens
