### ISSUE TITLE
[regression] Conflicting parameters when disconnect multiple nested fields

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#2782]
given the schema ([taken from the tests](https://github.com/neo4j/graphql/blob/a66deb9d13e027c4b4076477681d3dbeca60968d/packages/graphql/tests/tck/operations/disconnect.test.ts))

https://github.com/neo4j/graphql/blob/a66deb9d13e027c4b4076477681d3dbeca60968d/packages/graphql/tests/tck/operations/disconnect.test.ts#L32-L56

the query:

https://github.com/neo4j/graphql/blob/a66deb9d13e027c4b4076477681d3dbeca60968d/packages/graphql/tests/tck/operations/disconnect.test.ts#L67-L105

is using the parameter `updateProducts_args_update_photos0_disconnect_disconnect_color_where_Colorparam0` with value `Red` twice.

there should be two different params:

1. `updateProducts_args_update_photos0_disconnect_disconnect_color_where_Colorparam0` with value `Green`
2. `updateProducts_args_update_photos0_disconnect_disconnect_color_where_Colorparam1` with value `Red`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
