### ISSUE TITLE
Wrongly generated cypher when using combining operators AND/OR

### ISSUE THREAD

**Issue by teenkevo** [neo4j/graphql#2801]
**Describe the bug**
Wrong cypher is generated when using combining operators AND/OR in some situations

**Type definitions**
```graphql
type Organization {
  organizationId: ID! @id
  admins: [Admin!]! @relationship(type: "HAS_ADMINISTRATOR", direction: OUT)
  students: [Student!]! @relationship(type: "HAS_STUDENT", direction: OUT)
  parents: [Parent!]! @relationship(type: "HAS_PARENT", direction: OUT)
  teachers: [Teacher!]! @relationship(type: "HAS_TEACHER", direction: OUT)
}

type Admin {
  userId: String!
}

type Student {
 userId: String!
}

type Teacher {
 userId: String!
}
```
```graphql
query Organizations($where: OrganizationWhere) {
  organizations(where: $where) {
    title
  }
}


{
  "where": {
    "OR": [
      {
        "admins_SOME": {
          "userId": "auth0|63cad8c11d4294581f2373fe",
        },
        "students_SOME": {
          "userId": "auth0|63cad8c11d4294581f2373fe",
        },
        "teachers_SOME": {
          "userId": "auth0|63cad8c11d4294581f2373fe",
        }
      }
    ]
  }
}
``` 

**To Reproduce**

Run the query and you will see the cypher below generated. It is wrong cypher
The returned cypher
```cypher
WHERE ((EXISTS {
    MATCH (this)-[:HAS_ADMINISTRATOR]->(this0:`Admin`)
    WHERE this0.userId = "auth0|63cad8c11d4294581f2373fe"
} AND EXISTS {
    MATCH (this)-[:HAS_STUDENT]->(this1:`Student`)
    WHERE this1.userId = "auth0|63cad8c11d4294581f2373fe"
} AND EXISTS {
    MATCH (this)-[:HAS_TEACHER]->(this2:`Teacher`)
    WHERE this2.userId = "auth0|63cad8c11d4294581f2373fe"
})) 
```

**Expected behavior**
This is the correct cypher
```cypher
WHERE ((EXISTS {
    MATCH (this)-[:HAS_ADMINISTRATOR]->(this0:`Admin`)
    WHERE this0.userId = "auth0|63cad8c11d4294581f2373fe"
} OR EXISTS {
    MATCH (this)-[:HAS_STUDENT]->(this1:`Student`)
    WHERE this1.userId = "auth0|63cad8c11d4294581f2373fe"
} OR EXISTS {
    MATCH (this)-[:HAS_TEACHER]->(this2:`Teacher`)
    WHERE this2.userId = "auth0|63cad8c11d4294581f2373fe"
})) 

```

**Screenshots**

**System (please complete the following information):**

* OS: macOS Ventura 13.2
* Version: @neo4j/graphql@13.14.2
* Node.js version: 14.17.4

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @teenkevo. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @teenkevo. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @teenkevo! :pray: We will now prioritise the bug and address it appropriately.

**Comment by teenkevo** [comment]
@angrykoala this makes sense now. Thanks for your prompt response.
