### ISSUE TITLE
Invalid cypher when filtering by an aggregate in double nested relationships/connections

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#2803]
**Type definitions**

```graphql
type Movie {
    actors: [Actor!]! @relationship(type: "HAS_ACTOR", direction: OUT)
    released: Int!
}

type Actor {
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
    name: String
}
```

**Query**

```graphql
query {
    actors(where: { movies_SOME: { actors: { moviesAggregate: { count_GT: 0 } } } }) {
        name
    }
}
```

**Cypher**
```
MATCH (this:`Actor`)
OPTIONAL MATCH (this0)-[:HAS_ACTOR]->(this1:`Actor`) # This OPTIONAL MATCH should match all the way from this to this1 so the aggregation subquery has the correct info
CALL {
    WITH this1
    MATCH (this1)-[this2:ACTED_IN]->(this3:`Movie`)
    RETURN count(this3) > $param0 AS var4
}
WITH this0, collect(var4) AS var4 # This WITH should use this not this0
WITH *
WHERE EXISTS {
    MATCH (this)-[:ACTED_IN]->(this0:`Movie`)
    WHERE EXISTS {
        MATCH (this0)-[:HAS_ACTOR]->(this1:`Actor`)
        WHERE true IN var4
    }
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.
