### ISSUE TITLE
Prevent sort/where/aggregate by a @writeonly field 

### ISSUE THREAD

**Issue by vpctorr** [neo4j/graphql#2804]
**Is your feature request related to a problem? Please describe.**

Setting @/writeonly on a field doesn't prevent using that field with sort and where and aggregate.

**Describe the solution you'd like**

Something along the lines of `@/writeonly(allowSort: Boolean, allowFilter: Boolean)` which would default to true, so it is not breaking.
Fields marked as @/writeonly should perhaps be excluded from aggregate selection by default?

**Describe alternatives you've considered**

As there is no way to transform/validate inputs without creating a top-level mutation, I'm using a callback on a second field to set the actual value. The ability to use @/private alongside @/populatedBy would solve the issue in my case, but this is currently not possible.

**Comment by darrellwarde** [comment]
We now have more fine-grained access control directives in `@filterable`, `@selectable` and `@settable`. We just need to implement `@sortable`, but I'll close this issue as `@writeonly` doesn't even exist any more. Docs here: https://neo4j.com/docs/graphql/current/schema-configuration/field-configuration
