### ISSUE TITLE
Filtering on fields in authorization for  allow and where.

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#2811]
**Is your feature request related to a problem? Please describe.**
Filtering on fields in authorization for  `allow` and `where`. This would allow even more declarative and expressive authorization logic.

**Describe the solution you'd like**
As far as I read it in the documentation it is not possible to do something like this:

```
extend type User @auth(
    rules: [
        {
            operations: [READ],
            allow: { uri_STARTS_WITH: "$jwt.uri" }
        }
    ]
)
```
OR
```
extend type User @auth(rules: [
    {
        where: { username: "$jwt.id" }
    }
    {
        where: { username_NOT_CONTAINS: "system" }
    }
])
```
OR
```
extend type PsychologicalEvaluationRecord @auth(rules: [
    {
        roles: ["psychologist"]
        where: { birthYear_LTE: $ctx.currentLegalAgeBirthYear }
    }
    {
        roles: ["child_psychologist"]
    }
])
```

**Describe alternatives you've considered**
I haven't tried implementing above rules, so if this is already available: please consider updating the documentation and close this issue.

I also considered if these fields should be stored in the database as distinct values, for example `birthYear` could be replaced with `isChild: true/false` or `username_NOT_CONTAINS: "system"` be replaced by `systemUser: true/false`. But that requires adding this to the schema and storing these values for every node. In the case of birthYear it would need to be updated on each node every year instead of injecting the current year in the context or the JWT.

**Additional context**
N/A

**Comment by darrellwarde** [comment]
Hi, this requirement is already covered in #1871, and will soon be introduced in a rearchitecture of auth. Thanks!
