### ISSUE TITLE
Items of interfaces are wrongly merged.

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#2820]
When selecting items of an interface without selecting a unique property (such as the id)

Let's say we have the following types:

```GraphQL
interface I {
  id: ID! @id
  foo: String!
}


type A implements I {
  id: ID! @id
  foo: String!
}

type B implements I {
  id: ID! @id
  foo: String!
}

type C {
  missingItems: [I!]! @relationship(type: "IN_C", direction: IN)
}
```

Let's say we have two nodes of type A and one of type B, all with the same text on "foo" but a different id.

And the query:

```GraphQL
{
 c {
   foo
 }
}
```

This will only return a single item, since no unique field is included and the query is translated to a UNION query.
In this case a possible workaround is to query the id, however the problem is more subtle if a connection is used:

```GraphQL
{
 cConnection {
   totalCount
 }
}
```

This would return the wrong count (1). The only way to avoid this is to also retrieve a unique field which defeats the purpose of just getting the count.

Possible fix: It appears like the neo4j GraphQL library should internally include the ID(n) of the node n for each sub-query that is included in the UNION kind of like this __ID field here:

```
        CALL {
            WITH ...
            MATCH (...)<-[x1:LABEL]-(...)
            WITH { node: { __resolveType: "A", __ID: ID(x1) } } AS edge
            UNION
            WITH ...
            MATCH (...)<-[x2:LABEL]-(...)
            WITH { node: { __resolveType: "B", __ID: ID(x2) } } AS edge
            RETURN edge
        }
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @jroith! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
