### ISSUE TITLE
Relationships to interface types cause problems if the field is mandatory

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#2847]
**Describe the bug**
Relationships to interface types cause problems if the field is mandatory. The object can be created with a mutation, although a mandatory field was not specified. 
If the just created object is read out, there are also problems, but only if the field is queried, which is actually mandatory.

I think there are two separate issues here. Firstly, the input type is not generated correctly (see screenshot below). And on the other hand a query of a type should lead to an error if a mandatory field is not present

**Type definitions**
````gql
interface Product {
  name: String!
}

type Movie implements Product {
  name: String!
}

type Actor {
  name: String!
  product: Product! @relationship(type: "HAS_PRODUCT", direction: OUT)
}
````
See ActorCreateInput from Introspection:
![image](https://user-images.githubusercontent.com/49721200/217137160-4068d9fd-9719-420c-9a78-432d15f56fc8.png)
product is not mandatory, but should

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...
````gql
mutation {
  createActors(input: {
    name: "TestActor"
  }) {
    actors {
      name
    }
  }
}
````
Response: Should not work, but it does
````json
{
  "data": {
    "createActors": {
      "actors": [
        {
          "name": "TestActor"
        }
      ]
    }
  }
}
````
3. Then run the following Query...
Works:
````gql
query {
  actors {
    name
  }
}
````
````json
{
  "data": {
    "actors": [
      {
        "name": "TestActor"
      }
    ]
  }
}
````
Doesn't work:
````gql
query {
  actors {
    name
    product {
      name
    }
  }
}
````
````json
{
  "data": {
    "actors": []
  }
}
````
Why is the response empty but successful? I would rather have expected there to be an error response because there is no value for a required field in the database.

**Expected behavior**
- Input types for interface relationships must be generated correctly
- Query must result in an error if a mandatory field is not present.

**System (please complete the following information):**
* Version: @neo4j/graphql@3.16.0
* Node.js version: 16.16.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.
