### ISSUE TITLE
Option to disable generation of mutations at runtime

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#2854]
Currently the generated GraphQL can become extremely large (requiring a few GB of memory). Besides the predicates the other reason for that seem to be mutations. However, mutations are not always necessary or not necessary on all instances. It would be useful to be able to run scalable read-only instances that generate no mutations, thereby significantly reducing the memory requirements of those nodes.

**Comment by darrellwarde** [comment]
Hey @jroith, this was actually discussed coincidentally in the team today! We are probably _not_ going to add this into the library, and instead offer guidance on how to use `@graphql-tools/wrap` to achieve the same value.

For example, the following code will remove all Mutations from your schema, and prune the resulting unused types:

```js
import { Neo4jGraphQL } from "@neo4j/graphql";
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";
import { wrapSchema, FilterTypes, PruneSchema } from "@graphql-tools/wrap";
import { gql } from "graphql-tag";
import * as neo4j from "neo4j-driver";

const typeDefs = gql`
  type Movie {
    title: String!
  }
`;

const driver = neo4j.driver(
  "neo4j://localhost:7687",
  neo4j.auth.basic("neo4j", "password")
);

const neo4jgraphql = new Neo4jGraphQL({ typeDefs, driver });

let schema = await neo4jgraphql.getSchema();

const mutationFilter = (type) => {
  return type.name !== "Mutation";
};

schema = wrapSchema({
  schema,
  transforms: [new FilterTypes(mutationFilter), new PruneSchema()],
});

const server = new ApolloServer({ schema });

const { url } = await startStandaloneServer(server, {
  listen: { port: 4000 },
});

console.log(`🚀  Server ready at: ${url}`);
```

In order to use this, you will need the following dependency install:

```bash
npm install @apollo/server @graphql-tools/wrap @neo4j/graphql graphql graphql-tag neo4j-driver
```

It would be great if you could give this a go, and see if it reduces your memory usage! I would suggest to ensure you overwrite the `schema` variable instead of assigning the wrapped schema to a new variable.

**Comment by darrellwarde** [comment]
I should add, we will probably add functionality to disable _all_ Mutations to the library, but probably not functionality to disable, say, delete Mutations only.

**Comment by jroith** [comment]
I think this would help - but probably not with the memory consumption during API startup (I had 2 GB which then falls to 700 MB). But the second suggestion (disabling all mutations) might help.

**Comment by jroith** [comment]
I think this would help - but probably not with the memory consumption during API startup (I had 2 GB which then falls to 700 MB). But the second suggestion (disabling all mutations) might help.

**Comment by darrellwarde** [comment]
Hey @jroith, in the current 4.0.0 beta and the upcoming 4.0.0 stable release, we have added the `@mutation` directive which covers exactly the features requested here. 🙂 https://neo4j.com/docs/graphql-manual/4.0/reference/directives/schema-configuration/type-configuration/#_mutation
