### ISSUE TITLE
Custom resolvers come with some limitations not clear from documentation??

### ISSUE THREAD

**Issue by cramatt** [neo4j/graphql#287]
**Describe the bug**

Not sure if this is a bug or a limitation - but here it goes. The example on custom resolvers located here https://neo4j.com/docs/graphql-manual/current/custom-resolvers/#_custom_object_type_field_resolver seems a little misleading. It documents the following is possible:

```js
const resolvers = {
    User: {
        fullName(obj) {
            return `${obj.firstName} ${obj.lastName}`;
        },
    },
};
```

BUT in practice this only works if you include `firstName` and `lastName` in your graphQL query. If they are absent, these values will be undefined. So, you'd need the following query to work: 

```graphql
query itWorks {
  users {
    firstName,
    lastName,
    fullName
  }
}

query itFails {
  users {
    fullName
  }
}
```

If you don't select firstName and `lastName` they will be `undefined` in the resolver - at least this is what I'm seeing in my application. If this is not the expected behavior there is either a bug or I'm doing something incorrect!!! 

Here is an example I'm trying with a `File` type. Here is the broken instance:
![image](https://user-images.githubusercontent.com/22599518/124055983-bf90ca80-d9d9-11eb-8d20-04ae5697cae6.png)

And the working instance: 
![image](https://user-images.githubusercontent.com/22599518/124056782-35e1fc80-d9db-11eb-8338-62c5d5aac93f.png)

And here is my resolver: 

```js
File: {
    url: ({ path }) => {
      // @TODO get from process.env
      return `http://localhost:9000/${path}`
    },
  },
```

**Type definitions**
See above

**To Reproduce**
N/A

**Expected behavior**
I kind of expected the resolver first argument to be the full object with all properties, but in actuality it seems to be the picked object properties - which, makes sense. I'm just not sure there is a workaround then. The docs example might need clarification if this is a limitation. 

**Screenshots**
See above

**System (please complete the following information):**

-   OS: Mac OS
-   Version: @neo4j/graphql@1.0.1
-   Node.js version: 14.x

**Additional context**
N/a

**Comment by darrellwarde** [comment]
Thanks for this @cramatt. You're right, it is a limitation of the library for now due to the way that we only project properties in your selection set, and we're not really in a position to change this right now (however, we are aware of it). Regarding documentation, this has been updated in the prerelease of the next version of the docs (https://neo4j.com/docs/graphql-manual/2.0/custom-resolvers/) which will soon be stable, so closing this for that reason.
