### ISSUE TITLE
Emit warning or error when defining jwt-property at the same time as the Authentication plugin.

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#2878]
**Describe the bug**
After installing and successfully testing the JWT plugin I added a field where I decoded my JWT to my context when starting the Apollo server. This had the effect of silently disabling the neo4j auth plugin. Since I set the jwt-field neo4j grapql also sets `isAuthenticated: true`, silently bypassing the plugin verification of the JWT.

I now know I can access the jwt-field from the context without setting it manually as I did. But I didn't realize that the context would shadow the auth plugin context.

My context config:
```typescript
expressMiddleware(apolloServer, {
  context: async ({ req }) =>
    ({
      driver: driver,
      cache: apolloServer.cache,
      req: req,
      jwt: pipe(
        O.fromNullable(req.headers?.authorization),
        O.map(jwtDecode)
      ),
    } as MyContext),
})
```
My plugin config:
```typescript
plugins: {
  auth: new Neo4jGraphQLAuthJWKSPlugin({
    jwksEndpoint: jwksUrl,
    globalAuthentication: true,
  }),
},

```

**To Reproduce**

1. Run a server where you set the jwt field in your Context, like I did above.
2. Configure the auth plugin without specifying manual parsing of jwt, like I did above.
3. Use an expired token.
4. Gain access.

**Expected behavior**
I realize you can argue that this is a user error on my part when configuring. But it was not obvious to me that my context would shadow the Plugin Context and in essence bypass the auth verification. 

I may have been a bit lazy reading the documentation. However since the consequences are so dire I would suggest that an error or a warning is emitted when shadowing fields that the auth plugin uses.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by magnusart** [comment]
Realized that this actually is documented. So I can accept that. But I still feel this could be a flag in the plugin config to make this behavior explicit instead of implicit.

**Comment by Liam-Doodson** [comment]
Hi @magnusart! As you've said this is the intended behaviour of the library so this isn't really a bug. We are currently working on changes to auth in the library so we'll consider the feature request for a warning/error as part of that work

**Comment by magnusart** [comment]
@Liam-Doodson now that the new auth library is in place, should this be closed?
