### ISSUE TITLE
Nodes may disappear if an interface is requested that is not connected

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#2883]
I will later provide a more complete example of this.

```GraphQL
interface I {
  foo: String!
}

type A implements I {
  foo: String!
}

type B implements I {
  foo: String!
}

type T {
  bar: Int!
  related: I @relationship(type: "SOMETHING", direction: OUT)
}
```

If we would now have several objects of type T only the ones with a SOMETHING edge would be returned.

For example, this  might return 5 items:

```GraphQL
{
  ts {
    bar
  }
}
```

But this might return only 2 items:

```GraphQL
{
  ts {
    bar
    related {
      foo
    }
  }
}
```

Ts that not have this the relation would be missing in the list. On the other hand, if queried via a Connection it would work. Is this intentional? It seems wrong. The issue only occurs if interfaces are used, not if "related" is directly of type A or B.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
