### ISSUE TITLE
Why is generateExecutableSchema() wrapped in a promise?

### ISSUE THREAD

**Issue by inf3rnus** [neo4j/graphql#2886]
Hey all,

Some feedback / a question.

Is there a reason for why generateExecutableSchema() is wrapped in a promise?

I just ran the code through a debugger and I don't see why it should be wrapped in a promise. No call in the code block is async, and I don't see a reason for the use of the Promise object, unless I missed something?

If it's not required, can we make it sync? (I'll make a PR if this isn't priority.)

This is burdensome to my team as we have written a wrapper around the package that acts as an adapter to help decouple upstream changes from our code for flexibility, and that method happens to be handy to us.

Things become a little inconvenient when it comes to importing packages that implement this package because the construction of the object requires awaiting async code, so you need to await that async code in every service that imports the package. Would simplify user code greatly if the need for that could be eliminated. At least for that particular method.

And this is a stretch, but if there's someway to make the "base" construction of the schema object and the initialization of the ogm sync, I think that would increase the ergonomics of this package. Idea would be that if the async portion of it is optional in any way, to separate out the async portion into its own methods that are called separately.

Also, If there's an alternative path to take, I'm all ears!

Best,
Aaron

**Comment by inf3rnus** [comment]
I see that the method is also private... I guess that kind of shoots myself in the foot.

Guess I'd like my request to be to provide a convenience synchronous static method on the Neo4jGraphQL class that returns all of the information that is set on the class instance and all the information returned by the generateExecutableSchema() into one object.

**Comment by darrellwarde** [comment]
Hey @inf3rnus, as you have noted, that method is private, it was made asynchronous for future proofing purposes.

Schema fetching is asynchronous because initialization of a Subscriptions plugin is an asynchronous activity. I'm going to close this as I'm afraid there's nothing we can do here.
