### ISSUE TITLE
Unable to insert list of with mutations 

### ISSUE THREAD

**Issue by janjelinek** [neo4j/graphql#2889]
**Describe the bug**
Hi. I am trying to insert mandatory list of enums via mutations but it files. 

**Type definitions**
Minimal example types:

```graphql
enum MyEnum {
    FIRST
    SECOND
}

type MyEnumHolder {
    myEnums: [MyEnum!]!
}
```

Mutation query:

```graphql
mutation {
  createMyEnumHolders(input: [{
    myEnums: [FIRST, SECOND]
  }]) {
    myEnumHolders {
      myEnums
    }
  } 
}
```

Error I am getting 

`"Cannot return null for non-nullable field MyEnumHolder.myEnums."`

**To Reproduce**
Neo4j where is running Apollo server running  

**Screenshots**
![Screenshot 2023-02-15 at 11 20 32](https://user-images.githubusercontent.com/5626634/219001829-9f76343c-b2d3-45a7-ad45-b1f9adf8ca11.png)

* OS: macOS but server is running in docker `neo4j:4.4.14-community` 

**Additional context**
If I query db after failed insert attempt it contains node without enums list

![Screenshot 2023-02-15 at 11 28 28](https://user-images.githubusercontent.com/5626634/219002667-61da0135-d5d3-4bb4-9e1b-5c0a1bb1a930.png)

And if I try to create item via cypher query it is OK.

![Screenshot 2023-02-15 at 11 29 26](https://user-images.githubusercontent.com/5626634/219002786-025dfc74-de5e-46fe-817f-e197736722bd.png)
![Screenshot 2023-02-15 at 11 29 35](https://user-images.githubusercontent.com/5626634/219002801-818be89c-f91b-4c50-90bb-278f2dce110f.png)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @janjelinek. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @janjelinek. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
