### ISSUE TITLE
Incorrect deprecation warning on single relation filters

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#2890]
### Type definitions

```GraphQL
type Movie {
    director: Director! @relationship(type: "HAS_DIRECTOR", direction: OUT)
}

type Director {
    name: String!
}
```

### Steps to reproduce

Attempt to make the following query:

```gql
query {
  movies(where: { **director:** { name: "" } }) {
    director {
      name
    }
  }
}
```

Note that the director filter is marked as deprecated with the following message: "Use director_SOME instead".

### What happened

The deprecation message does not make sense as there is no director_SOME filter as it is a single relationship. This filter does not exist as only `SINGLE`/`NONE`(currently `director`/`director_NOT`) filters are applicable to single relationships

### Expected behaviour

No deprecation message for the field

### Version

3.16.1

### Database version

5.4

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.
