### ISSUE TITLE
Throw better error when using @relationship on scalar field.

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#2895]
**Describe the bug**
When annotating a `String` type with `@relationship(...)` the error message makes no sense:
`TypeError: Cannot read properties of undefined (reading 'name')`

This caused about one hour of debugging the library code for what amounted to a copy paste error. My schema is about 3000 lines with many relations so a manual analysis was out of the question. Also since this is in a promise, the error source line was lost from the context.

**Type definitions**
```graphql
type Person {
  name: String! @relationship(type: "NAME_LINK", direction: OUT)
}
```
**To Reproduce**

1. Run a server with type def similar to above.
2. See error

**Expected behavior**
A clear and concise description that says scalar fields must not be annotated with `@relationship` with some contextual information like the name of the offensive field and type. 

**Additional context**
The code that produces the error is the following snippet in `create-relationship-fields`
```javascript
const n = nodes.find((x) => x.name === rel.typeMeta.name); // When rel.typeMeta.name === String, then this returns undefined
const updateField = `${n.name}UpdateInput`; // This is where the error is thrown
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Couldn't agree more @magnusart, we need to work on our error messaging. Apologies for this!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @magnusart! :pray: We will now prioritise the bug and address it appropriately.

**Comment by a-alle** [comment]
This has been improved, error message is now the following:
`Invalid field type: Scalar types cannot be relationship targets. Please use an Object type instead.`
