### ISSUE TITLE
Incorrect @cypher annotation check

### ISSUE THREAD

**Issue by webberwang** [neo4j/graphql#2899]
**Describe the bug**
`@cypher statement required` is showing even though no @cypher is used. This only happened during jest testing.

**Type definitions**

**To Reproduce**
A bit difficult, but the code does seem incorrect

**Expected behavior**
Message shouldn't show up

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @webberwang. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @webberwang. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
