### ISSUE TITLE
Next.js with turbopack causes Ensure that there is only one instance of "graphql"

### ISSUE THREAD

**Issue by mattorp** [neo4j/graphql#2906]
**Describe the bug**
The reference implementation for Next.js using --turbo causes
Ensure that there is only one instance of "graphql" in the node_modules directory nextjs

**Steps to reproduce the behavior**

Use the implementation in https://neo4j.com/docs/graphql-manual/current/guides/frameworks/nextjs/
Use next dev --turbo

**Expected behavior**
Should function like the version without --turbo

**Output**

An error occurred while proxying a request to Node.js: Error: Cannot use GraphQLScalarType "Boolean" from another module or realm. Ensure that there is only one instance of "graphql" in the node_modules directory. If different versions of "graphql" are the dependencies of other relied on modules, use "resolutions" to ensure only one version is installed. https://yarnpkg.com/en/docs/selective-version-resolutions Duplicate "graphql" modules cannot be used at the same time since different versions may have different capabilities and behavior. The data from one version used in the function from another could produce confusing and spurious results. at https://yarnpkg.com/en/docs/selective-version-resolutions at instanceOf (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:44848:19) at isScalarType (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:37012:39) at isLeafType (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:37102:12) at astFromValue (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:43522:36) at printInputValue (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148467:56) at at printArgs (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148461:25) at (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148445:98) at at printFields (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148445:31) at printObject (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148402:146) at ObjectTypeComposer.toSDL (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:142688:48) at (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148308:41) at at printSchemaComposer (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:148308:28) at SchemaComposer.toSDL (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:141451:56) at makeAugmentedSchema (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:71182:40) at (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:67938:104) at at Neo4jGraphQL.generateSchema (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:67935:16) at Neo4jGraphQL.getSchema (/.next/server/pages/api/graphql/chunks/node_modules_0e4500.js:67835:32) at handler (/.next/server/pages/api/graphql/chunks/pages_api_graphql_index.ts.js:40:33) at Object.apiResolver (/node_modules/next/dist/server/api-utils/node.js:372:15) at (/.next/server/pages/api/graphql/chunks/_98af67.js:131:98) at createOperation (/.next/server/pages/api/graphql/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts.js:73:27) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async (/.next/server/pages/api/graphql/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts.js:48:41) status: exit status: 1

**System**

* OS: [e.g. macOS, Windows]

macOS 13.1 (22C65)

* Version:

    "@neo4j/graphql": "^3.16.1",
    "apollo-server-micro": "^3.11.1",
    "graphql": "^16.0.0",
    "micro": "^10.0.1",
    "neo4j-driver": "^5.5.0",
    "next": "^13.1.6",

* Node.js version: v18.12.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mattorp. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @mattorp! I've relatively recently opened a [PR to the Next.js repository](https://github.com/vercel/next.js/pull/44570) to update their example code for using this library in conjunction with the latest Apollo client and server (instead of apollo-server-micro as suggested in our current docs).

Could you try this code out and see if you still have the same problem?

The error you've reported seems to be quite specific to turbopoack. If other bundlers aren't reporting the same problem then I recommend looking into the problem starting from turbopack's perspective.
