### ISSUE TITLE
Support unions as implemented field types as long as the union members implement the same interface

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#2909]
It is currently not possible to restrict the valid implementations of an interface at a location where it is used. A natural way to do this would be union types in combination with interfaces but this would generate an error as I will show later.

Here is an fictional example that demonstrates what I want to achieve:

```GraphQL

interface Vehicle {
 name: String
}

type Car implements Vehicle {
 name: String
}

type Bicycle implements Vehicle {
 name: String
}

type KickScooter implements Vehicle {
 name: String
}

interface Country {
  permittedVehicles: [Vehicle!]!
}

union GreenCountryPermittedVehicles = Bicycle | KickScooter

type GreenCountry implements Country {
  permittedVehicles: [GreenCountryPermittedVehicles!]!
}

```

The intention is that GreenCountryPermittedVehicles restricts what vehicles can be saved in the database  when data is mutated and also having restricted filter options on known types of GreenCountry while still making it possible to treat all vehicles the same in if accessing a list of countries. Since all union members (Bicycle and KickScooter) implement Vehicle this should in theory work.

However in practice it doesn't work, because neo4j would produce an error like "Error: Interface field Country.permittedVehicles expects type [Vehicle!]! but GreenCountry.permittedVehicles is type [GreenCountryPermittedVehicles!]!"

I'm currently working around this by preprocessing the schema and replacing the unions with the base interface (here "Vehicle") and a comment and annotation, but of course this does not fix the mutations or filtering capabilities.

**Comment by jroith** [comment]
And intermediate solution would be to support "readonly" on relationships ( see: https://github.com/neo4j/graphql/pull/1493 ) and to support multiple such relationships on the same type. It would then be possible for "GreenCountry" to implement permittedVehicles as readonly and to have a writeable second field that has the union type.

It's less perfect but perhaps simpler to implement - and supporting readonly on relationships and having more than one is something I'm already working around using other techniques as well ...

**Comment by darrellwarde** [comment]
Hey @jroith, as to your first comment here, that is nothing to do with us but just not valid GraphQL which fails validation.

I'll close this as we're already looking into read-only for relationships elsewhere, but even with that implemented, type definitions will always have to pass GraphQL validation.
