### ISSUE TITLE
Filter on intermediate interfaces

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#2910]
It seems to be impossible to currently filter on interfaces: If a field has an interface type only the types implementing that interface occur in the "where: { _on: {} }" This is a pretty big restriction. If I have a field that has as type "Vehicle" and that type is an interface Vehicle and I also have an interface ElectricVehicle and type  ElectricCar and another type ElectricScooter and another type DieselCar, then I want to not only filter on ElectricCar and ElectricScooter. I also want to filter on "ElectricVehicle".

```GraphQL
interface Vehicle { ... }
interface ElectricVehicle implements Vehicle { ... }
type ElectricCar implements ElectricVehicle { ... }
type ElectricScooter implements ElectricVehicle { ... }
interface DieselCar implements Vehicle { ... }

type Foo {
  bar: [Vehicle!]!
}

```

Now bar(where: {...}) will not contain { ElectricCar: ... } and that's a problem. Clearly such an entry could be created and also implemented, since it's known that ElectricCar and ElectricScooter implement the intermediate interface.

**Comment by darrellwarde** [comment]
This gets extremely complex extremely quickly once you go down several levels of interfaces implementing interfaces, however, I agree that this functionality should be more clear on schema generation.

Whatever we do here, we need to be more opinionated about what we do and don't support. We're taking a look at interfaces and unions soon, and we will include this in those discussions.

**Comment by jroith** [comment]
Yes. I was thinking that it would make sense to basically include the common interfaces: That is all interfaces that are ultimately derived from the interface of the field type while also implemented by all actual types of that interface.

**Comment by darrellwarde** [comment]
In version 5.0.0 we're actually scaling back the filtering abilities for interfaces. It was becoming unworkable, so now you can only filter on the fields defined within the interface.
