### ISSUE TITLE
Offset based pagination should use offset instead of (or optionally) skip.

### ISSUE THREAD

**Issue by tlester** [neo4j/graphql#292]
**Describe the bug**
Evidently, the way Apollo 3 wants to handle pagination now since it's deprecating the fetchMore call back requires the paginaiton variables be "offset" and "limit".  Since neo4j uses "skip" instead of "offset", this will break.  

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

**To Reproduce**
Newst Apollo client... use skip instead of offset... it'll break.  

**Expected behavior**
since apollo is the biggest graphql client, I'd expect neo4j/graphql to accept what they expect as it's kind of a standard.

Here's more:

https://stackoverflow.com/questions/62742379/apollo-3-pagination-with-field-policies

**Comment by litewarp** [comment]
I posted a [temporary workaround](https://gist.github.com/litewarp/913c1f77581f2ed7e75d7c489b79488c) using `@graphql-tools/wrap` in the discord, but thought I'd put it here in case anyone else needs it.

**Comment by darrellwarde** [comment]
This has now been changed and will be released in 2.0.0. 🙂
