### ISSUE TITLE
Optimize query between two nodes

### ISSUE THREAD

**Issue by holleyism** [neo4j/graphql#2925]
**Is your feature request related to a problem? Please describe.**
I have a query that within Cypher, I can get the data within 9 ms.  However when accessing the same data through GraphQL, the query takes 27000 ms.

**Describe the solution you'd like**
I'd like to be able to run similar queries with GraphQL without such a performance hit.

**Additional context**
I have two node types, User and Group.   There are 10M Users and 3000 Groups with a power-law distribution.
Running this query takes about 9 ms and returns a count of 350.
```MATCH (u:User)-[:HAS_GROUP]->(g:Group) where g.name in ["Group A"] return {count: count(u) }```

The query generated by GraphQL for the aggregation data runs in about 27000 ms and is:
```MATCH (this:`User`) WHERE single(this0 IN [(this)-[:HAS_GROUP]->(this0:`Group`) WHERE this0.name IN ['Group A'] | 1] WHERE true) RETURN { count: count(this) }```

The query to get the actual data ( 350 records ) through GraphQL runs in about the same time.

Profiling shows a NodeByLabelScan which I'm assuming is the expensive part.
I have indexes on the group name, as well as node and relationship label indexes.

Is there some option I missed to optimize this, or something I can add to the database to improve this?

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @holleyism. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @holleyism, thanks for this - I've relabelled this as a bug report.

We've just spent a lot of time trying to optimize this part of our Cypher generation, it's proving to be a real tough nut to crack.

Just so we can accurately reproduce, can you please provide some example type definitions and a GraphQL query which can be used to generate the Cypher in the question? It will save us inferring it (potentially inaccurately) from your report.

**Comment by holleyism** [comment]
Thanks for the quick response.  Here's the GraphQL type definition:
```
type Group {
 name:String
 hasGroupUser:[User!]! @relationship(type: "HAS_GROUP", direction:IN )
 }

type User {
 name:String
 hasGroupGroup:Group @relationship(type: "HAS_GROUP", direction:OUT )
}
```

Here's the example query:
```
Query:
query Query($where: UserWhere) {
  users(where: $where) {
    name
  }
}
Variables:
{
  "where": {
    "hasGroupGroup": {
      "name_IN": [
        "Group A"
      ]
    }
  }
}
```

**Comment by darrellwarde** [comment]
Hey @holleyism, investigating this further, there is actually somewhat of a large performance regression of the `single()` predicate in Neo4j 5, which is causing this poor performance. We have raised this with the relevant teams and are working towards a solution, whether that be a change in the database or us choosing an alternative Cypher solution.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @holleyism! :pray: We will now prioritise the bug and address it appropriately.

**Comment by holleyism** [comment]
Thanks for the response.  FYI. We're not on Neo4j 5 yet.  We're seeing this on 4.4.11.

**Comment by angrykoala** [comment]
This seems to be a problem with list comprehensions not taking full advantage of indexes.

The proposed alternative cypher could be used, but would be a breaking change, as it will change how we do validation and what our library supports when the database does not match the schema, but it could be a good way forward after the breaking change.

 I'll write a few tests to cover this performance problem case and try to come with a non-breaking alternative.

**Comment by angrykoala** [comment]
After some tinkering, the option proposed seem to be the best one, there are some edge cases to take care of, but the plan is to try and move 1-* relationships from `single` to a proper pattern

**Comment by angrykoala** [comment]
Hi @holleyism 

A PR optimising this query use case has been opened (#3037)

This optimisation, however, requires the field to be required, in your case: 
```
hasGroupGroup:Group! @relationship(type: "HAS_GROUP", direction:OUT
````

Would that be possible in your schema?

**Comment by angrykoala** [comment]
The query provided your example would be translated (assuming a non-nullable relationship) to:
```
MATCH (this:User)
MATCH (this)-[:HAS_GROUP]->(this0:Group)
WHERE this0.name IN $param0
RETURN this { .name } AS this
```

Which should be able to take advantage of any index and be equivalent to the cypher query you posted before.

I cannot give you an exact estimate, but you could try this query on your database and that should be a much better estimate of how this will run with the graphql library

**Comment by angrykoala** [comment]
This cypher optimisation should be available on the next release of the graphql library.

Please @holleyism , feel free to comment here if this optimisation is not enough to solve your issue
