### ISSUE TITLE
Allow label to be specified when using `@unique`

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#2941]
**Describe the bug**
I don't know the exact background why the label + additionalLabel argument was replaced by the labels argument. But this change caused an unexpected behavior.

Apparently the order of the entries in the list is relevant. This behavior seems a bit undeterministic or unpredictable to me. At least there is no clear documentation here that the first element of the labels argument has a special meaning.

**Type definitions**
1. label and addionalLabels arguments (deprecated):
````gql
interface Classification {
  termId: String!
}

type ProductType implements Classification {
  termId: String! @unique
}

extend type ProductType
  @node(label: "ProductType", additionalLabels: ["Classification "])

type RolePlayType implements Classification {
  termId: String! @unique
}

extend type RolePlayType
  @node(label: "RolePlayType", additionalLabels: ["Classification "])
````

2. labels argument:
````gql
interface Classification {
  termId: String!
}

type ProductType implements Classification {
  termId: String! @unique
}

extend type ProductType
  @node(labels: ["Classification", "ProductType"])

type RolePlayType implements Classification {
  termId: String! @unique
}

extend type RolePlayType
  @node(labels: ["Classification", "RolePlayType"])
````

3. labels argument with different order:
````gql
interface Classification {
  termId: String!
}

type ProductType implements Classification {
  termId: String! @unique
}

extend type ProductType
  @node(labels: ["ProductType", "Classification"])

type RolePlayType implements Classification {
  termId: String! @unique
}

extend type RolePlayType
  @node(labels: ["RolePlayType", "Classification"])
````

**Constraints and Indexes**
1.
![image](https://user-images.githubusercontent.com/49721200/221735447-a54e0844-aa7a-4eed-b5ef-02e5d56117ec.png)

2.
![image](https://user-images.githubusercontent.com/49721200/221735791-108da0b5-41bf-4e3d-8fa8-6c2671ad2580.png)

3.
![image](https://user-images.githubusercontent.com/49721200/221736659-cd2cfa36-12c5-482c-b0a3-ca9f292ed25d.png)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @AccsoSG! Regarding the background of this change, due to their being no concept of a "main label" in Neo4j, we thought it best to reflect this behaviour in the GraphQL Library with a simple list of labels.

However, I do understand the confusion here! At the very least this can be documented.

As a more flexible solution, an idea off the top of my head is we would add an `onLabel` argument to the `@unique` directive which by default takes the first entry, but could also be used to select a different label. What do you think of this idea?

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
> @darrellwarde Yes that sounds like a good idea!
> 
> But you would have to make sure that the label under onLabel is in the list of labels. So that no constraint is created for a label that does not exist.

Naturally, just wanted to float the idea!! This being the case, I will label this as a feature request. 🙂

**Comment by darrellwarde** [comment]
The documentation is quite clear for how this works (https://neo4j.com/docs/graphql/current/type-definitions/directives/indexes-and-constraints/#_usage), so we don't feel the need to add additional features around this at this time.
