### ISSUE TITLE
Autogeneration for relationships not working

### ISSUE THREAD

**Issue by YizYah** [neo4j/graphql#296]
**Describe the bug**
I do not see CRUD functions generating for relationships in the way that your documentation implies.

**Type definitions**
type Person {
    name: String!
    born: Int!
    actedInMovies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
    directedMovies: [Movie!]! @relationship(type: "DIRECTED", direction: OUT)
}

type Movie {
    title: String!
    released: Int!
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
    director: Person! @relationship(type: "DIRECTED", direction: IN)
}

**To Reproduce**

1. Follow the code in your [Getting Started](https://neo4j.com/docs/graphql-manual/current/getting-started/) document to create a local server.
2. Replace the Type Definitions with those shown in your [Relationship Type Definitions Example](https://neo4j.com/docs/graphql-manual/current/type-definitions/relationships/#_type_definitions).
3. Execute the Mutations shown in your [Inserting Data Example](https://neo4j.com/docs/graphql-manual/current/type-definitions/relationships/#_inserting_data)
4. See error for the `CreateActor` mutation
```
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"createActors\" on type \"Mutation\". Did you mean \"createMovies\"?",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"createActors\" on type \"Mutation\". Did you mean \"createMovies\"?",
              "    at Object.Field (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
              "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:323:29)",
              "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/utilities/TypeInfo.js:370:25)",
              "    at visit (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:243:26)",
              "    at Object.validate (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/validate.js:69:24)",
              "    at validate (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:233:34)",
              "    at Object.<anonymous> (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
            ]
          }
        }
      }
    ]
  }
}
```

**Expected behavior**
I would expect that the createActors mutation would have been autogenerated, as is suggested in the example.

**Screenshots**

**System (please complete the following information):**

-   OS: [e.g. macOS, Windows]  Ubuntu 20.04.2 LTS
-   Version: [e.g. @neo4j/graphql@1.0.0] @neo4j/graphql ^1.0.3"
-   Node.js version: [e.g. 14.16.0] Node v14.9.0

**Additional context**
While it's not relevant directly to this bug, I tried following your sample because I am migrating from `neo4j-graphql-js` and I cannot get `@relationship` to work in general.  (It did before as `@relation` with `name`.)

**Comment by danstarns** [comment]
Hey, This is an issue with the docs. Try calling `createPeople`.

**Comment by YizYah** [comment]
Hi @danstarns 

I did try that when I saw the initial failure.  But I got:
```
{
  "error": {
    "errors": [
      {
        "message": "Field \"movies\" is not defined by type \"PersonCreateInput\".",
        "locations": [
          {
            "line": 3,
            "column": 45
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Field \"movies\" is not defined by type \"PersonCreateInput\".",
              "    at ObjectField (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:73:29)",
              "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:323:29)",
              "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/utilities/TypeInfo.js:370:25)",
              "    at visit (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:243:26)",
              "    at Object.validate (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/validate.js:69:24)",
              "    at validate (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:233:34)",
              "    at Object.<anonymous> (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
            ]
          }
        }
      },
      {
        "message": "Cannot query field \"movies\" on type \"CreatePeopleMutationResponse\".",
        "locations": [
          {
            "line": 5,
            "column": 5
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"movies\" on type \"CreatePeopleMutationResponse\".",
              "    at Object.Field (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
              "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:323:29)",
              "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/utilities/TypeInfo.js:370:25)",
              "    at visit (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:243:26)",
              "    at Object.validate (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/validate.js:69:24)",
              "    at validate (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:233:34)",
              "    at Object.<anonymous> (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
            ]
          }
        }
      }
    ]
  }
}
```
So I figured that relationship CRUD functions are supposed to be generating as well.

**Comment by danstarns** [comment]
> Hi @danstarns
> 
> I did try that when I saw the initial failure. But I got:
> 
> ```
> {
>   "error": {
>     "errors": [
>       {
>         "message": "Field \"movies\" is not defined by type \"PersonCreateInput\".",
>         "locations": [
>           {
>             "line": 3,
>             "column": 45
>           }
>         ],
>         "extensions": {
>           "code": "GRAPHQL_VALIDATION_FAILED",
>           "exception": {
>             "stacktrace": [
>               "GraphQLError: Field \"movies\" is not defined by type \"PersonCreateInput\".",
>               "    at ObjectField (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:73:29)",
>               "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:323:29)",
>               "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/utilities/TypeInfo.js:370:25)",
>               "    at visit (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:243:26)",
>               "    at Object.validate (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/validate.js:69:24)",
>               "    at validate (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:233:34)",
>               "    at Object.<anonymous> (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
>               "    at Generator.next (<anonymous>)",
>               "    at fulfilled (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
>               "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
>             ]
>           }
>         }
>       },
>       {
>         "message": "Cannot query field \"movies\" on type \"CreatePeopleMutationResponse\".",
>         "locations": [
>           {
>             "line": 5,
>             "column": 5
>           }
>         ],
>         "extensions": {
>           "code": "GRAPHQL_VALIDATION_FAILED",
>           "exception": {
>             "stacktrace": [
>               "GraphQLError: Cannot query field \"movies\" on type \"CreatePeopleMutationResponse\".",
>               "    at Object.Field (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
>               "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:323:29)",
>               "    at Object.enter (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/utilities/TypeInfo.js:370:25)",
>               "    at visit (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/language/visitor.js:243:26)",
>               "    at Object.validate (/home/yisroel/projects/neo4jGraphql/node_modules/graphql/validation/validate.js:69:24)",
>               "    at validate (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:233:34)",
>               "    at Object.<anonymous> (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:119:42)",
>               "    at Generator.next (<anonymous>)",
>               "    at fulfilled (/home/yisroel/projects/neo4jGraphql/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
>               "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
>             ]
>           }
>         }
>       }
>     ]
>   }
> }
> ```
> 
> So I figured that relationship CRUD functions are supposed to be generating as well.

Please share your query. I assume it should be: `actedInMovies` or `directedMovies` over `movies`.

**Comment by YizYah** [comment]
Oops, I see.  Yes it's working!

**Comment by danstarns** [comment]
Reopen due to the documentation issue

**Comment by darrellwarde** [comment]
Documentation has now been updated with fixed examples.
