### ISSUE TITLE
inferSchema

### ISSUE THREAD

**Issue by danstarns** [neo4j/graphql#298]
**Is your feature request related to a problem? Please describe.**
Create a schema from introspecting an existing database.

**Comment by SSSofyen** [comment]
we have a neo4j db that can change, if we are to keep using graphql we cant rewrite schemas etc everytime we swap the db content, inferSchema is gold in a context like this (where we wanna do the same things to different data sets or even databases).

**Comment by danstarns** [comment]
#581
