### ISSUE TITLE
Unable to create a nested object when type is an union

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#2981]
**Describe the bug**
When I try to create a nested object I get a null exception.

**Type definitions**
```graphql
type Book {
  originalTitle: String!
  translatedTitle: BookTitle @relationship(type: "TRANSLATED_BOOK_TITLE", direction: IN) 
  isbn: String!
}

union BookTitle = BookTitle_SV | BookTitle_EN

type BookTitle_SV {
  book: Book! @relationship(type: "TRANSLATED_BOOK_TITLE", direction: OUT)
  value: String!
}

type BookTitle_EN {
  book: Book! @relationship(type: "TRANSLATED_BOOK_TITLE", direction: OUT)
  value: String!
}
```

**To Reproduce**

1. Run a server with the code
2. Execute the following Mutation
```graphql
mutation CreateBooks {
  createBooks(
    input: [
      {
        isbn: "123"
        originalTitle: "Original title"
        translatedTitle: {
          BookTitle_SV: {
            create: { node: { value: "Exempel på svensk titel" } }
          }
        }
      }
    ]
  ) {
    info {
      bookmark
      nodesCreated
      relationshipsCreated
    }
    books {
      isbn
      originalTitle
      translatedTitle {
        ... on BookTitle_SV {
          value
        }
        ... on BookTitle_EN {
          value
        }
      }
    }
  }
}
```
4. Then run the following Mutation
```graphql
mutation UpdateBooks {
  updateBooks(
    where: { isbn: "123" }
    create: { translatedTitle: { BookTitle_EN: [{ node: { value: "English book title" } }] } }
  ) {
    info {
      nodesCreated
      nodesDeleted
      relationshipsCreated
      relationshipsDeleted
    }
    books {
      isbn
      originalTitle
      translatedTitle {
        ... on BookTitle_SV {
          value
        }
        ... on BookTitle_EN {
          value
        }
      }
    }
  }
}
```
6. See error
```
TypeError: Cannot convert undefined or null to object",
          "    at Function.entries (<anonymous>)",
          "    at createCreateAndParams (/Users/x/y/node_modules/@neo4j/graphql/dist/translate/create-create-and-params.js:238:44)",
```
**Expected behavior**
I looked at the code. It seems that in the file `translate-update.js` the snippet below expect `create.node` to be a nested object when it in fact an array with objects. If I type `create[0].node` in watch expressions I get the correct values:
```javascript
 const createAndParams = (0, create_create_and_params_1.default)({
                        context,
                        callbackBucket,
                        node: refNode,
                        input: create.node,
                        varName: nodeName,
                        withVars: [...withVars, nodeName],
                        includeRelationshipValidation: false,
                    });

```
**Screenshots**
N/A

**System (please complete the following information):**
N/A

**Additional context**
Not sure if this has been registered, did try to do a search but didn't find anything.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by butchmarshall** [comment]
I'm having a related issue.

If I use properties on the relationship directive of a union type, the properties are not added to the input.

e.g.

```graphql
union DatabaseColumnReadWriteRelationship =
      KubernetesNamespace
    | GraphqlResolver
    | RestfulEndpoint
    | GithubRepository

interface DatabaseColumnReadBy @relationshipProperties {
    uuid: String!
}

type DatabaseColumn {
    readBy: [DatabaseColumnReadWriteRelationship!]!
      @relationship(
        type: "READ"
        properties: "DatabaseColumnReadBy"
        direction: IN
      )
}
```

the generated input on the schema is missing the uuid property property:

```graphql
input DatabaseColumnReadByCreateInput {
  GithubRepository: DatabaseColumnReadByGithubRepositoryFieldInput
  RestfulEndpoint: DatabaseColumnReadByRestfulEndpointFieldInput
  GraphqlResolver: DatabaseColumnReadByGraphqlResolverFieldInput
  KubernetesNamespace: DatabaseColumnReadByKubernetesNamespaceFieldInput
}
```

without the union

```graphql
type DatabaseColumn {
    readBy: [KubernetesNamespace!]!
      @relationship(
        type: "READ"
        properties: "DatabaseColumnReadBy"
        direction: IN
      )
}
```


the outputted schema has the properties:

```graphql
input DatabaseColumnReadByCreateInput {
  uuid: String!
}
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @magnusart! :pray: We will now prioritise the bug and address it appropriately.

**Comment by MacondoExpress** [comment]
Hi [magnusart](https://github.com/magnusart), we were able to reproduce your issue and the fix is on dev and will be released soon, although we found an underneath bug defined by this issue: https://github.com/neo4j/graphql/issues/3027.
In your reproduction steps, you create a node `Book` with a `translatedTitle` of type`BookTitle_SV` and then you are trying to update the same`Book` by adding a new `translatedTitle` of type `BookTitle_EN`. This should fail anyway, as in your typeDefs you defined `translatedTitle` to be a single `BookTitle`. 
Very likely we will release the fix with also the cardinality check bug fix, perhaps you might want your typeDefs to reflect the fact that you could have more than one translation for the same Book.

**Comment by magnusart** [comment]
You're right. However the typedefs were just a toy example to showcase the issue. My model does not contain any books. 😄 

Glad you seem to be making progress!
