### ISSUE TITLE
Count aggregation breaks when querying fields in inline fragments

### ISSUE THREAD

**Issue by happenslol** [neo4j/graphql#2982]
**Describe the bug**
When querying the `count` aggregate field on an inline fragment, incorrect cypher syntax is generated and the query fails.

The resulting error is:

```
Received: [[GraphQLError: Variable `count` not defined (line 13, column 117 (offset: 648))
"        WITH this_Posts { __resolveType: "BlogArticle", __id: id(this), CommentsAggregate:  count: this_Posts_CommentsAggregate_var2 } AS this_Posts"
```

**Type definitions**
The following type definitions are used:

```graphql
type User {
    id: ID!
    posts: [Post!]! @relationship(type: "USER_POSTS", direction: OUT)
}

interface Post {
    id: ID!
}

type Comment {
    id: ID!
}

type BlogArticle implements Post {
    id: ID!
    comments: [Comment!]! @relationship(type: "ARTICLE_COMMENTS", direction: OUT)
}
```

**To Reproduce**

1. With the type definitions above, create a `User` and a `BlogArticle` and `MERGE` them
2. Run the following query:

```graphql
query {
    users {
        posts {
            ... on BlogArticle {
                commentsAggregate {
                    count
                }
            }
        }
    }
}
```

3. See the resulting error

**Expected behavior**
The count aggregate field should be returned (with a value of 0 in the case above)

* OS: Linux
* Version: @neo4j/graphql@3.17.0
* Node.js version: 18.14.2

**Additional context**
Please see #2983 for a test case triggering this bug and the fix.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @happenslol. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
