### ISSUE TITLE
Error generating schema when relationship properties of type interface consist of only generated fields

### ISSUE THREAD

**Issue by danifaiz** [neo4j/graphql#2993]
**Describe the bug**
- When we specify the type of the property of an entity as Interface. And also if that property has a relationship and that relationship is using an interface of `@relationshipProperties` directive. If we define a field which is auto generated. And try to to launch the app with provided Schema. The app fails and throws an error.

`Input Object type <Relationship-Interface-name>CreateInput must define one or more fields`

**Type definitions**
```
interface Profile {
  id: ID! @id(autogenerate: true)
  userName: String!
}
type User implements Profile {
  id: ID!
  userName: String!
  following: [Profile!]! @relationship(type: "FOLLOWS", direction: OUT, properties: "FOLLOWS")
}

interface FOLLOWS @relationshipProperties {
  since: DateTime! @timestamp(operations: [CREATE])
}
```

**To Reproduce**

1. Use the schema as shared above.
2. Try to run the application
3. It will fail and show a schema error.

**Expected behavior**
Expect to not to create `CreateInput` and `UpdateInput` for relationship properties that only consist of autogenerated or timestamped fields.

OS: macOS@12.3.1
Version: @neo4j/graphql@3.17.0
Node.js version: 16.14.0

**Screenshots**
`error : Input Object type FOLLOWSCreateInput must define one or more fields.`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @danifaiz. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @danifaiz. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @danifaiz! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
