### ISSUE TITLE
@unique constraint not being respected

### ISSUE THREAD

**Issue by Alex-Garay** [neo4j/graphql#3014]
### Type definitions

```GraphQL
type User {
    id: ID @id
    username: String! @unique(constraintName: "unique_username") // Example #1
    email: String! @unique // Example #2
    password: String!
}
```

### Test data

```Shell
user.create({
    input: {
        username: "george",
        email: "george@email.com",
        password: "hunter2",
    },
});
```

### Steps to reproduce

1. Configure an Apollo Server using neo4j's official [OGM](https://neo4j.com/docs/graphql-manual/current/ogm/)
2. Create a User type inside typeDefs
3. Use ogm to create a "User" model
4. Use the ogm "User" model to create a new user 

### What happened

When using the ogm "User" model to create a new user with a hardcoded username and email with a @unique constraint, it creates the same "User". When checking the database, there are duplicate "User"s sharing username and password but with different "User.id".

When using a [cypher query](browser.neo4j.io) it is throws an error.
`Neo.ClientError.Schema.ConstraintValidationFailed`
`CREATE (u:user {id: 1, username: "george", email: "george@email.com", password: "hunter2"})`

### Expected behaviour

Whether using "@unique", "@unique(constraintName: "unique_username")", and or creating a @unique constraint using cypher, it should throw an error when attempting to create a value that is not @unique.
 `CREATE CONSTRAINT unique_email for (u:USER) require u.email IS UNIQUE`

### Version

3.13.1

### Database version

5.3

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Alex-Garay. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Alex-Garay** [comment]
Partially fixed:
