### ISSUE TITLE
Interfaces and Unions produce the wrong cardinality check, during the update create.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#3027]
**Describe the bug**
Interfaces and Unions produce the wrong cardinality check.

**Type definitions**
```graphql
type Book {
    originalTitle: String!
    translatedTitle: BookTitle @relationship(type: "TRANSLATED_BOOK_TITLE", direction: IN)
    isbn: String!
}

interface BookTitle {
    value: String!
}

type BookTitle_SV implements BookTitle {
    book: Book! @relationship(type: "TRANSLATED_BOOK_TITLE", direction: OUT)
    value: String!
}

type BookTitle_EN implements BookTitle {
    book: Book! @relationship(type: "TRANSLATED_BOOK_TITLE", direction: OUT)
    value: String!
}
```

**To Reproduce**

The following mutation:
```graphql
mutation UpdateBooksInterface {
  updateBooks(
    where: { isbn: "123" }
    create: {
      translatedTitle: {
        node: { BookTitle_EN: { value: "English book title" } }
      }
    }
  ) {
    books {
      isbn
      originalTitle
      translatedTitle {
        ... on BookTitle_SV {
          value
        }
      }
    }
  }
}
```

The above mutation produces the following predicate:

```cypher
CALL apoc.util.validate(EXISTS((this)<-[:TRANSLATED_BOOK_TITLE]-(:BookTitle_EN)),'Relationship field "%s.%s" cannot have more than one node linked',["Book","translatedTitle"])
```

**Expected behavior**
The cardinality validation should check not only the implementation present in the input, in this case `BookTitle_EN`,  but also the existence of any other implementations that may already be related to the `Book` node.
The above is also reproducible with `BookTitle` defined as an union.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
