### ISSUE TITLE
@neo4j/inspector -  `TypeError: relType.replaceAll is not a function` on Node 14

### ISSUE THREAD

**Issue by ardatan** [neo4j/graphql#3069]
**Describe the bug**
When `toGraphQLTypeDefs` is called,  `TypeError: relType.replaceAll is not a function` is thrown on Node v14 

Node v14 doesn't have `String.prototype.replaceAll` implemented so it seems it started breaking after this commit
https://github.com/neo4j/graphql/commit/c2eaff8ef94b8cc6297be1435131967ea8a71115#diff-c54a5c229ea321bcb25927cd72a3c1bcd109de6bca8d20d41dd70927ba21d3e5R30

**System (please complete the following information):**

* OS: Not relevant
* Version: [neo4j/introspector@1.0.3](https://github.com/neo4j/graphql/releases/tag/%40neo4j%2Fintrospector%401.0.3) and above
* Node.js version: 14.x

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @ardatan. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @ardatan. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
Hi @ardatan ,
This library works correctly only with NodeJS version 16 or above,
https://neo4j.com/docs/graphql-manual/current/introduction/#introduction-requirements

**Comment by angrykoala** [comment]
Hi @ardatan 

As v14 is officially deprecated, we do not guarantee support for versions below 16

If the only problem with v14 is `replaceAll` we will gratefully accept contributions to add support for v14 but it will still not be officially tested nor supported so I recommend you migrate to a more recent version or NodeJS as v14 will soon be a security concern as security updates support is being dropped in less than 2 months

**Comment by angrykoala** [comment]
@ardatan 
Indeed, you are right, I misread the dates of LTS, sorry

As we mentioned we only support 16.x officially, but you are right in that we should have officially supported it until now and a PR making it work will be really appreciated

Thanks!
