### ISSUE TITLE
Deep sorting on labels with multiple relationship types fails

### ISSUE THREAD

**Issue by wolfgang-ldc** [neo4j/graphql#3074]
**Is your feature request related to a problem? Please describe.**
I have several examples with labels that have relations to other labels using multiple relationship types, rather than just a single one. If I attempt to sort the related label nodes it ONLY works when there is a single relationship type. Examples are shown below:

In this case, Company has a SINGLE relationship type to BioStructures and sorting works fine:
```gql
{
  companies(where:{Name:"AbCellera Biologics Inc."}){
    Name
    BioStructures(options: {
            sort: [
                {
                    Name: ASC
                }
            ]
        }){
      Name
    }
  }
}
```
```gql
BioStructures: [BiologicalStructure!]! @relationship(type: "worksOn", direction: OUT)
```

In this case, Company has multiple relationship types to PipelineMolecules and sorting FAILS:
```gql
{
  companies(where:{Name:"Amgen"}){
    Name
    PipelineMolecules(options: {
            sort: [
                {
                    Name: ASC
                }
            ]
        }){
      Name
    }
  }
}
```
```gql
PipelineMolecules: [TherapeuticMolecule!]! 
    @cypher(statement: "MATCH (this)<-[:developedByCompany|developedWithCollaborator|developedThroughAcquisitionByCompany]-(t:TherapeuticMolecule) RETURN t")
```

**Describe the solution you'd like**
I would like sorting to work no matter whether there is a single or multiple relationship types at work.

**Describe alternatives you've considered**
No alternatives come to mind.

**Additional context**

**Comment by darrellwarde** [comment]
@wolfgang-ldc, relationship fields with multiple relationships isn't currently a feature that this library supports. Regardless, can you provide us with your type definitions so we can actually look at this? Thanks!

**Comment by wolfgang-ldc** [comment]
Thanks for getting back to me. I thought so, haven't seen it mentioned in the documentation. But it would be a good feature to have as people move onto have more than just a single relationship type.
Here are the type definitions for the two labels that relate to each other with multiple relationship types. Hope this helps! 

type Company {
  FID: ID!
  FID_S: Int
  Name: String
  CreationDate: Date
  BioStructures: [BiologicalStructure!]! @relationship(type: "worksOn", direction: OUT)
  PipelineMolecules: [TherapeuticMolecule!]! 
    @cypher(statement: "MATCH (this)<-[:developedByCompany|developedWithCollaborator|developedThroughAcquisitionByCompany]-(t:TherapeuticMolecule) RETURN t")
 }

type TherapeuticMolecule {
  FID: ID!
  FID_S: Int
  Name: String
  CreationDate: Date
  Companies: [Company!]!
    @cypher(statement: "MATCH (this)-[:developedByCompany|developedWithCollaborator|developedThroughAcquisitionByCompany]->(co:Company) RETURN co")
}

 type BiologicalStructure {
   FID: ID!
   FID_S: Int
   Name: String
   CreationDate: Date
   Companies: [Company!]! @relationship(type: "worksOn", direction: IN)
 }

**Comment by darrellwarde** [comment]
Closing because we don't currently natively support multiple relationship types.

**Comment by wolfgang-ldc** [comment]
Hi Darrell, I think you might have misunderstood my request. Neo4j allows the use of multiple types of relationships between nodes of different labels. Here is an example:
An instance of a TherapeuticMolecule can be related via developedByCompany to an instance of Company. The same instance of a TherapeuticMolecule can also be related via developedWithCollaborator to an instance of another Company. So we have two relationship types between TherapeuticMolecule and Company. 
If that is defined in the graphQL cypher statement as such @cypher(statement: "MATCH (this)-[:developedByCompany|developedWithCollaborator]->(co:Company) RETURN co") then the sort option does not appear to work. Hope that makes sense.
Thanks!

**Comment by angrykoala** [comment]
Hi @wolfgang-ldc 

So, at the moment, we cannot support multiple type relationships, because it is not possible to create such relationships.

You point of sorting through multiple relationship types however, makes perfect sense. I can think of 2 ways of achieving this:

* Support for sorting `@cypher` results. This would basically be supporting for sort on the approach you've taken to fetch relationships of different types
* Add support for multiple labels on the proposal for #596, these issues are a bit different, but at their core both are about supporting complex patterns read-only and may be a nice fit.

**Comment by wolfgang-ldc** [comment]
Hi @angrykoala
thanks for getting back to me. Just wanted to clarify that your statement below is incorrect. One can create such relationships!
"So, at the moment, we cannot support multiple type relationships, **because it is not possible to create such relationships.**"

If you look at this page you will see an example of the Movie database where one created multiple relationships between Movie and Person - [DIRECTED|WROTE|PRODUCED|ACTED_IN|REVIEWED]. https://neo4j.com/developer/example-project/

I understand that currently it is not possible to sort related People for a Movie by name using the GraphQL library, but I am sure that someone would want to do this in the future. It works nicely if there is only ONE relationship defined. 
People: [Person!]! @relationship(type: "ACTED_IN", direction: OUT)
If it cannot be done right now for multiple relationshipsI understand priorities, but I wanted to clarify that it is possible to create such relationships and sorting should be possible in the future.

Thanks for your understanding and time, Wolfgang

**Comment by angrykoala** [comment]
Hi @wolfgang-ldc 
I meant you cannot create a relationship with multiple types different relationships to the same node can be created with different types, but those are modeled as different fields in graphql, which makes it incapable of sorting them together.

A relationship in graphql cannot have multiple types, as then it wouldn't be possible to create it, relationship types operations such as "|" are read-only operations that we may support in the future (along with variable length relationships)

Hope this comment makes it  a bit clearer

**Comment by wolfgang-ldc** [comment]
😁👍🏻
