### ISSUE TITLE
Type Definition not working - "@neo4j/graphql": "^1.1.0"

### ISSUE THREAD

**Issue by wolfgang-ldc** [neo4j/graphql#308]
Hi, I have tried a simple type definition that should cover any node in my database as such as described in the manual (https://neo4j.com/docs/graphql-manual/current/type-definitions/):

```graphql
type Node {
  FID: ID!
  FID_S: Int
  Name: String
  AlternateNames: String
  NewSynonyms: String
  Description: String
  HomePage: String
  CreationDate: String
  Type: String
  image: String
}
```

Then I tried to query as such:

```graphql
{
nodes{
  Name
}
}
```

I get:

```json
{
  "data": {
    "nodes": []
  }
}
```

The database obviously has a lot of nodes but nothing is returned. What am I missing? This worked fine using the old, no longer supported graphql library.

Thank you.

**Comment by darrellwarde** [comment]
Hi @wolfgang-ldc, can you clarify what you mean by "type definition that should cover any node in my database"? Does every single node in your database have the label "Node"?

You should note, that in version 2.0.0 of the library which is coming soon, `Node` will be a protected word that can't be used in your type definitions.

**Comment by wolfgang-ldc** [comment]
Hi Darrell,

thanks for getting back to me. The previous Neo4j GraphQL library which I am using currently allowed the definition of a type that covers ALL node labels within the database. I had actually called it "Item" rather than "Node" in my database, as such the actual name is not important. What is important is that one can define it without having it tied to an actual node label in the database, as long as the labels all have a unique ID and other common properties, such as Name and Description, for example.

This actually enables a powerful cross-database/label search irrespective of the associated node label. Type definitions that are associated with a node label currently work fine, but my "Item" example doesn't. I understand that the term "Node" is going to be protected going forward, which makes a lot of sense. Please let me know if I am not making myself clear. I really hope that the cross-label type definition functionality is retained.

Thanks so much, Wolfgang

**Comment by wolfgang-ldc** [comment]
Just to add an example to my previous description. I have a regular type definition for a label called Company, and within I have defined what I call "Items", which is a @cypher directive defined as such:
type Company {
  FID: ID!
  FID_S: Int
  Name: String
  Items: [Item]
    @cypher(statement: "MATCH (this)-[]-(n) RETURN n")
}
It returns anything that is related to this company. This operation works perfectly fine.

However, querying the Item definition directly returns nothing.
type Item {
  FID:ID!
  FID_S:Int
  Name: String
}

Hope that adds a little more context.

**Comment by wolfgang-ldc** [comment]
Hi Darrell,

upon further testing I realized that I also don't get any results returned for my Item query using the original neo4j GraphQL library. It seems I was following a different query doing my refactoring steps.
As such I think we can close this query as things seems to be working fine now.
Sorry for the extra time to think about this issue, which wasn't an issue :-)

Wolfgang
