### ISSUE TITLE
The generated schema is invalid if uppercase names are used

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3098]
Try to define an interface ABCDFoo and generate the schema (e.g. using the ORM schema generation command). The type is sometimes called ABCDFoo and sometimes AbcdFoo and so the schema will be invalid.

I'll provide a full example of this later if necessary.

**Comment by darrellwarde** [comment]
Please do provide an example @jroith, we'll check back on this later!

**Comment by darrellwarde** [comment]
@jroith, I've tried and failed to reproduce this - can you please provide a set of type definitions which can be used to reproduce this?
