### ISSUE TITLE
Use the neo4j internal ID with the id() function

### ISSUE THREAD

**Issue by glickel** [neo4j/graphql#311]
**Is your feature request related to a problem? Please describe.**
I want to create a graphQL on a existing neo4j that use the internal id `<id>`. 
I need to get this id, have it read-only and auto-generated by neo4j, and have the same where conditions than other fields.

**Describe the solution you'd like**
I would like a new option like `internal` to put at true, or a new directive like `internalId`. This change should use the [id function](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-id) on every query.

**Describe alternatives you've considered**
Current I tried something like that:
```
id: ID! @readonly @cypher(
    statement: """
        MATCH (this)
        RETURN ID(this)
    """
)
```
But it's impossible to use the id field in the where part.

**Additional context**
If this feature is interesting for you and you accept it, I can do the PR.

**Comment by danstarns** [comment]
I like this idea. Contrasting between `neo4j-graphql-js` and this lib, we deliberately removed the exposure of the internal node id as we found that it is both leaky and not particularly safe for most application use cases(as the ids can be reused). In my opinion, allowing users to specify a directive such as `internalId` should enable users to; read, filter and sort by the internal node id, however, shouldn't allow upserts on the field. What do you think about this?

**Comment by glickel** [comment]
This is exactly what I need, so it's good for me :)
In my issue I miss something, when I said `I would like a new option like internal`, I wrote about the current `@id` directive.
What do you prefer between adding a new option for `@id` directive and adding a new `@internalId` directive ?

**Comment by danstarns** [comment]
> This is exactly what I need, so it's good for me :)
> In my issue I missed something, when I said `I would like a new option like internal`, I wrote about the current `@id` directive.
> What do you prefer between adding a new option for `@id` directive and adding a new `@internalId` directive ?

The `@id` directive is for autogeneration so let's go for a new one. Would love to hear @darrellwarde thoughts here too.

**Comment by darrellwarde** [comment]
Personally, I favour making use of the existing `@id` directive rather than adding _yet more_ directives. Our current directive definition is:

```graphql
directive @id(
  autogenerate: Boolean! = true
) on FIELD_DEFINITION
```

Whilst at the moment its only real use is autogeneration, it could easily be extended in my opinion. It would be a breaking change, but what if we had something like:

```graphql
enum IDType {
  AUTOGENERATED
  INTERNAL
}

directive @id(
  type: IDType! = AUTOGENERATED
) on FIELD_DEFINITION
```

This way, the default behaviour would still be autogeneration if used without any arguments, but you could expose the internal ID using:

```graphql
type Node {
  _id: ID! @id(type: INTERNAL)
}
```

It would also give us options for adding different ID formats in the future.

**Comment by glickel** [comment]
@darrellwarde If your solution is taken, could it be integrated to the version 2 ?

**Comment by darrellwarde** [comment]
> @darrellwarde If your solution is taken, could it be integrated to the version 2 ?

Hey @glickel, @danstarns and I had a bit of a chat about this morning and I think we're going to run with the solution above!

We're at an interesting point of 2.0.0 development where we're about to go beta, and we really shouldn't be adding any more features at that point until after we've performed the stable release.

However, you mentioned that you might be keen on contributing this feature yourself - if that is the case then please feel free to branch off the 2.0.0 branch and then we can merge it in as we see fit to fit into our release schedule. Let us know if that's something you would want to have a go at! 🙂

**Comment by glickel** [comment]
Hi @darrellwarde, just to avoid misunderstandings the solution above is to change the current `@id` directive ?
But yes that something I want to do ! 🙂  
I will try to push to push a first draft in several days

**Comment by darrellwarde** [comment]
Indeed, we'll go for the approach below:

> Personally, I favour making use of the existing `@id` directive rather than adding _yet more_ directives. Our current directive definition is:
> 
> ```graphql
> directive @id(
>   autogenerate: Boolean! = true
> ) on FIELD_DEFINITION
> ```
> 
> Whilst at the moment its only real use is autogeneration, it could easily be extended in my opinion. It would be a breaking change, but what if we had something like:
> 
> ```graphql
> enum IDType {
>   AUTOGENERATED
>   INTERNAL
>   UNMANAGED
> }
> 
> directive @id(
>   type: IDType! = AUTOGENERATED
> ) on FIELD_DEFINITION
> ```
> 
> This way, the default behaviour would still be autogeneration if used without any arguments, but you could expose the internal ID using:
> 
> ```graphql
> type Node {
>   _id: ID! @id(type: INTERNAL)
> }
> ```
> 
> And what would have used to have been `@id(autogenerate: false)` (which I doubt anyone was using anyone because there was literally zero benefits to it) would now be `@id(type: UNMANAGED)`.
> 
> It would also give us options for adding different ID formats in the future.

Looking forward to receiving your contribution, give us a shout if you need a hand at all (we're pretty active on Discord - https://discord.gg/neo4j if you're not already signed up)!

**Comment by danstarns** [comment]
Going to close this one as a no-go. On the [Neo4j docs it states](https://neo4j.com/docs/cypher-manual/current/clauses/match/#match-node-by-id): 

>Neo4j reuses its internal ids when nodes and relationships are deleted. This means that applications using, and relying on internal Neo4j ids, are brittle or at risk of making mistakes.

We don't want to encourage our lib users to use this functionally.

**Comment by mchaliadzinau** [comment]
Are there any workaround for this?
We're hoping to make use of internal Neo4j ids since we are not going to delete any nodes (only soft-delete is allowed, so ids reuse concern not really applicable to our use case).
