### ISSUE TITLE
@auth decorator supporting "one of" in allow conditions

### ISSUE THREAD

**Issue by GearsAD** [neo4j/graphql#3111]
**Is your feature request related to a problem? Please describe.**
It would be helpful to define @auth allow conditions that have to be true for one element in the condition when referring to an array. 

> Note: This may already be possible, but I haven't found it in the documentation. 

For example, in the schema below, there are multiple Owners of an Apple (similar to multiple users in a team). I would like to use that condition in the `allow` part of the @auth conditions. 

```
type Apple @auth(
    rules: [
      {
        allow: {
          # Allow if you are one of the owners
          owners: { id: "$jwt.sub" }
        }
      }
    ])
{
  name: String!
  species: String

  # This a co-op and there are many owners
  owners: [Owner!]!
}

type Owner {
  id: ID!
  name: String!
  apples: [Apple!]!
}
```

**Describe the solution you'd like**

A simple solution would be to provide the array filter extensions to the @auth conditions, so that we could do something like:
```
type Apple @auth(
    rules: [
      {
        allow: {
          # Allow if you are one of the owners
          owners_SOME: { id: "$jwt.sub" }
        }
      }
{
``` 

**Describe alternatives you've considered**
The alternative is to rewrite part of the @auth decorators, I'm not certain there is another way to set up the schema.

**Additional context**
Fantastic library, thank you for developing it!

**Comment by darrellwarde** [comment]
This is being worked right now @GearsAD, as part of a complete rearchitecture of authorizaton - watch this space!!

**Comment by to-kn** [comment]
@darrellwarde is there any documentation available what new possibilities are possible after your rewrite? any hints about a possible release? (could that also be helpful regarding the following question: https://github.com/neo4j/graphql/discussions/3090)

**Comment by to-kn** [comment]
for the first part of my question, i found the rfc, thanks for your great work: https://github.com/neo4j/graphql/blob/dev/docs/rfcs/rfc-036-authorization.md

**Comment by darrellwarde** [comment]
> > This is being worked right now @GearsAD, as part of a complete rearchitecture of authorizaton - watch this space!!
> 
> That's great news! AuthZ is always a fun one, appreciate you making it easy to do. I believe I have a workaround for the moment, but if that pattern is possible in the new release that would be amazing.
> 
> Would you like me to keep this open, or close it? Feel free to close if you prefer.

I will close it as we already have a few issues covering this work - I'll mention it in there!
