### ISSUE TITLE
Enable transactions on the OGM

### ISSUE THREAD

**Issue by HiiiiD** [neo4j/graphql#3151]
**Is your feature request related to a problem? Please describe.**
As far as I tried to understand, there's no concept of transactions in the OGM library since, under the hood, is using GQL.
This feature is so important for the usage of the OGM library, since no one will use it without them, am I missing something or you have plans for adding it in the future?

**Describe the solution you'd like**
I'd like to be able to pass a Neo4J native session to OGM functions (create, update, delete) in order to potentially rollback if the queries that I've run are broken.

**Describe alternatives you've considered**
The one and only alternative is to use raw cypher queries

**Comment by darrellwarde** [comment]
Hey @HiiiiD, you can pass a driver, session or transaction into the `executionContext` field of the context, and this works exactly as you describe. Thanks!

**Comment by mc-luisg** [comment]
> Hey @HiiiiD, you can pass a driver, session or transaction into the `executionContext` field of the context, and this works exactly as you describe. Thanks!

You literally saved my life just right now.
