### ISSUE TITLE
Query by edge property not working with union type

### ISSUE THREAD

**Issue by mklinger** [neo4j/graphql#3165]
**Describe the regression**

Querying a node by edge property with union type is not working anymore.

**Last working version**

Worked up to version: @neo4j/graphql@3.17.1

Stopped working in version: @neo4j/graphql@3.17.2

**Type definitions**

```graphql
type A  {
  name: String!
  related: [Related!]!
  @relationship(
    type: "PROPERTY_OF"
    properties: "RelatedProperties"
    direction: IN
  )
}

type B  {
  name: String!
  related: [Related!]!
  @relationship(
    type: "PROPERTY_OF"
    properties: "RelatedProperties"
    direction: IN
  )
}

union RelatedTarget = A | B

interface RelatedProperties @relationshipProperties {
  prop: String!
}

type Related {
  name: String!
  value: String!
  target: RelatedTarget!
  @relationship(
    type: "PROPERTY_OF"
    properties: "RelatedProperties"
    direction: OUT
  )
}
```

**To Reproduce**

Create mutation:

```graphql
mutation CreateA {
  createAs(input: {
    name: "A",
    related: {
      create: {
        edge: {
          prop: "propvalue"
        },
        node: {
          name: "Related",
          value: "value"
        }
      }
    }
  }) {
    as {
      name,
      relatedConnection {
        edges {
          prop
          node {
            name
          }
        }
      }
    }
  }
}
```

Query:
```graphql
query Relateds {
  relateds(
    where: {
      OR: [
        { targetConnection: { A: { edge: { prop: "propvalue" } } } }
        { targetConnection: { B: { edge: { prop: "propvalue" } } } }
      ]
    }
  ) {
    name
  }
}
```

Actual result:
```json
{
  "data": {
    "relateds": []
  }
}
```

**Expected behavior**

Expected result:
```json
{
  "data": {
    "relateds": [
      {
        "name": "Related"
      }
    ]
  }
}
```

**System (please complete the following information):**

-   OS: Ubuntu 22.04.2
-   Node.js version: 18.13.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mklinger. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mklinger! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
Thank you for the detailed reproduction steps @mklinger, I've been able to reproduce what you describe. We'll take a closer look!

**Comment by darrellwarde** [comment]
De-parameterized Cypher for the query below:

```
MATCH (this:`Related`)
MATCH (this)-[this0:PROPERTY_OF]->(this1:`A`)
MATCH (this)-[this2:PROPERTY_OF]->(this3:`B`)
WITH *
WHERE (this0.prop = "propvalue" OR this2.prop = "propvalue")
RETURN this { .name } AS this
```

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
