### ISSUE TITLE
Extension of the full text queries to determine the total number

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#3208]
**Is your feature request related to a problem? Please describe.**
The fulltext directive generates a query where you can paginate with limit and offset.
But there is currently no way to find out how many results exist in total. However, this is necessary for pagination - for example, to display in a frontend how many pages exist.

**Describe the solution you'd like**
Besides the result itself and the score, the result type of the full text search could contain a new field "totalCount".

**Comment by darrellwarde** [comment]
Closing as a duplicate of #2681 because total count is an aggregation.
