### ISSUE TITLE
First and offset parameters when querying fields

### ISSUE THREAD

**Issue by ricardocastanho** [neo4j/graphql#3210]
In neo4j-graphql-js we had additional parameters as `first` and `offset` when accessing a field with the `@cypher` directive.
My app sometimes use these additional parameters and sometimes don't, but now I have a problem because I can only have or not have these parameters. 

**neo4j-graphql-js**
```graphql
type Movie {
  title: String!
  similarMovies: [Movies] @cypher(
    statement: """
    MATCH (this)-[:IN_GENRE]->(g:Genre)<-[:IN_GENRE]-(m:Movies)
    RETURN m
    """
  )
}
```

In the old lib I can query similar movies without needing to explicity add a `limit` parameter in the field definition:

```graphql
query {
  Movie {
    title
    similarMovies {
      title
    }
    #  Or querying the first 10:
    #  similarMovies(first: 10) {
    #    title
    #  }
  }
}
```

<hr>

**@neo4j/graphql**
To reproduce the same comportament as above with the current lib, I have to explicity add a `first` or a `limit` column in the field `similarMovies`.

```graphql
type Movie {
  title: String!
  similarMovies(limit: Int!): [Movies] @cypher(
    statement: """
    MATCH (this)-[:IN_GENRE]->(g:Genre)<-[:IN_GENRE]-(m:Movies)
    RETURN m
    LIMIT $limit
    """
  )
}
```

It's alright when querying with the `limit` param. The problem is when querying similar movies without it.

```graphql
query {
  movies {
    title
    similarMovies { #  This throws an error
      title
    }
    #  This works
    #  similarMovies(limit: 10) {
    #    title
    #  }
  }
}
```

For now I couldn't find a workaround for this problem.

**Comment by a-alle** [comment]
Hi @ricardocastanho, is there a reason why you defined the `limit` argument to be required? 
```gql
similarMovies(limit: Int!): [Movies]
```
Would making it a non-required field solve your problem? 
```gql
similarMovies(limit: Int): [Movies]
```

**Comment by ricardocastanho** [comment]
@a-alle Sorry for not beeing especific. I need the `limit` to be required because the cypher gives me the following error:

> Failed to invoke function `apoc.cypher.runFirstColumnMany`: Caused by: org.neo4j.exceptions.CypherTypeException: Expected a numeric value for org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.NumericHelper$@4f56af0, but got null

I've found two possible workarounds for this behavior:

1.  Set up a big default value in the `limit` parameter.
```graphql
similarMovies(limit: Int = 10000000, offset: Int = 0): [Movies]
  @cypher(
    statement: """
      MATCH (this)-[:IN_GENRE]->(g:Genre)<-[:IN_GENRE]-(m:Movies)
      RETURN m
      SKIP $offset
      LIMIT $limit
    """
```

2. Use `apoc.when` to handle when the `limit` parameter is not set.
```graphql
similarMovies(limit: Int = 0, offset: Int = 0): [Movies]
  @cypher(
    statement: """
      WITH this, toInteger($limit) as pageSize, toInteger($offset) as skipSize
      CALL apoc.when(
        toBoolean(pageSize > 0),
        'MATCH (this)-[:IN_GENRE]->(g:Genre)<-[:IN_GENRE]-(m:Movies)
        RETURN m
        SKIP $skipSize
        LIMIT $pageSize',
        'MATCH (this)-[:IN_GENRE]->(g:Genre)<-[:IN_GENRE]-(m:Movies)
        RETURN m
        SKIP $skipSize',
        {pageSize: pageSize, skipSize: skipSize, this: this}
      ) YIELD value
      RETURN value.m
    """
```

As you can see, this is a little awkward and some expensive if you are migrating from `neo4j-graphql-js`.
I hope we can discuss a better solution and that this can help someone 😉.

**Comment by darrellwarde** [comment]
We'll leave pagination for actual relationships, and try to add support for more complex relationship paths in future additions. We won't add it for custom Cypher.
