### ISSUE TITLE
Reconnect in case of a To-1 relationship

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#3248]
**Describe the bug**
I have a simple To-1 relationship where I want to change the relationship to one node to another node. Unfortunately an update does not work. I get the error message "... required exactly once"

**Type definitions**
````graphql
type Movie {
  name: String!
  genre: Genre! @relationship(type: "HAS_GENRE", direction: OUT)
}

type Genre {
  name: String! @unique
  movies: [Movie!]! @relationship(type: "HAS_GENRE", direction: IN)
}
````
**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...
2.1. Init Genres
````graphql
mutation CreateGenres {
  createGenres(input: [
    {
      name: "Action"
    },
    {
      name: "Thriller"
    }
  ]) {
    genres {
      name
    }
  }
}
````
2.2. Init Movie with connection to the Genre "Action"
````graphql
mutation CreateMovie {
  createMovies(input: {
    name: "TestMovie1",
    genre: {
      connect: {
        where: {
          node: {
            name: "Action"
          }
        }
      }
    }
  }) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````
3. Then run the following Mutation to update the relationship...
````graphql
mutation UpdateMovieWithUpdateConnect {
  updateMovies(
    where: {
      name: "TestMovie1",
    },
    update: {
      genre: {
	connect: {
          where: {
            node: {
              name: "Thriller"
            }
          }
        }
      }
    }
  ) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````
````json
{
  "errors": [
    {
      "message": "Movie.genre required exactly once",
      "locations": [
        {
          "line": 39,
          "column": 3
        }
      ],
      "path": [
        "updateMovies"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}
````

**Expected behavior**
As a client, I would like to be able to reconnect an existing relationship to a new node.

**Current workaround**
Perform an explicit disconnect in addition to the connect.
As a client, however, this behavior is not intuitive

````graphql
mutation UpdateMovieWithUpdateConnectAndDisconnect {
  updateMovies(
    where: {
      name: "TestMovie1",
    },
    update: {
      genre: {
	connect: {
          where: {
            node: {
              name: "Thriller"
            }
          }
        },
        disconnect: {
          where: {
            node: {
              NOT: {
                name: "Thriller"
              }
            }
          }
        }
      }
    }
  ) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````

**System (please complete the following information):**
* Version: 3.18.2

**Additional context**
1. I noticed that there is a new parameter "overwrite" in connect. I'm not sure if that helps or has anything to do with it at all. I can't find any documentation on this.
2. When you want to perform a reconnect to a node that does not exist/ could not be found, there is no error message. The response is successful, but logically no reconnect has taken place. Unfortunately, the client does not notice this.

**Comment by AccsoSG** [comment]
Hi @darrellwarde 
Thanks for the quick reply. That makes sense!

In this case it is so that the relationship of Movie to Genre is mandatory. So a Movie always needs a Genre. That would mean that the workaround we are currently using is the only way for a reconnect/redirect. It has to happen in a single mutation. 

First the disconnect in a single mutation and then a new connect in a second mutation would not work...

Or do you have another suggestion to solve the problem with the current possibilities?

This workaround works quite well so far. However, it's not really intuitive for our client applications. A redirect/reconnect would be a really valuable feature!

**Comment by darrellwarde** [comment]
I'm afraid not, the best workaround is the one which you have described of `disconnect` and `connect` in a single Mutation.

I will note down this feature need as something we might address soon(ish), sorry about the unintuitive experience at the moment!

**Comment by AccsoSG** [comment]
@darrellwarde Thanks for the reply. That sounds good 👍 

But apart from that, I found an error in the context of this problem I think. I ran the following mutations and found some strange behavior.

In the example, a movie is supposed to have exactly one genre.

1. Initialize the data for Movie and Genre as described above
2. This mutation works as expected -> error message: "Movie.genre required exactly once"
````graphql
mutation UpdateMovieWithConnect {
  updateMovies(
    where: {
      name: "TestMovie1",
    },
    connect: {
      genre: {
        where: {
          node: {
            name: "Thriller"
          }
        }
      }
    }
  ) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````
3. But this mutation then creates inconsistent data by creating a second relation
````graphql
mutation UpdateMovieWithConnectAndUpdate {
  updateMovies(
    where: {
      name: "TestMovie1",
    },
    update: {
      name: "TestMovie1"
    }
    connect: {
      genre: {
        where: {
          node: {
            name: "Thriller"
          }
        }
      }
    }
  ) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````
![image](https://user-images.githubusercontent.com/49721200/235113563-bc245ec8-28dd-4f14-83fb-e1442089865d.png)

**Comment by darrellwarde** [comment]
Hey @AccsoSG, I've referenced the above in a new bug report, we will look into it.

Frankly, we're considering just getting rid of this validation altogether - it's just an extremely poor fit for the library; it performs terribly and it's extremely difficult or even impossible to account for all cases in Cypher.

There are plans for a lot more constraints to be added to the database itself, and we're hoping that down the line, we will be able to leverage these instead.

**Comment by darrellwarde** [comment]
In Version 7 of the library, we will only be supporting m:m relationships because that is all that the database natively supports.
