### ISSUE TITLE
Using `update` and `connect` allows for violation of 1:1 rule

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#3251]
@darrellwarde Thanks for the reply. That sounds good 👍 

But apart from that, I found an error in the context of this problem I think. I ran the following mutations and found some strange behavior.

In the example, a movie is supposed to have exactly one genre.

1. Initialize the data for Movie and Genre as described above
2. This mutation works as expected -> error message: "Movie.genre required exactly once"
````graphql
mutation UpdateMovieWithConnect {
  updateMovies(
    where: {
      name: "TestMovie1",
    },
    connect: {
      genre: {
        where: {
          node: {
            name: "Thriller"
          }
        }
      }
    }
  ) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````
3. But this mutation then creates inconsistent data by creating a second relation
````graphql
mutation UpdateMovieWithConnectAndUpdate {
  updateMovies(
    where: {
      name: "TestMovie1",
    },
    update: {
      name: "TestMovie1"
    }
    connect: {
      genre: {
        where: {
          node: {
            name: "Thriller"
          }
        }
      }
    }
  ) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
````
![image](https://user-images.githubusercontent.com/49721200/235113563-bc245ec8-28dd-4f14-83fb-e1442089865d.png)

_Originally posted by @AccsoSG in https://github.com/neo4j/graphql/issues/3248#issuecomment-1527283431_

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @darrellwarde. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Steps for setup before reproduction:

Type definitions:

````graphql
type Movie {
  name: String!
  genre: Genre! @relationship(type: "HAS_GENRE", direction: OUT)
}

type Genre {
  name: String! @unique
  movies: [Movie!]! @relationship(type: "HAS_GENRE", direction: IN)
}
````

Data Mutations:

````graphql
mutation CreateGenres {
  createGenres(input: [
    {
      name: "Action"
    },
    {
      name: "Thriller"
    }
  ]) {
    genres {
      name
    }
  }
}
````

````graphql
mutation CreateMovie {
  createMovies(input: {
    name: "TestMovie1",
    genre: {
      connect: {
        where: {
          node: {
            name: "Action"
          }
        }
      }
    }
  }) {
    movies {
      name
      genre {
        name
      }
    }
  }
}
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
When looking at the generated Cypher, it can be seen that the cardinality check only happens after the update:

```
MATCH (this:`Movie`)WHERE this.name = $param0SET this.name = $this_update_nameWITH thisCALL {	WITH this	MATCH (this)-[this_genre_Genre_unique:HAS_GENRE]->(:Genre)	WITH count(this_genre_Genre_unique) as c	CALL apoc.util.validate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDMovie.genre required exactly once', [0])	RETURN c AS this_genre_Genre_unique_ignored}WITH thisCALL {	WITH this	OPTIONAL MATCH (this_connect_genre0_node:Genre)	WHERE this_connect_genre0_node.name = $this_connect_genre0_node_param0	CALL {		WITH *		WITH collect(this_connect_genre0_node) as connectedNodes, collect(this) as parentNodes		CALL {			WITH connectedNodes, parentNodes			UNWIND parentNodes as this			UNWIND connectedNodes as this_connect_genre0_node			MERGE (this)-[:HAS_GENRE]->(this_connect_genre0_node)			RETURN count(*) AS _		}		RETURN count(*) AS _	}WITH this, this_connect_genre0_node	RETURN count(*) AS connect_this_connect_genre_Genre}WITH *CALL {    WITH this    MATCH (this)-[update_this0:HAS_GENRE]->(update_this1:`Genre`)    WITH update_this1 { .name } AS update_this1    RETURN head(collect(update_this1)) AS update_var2}RETURN collect(DISTINCT this { .name, genre: update_var2 }) AS data
```

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
