### ISSUE TITLE
Custom Directives do not support input types

### ISSUE THREAD

**Issue by dnorton** [neo4j/graphql#3270]
I posted this on Discord some time ago, but I think it warrants opening a bug here.  The current implementation of `neo4j-graphql` does not support adding input types on custom directives.

Here is a simple way to reproduce the problem.  This code is completely valid if I use `makeExecutableSchema` and aligns to the GraphQL schema definition but not if I instantiate it from `neo4jGraphQl.getSchema()`

```gql
directive @testDirective(
          action_mapping: [ActionMapping]
        ) on OBJECT | FIELD_DEFINITION | QUERY

input ActionMapping {
   action: [String!]
}  
```

If I run this through `neo4jGraphQL.getSchema()`:

```typescript
try {
    const schema = await neo4jGraphQL.getSchema();
  } catch (e: any) {
    expect(e.message).toEqual('Error: Type with name "ActionMapping" does not exists');
  }
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @dnorton. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by dnorton** [comment]
Here is a jest test that I wrote to reproduce the problem:

```typescript
test('test with Neo4j GraphQL Schema', async () => {
  const originalSchema = buildTestSchema();
  const neo4jGraphQL = new Neo4jGraphQL({
    typeDefs: originalSchema,
  });
  expect(neo4jGraphQL).toBeDefined();
  try {
    const schema = await neo4jGraphQL.getSchema();
  } catch (e: any) {
    expect(e.message).toEqual('Error: Type with name "ActionMapping" does not exists');
  }
});
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @dnorton! :pray: We will now prioritise the bug and address it appropriately.

**Comment by a-alle** [comment]
Hey @dnorton,
I used the following type definitions in order to reproduce your problem:
```gql
  directive @testDirective(action_mapping: [ActionMapping]) on OBJECT | FIELD_DEFINITION | QUERY
  input ActionMapping {
     action: [String!]
   }
  type TestType {
     someField: String
   }
```
Basically you need to define a type in order to avoid the `Type Query must define one or more fields.` error. The assumption is you would always define an ObjectType in your schema in order to take advantage of the library, which would resolve this error.

Let me know if this works for your use case and we'll merge the fix soon. Thank you!

**Comment by dnorton** [comment]
I finally test this, and it's working now! Thank you @a-alle
