### ISSUE TITLE
Invalid cypher generation with info response body

### ISSUE THREAD

**Issue by Hellenic** [neo4j/graphql#3355]
**Describe the bug**
When doing an update mutation, with subscription plugin enabled, requesting only the `info` object in response body generates invalid cypher, returning an error: ` "Invalid input ',': expected \"*\", \"DISTINCT\" or an expression (line 27, column 8 (offset: 1318))\n\"RETURN , collect(DISTINCT m) as meta\"\n        ^"`

**To Reproduce**
I have not yet tested this with clean install, but should be reproducable with something like this:

1. On `subscriptions` plugin (e.g. `Neo4jGraphQLSubscriptionsSingleInstancePlugin`)
2. Execute a mutation with only `info` fields in the response (example screenshot below)

**Expected behavior**
This should not throw an error, and was still working in at least `3.16.1` version. Including any field about updated object will work-around the issue. Also, commenting out the subscription plugin will work-around the issue.

From debug logs I can see that erronous query being generated, and with that, I suspect this part of the code is the culprit: https://github.com/neo4j/graphql/blob/4259f84ce8f7c24739ca6877ba12d0835c42a983/packages/graphql/src/translate/translate-update.ts#L508

**Screenshots**
![image](https://github.com/neo4j/graphql/assets/1734471/6d438c36-e1b8-49f1-8e83-525801efcc59)

**System (please complete the following information):**

* OS: Ubuntu
* Version: `@neo4j/graphql@3.18.3`, 
* Node.js version: Node `8.19.4`, npm `16.20`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Hellenic. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Hellenic! :pray: We will now prioritise the bug and address it appropriately.
