### ISSUE TITLE
Ordering not taking alias into account

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#3394]
**Describe the bug**
Sorting by `@alias` properties do not take into account aliased name, and instead sorts by property name.

**Type definitions**
```graphql
type Product {
  id: String! @alias(property: "fg_item_id")
  description: String!
  partNumber: ID! @alias(property: "fg_item")
}
```

**To Reproduce**
```
query listProducts {
  products(options: { sort: { partNumber: DESC } }) {
    id
    partNumber
    description
  }
}
```

Generates the Cypher:

```cypher
MATCH (this:`Product`)
WITH *
ORDER BY this.partNumber DESC
RETURN this { id: this.fg_item_id, partNumber: this.fg_item, .description } AS this
```

**Expected behavior**
The ordering should be using the aliased value:

```
MATCH (this:`Product`)
WITH *
ORDER BY this.fg_item DESC
RETURN this { id: this.fg_item_id, partNumber: this.fg_item, .description } AS this
```

**Additional context**
Original message: https://discord.com/channels/787399249741479977/1112848457015754904

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @angrykoala! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
