### ISSUE TITLE
`nestedOperations` `UPDATE` also controls the top-level operations

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#3413]
**To Reproduce**
There is a schema test for `nestedOperations` with the following type defs:

```gql
type Person {
  name: String
}

type Movie {
  id: ID
  actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
  producers: [Person!]! @relationship(type: "PRODUCED", direction: IN, nestedOperations: [DISCONNECT])
}
```

If I add UPDATE to the nested operations, I see the following additions to the schema:

```
  + input MovieProducersUpdateConnectionInput {
  +  node: PersonUpdateInput
  + }
  +
  + input MovieProducersUpdateFieldInput {
  +  disconnect: [MovieProducersDisconnectFieldInput!]
  +  update: MovieProducersUpdateConnectionInput
  +  where: MovieProducersConnectionWhere
  + }
  +

   input MovieUpdateInput {
    actors: [MovieActorsUpdateFieldInput!]
    id: ID
  +  producers: [MovieProducersUpdateFieldInput!]
   }
```

**Expected behavior**
The problem is that I would have expected the following:

1. The `producers` field on `MovieUpdateInput` should have already been there - this should be controlled by the new `@settable` directive
2. The `MovieProducersUpdateFieldInput` should have already existed with just the `disconnect` and `where` fields (the `DISCONNECT` operation was already enabled)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
