### ISSUE TITLE
`nestedOperations` does not work with interfaces/unions

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#3429]
**Describe the bug**
Using `nestedOperations` on an interface/unions relationship does not change the schema.

**Interface**

There is not differences in the generated schema between the following type definitions:

All nested operations should be generated:
```gql
  interface Actor {
      name: String
  }

  type ActorFoo implements Actor {
      name: String
  }

  type Movie {
      id: ID
      actors: [Actor!]! @relationship(type: "HAS_ACTOR", direction: OUT)
  }
```

No nested operations should be generated:
```gql
  interface Actor {
      name: String
  }

  type ActorFoo implements Actor {
      name: String
  }

  type Movie {
      id: ID
      actors: [Actor!]! @relationship(type: "HAS_ACTOR", direction: OUT, nestedOperations: [])
  }
```

**Union**
There is not differences in the generated schema between the following type definitions:

All nested operations should be generated:
```gql
type Actor {
    name: String
}

type Director {
    name: String
}

union Person = Actor | Director

type Movie {
    id: ID
    actors: [Person!]! @relationship(type: "HAS_ACTOR", direction: OUT)
}
```

No nested operations should be generated:
```gql
type Actor {
    name: String
}

type Director {
    name: String
}

union Person = Actor | Director

type Movie {
    id: ID
    actors: [Person!]! @relationship(type: "HAS_ACTOR", direction: OUT, nestedOperations: [])
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
