### ISSUE TITLE
Certain `nestedOperations` cause empty `<type><rel-field>FieldInput` types to be generated with no field

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#3437]
### Type definitions

```GraphQL
type Person {
    name: String
}

type Movie {
    id: ID
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN, nestedOperations: [CREATE])
}
```

### Test data

```Shell
N/A
```

### Steps to reproduce

The following `nestedOperations` arrays cause the error to be thrown:

- [UPDATE]
- [DISCONNECT]
- [DELETE]

### What happened

An error stating: `Input Object type <type><rel-name>FieldInput must define one or more fields.`

### Version

3.20.1

### Database version

N/A

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by MacondoExpress** [comment]
I think I involuntary fixed it on https://github.com/neo4j/graphql/pull/3432

**Comment by MacondoExpress** [comment]
> Input Object type <type><rel-name>FieldInput must define one or more fields.

My bad, thought that the error was raised at the startup time!
