### ISSUE TITLE
Nested deletes on related unions errors

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#3455]
### Type definitions

```GraphQL
type PersonOne {
  name: String
}

type PersonTwo {
  nameTwo: String
}

union Person = PersonOne | PersonTwo

type Movie {
  id: ID
  actors: [Person!]!
    @relationship(type: "ACTED_IN", direction: IN)
}
```

### Steps to reproduce

Execute the following query:

```gql
mutation {
  updateMovies(
    update: {
      actors: {
        PersonOne: { delete: { where: { node: { name: "someName" } } } }
      }
    }
  ) {
    info {
      nodesCreated
      nodesDeleted
    }
  }
}

```

### What happened

The following error in response:

```json
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'name')",
      "locations": [{ "line": 2, "column": 3 }],
      "path": ["updateMovies"]
    }
  ],
  "data": null
}
```

### Expected behaviour

No error

### Version

3.20.1

### Database version

N/A

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.
