### ISSUE TITLE
Return nodes with context from OGM in custom resolvers to support additional @cypher queries on properties

### ISSUE THREAD

**Issue by kristjanmik** [neo4j/graphql#347]
**Is your feature request related to a problem? Please describe.**
An issue was raised on Discord regarding OGM instances in custom resolvers not having any request context. This results in broken nested cypher queries that rely on context such as `$auth`.

A slimmed down schema looks like this:
```graphql
type User {
  id: ID! @id
  knownByMe: Boolean
    @cypher(
      statement: """
      OPTIONAL MATCH (this)<-[rel:KNOWS]-(user:User {id: $auth.jwt.sub})
      WITH user IS NOT NULL AS isFound
      RETURN isFound
      """
    )
}

type Query {
  me: User
}
```

Through autogeneration, a users query is made available:
```graphql
query AllUsers{
  users(where:{id:"user2"}){
    id
    knownByMe
  }
}
```

It returns expected results, with **knownByMe:true**:
```json
{
  "data": {
    "users": [
      {
        "id": "user2",
        "knownByMe": true
      }
    ]
  }
}
```

So far, so good! Now we venture on and write a custom resolver for the single user query.

The same query as above but through the custom resolver:
```graphql
query SingleUser {
  user(id:"user2"){
    id
    knownByMe
  }
}
```

It returns wrong results, with **knownByMe:false** :
```json
{
  "data": {
    "user": {
      "id": "user2",
      "knownByMe": false
    }
  }
}
```

The `$auth.jwt.sub` is unavailable on the OGM object that is returned in the custom resolver. A simplified resolver to provide more clarity.
```ts
async me(root, _, context, info) {
  const userId = context?.jwt?.sub;

  if (!userId) return null;

  return context.ogm.model('User').find({
    where: {
      id: userId,
    },
    selectionSet: ...,
  }).then(results => results[0]);
}
```

_**Based on the example above, there is no way to make knownByMe work for custom resolvers.**_

**Describe the solution you'd like**
We need a way to inject context into the OGM to support nested queries all the way down. It would make more sense if we had a method in the custom resolvers (as a part of the context, for example) to query the database as the non-custom resolvers use that honor all rules defined in the schema. 

**Describe alternatives you've considered**
No other solution comes to mind

**Comment by danstarns** [comment]
Hey @kristjanmik . You can achive a simmilar outcome by leveraging [Auth on Cypher](https://neo4j.com/docs/graphql-manual/current/auth/setup/#_auth_on_cypher). Try this: 

```gql
type Query {
    me: User
        @cypher(
            statement: """
            MATCH (u:User { id $auth.jwt.sub })
            RETURN u
            """
        )
}
```

Then you should be able to query as normal: 

```gql
{
    me {
        id
        knownByMe
    }
}
```

That being said, my proposal is a workaround and doesn't address the real issue at hand.

**Comment by MacondoExpress** [comment]
Hi, @kristjanmik,
In your scenario, it's possible to share the context with OGM, using your example:
```js
async me(root, _, context, info) {
  const userId = context?.jwt?.sub;

  if (!userId) return null;

  return context.ogm.model('User').find({
    where: {
      id: userId,
    },
    selectionSet: ...,
   context  <-- this makes the job done
  }).then(results => results[0]);
}
```
Sorry to re-open the thread after a while :)
Let me know if I can close.
