### ISSUE TITLE
Error while migrating to version 3.19.0 and above

### ISSUE THREAD

**Issue by nsenoge63** [neo4j/graphql#3488]
### Discussed in https://github.com/neo4j/graphql/discussions/3479

<div type='discussions-op-text'>

<sup>Originally posted by **nsenoge63** June 13, 2023</sup>
Hi, I'm trying to migrate my version of the livb from 3.18.3 to 3.19.0 or above. But when doing it, all of my requests gets the same answer : 

`{
  "errors": [
    {
      "message": "performance is not defined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "xlDeployApplications"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "ReferenceError: performance is not defined",
            "    at Object.xlDeployApplications (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\@neo4j\\graphql\\dist\\schema\\resolvers\\wrapper.js:39:16)",
            "    at field.resolve (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\apollo-server-core\\dist\\utils\\schemaInstrumentation.js:56:26)",
            "    at executeField (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\graphql\\execution\\execute.js:481:20)",
            "    at executeFields (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\graphql\\execution\\execute.js:413:20)",
            "    at executeOperation (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\graphql\\execution\\execute.js:344:14)",
            "    at execute (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\graphql\\execution\\execute.js:136:20)",
            "    at execute (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:205:48)",
            "    at processGraphQLRequest (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:148:34)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
            "    at async processHTTPRequest (D:\\DEVOPS\\workspace-intellij\\PROJETS_OCDA\\graphqlappli\\node_modules\\apollo-server-core\\dist\\runHttpQuery.js:220:30)"
          ]
        }
      }
    }
  ],
  "data": null
}`

Any idea what is going on ?

Thanks
</div>

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @nsenoge63. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @nsenoge63 
This seems to be caused by a call to `performance.now` that we use for some internal benchmarking, I'll remove those in the next version

I'm curious about the environment you are using, as this method should be available in Node.js >=16 and it would be useful to us to be able to replicate this problem in our tests

**Comment by nsenoge63** [comment]
> Hi @nsenoge63 This seems to be caused by a call to `performance.now` that we use for some internal benchmarking, I'll remove those in the next version
> 
> I'm curious about the environment you are using, as this method should be available in Node.js >=16 and it would be useful to us to be able to replicate this problem in our tests

Indeed, I was using Node.js 14.21.2. I've upgraded my Node.js version and it is now working. Sorry for the inconvenience
