### ISSUE TITLE
Top-level queries for interfaces

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3507]
It is currently only possible to query types, not interfaces at the top-level. I'm working around that limitation by attaching nodes to a global shared node and then querying the interface from that node. Obviously this is not a good solution.

It would be nice to support interfaces in the Query type.

As an example, if I currently have Foo and Bar implementing interface It, then I can query for 'foos' and 'bars', but not 'its'.

**Comment by darrellwarde** [comment]
This is one of the next "big things" we want to work on, but is covered by #146, so closing this as a duplicate. 🙂
