### ISSUE TITLE
Optimistic locking

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#3519]
**Is your feature request related to a problem? Please describe.**
Has any thought been given to concepts like (optimistic) locking? The problem is as follows:

A user starts working on a node. He queries the node and makes changes to it. Before saving the changes, another user starts working on the same node. This user saves his changes before the first user. Afterwards, the first user saves his changes. 

Currently, the changes made by the second user are simply lost: The last one wins.

One possibility to implement optimistic locking would be to work with versions:
The first user queries the node with version n. He can only make his update if the version is still n when writing. If the second user also queries the node with version n in the meantime and makes his change and counts up the version to n+1, the first user can no longer change the node. He would then receive an error message because the node has already been changed in the meantime.

**Describe the solution you'd like**
I have seen that this is probably supported by the Neo4j OGM: https://neo4j.com/docs/ogm-manual/current/reference/#reference:annotating-entities:version

**Comment by darrellwarde** [comment]
I'm struggling to see how the concept applies here. You don't particularly "start working" on a node in the GraphQL Library. You provide a mutation, this is translated into a single Cypher query and this is then executed against the database. During this query, database transactions and locks apply. There's no concept of "saving changes" as you talk about here, so I find myself a little confused at the request.

**Comment by AccsoSG** [comment]
Hi @darrellwarde 

Thanks for your reply. I know this feature request is very specific. I just saw that it exists with the Neo4j OGM and wondered if there is also a way to implement it with the generated GraphQL API.

I'll try to explain it again with an example in more detail:

There is a user interface for editing movies. This user interface can be used by many users at the same time.
If a user wants to change a movie, he first has to get the current data for this movie. This is done with a GraphQL query. This user now starts editing the movie. Maybe it takes him a while, let's say 2 minutes.
Meanwhile, another user fetches the data for the same movie. He is faster and has sent the mutation within 1 minute. Shortly after that, the first user is also finished and sends his mutation. The second user is now surprised that his data is gone. And the first user didn't even notice the changes of the second user. A conflict.

A simple method to minimize such conflicts is Optimistic Locking.
Here the first user would get a message like "Hey, in the meantime the dataset has updated. Please reload the data and confirm your changes".

**Comment by darrellwarde** [comment]
In my opinion, this could be a use case for Subscriptions - if the node gets updated, consume the Subscription event in the front end, and render this warning that you speak of and prompt the user to reload. To me, this is a more "web native" approach to solving this kind of problem.

I don't think optimistic locking is something we're going to implement into the library - right now my thinking is that it doesn't really fit into this kind of product.
