### ISSUE TITLE
Support non-specific relationship directions in the @relationship directive

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#353]
**Is your feature request related to a problem? Please describe.**
Currently IN and OUT are the only supported direction.

**Describe the solution you'd like**
I'd like to be able to support undirected "()-[]-()" relationships by not specifying direction.

**Describe alternatives you've considered**
There is no good alternative.

**Additional context**
Something like:
shows: [Thing] @relationship(type: "SHOWS", direction: ANY)

**Comment by darrellwarde** [comment]
Technically, a relationship in Neo4j always has a direction - it's just how you query it where the difference lies. So essentially, you want the `shows` field to return all `Thing` nodes going either in or out of the current node via the `SHOWS` directive?

And for Mutations, you would see it as acceptable to just create relationships in an arbitrary direction?

**Comment by acmeguy** [comment]
Well cypher allows you to specify or ignore a dierction when MATCHing.

I understand that the mutation demand a direction :)

For me that signals that there should be two direction parameters or something that ignors direction when MATCHING and enforces directions when adding/updating data with mutations.

In other words; For me it ideal that the @relationship directive offers the same flexibility as the Cypher code that it is masking.

**Comment by morningcloud** [comment]
Was reading #142, then saw this related issue... Cypher does support merge/mutation with undirect relationship ([related cypher manual](https://neo4j.com/docs/cypher-manual/current/clauses/merge/#merge-merge-on-an-undirected-relationship)), it also supports query with undirected relationship ([related cypher manual](https://neo4j.com/docs/cypher-manual/current/clauses/match/#match-on-bound-rel)). So I don't see why it is treated as a special use case? The current [connection translate](https://github.com/neo4j/graphql/blob/235331e55476fde14d0244663eae645971cfdb16/packages/graphql/src/translate/connection/create-connection-and-params.ts#L63) code looks sufficient to me as `-` is the default value set so the only change needed is to update the schema validation script to either have `direction` as optional or introduce another keyword `UNDIRECTED` as a direction option.
