### ISSUE TITLE
Extending the schema with `@neo4j/graphql` directives does not work with `getSubgraphSchema`

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#3537]
**Describe the bug**
Extending the schema with `@neo4j/graphql` directives does not work with `getSubgraphSchema`.

**Type definitions**
```gql
extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

type Actor {
    username: String!
    password: String!
}

type Movie {
    title: String
}

extend schema @mutation(operations: [])
```

**To Reproduce**
```js
const typeDefs = `
    extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

    type Actor {
        username: String!
        password: String!
    }

    type Movie {
        title: String
    }
    
    extend schema @mutation(operations: [])
`;

const neoSchema = new Neo4jGraphQL({ typeDefs });
const schema = await neoSchema.getSubgraphSchema();
```

**Expected behavior**
No error

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Liam-Doodson! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
