### ISSUE TITLE
OGM TS Type Generations not working on uppercase types

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#3539]
**Describe the bug**
When I want to create Typescript Types for the OGM I have the issue that the generated types have errors if the name of the GraphQL Type has more than one consecutive uppercase letter.

For my FAQ and FAQEntry types the generated OGM Model Class looks like this: 
![image](https://github.com/neo4j/graphql/assets/12431981/c4e8a970-7e77-43a6-8fc8-261267ed9c21)

Here the types like "FAQWhere" are referenced in uppercase, while the actual generated type is named "FaqWhere" in camelcase.

![image](https://github.com/neo4j/graphql/assets/12431981/488f8308-944b-4d84-93ce-7648b570b948)

**Type definitions**

```
type FAQ {
    id: ID! @id
    activated: Boolean!
    name: String!
    entries: [FAQEntry!]! @relationship(type: "FAQ_ENTRY_IN_FAQ", properties: "FaqEntryInFaq", direction: IN)

  }

  type FAQEntry {
    id: ID! @id
    title: String!
    body: String!
    inFAQs: [FAQ!]! @relationship(type: "FAQ_ENTRY_IN_FAQ", properties: "FaqEntryInFaq", direction: OUT)

  }

  interface FaqEntryInFaq @relationshipProperties {
    position: Int
}
```

**To Reproduce**

Use the provided types and generate OGM types

**Expected behavior**

The generated Types like "FaqWhere" should be generated as "FAQWhere" so that they are matching to the generated Schema.
The GraphQL API works totally fine currently and generates and works with the Types correctly. Here its also generated as uppercase "FAQWhere":
![image](https://github.com/neo4j/graphql/assets/12431981/9204e0ff-ad1b-4f08-8a90-1e6fbbbb9a01)

**System (please complete the following information):**

  "dependencies": {
    "@neo4j/graphql": "^3.21.0",
    "@neo4j/graphql-ogm": "^3.21.0",

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @eriklueth! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by eriklueth** [comment]
Hey @darrellwarde,
thank you very much for your work and the quick response. I am using the library now for quite some time and really love what you guys are doing here. This repo has actually become a place I look at every day since you are making progress so fast and I am always happy to see when you are releasing a new version.

Awesome to see that you fixed it. And bad to hear that we failed in two different ways with the naming of our types. 😅

What would be from your point of view the best way to rename such a type in a production environment with several thousands of users which can't switch their client-side schema directly? 

My plan would be to:
1. Redeploy our current backend with old types  
```
FAQ @node(labels: ["FAQ", "Faq"]){
...
}

FAQEntry @node(labels: ["FAQEntry ", "FaqElement"]){
...
}

```

2. Deploy another backend with the new Schema 
```
Faq @node(labels: ["FAQ", "Faq"]){
...
}

FaqElement @node(labels: ["FAQEntry ", "FaqElement"]){
...
}

```
3. Rename the existing Nodes in Neo4J to the new Typenames
4. Deploy a new version of our App to the Appstore with the new Schema and Backend Endpoint
5. Wait until most users are with the new version and deprecate the old backend
6. Remove the @node directives

Do you have any take on how to do it? 😊
