### ISSUE TITLE
@auth roles do not have an effect on where clauses

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3560]
@auth roles do not have an effect on where clauses.

Take this example:

```graphql
type A @auth(rules: [{ operations: [READ], roles: ["read:customer"] }])  {
  val: Boolean
}

type B {
  name: String
  a: A @relationship(type: "TO_A", direction: OUT)
}
```

It becomes impossible to read "a" on "b" which is correct. so for example:

```graphql
{
  bs {
    name
    a
  }
}
```

would fail with a Forbidden error. 

But it is possible to filter "bs" on a properties, which effectively exposes that data. Let's say I want to check if val is true or false. I can do:

```graphql
{
  bs(where: { a: { val: true }}) {
    name
  }
}
```

This should not be allowed for security reasons. It would make sense to reject any query if a "where" contains any parts that refer to objects of a type that would normally also be rejected based on an @auth READ role with a forbidden error.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by jroith** [comment]
Let me add that, given the schema, and using STARTS_WITH predicates for Strings and _LT and _GT operations and a binary search for numbers it's possible to determine all database values using a reasonable amount of queries.

So this is equivalent to not having READ authorisation at all and fixing this is critical. "allow" may be more difficult to get right but from my understanding "roles" should can be fixable by checking the where against the schema permissions and rejecting queries.

**Comment by darrellwarde** [comment]
@jroith, we're on the brink of releasing a completely redesigned authorization system, where this of course will work exactly as you would expect. 🙂

**Comment by darrellwarde** [comment]
Hey @jroith! Version 3.23.0 brings the new authorization directives. If you're willing, it would be great if you could [migrate](https://neo4j.com/docs/graphql-manual/current/guides/v4-migration/authorization/), we're keen on any feedback that anyone wants to give!

For this specific problem, the type definitions that you mentioned would be:

```gql
type JWT @jwt {
  roles: [String!]! # assuming `roles` is at the root of your JWT
}

type A @auth(filter: [{ operations: [READ], where: { jwt: { roles_INCLUDES: "read:customer" } } }])  {
  val: Boolean
}

type B {
  name: String
  a: A @relationship(type: "TO_A", direction: OUT)
}
```

I'll close this issue for now, any issues you have, please raise a new one! 🙂
