### ISSUE TITLE
OGM does not generate types when used within Schema Configuration directives.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#3591]
**Describe the bug**

OGM does not generate types when used within Schema Configuration directives.

**To Reproduce**
Schema Configuration directives break OGM-generated types.
The following code:
```typescript
 const typeDefs = `
 type User @query(aggregate: false) {
    id: ID! @id
    company: [Company!]! @relationship(type: "WORKS_AT", direction: OUT)
  }

  type Company {
    id: ID! @id
  }

`;

const ogm = new OGM({
  typeDefs,
  // @ts-ignore
  driver: {},
});
generate({
  ogm,
  noWrite: true,
});

```
raise `TypeError: Cannot read properties of undefined (reading 'split')`.
Although this does not happen when aggregation is enabled by changing the argument aggregate to `true` `@query(aggregate:true)`

**System (please complete the following information):**

* Version: [@neo4j/graphql-ogm@3.22.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
