### ISSUE TITLE
Make apoc.util.validatePredicate available on objects

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3613]
I have multiple use-cases where I want a behaviour very similar to the @authorization-validate directive but either they don't quite work because they require cypher or they do work, but it looks like I'm stretching what this directive is supposed to do (because the task is sometimes not authorization related at all).

For example it would be nice to be able to access @cypher properties as part of "allow" paths - and this doesn't work.

Ultimately, a clean approach would be to more directly expose apoc.util.validatePredicate in the same way it is used in the authorisation framework. 

```GraphQL
type MyType @validate(
        name: "MyRule1"
        operations: [UPDATE]
        cypherPredicate: "datetime() <= this.writableUntil AND this.id = '$jwt.sub'"
  )
{
  id: ID!
  name: String!
}
```

and I want this translated to:

```
WHERE apoc.util.validatePredicate(NOT(datetime() <= this.writableUntil AND this.id = $param0), 
               "@neo4j/graphql/VALIDATE/MyRule1", [0])
```

This has a lot of potential to validate all kinds of business requirements when reading and especially when writing.

I think, based on the existing infrastructure it is fairly easy to implement - at least I can often get 90% there with the existing @auth directive.

**Comment by darrellwarde** [comment]
Hey @jroith, thanks for this feature request!

This isn't exactly what we have in our vision for the library, we really want to reduce the amount of Cypher that is needed when using the library, not increase it.

One thing we have already discussed is almost a sugar syntax directive for the `@authorization`, likely `@validate` and `@filter` which map to the two arguments of the `@authorization` directive.

However, these will have the same arguments as the `@authorization` directive, minus the authorization features.

It is also very important to us to add in filtering for custom Cypher fields, which we believe will unlock the majority of features that users are asking for when requesting the kind of features which are similar to this one. 

I'm hoping we'll be able to get around to this filtering functionality after the summer.

**Comment by jroith** [comment]
Yes, this would also solve it and be even better - I was hoping to be able to filter custom cypher fields for a long time. I think both the `@validate` or `@filter` directives and supporting cypher fields within those directives as well as in where clauses would help enormously.

**Comment by darrellwarde** [comment]
We would like to add "sugar syntax" directives for the `@authorization` `validate` and `filter` functionalities, however, it's not on the roadmap.

Support for filtering by custom Cypher fields will be added to authorization when we add this for the whole library, we won't add something specific for authorization.

Closing due to lack of timeline on new directives for this.
