### ISSUE TITLE
Create option for populating a relationship

### ISSUE THREAD

**Issue by ycadaner-merkos302** [neo4j/graphql#3646]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to populate a relationship on the server's side. This is needed for created and updated scenarios. 
For example, a user creates a post, there's no way to attach a User to a CREATED_BY the Post. 

**Describe the solution you'd like**
Add the option to define a relationship declaration to apply on create or update of a node. 
Declaratively, 
When a Post gets created, I would like to add a CREATED_BY relationship to the logged in user. 

In other words, to populate a relationship by default. Perhaps it would look  like
```
createdBy: User! @relationship(type: "CREATED_POST", default: {
  uniqueness: SINGLE | UNIQUE | MULTIPLE
  [connect | connectOrCreate | create]:{
    where: { //on User node
      uuid: "$jwt.sub"
    }
}, 
onUpdate: {
 ...
}
)
```
 
**Describe alternatives you've considered**
Alternatively, it's possible to use something like the populatedBy (which can also be used for updatedBy and more versatile)
```
createdBy: User! @populatedByCypher("MATCH (u: User{uuid: $jwt.sub}})
 MERGE (this)-[:CREATED_BY]-(u)
")
```

**Comment by ycadaner-merkos302** [comment]
Hi,
Does anyone have any idea how I can code in custom functionality for creating a specific node, like 
`createProduct` can be overriden without breaking the graphql chain of returns and additional functionality provided?

**Comment by helenesanche** [comment]
Hi @ycadaner-merkos302 thank you for raising this feature request. If I understand correctly, you'd like the library to automatically create relationships on the server side. 

I believe this is important for data integrity as currently we are shifting the responsibility of this to the users of the API, plus they have to repeat themselves when the library could do some of this work for you. 

There are 2 "somewhat" workarounds that will enable you to enforce a relationship:
1. Use the ! non nullable operator, available [here](https://neo4j.com/docs/graphql/current/type-definitions/types/relationships/#_cardinality)
2. Use the new @authorization directive, available [here](https://neo4j.com/docs/graphql/current/authentication-and-authorization/authorization/)

There is a [merged PR](https://github.com/neo4j/graphql/pull/813) that provides you with a way to enforce the relationship, however we still don't have a way to automatically do this for you. 

I really appreciate your input with this feature request, we will discuss it and come up with a plan.

**Comment by darrellwarde** [comment]
If we do this, it will be covered by #2265.
