### ISSUE TITLE
OGM Model.update and Model.delete should require at least one where parameter or generate a warning

### ISSUE THREAD

**Issue by k-amin07** [neo4j/graphql#3685]
**Is your feature request related to a problem? Please describe.**
During development and testing phase of our application, a where parameter for an update call was accidentally set to empty ({}). It was being built dynamically based on certain conditions which resulted in an empty object when no condition matched in a fringe case. It was discovered early and was not disastrous but can potentially become disastrous. OGM matches all nodes in that case, likewise, if where parameter is set to something like {id: null} when id is non-nullable, it would not update any node, which is fine, but this should generate a warning.

**Describe the solution you'd like**
 updateAll and deleteAll should either be separate operations or regular update and delete should require at least one where parameter or warn if there is no where parameter. Likewise OGM should warn if a non-nullable field is queried against null.

**Describe alternatives you've considered**
Better checks in the code.

Currently using @neo4j/graphql 3.17.1, @neo4j/graphql-ogm 3.17.1

I understand that all of these are human errors, but someone trying out neo4j, graphql and ogm for the first time could benefit from such warnings.

**Comment by darrellwarde** [comment]
The OGM is a bit of a "power tool", so we won't add a feature like this to avoid human error.
