### ISSUE TITLE
Error when using the subscription plugin in combination with interfaces and customResolver directive

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#3698]
Follow-up ticket for https://github.com/neo4j/graphql/issues/3439

**Describe the bug**
The application does not start with activated subscription plugin, when using customResolver and interfaces

**Type definitions**
````graphql
interface IProduct{
  id: String!

  name: String!
  genre: Genre!
  info: String!
}

type Movie implements IProduct {
  id: String!

  name: String!
  genre: Genre! @relationship(type: "HAS_GENRE", direction: OUT)
  info: String! @customResolver(requires: ["id", "name"])
}

type Genre {
  name: String! @unique
  product: [IProduct!]! @relationship(type: "HAS_GENRE", direction: IN)
}
````

**To Reproduce**

1. Run a server with the following code...
````typescript
const resolvers = {
  Movie: {
    info: ({id, name}, args, context, info) => {
      return `${id}, ${name}`
    }
  }
}
````
2. See error
````
Error: Interface field IProductEventPayload.info expected but MovieEventPayload does not provide it.
````

**System (please complete the following information):**

* Version: @neo4j/graphql@3.24.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment]
Hi @AccsoSG 
As custom resolvers are not supported by the subscription types, these are removed from the resulting type. 

In this case, I think that if you add the ` @customResolver(requires: ["id", "name"])` to the interface itself as well, it won't throw the error, as that type will be removed from the subscription interface type as well (`IProductEventPayload`)

This doesn't solve the underlying problem, but it may be a workaround in your case

**Comment by angrykoala** [comment]
Hi @AccsoSG 
Yeah, I could imagine that would be the case, good to know that it is not blocking you at the moment

**Comment by a-alle** [comment]
Closing this as it is no longer happening. Added tests to prevent it happening again in #4979
