### ISSUE TITLE
@customResolver(requires: ["firstName", "lastName"]) does not work

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#3711]
**Describe the bug**
In the documentation for the 4.0.0 Migration you have:

> @computed renamed to @customResolver
> Previously, there was ambiguity over the behaviour of @computed and it wasn’t clear that it was intended to be used with a custom resolver. In order to make this clear, @computed has been renamed to @customResolver. Furthermore, the behaviour of the from argument was not clear. The argument is used to specify which fields other fields are required by the custom resolver. As a result, from has been renamed to requires.
> 
> These changes mean that the following type definition is invalid in version 4.0.0:
> 
> type User {
>   firstName: String!
>   lastName: String!
>   fullName: String! @computed(from: ["firstName", "lastName"])
> }
> Instead, it would need to be updated to use the new directive and argument as below:
> 
> type User {
>   firstName: String!
>   lastName: String!
>   fullName: String! @customResolver(requires: ["firstName", "lastName"])
> }
> 

but @computed(from: ["firstName", "lastName"]) does not work currently because

![image](https://github.com/neo4j/graphql/assets/12431981/9c32e671-35f2-4d3b-86a8-f1da1681454c)

here the requires type is just a single string. 

Does writing a multiline string like that with multiple parameters work for the selectionSet?

```
      @customResolver(
        requires: """
        id
        email
        realName
        """
        # [ "id", "email", "realName"]
      )
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by tbwiss** [comment]
Hi @eriklueth, thanks for reaching out!
If you're using the `beta` release of the `@neo4j/graphql` library, [4.0.0-beta.0](https://www.npmjs.com/package/@neo4j/graphql?activeTab=versions), then please refer to this (intermediate) [documentation of the customResolver directive](https://neo4j-graphql-docs-2773.surge.sh/graphql-manual/4.0/custom-resolvers/). You'll see that the `requires` argument indeed expects a string and you'll see how you can provide the selection set.

**Comment by eriklueth** [comment]
Hey @tbwiss,
thanks for the answer. Seems like it's working now with the selection set. Yes, I am trying to switch to the beta right now.
Awesome that you guys released it to beta finally. 🔥
