### ISSUE TITLE
OGM TS Type Generations not working on uppercase types on 4.0.0 Beta

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#3723]
**Describe the bug**
In the new 4.0.0 Beta the type generation for uppercase typenames seems to be broken again.
Its the same Issue as in #3539 and was fixed by @darrellwarde in #3556 .

Seems like there are some new node.name instead of normalizedNodeName in the code.

![image](https://github.com/neo4j/graphql/assets/12431981/030f781f-87af-46db-9f77-c8ce7655319d)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @eriklueth! :pray: We will now prioritise the bug and address it appropriately.
