### ISSUE TITLE
Relationship count and sorting by this count

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/graphql#374]
**Is your feature request related to a problem? Please describe.**
It would be great to have an ability to query count of specific relationship type and sort by this count using standard syntax

**Describe the solution you'd like**
`(:Post) <-[:LIKE]- ()`
`query Posts{
  posts(options: {
    sort: [{
      LIKE_count: DESC
    }]
  }) {
    id
    LIKE_count
  }
}`

**Describe alternatives you've considered**
Currently relationship's count can be done using @cypher directive, but sorting is hard to be done, it is not compartable with standard syntax.

**Comment by Kubera2017** [comment]
It was possible in previous package, because it arguemented @cypher fields too https://github.com/neo4j-graphql/neo4j-graphql-js/issues/303

**Comment by rcbevans** [comment]
@Kubera2017 did you find an acceptable way of  sorting of nodes by a deep property/edge count, such as your example of sorting posts by the number of likes.

I tried generating @cypher backed virtual fields, but the GraphQL library isn't generating order by augmentations for those properties.

**Comment by Kubera2017** [comment]
@rcbevans no, with current state of the library it is impossible. This can be done only by keeping that counts precomputed as node properties

**Comment by rcbevans** [comment]
Ok. Denormalization is what I was looking at having to do but it's not good enough given the dynamic nature of the data.

I'm looking into the code to see how easy it is to support sorting cypher fields.  I just spent half an hour hacking around and have got it working, but I don't know what other things it could possibly break...  It seems like it should be a pretty safe change, but I'd need to run the integration test suite and see.

**Comment by Kubera2017** [comment]
@rcbevans I thought about it too, but I analyzed and understood, that it will not work for all users of this library and all their graphs., and this is a controversy addition.
I know that Neo4j doesn't keep these edges counts for every node automatically like some other graph databases do, this means that the library should run count queries every time before the sorting. Also I know that Neo4j reads large number of relationships very slow (from my observations it reads it from disk using only single thread with 6-7 MB/sec). And when we come to super nodes, this becomes a serious problem and may cause misunderstanding for the library users who don't know the facts above.

**Comment by dmoree** [comment]
@Kubera2017 An implementation of @rcbevans suggestion for sorting primitive `@cypher` fields like `LIKE_count` is in #501.

**Comment by darrellwarde** [comment]
As aggregations on relationships are now supported, the missing piece of the puzzle is sorting by these, which is covered specifically in #1156. So I'm going to close this in favour of that for now.
