### ISSUE TITLE
Update Mutations Not Returning Updated Relations

### ISSUE THREAD

**Issue by smkhalsa** [neo4j/graphql#375]
Using v2.0.0-rc.1 with the following schema

```graphql
  type Objective {
    id: ID! @id
    text: String!
    children: [Objective!]! @relationship(type: "HAS_CHILD", direction: OUT)
    parents: [Objective!]! @relationship(type: "HAS_CHILD", direction: IN)
  }
```

If I use the generated update mutation to create a sub-objective for a given objective...

```graphql
mutation Mutation($updateObjectivesCreate: ObjectiveRelationInput, $updateObjectivesWhere: ObjectiveWhere) {
  updateObjectives(create: $updateObjectivesCreate, where: $updateObjectivesWhere) {
    objectives {
      id
      text
      children {
        id
        text
      }
    }
  }
}
```

... with these variables: 

```JSON
{
  "updateObjectivesWhere": {
    "id": 123,
  },
  "updateObjectivesCreate": {
    "children": [
      {
        "node": {
          "text": "My sub-objective",
        },
      },
    ],
  },
}
```

... the returned updated objective doesn't include the newly created child (or any other children for that matter).

**Comment by darrellwarde** [comment]
Morning! Just wrote up a couple of tests for this (#377) and everything seems to be working as expected. 🧐

**Comment by smkhalsa** [comment]
Oops! I just tried this again directly in GraphiQL, and it's working correctly. My apologies, my issue must be unrelated to @neo4j/graphql.

Thanks so much for the great work on v2!
