### ISSUE TITLE
Implicit AND does not work correctly inside aggregation filters.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#3765]
**Describe the bug**
Multiple filters living inside the same GraphQL input Object should be treated as if they were separated by the "AND" filter.

For instance, the following syntax:

```graphql
{
    posts(where: { content: "stuff", alternateContent: "stuff2" }) {
        content
    }
}
```
should be considered a syntax sugar of the more verbose:

```graphql
{
    posts(where: { AND: [{ content: "stuff" }, { alternateContent: "stuff2" }] }) {
        content
    }
}
```

This behavior is not consistent with the aggregation filters, where the query:
```graphql
{
    posts(
        where: {
            likesAggregate: {
                count_GT: 10
                count_LT: 20
                OR: [{ count_GT: 13, count_GTE: 99 }, { count_LT: 54 }]
            }
        }
    ) {
        content
    }
}

```
produce the following cypher:
```cypher
MATCH (this:Post)
CALL {
    WITH this
    MATCH (this)<-[this0:LIKES]-(this1:User)
    RETURN (count(this1) < $param0 AND count(this1) > $param1 AND (count(this1) > $param2 OR count(this1) >= $param3 OR count(this1) < $param4)) AS var2
}
WITH *
WHERE var2 = true
RETURN this { .content } AS this
```
when instead the alternative syntax:

```graphql
{
    posts(
        where: {
            likesAggregate: {
                count_GT: 10
                count_LT: 20
                OR: [{ AND: [{count_GT: 13}, {count_GTE: 99 }]}, { count_LT: 54 }]
            }
        }
    ) {
        content
    }
}
```
produces:

```cypher
MATCH (this:Post)
CALL {
    WITH this
    MATCH (this)<-[this0:LIKES]-(this1:User)
    RETURN (count(this1) < $param0 AND count(this1) > $param1 AND ((count(this1) > $param2 AND count(this1) >= $param3) OR count(this1) < $param4)) AS var2
}
WITH *
WHERE var2 = true
RETURN this { .content } AS this
```

Here is an attached gist with tests to showcase the difference in behavior:
https://gist.github.com/MacondoExpress/6775f244a482a42cc375c3975a072ada

**System (please complete the following information):**

* OS: [macOS]
* Version: [e.g. @neo4j/graphql@4.0.0]
* Node.js version: [18.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
