### ISSUE TITLE
External JWT token decoding and unauthenticated users

### ISSUE THREAD

**Issue by eriklueth** [neo4j/graphql#3771]
**Describe the bug**
Iam using the current beta and firebase auth for authentication. Because of that I decode the auth tokens myself and pass them into the context.

The problem is that I don't have a decoded jwt for unauthenticated users which I can pass into the context.
If I leave it void and pass nothing for jwt, I get a "undefined Claims" error.
On the other hand, if I pass {} everything works but I see that isAuthenticated is true.

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

```
// Express call to decode token
app.use(
    "/graphql",
    cors<cors.CorsRequest>(),
    json(),
    expressMiddleware(server, {
      context: async ({ req }) => await graphql.getContextFromRequest(req),
    })
  );

// Add jwt to context
//decodedJWT() returns Promise<DecodedIdToken | void>
export const getContextFromRequest = async (req: express.Request) =>
  await decodedJWT(req.headers.authorization || "").then(
    async (decodedJWT) => 
      ({
        req,
        jwt: decodedJWT ?? {}, // Leads to isAuthenticated = true but it should be false
        //jwt: decodedJWT, This leads to "Cannot read properties of undefined (reading 'claims')," if decodedJWT is void
        authHeader: req.headers.authorization,
        flavorConfig: flavorConfig(parseAPPFlavorHeader(req.rawHeaders)),
      } as Context)
  );
```

**Expected behavior**
When passing just {} as jwt the isAuthenticated should be false.
When passing no jwt at all, so it is undefined or void, there should not be an error thrown and it should be handled as unauthenticated.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @eriklueth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Thanks for this @eriklueth, I'll take a look next week!

**Comment by eriklueth** [comment]
Have a great weekend. ☀️

**Comment by darrellwarde** [comment]
Hey @minh160302, of course, that would be very welcome!

Give me a shout if you need any guidance at all.

**Comment by minh160302** [comment]
Hi @darrellwarde , my PR is up. The fix is straightforward, but I changed `create-bearer-token.ts`, which affects many other tests. If this approach looks good to you, I'll continue fixing the remaining tests.

**Comment by darrellwarde** [comment]
Hey @minh160302, I've just been thinking about this issue and I think it's more interesting than we think.

First off, I think your changes in `createBearerToken` look good, and I think you should continue down this path.

_However_, who are we to decide that an empty JWT could not belong to an authenticated user? According to the [JWT specification](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1), the use of every single registered JWT claim name is optional. Thus, as long as it could be verified that a JWT was signed appropriately and could be decoded, it's perfectly feasible that a JWT payload could decode to an empty object.

The biggest problem here is that the `jwt` as `undefined` seems to be throwing an error in some cases. @eriklueth, I was unable to reproduce this, could you please provide a comprehensive example of how to trigger this error?

**Comment by darrellwarde** [comment]
Feel free to reopen if you want to provide steps to reproduce.
