### ISSUE TITLE
`@authorization` evaluation for selections under a custom `@cypher` field

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3777]
Here the @authorization on the roles field is evaluated if queries on the "users" list but not if queries from an object of type A via the cypher field.

(Additionally, if the query fails on the users lists, the node server crashes, but I might open a separate ticket for that.)

```GraphQL
type User {
  id: ID! @id
  roles: [Role!]!
    @authorization(validate: [{ where: { jwt: { roles_INCLUDES: "ADMIN" } } }])
}

type A {
  test: User
    @cypher(
      statement: "MATCH (u:User { id: "47cc732a-947d-4eae-bd6b-2f504b1ac99a" }) RETURN u"
      columnName: "u"
    )
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
This one's interesting, thanks @jroith! Do you by any chance know if this used to work with the `@auth` directive?

**Comment by jroith** [comment]
> This one's interesting, thanks @jroith! Do you by any chance know if this used to work with the `@auth` directive?

I think so, but I'm not complete sure.

**Comment by darrellwarde** [comment]
Assuming that you're talking about a query such as the following (with a dummy `Role` type added):

```gql
{
    as {
        test {
            roles {
                name
            }
        }
    }
}
```

This has never been a feature - I have just tried this with `@auth` to no avail. As you may be able to tell, we're aiming for feature parity with `@auth` as a bare minimum at the moment and coming back to new features later, so this will be relabelled as a feature request for now.

**Comment by jroith** [comment]
Correct, that would be the query.

**Comment by darrellwarde** [comment]
Looking back, this is actually a duplicate of an old issue #468.
