### ISSUE TITLE
@customResolver requires is broken in version 4.

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3804]
The documentation says requires is an array, like: @customResolver(requires: ["id"])

If I do this I get an error:             throw new Error("@customResolver requires expects a string");
Error: @customResolver requires expects a string

If I instead use a string @customResolver(requires: "id")  it passes but has not effect and then the field is missing and the resolver will fail.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by jroith** [comment]
I should add that it fails because then the second property is not fetched. In other words it has to be an array. But this seems to not be allowed anymore.

**Comment by Liam-Doodson** [comment]
Hi @jroith, this sounds more like missing documentation than a bug. In 4.0 `@customResolver`, `requires` is going to accept a selection set instead of an array of fields. This allows you to make use of fields on related types as below:

```js
const typeDefs = gql`
    type Address {
        street: String!
        city: String!
    }

    type User {
        id: ID!
        firstName: String!
        lastName: String!
        address: Address @relationship(type: "LIVES_AT", direction: OUT)
        fullName: String @customResolver(requires: "firstName lastName address { city }")
    }
`;

const fullNameResolver = ({ firstName, lastName, address }) => `${firstName} ${lastName} from ${address.city}`;

const resolvers = {
    User: {
        fullName: fullNameResolver,
    },
};
```

Having said that `@customResolver(requires: "id")` should work and we have tests where similar usage is successful. Have you got some specific type defs/resolvers/queries where this fails?

**Comment by jroith** [comment]
Ah, got it! I can close and update the documentation then.
It only failed because a second field was required - and that worked with the array notation. I'll use the new notation then. Thank you.

**Comment by Liam-Doodson** [comment]
Ah okay, I'm glad that helped! The documentation is coming here: #3805
