### ISSUE TITLE
Error in schema generation when using nestedOperations

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#3816]
**Describe the bug**
There is an error in schema generation if you restrict a bidirectional relationship only on one side with nestedOperations.

**Type definitions**
````graphql
type Movie {
  name: String!
  genre: Genre! @relationship(type: "HAS_GENRE", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
}

type Genre {
  name: String!
  movies: [Movie!]! @relationship(type: "HAS_GENRE", direction: IN)
}
````

**To Reproduce**

1. Run a server with the following code...
2. See error
````
Error: Type with name "MovieDeleteInput" does not exists
````

**System (please complete the following information):**

* Version: @neo4j/graphql@3.24.1

**Additional context**
It works if you restrict nestedOperations to [CONNECT, DISCONNECT] on both sides.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
