### ISSUE TITLE
@populatedBy should work even if no fields are defined. Also "edge" should not be required in that case.

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3817]
When using @relationshipProperties (maybe also for normal nodes, I have not tested this) it is not possible to define a single field that is populatedBy.

```GraphQL
interface TestProperties @relationshipProperties {
  owns: Boolean! @populatedBy(callback: "someCallback", operations: [CREATE])
}
```

On startup the error "Input Object type TestPropertiesCreateInput must define one or more fields." is thrown. Obviously the CreateInput should not even be generated in that case.

As a workaround I have added an optional property - a very ugly hack.

```GraphQL
interface TestProperties @relationshipProperties {
  foo: String # ignore
  owns: Boolean! @populatedBy(callback: "someCallback", operations: [CREATE])
}
```

Additionally now it is necessary to provide an "edge" in the mutation. This should not be the case if all properties are generated using callback.
```Graphql
mutation Test {
  updateBlah(
    update: {test: {create: {edge: {
      foo: "bar"
    } node: {TestNode: {label: "TestLP"}}}}}
  ) {
    deviceTemplates {
      id
    }
  }
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @jroith! :pray: We will now prioritise the bug and address it appropriately.

**Comment by jroith** [comment]
I see that this bug is currently marked as low priority. Unfortunately this is a really important feature for us, let me explain our use case:

We have a schema where we later need to perform a computation on all nodes, following certain edges along the graph and not others. Because we follow along the graph and because the edge names may have various different names we cannot safely and efficiently just use edge labels. This computation happens in cypher and the pattern looks kind of like:

`MATCH (a:A)-[* {marker: true}]-(b:B) RETURN b`

In order to be able to do this, we need the marker on those edges and the only way to do this automatically on edges using the GraphQL library without forcing the user to write complicated mutations in all cases is to use @populatedBy.

Unfortunately this bug currently prevent this.

**Comment by a-alle** [comment]
Hi @jroith, I tried reproducing this bug and it seems to have been fixed during a refactor of the schema generation logic that we underwent some weeks ago. 
Could you please update to the latest version of the library and try it again? 
If you still get an error please do come back with your type definitions so we can address it!
