### ISSUE TITLE
Ability to filter types based on the interfaces they implement

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3832]
I have previously asked about the option to filter on interfaces and it was previously rejected. However with the newer @query, @mutation, @settable, etc. directive it seems natural to make it possible to opt-in specific interfaces.

Like this:

```graphql
interface Foo @filterable {
  bar: String!
}
```

In particular:

```graphql
type Test @query {
  foos: Foo
}

...

{
tests(where: { _on: { Foo: {} }}) {
  bar
}
}

```

**Comment by darrellwarde** [comment]
Hi @jroith, could you possibly elaborate on what you're after here? Because if you have the following type definitions:

```gql
interface Foo {
  bar: String!
}

type Test @query {
  foos: Foo @relationship(type: "FOO", direction: OUT)
}
```

It's absolutely possible to filter on `foo` as you've requested:

```gql
query {
  tests {
    foos(where: { bar: "bar" }) {
      bar
    }
  }
}
```

**Comment by jroith** [comment]
@darrellwarde You're right, I gave a bad example. I have a hierarchy of interfaces / implement multiple interfaces.

```GraphQL
interface Foo @query {
  bar: String!
}

type Attachment {
  test: String!
}

interface WithAttachment {
  attachments: [Attachment!]!
}

type ActualType implements Foo, WithAttachment  {
  foos: Foo @relationship(type: "FOO", direction: OUT)
  attachments: [Attachment!]!
}

type AnotherType implements Foo, WithAttachment  {
  foos: Foo @relationship(type: "FOO", direction: OUT)
  attachments: [Attachment!]!
}

type Test {
  foos: Foo @relationship(type: "FOO", direction: OUT)
}
```

And they query is more like:

```GraphQL
query {
  tests {
    foos(where: { _on: { WithAttachments: {}}}) {
      bar
    }
  }
}
```

In short I very frequently select from a collection where some objects may implement another interface (WithAttachments) or not. I want to be able to select all types implementing that interface. It's arguably a common case and I currently end up duplicating the where-filter and ...on Fragments for all subtypes - and of course I need to know the exhaustive list of subtypes in the first place.

**Comment by darrellwarde** [comment]
I'm with you. This just isn't possible, `foos.where` is of type `FooWhere`. This is already complex by going through every type which implements the interface. To do this, we would have to go _another_ level deeper and go from those types to the other interfaces that they implement. It would lead to just a completely unwieldy schema, especially in cases where the implementing types implement a wide variety of other interfaces - the types would just be crazy. I'll leave this open as a reference when we look at interfaces soon, but I just can't see this being a feature we end up supporting.

**Comment by darrellwarde** [comment]
After much design and implementation, the filtering for interface in the upcoming 5.0.0 is where we're going to leave interface filtering. This isn't covered under that. Sorry!
