### ISSUE TITLE
Change example for assigning token to case insensitive compatible code

### ISSUE THREAD

**Issue by magnusart** [neo4j/graphql#3848]
**Describe the bug**
When migrating to neo4j/graphql 4.0.0 the documentation tells me to change from 
```typescript
context: async ({ req }) => ({ req }),
``` 
to 
```typescript
context: async ({ req }) => ({ token: req.headers.Authorization }),
``` 

The issue I ran into was that headers which are supposed case insensitive become case sensitive when added to a js object. Further more, express takes headers and convert them to lower case names when adding to the request object. I figured it out after a some debugging with breakpoints in the neo4j/graphql library code.

To save time for new users, change the example to the get method on the request object which accepts case insensitive HTTP header names. That may save some time for the next guy and is more robust.
```
context: async ({ req }) => ({ token: req.get("Authorization") }),
```

Link to migration docs: https://neo4j.com/docs/graphql-manual/current/guides/v4-migration/authorization/#_server

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @magnusart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @magnusart this is now updated, thank you for letting us know!
