### ISSUE TITLE
Labels incorrectly ORed together on connects.

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3853]
I have a query of the form "{connect: {where: {node: { ... barConnection:{node:{id: ... }}}}}}" that i cannot provide for various reasons and it's currently too much work to clean it.

In any case, it seems like all labels of all types are ORed together in the WHERE (the part of the cypher query ending with ")) | 1] WHERE true))".

This seems to be incorrect if there is more than one label per type. It should probably be an OR of ANDs, combining all the labels of each type.

(In any case the query is mind-boggling large and runs for 15 seconds with an essentially empty database. A first steps would be to support #3814 to at least make the query readable since it filters on many unnecessary labels.)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by jroith** [comment]
Okay, I will try to recreate an anonymised version of the schema in the next days and provide the actual output.

**Comment by mjfwebb** [comment]
Hi @jroith have you had a chance to look at this yet?

**Comment by jroith** [comment]
Not yet, but I will look at it when I'm back in about two weeks.
