### ISSUE TITLE
Support redis for subscriptions

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3856]
This is a popular option with GraphQL yoga so it would be nice if it would be officially supported. It's certainly easier to run redis then a typical message broker and more importantly it is available, as a managed service, pretty much everywhere.

**Comment by angrykoala** [comment]
Hi @jroith 
We don't support Redis out of the box at the moment, however, you can write a custom Subscription Engine to support it. 

In fact, you can see an example of a custom engine with Redis in our [docs](https://neo4j.com/docs/graphql-manual/4.0/subscriptions/engines/#custom-subscription)

**Comment by jroith** [comment]
Perfect, thank you.
