### ISSUE TITLE
Allow to trigger a callback function after executing a custom cypher

### ISSUE THREAD

**Issue by pjaydev** [neo4j/graphql#3866]
**Is your feature request related to a problem? Please describe.**
In my schema I defined a mutation, which executes a custom cypher statement defined via `@cypher` directive and then returns a node, which has some attributes and relations to other nodes. In my use case, would like to trigger the sending of an e-mail via JS after the cypher was executed, which should contain information obtained from the node returned from the executed cypher and its related nodes.

**Describe the solution you'd like**
Perfect would be a third argument `callback` for the `@cypher` directive, which contains the name of a definable callback function, which gets called after the cypher was executed and receives an object with the result as an argument.

**Describe alternatives you've considered**
The alternative is to implement a custom resolver, which executes cypher statement on the driver and then generates and returns the proper result object. But generating the result in a way that it contains all the attributes of the related nodes depending on the passed selection subset is not trivial and requires some dirty nested OGM evaluations (e.g. as in the workaround described [here](https://github.com/neo4j/graphql/issues/227#issuecomment-852819253)). Also the easy access to the `cypherParams` or `auth` objects from within the cypher statement is not available with this solution.

**Additional context**
Being able to receive all the information from nodes and related nodes returned by a custom cypher query is a really useful feature, which I use a lot, and I can imagine many use cases where it would make sense to be able to trigger some JS code executions for further processing or triggering of other actions. It is already possible for non custom cypher mutations using the `@populatedBy` directive, so maybe the effort to add this functionality for custom cypher might not be too high.

If this is already possible and I'm just missing the right approach, I apologize in advance and would appreciate any advice.

**Comment by darrellwarde** [comment]
This would just add so much complexity to the `@cypher` directive, which we don't have appetite for.
