### ISSUE TITLE
Urgent !! Apollo Server 4 supports graphql v16.6.0 and later, while the package @neo4j/graphql requires graphql@^15.0.0. 

### ISSUE THREAD

**Issue by simpyparveen** [neo4j/graphql#3868]
**Is your feature request related to a problem? Please describe.**
Apollo Server 4 supports graphql v16.6.0 and later, while the package @neo4j/graphql requires graphql@^15.0.0. Incompatible versions is making migration to new ApolloServer ver4 impossible. 
Apollo Server 3 (that can work with graphql@^15.0.0), will be deprected and reaches EOL in October 2023, hence cannot be used any longer in a month. Hence this is urgent requirement.

**Describe the solution you'd like**
I would like package @neo4j/graphql to supports graphql v16.6.0 and later.

**Describe alternatives you've considered**
There no alternative, other than completely going to may be Envelope rather than ApolloServer ad this will take months for current codebase and microservices.

I am using :
"@neo4j/graphql": "^2.3.0"
"graphql": "^16.8.0"

**Comment by darrellwarde** [comment]
Hey @simpyparveen, please update to the latest version 3 of our library (version 4.0.0 is also being released today), which supports GraphQL 16. Thanks!
