### ISSUE TITLE
Custom scalars falsly expect arrays as return types when using the @cypher directive

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#387]
**Describe the bug**
I have a custom scalar (URLResolver from the graphql-scalars package) and I can not use it correctly @cypher statements.

**Type definitions**
type Place {
    url_works: String @cypher(statement: """ return '' + '' """)
    url_fails: URL @cypher(statement: """ return '' + '' """)
}

**To Reproduce**

1. Create a type defenition using custom Scalars
2. Create a type class using a @chypher directive for that that value
3. Run ant query that populates the value
4. See the error

**Expected behavior**
Values returned correctly.

**Error message**
<pre>
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Statement.TypeError",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: Invalid input for function 'head()': Expected String(\"\") to be a list",
            ": ",
            "    at captureStacktrace (C:\\Development\\quick-lookup\\ne-registry-api\\api\\node_modules\\neo4j-driver-core\\lib\\result.js:239:17)",
</per>

**System (please complete the following information):**

-   OS: Windows/Linux
-   Version: @neo4j/graphql@2.0.0 rc1
-   Node.js version: 14.16.0

**Comment by darrellwarde** [comment]
Thanks for the example @acmeguy, we'll look into it!

**Comment by darrellwarde** [comment]
Fixed in #390. 🙂
