### ISSUE TITLE
Call synchronous callbacks when triggering events

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3876]
It would be nice to be able to process events using a registered callback inside the server. Obviously it would be possible to subscribe using GraphQL, but it would be better to have a blocking call so that the running transaction can still be rolled back by the callback.

There is no performance impact since the callbacks are called locally and it can be made clear that they are blocking.

Since there are basically 3 or 4 points where the existing events are triggered this should be easy to support.

**Comment by darrellwarde** [comment]
We encourage the use of GraphQL subscriptions for these use cases.
