### ISSUE TITLE
Missing authorization rule for ensuring/enforcing a specific connection on node creation

### ISSUE THREAD

**Issue by mathix420** [neo4j/graphql#3901]
Following recent fix https://github.com/neo4j/graphql/pull/3890

> As `@authorization(filter)` can't impact node creations, we need to use `@authorization(validate)`, and I just realized the same issue occurred.

**Describe the bug**
Unable to ensure/enforce that a specific rule is valid on a connected node while creating the parent node, or in the example below unable to ensure that the post is being created by the logged-in user.

**Type definitions**
```graphql
type User {
    id: ID!
}

type Post @authorization(validate: [
    {
        operations: [CREATE]
        where: { node: { author: { id: "$jwt.sub" } } }
    }
]) {
    title: String!
    content: String!
    author: User! @relationship(type: "AUTHORED", direction: IN)
}
```

**To Reproduce**

Step 1, create user.
```graphql
mutation {
    createUsers(input: [{ id: "michel" }]) { users { id } }
}
```

Step 2, create post linked to previously created user => fail.
```graphql
mutation {
    createPosts(input: [{
        title: "Test1",
        content: "Test1",
        author: { connect: { where: { node: { id: "michel" } } } }
    }]) {
        posts { title }
    }
}
```
I got a `Neo4jGraphQLForbiddenError: Forbidden` where I should get the freshly created node.

**Expected behavior**
The post should be created successfully as all conditions are respected.

**System (please complete the following information):**

* OS: ArchLinux
* Version: "@neo4j/graphql": "4.1.1"
* Node.js version: v18.16.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by v-makh** [comment]
I've faced a similar issue as well and had been getting around by changing the check to `AFTER`. Something like `{ operations: [CREATE], when: [AFTER], where: { node: { author: { id: "$jwt.sub" }}}},`. Shouldn't this be the default behavior for `CREATE`?

**Comment by mathix420** [comment]
Oh okay, I wasn't even aware of the `when` parameter, will try this, thanks !

**Comment by darrellwarde** [comment]
Hey @v-makh, you're pretty much on the right track - `BEFORE` and `CREATE` are essentially a no-op. It's still perfectly valid to have `CREATE` without specifying `when` (we will only check `AFTER`), but perhaps there is a bug related to this which needs investigating. I'll take a look now. 🙂

**Comment by mathix420** [comment]
Sadly the `when` parameter only fixed half of the issue. Also I can't find any reference of this parameter in the docs, I believe it's an oversight.

Maybe it's due to my particular use case:

**Typedefs:**
```graphql
type User {
  id: ID! @id
  series: [Serie!]! @relationship(type: "PUBLISHER", direction: OUT)
}

type Serie @authorization(validate: [{
    operations: [CREATE]
    when: [AFTER]
    where: {
        AND: [
            { node: { publisher: { id: "$jwt.sub" } } }
            { jwt: { roles_INCLUDES: "verified" } }
            { jwt: { roles_INCLUDES: "creator" } }
        ]
    }
}]) {
    id: ID! @id
    title: String!

    seasons: [Season!]! @relationship(type: "SEASON_OF", direction: IN)
    publisher: User! @relationship(type: "PUBLISHER", direction: IN)
}

type Season @authorization(validate: [{
    operations: [CREATE]
    when: [AFTER]
    where: {
        AND: [
            { node: { serie: { publisher: { id: "$jwt.sub" } } } }
            { jwt: { roles_INCLUDES: "verified" } }
            { jwt: { roles_INCLUDES: "creator" } }
        ]
    }
}]) {
    id: ID! @id
    number: Int!
    serie: Serie! @relationship(type: "SEASON_OF", direction: OUT)
}    
```

**Mutation:**
```graphql
mutation createSerie($title: String!, $userId: ID!) {
  createSeries(input: [{
    title: $title
    publisher: { connect: { where: { node: { id: $userId } } } }
    seasons: { create: { node: { number: 1 } } }
  }]) {
    series {
      id
      title
    }
  }
}
```

And I get `Neo4jGraphQLForbiddenError: Forbidden` though I'm connected with the same account passed through `$userId`.

The `when` parameter helped me solve the first issue (at `Serie` level).
Now, the issue seems to be at `Season` level, as when removed the query executes successfully.

**Comment by mathix420** [comment]
@darrellwarde I believe the context I just added will help you a lot, as I'm not sure my original example did in fact include my issue!

**Comment by darrellwarde** [comment]
Thanks @mathix420, I'm taking a look now. And thank you for giving 4.x a shot - there's always a bit of a bit of a teething period for big new features like these, so this feedback is invaluable. 🙂

**Comment by mathix420** [comment]
Thanks you for your work, I was doing multiple big migrations on my project API and liked what you did so far with 4.x so I thought I'd give it a try!
This lib is a game changer for me so far, can't wait to see the future improvements.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mathix420! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
I understand the issue - I would like to discuss with the team the approach we take here, because I don't think this is going to be a small change to fix!

**Comment by mathix420** [comment]
Sure, np!

**Comment by mathix420** [comment]
Working fine now, thanks for the fix @darrellwarde!
