### ISSUE TITLE
Lists of lists not supported

### ISSUE THREAD

**Issue by nielsjansendk** [neo4j/graphql#3905]
**Describe the bug**
I have a cypher query that returns a List of lists. When I try to upgrade from version 3.x to 4.0, I get the following error:

```
Failed to get GraphQL schema: [
  GraphQLError: Invalid field type: Lists of lists are not supported.
      at createGraphQLError (/Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/schema/validation/custom-rules/utils/document-validation-error.js:36:12)
      at Object.FieldDefinition (/Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/schema/validation/custom-rules/valid-types/valid-field-types.js:49:88)
      at Object.enter (/Users/jansen/javascript/graphbiq-api/node_modules/graphql/language/visitor.js:301:32)
      at visit (/Users/jansen/javascript/graphbiq-api/node_modules/graphql/language/visitor.js:197:21)
      at validateSDL (/Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/schema/validation/validate-sdl.js:32:25)
      at runValidationRulesOnFilteredDocument (/Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/schema/validation/validate-document.js:177:51)
      at validateDocument (/Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/schema/validation/validate-document.js:219:5)
      at /Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:267:51
      at new Promise (<anonymous>)
      at Neo4jGraphQL.generateExecutableSchema (/Users/jansen/javascript/graphbiq-api/node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js:263:16) {
    path: [ 'pathList', 'paths' ],
    locations: [ [Object] ],
    extensions: [Object: null prototype] {}
  }
]
```

**Type definitions**
```type Entity  @mutation(operations: [])  {
    paths: pathList!
               @cypher(
                       statement: """
                       WITH [[{entity_id:1, other_entity_id: 2}],[{entity_id: 2, other_entity_id:3},{entity_id:3, other_entity_id: 4}]] as paths
                       RETURN {paths: paths} as result
                       """, columnName: "result"
                   )
}
type pathList @query(read: false, aggregate: false) @mutation(operations: []) @subscription(events: []) {
    paths: [[pathLink]]
}
type pathLink @query(read: false, aggregate: false) @mutation(operations: []) @subscription(events: []){
  entity_id: Int
  other_entity_id: Int
}
```

**To Reproduce**
1. Put the type definitions in a schema, create an index file as in  the 'getting started' example and try 'node index.js'

**Expected behavior**
I am expecting the schema to be able to handle query that returns a list of lists. Version 3.x was able to, no problem, so this is a breaking change, but is has not been documented in the migration guide.

**System (please complete the following information):**

* OS: MacOS 13.4.1
* Version: @neo4j/graphql@4.1.1
* Node.js version: v20.5.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @nielsjansendk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @nielsjansendk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @nielsjansendk! :pray: We will now prioritise the bug and address it appropriately.

**Comment by mathix420** [comment]
If that can help I had a similar issue, as a workaround I've created a new scalar for my use case which was a list of list of two integers: `[[1, 2], [2, 3], [9, 10]]`

```typescript
import { Kind } from "graphql/language/kinds";
import { GraphQLScalarType } from "graphql/type/definition";
import { UserInputError } from "~/graphql/errors";

export const twoIntScalar = new GraphQLScalarType({
    name: "TwoInt",
    description: "Two Integers inside an Array",
    serialize(value: string) {
        return value.split(":").map((x) => parseInt(x));
    },
    parseValue(value: unknown[]) {
        return value.join(":");
    },
    parseLiteral(ast) {
        if (ast.kind === Kind.LIST) {
            if (ast.values.length !== 2) throw new UserInputError("Need two integers");
            return ast.values
                .map((x) => {
                    if (x.kind === Kind.INT) return x.value;
                    throw new UserInputError("Only integers are allowed");
                })
                .join(":");
        }
        throw new UserInputError("Should be a list");
    },
});
```

You might need to adapt it to your use case, but basically I'm serializing the values into a string which Neo4J can then store.

Usage example:

```graphql
interface IsCaregorizedAs @relationshipProperties {
    timecodes: [TwoInt!]!
}
```

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by nielsjansendk** [comment]
@darrellwarde I am still getting a validation error from this: https://github.com/neo4j/graphql/blob/34715e332c737138c5c2f735a34de081afa1fc7a/packages/graphql/src/schema-model/attribute/AttributeType.ts#L99

I am also getting the new warning, but AttributeType still throws a validation error.

**Comment by darrellwarde** [comment]
Apologies @nielsjansendk, taking another look!
