### ISSUE TITLE
Filters on interfaces do not work as expected

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#3923]
**Describe the bug**
When filtering on different concrete types of an interface, only the first filter is taken into account

**Type definitions**

```graphql
            interface Production {
                id: ID
                title: String
            }

            type Movie implements Production {
                id: ID
                title: String
                actorCount: Int
                genres: [Genre!]! @relationship(type: "HAS_GENRE", direction: OUT)
            }

            type Series implements Production {
                id: ID
                title: String
                tagline: String
            }

            type Genre {
                name: String
                movies: [Production!]! @relationship(type: "HAS_GENRE", direction: IN)
            }
```

**To Reproduce**

The following query:
```graphql
            query Genres {
                genres(
                    where: {
                        moviesConnection_ALL: {
                            node: { _on: { Movie: { title: "Matrix" }, Series: { tagline: "Mr.Anderson" } } }
                        }
                    }
                ) {
                    name
                }
            }
```

Generates the following cypher:

```cypher
MATCH (this:Genre)
            WHERE (EXISTS {
                MATCH (this)<-[this0:HAS_GENRE]-(this1:Movie)
                WHERE this1.title = $param0
            } AND NOT (EXISTS {
                MATCH (this)<-[this0:HAS_GENRE]-(this1:Movie)
                WHERE NOT (this1.title = $param0)
            }))
            RETURN this { .name } AS this
```

Which ignores the filter `tagline: "Mr.Anderson"`

**Expected behavior**
The resulting cypher should take Series into account, for instance

**Additional observations**

This bug also with other operations like `_SOME`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
