### ISSUE TITLE
@default enum value not accepted if another enum type also contains the same value

### ISSUE THREAD

**Issue by v-makh** [neo4j/graphql#3932]
### Type definitions

```GraphQL
  enum ImageStatus {
    PENDING
    UPLOADED
  }

  type Image {
    status: ImageStatus!
      @default(value: PENDING)
  }

  enum InviteStatus {
    PENDING
    ACCEPTED
  }

  type Invite {
    status: InviteStatus!
      @default(value: PENDING)
  }
```

### Steps to reproduce

Start server.

### What happened

I get the following error upon server start.

`GraphQLError: @default.value on InviteStatus fields must be of type InviteStatus`.

If I use a different default value than `PENDING` for `Invite.status` then I don't see any errors.

### Expected behaviour

I expect the default value of `PENDING` to be valid and no errors should occur upon startup.

### Version

4.1.1

### Database version

Aura Professional 5

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Morning @v-makh, I've just tried this in our [GraphQL Toolbox](https://graphql-toolbox.neo4j.io/) and have been unable to reproduce.

**Comment by v-makh** [comment]
@darrellwarde looks like GraphQL Toolbox is currently deployed with `@neo4j/graphql@3.24.3`. I can confirm that the issue does not occur on `3.24.3` but it **_does_** occur on `4.1.1`.

**Comment by darrellwarde** [comment]
> @darrellwarde looks like GraphQL Toolbox is currently deployed with `@neo4j/graphql@3.24.3`. I can confirm that the issue does not occur on `3.24.3` but it **_does_** occur on `4.1.1`.

That is a great spot and another problem for us!!! I'll look at all of these things shortly, and helpful to know that this is a regression!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @v-makh! :pray: We will now prioritise the bug and address it appropriately.
