### ISSUE TITLE
Library fails when querying a `@cypher` field with a custom argument named "options".

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4004]
**Describe the bug**
Library fails when querying a `@cypher` field with a custom argument named `options`.

**Type definitions**
```graphql
type Episode {
     id: ID!
}

type Series {
    id: ID!
    allEpisodes(options: [Int]): [Episode!]!
        @cypher(
            statement: """
            MATCH(this)<-[:IN_SERIES]-(episode:Episode)
            RETURN episode as n
            """
            columnName: "n"
        )
}
```

**To Reproduce**

Run the following query:
```
 query {
     series {
         allEpisodes(options: [2]) {
             id
         }
     }
 }
```

When running the query above I receive the Error: `"((intermediate value) ?? []).map is not a function"`, but if I change the `allEpisodes` argument name to something else than `options`, then, the error disappears.

**System (please complete the following information):**

* OS: MacOS
* Version: [e.g. @neo4j/graphql@4.1.2]
* Node.js version: [v16.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
