### ISSUE TITLE
Node fields are not returned if the edges field is aliased.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4007]
**Describe the bug**
Node fields are not returned if the edges field is aliased.

**Type definitions**
```graphql
  type Movie {
      title: String!
      actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
  }

  type Actor {
      name: String!
      movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
  }
```

**To Reproduce**
The following query:
```graphql
{
    movies {
        actorsConnection {
            edges {
                node {
                    name
                }
            }
        }
    }
}
```
Produces the correct Cypher:
```
MATCH (this:Movie)
CALL {
    WITH this
    MATCH (this)<-[this0:ACTED_IN]-(this1:Actor)
    WITH { node: { name: this1.name } } AS edge
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    RETURN { edges: edges, totalCount: totalCount } AS var2
}
RETURN this { actorsConnection: var2 } AS this
```

But when the `edges` field is aliased, then the name field is no longer returned in the Cypher.
**GraphQL**:
```graphql
{
    movies {
        actorsConnection {
           e:edges {
                node {
                    name
                }
            }
        }
    }
}
```
**Cypher**:

```
MATCH (this:Movie)
CALL {
    WITH this
    MATCH (this)<-[this0:ACTED_IN]-(this1:Actor)
    WITH { node: { __resolveType: "Actor", __id: id(this1) } } AS edge
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    RETURN { edges: edges, totalCount: totalCount } AS var2
}
RETURN this { actorsConnection: var2 } AS this
```

**Expected behavior**
The actor's name should returned in both cases.

**Screenshots**

**System (please complete the following information):**

* OS: MacOS
* Version: [@neo4j/graphql@4.1.2]
* Node.js version: [v16.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
