### ISSUE TITLE
Selecting the node field twice with different fields, results in some fields be ignored.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4015]
**Describe the bug**
Selecting the node field twice with different fields selected, results in fields be ignored.

**Type definitions**
```graphql
  type Movie {
      title: String!
      actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
  }

  type Actor {
      name: String!
      surname: String
      movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
  }
```

**To Reproduce**
The following query:
```graphql
{
    movies {
        actorsConnection {
           edges {
                node {
                    surname
                }
                no:  node {
                    name
                }
            }
        }
    }
}
```
Produces the Cypher:
```
MATCH (this:Movie)
CALL {
    WITH this
    MATCH (this)<-[this0:ACTED_IN]-(this1:Actor)
    WITH { node: { surname: this1.surname } } AS edge
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    RETURN { edges: edges, totalCount: totalCount } AS var2
}
RETURN this { actorsConnection: var2 } AS this
```

This will result in `name` never being returned.

**Expected behavior**
Both `name` and `surname` should be returned.

**Screenshots**

**System (please complete the following information):**

* OS: MacOS
* Version: [@neo4j/graphql@4.1.2]
* Node.js version: [v16.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
