### ISSUE TITLE
Toolbox `@authorization` linting error

### ISSUE THREAD

**Issue by Liam-Doodson** [neo4j/graphql#4055]
### Type definitions

```GraphQL
type User
  @authorization(
    validate: [{ where: { node: { userId: "$jwt.id" } } }]
  ) {
  userId: String! @unique
}
```

### Steps to reproduce

Use the type definitions in the toolbox.

### What happened

A linting error for `@authorization` is shown:

<img width="569" alt="image" src="https://github.com/neo4j/graphql/assets/114480811/be39fb97-2d65-46aa-86ec-8e99e337e329">

It is still possible to build the schema.

### Expected behaviour

No linting error

### Version

4.2.0

### Database version

N/A

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Liam-Doodson. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
