### ISSUE TITLE
Strange error  when combining authorization and @populatedBy

### ISSUE THREAD

**Issue by afreakk** [neo4j/graphql#4056]
**Describe the bug**
This is  a difficult bug to reproduce, but I made a pretty minimal repository showing the bug.
Although as you see further below, I've gotten a different but similar error with another schema.

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

**To Reproduce**

1. Clone https://github.com/afreakk/n4j-issue-auth
2. `yarn install`
3. `./test.sh watch-test`
4. You should new get  the following error:
```
+             "code": "INTERNAL_SERVER_ERROR",
+             "stacktrace": Array [
+               "Neo4jError: Variable `this0_settings0_node_openingDays0_node` not defined (line 48, column 10 (offset: 2222))",
+               "\"    WITH this0_settings0_node_openingDays0_node\"",
+               "          ^",
+               ": ",
```

I have another instance with another schema.graphql where I get:
```
+           "extensions": Object {
+             "code": "INTERNAL_SERVER_ERROR",
+             "stacktrace": Array [
+               "Neo4jError: Variable `authorization_var0` already declared in outer scope (line 33, column 46 (offset: 1912))",
+               "\"    RETURN count(authorization_this1) = 1 AS authorization_var0\"",
+               "                                              ^",
```

**Expected behavior**
Shouldnt be any  errors

**System (please complete the following information):**

* OS: NixOs
* Version: @neo4j/graphql@4.2.0
* Node.js version: v18.17.1

**Additional context**
If I comment out the 
```
    updatedBy: String @populatedBy(callback: "getUserIDFromContext", operations: [CREATE, UPDATE])
```
The test passes.

Also, I  struggled reproducing this in a smaller scenario.
In the bigger codebase I get `Neo4jError: Variable `authorization_var0` already declared in outer scope` error instead, but they seem similar, both of the errors dissapear when I remove the `@populatedBy` field.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @afreakk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @afreakk! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
