### ISSUE TITLE
Issues with generated types for `@selectable(onAggregate: true)`

### ISSUE THREAD

**Issue by a-alle** [neo4j/graphql#4086]
### Description
`@relationship(aggregate: true)` not working for relationships to union types.
In the following, the `actedInAggregate` field is missing from the `Actor` type.

Test:
* file: packages/graphql/tests/schema/directives/selectable.test.ts
* test path: "relationships fields to a union type" / "Disable read on relationship field"

TypeDefs:
```graphql
union Production = Movie | Series
type Actor @query(aggregate: true) {
  name: String!
  actedIn: [Production!]!
    @relationship(type: "ACTED_IN", direction: OUT)
    @selectable(onRead: false, onAggregate: true)
}
```
Considerations:
* given that `@relationship(aggregation: true)` impacts the `Actor` type and true is the default value, there should be an `actedInAggregate` field. (* with arguments as well: where, directed)
Issues:
```graphql
type Actor {
  name: String!
# actedInAggregate field missing from here
}
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @a-alle. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @a-alle. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @a-alle! :pray: We will now prioritise the bug and address it appropriately.
