### ISSUE TITLE
Authorization validate rules are inconsistent between unwind create and normal create.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4087]
**Describe the bug**
Given the following Type Definitions:

```graphql
type User {
    id: ID
    name: String
}

extend type User {
    id: ID @authorization(validate: [{ when: BEFORE, where: { node: { id: "$jwt.sub" } } }])
}
```

and the following query:

```graphql
mutation {
    createUsers(input: [{ id: "id-1" }, { id: "id-2" }]) {
        users {
            id
        }
    }
}
```

Passing the wrong jwt.sub, the above mutation fails with the error "Forbidden", although if the subscription is enabled and therefore the query is no longer produced by the unwind create optimization, the mutation succeeds.

It also succeeds for both unwind optimization and simple create if the selection is changed to:

```graphql
mutation {
    createUsers(input: [{ id: "id-1" }, { id: "id-2" }]) {
        users {
            id
        }
    }
}
```

**Expected behavior**
The output should be the same in both cases.

**Screenshots**

**System (please complete the following information)**:

- OS: MacOS
- Version: [https://github.com/orgs/neo4j/teams/graphql@4.1.2]
- Node.js version: [v16.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
