### ISSUE TITLE
Query with nested aggregate count not working with @authorization directive

### ISSUE THREAD

**Issue by v-makh** [neo4j/graphql#4095]
### Type definitions

```GraphQL
type User {
  id: ID! @unique
}

type Family {
  id: ID! @id @unique
  members: [Person!]! @relationship(type: "MEMBER_OF", direction: IN)
  creator: User! @relationship(type: "CREATOR_OF", direction: IN)
}

type Person @authorization(filter: [{ where: { node: { creator: { id: "$jwt.uid" }}}}]) {
  id: ID! @id @unique
  creator: User! @relationship(type: "CREATOR_OF", direction: IN, nestedOperations: [CONNECT])
  family: Family! @relationship(type: "MEMBER_OF", direction: OUT)
}

extend schema @authentication
```

### Steps to reproduce

Run the following query:
```GraphQL
query Family {
  families {
    id
    membersAggregate {
      count
    }
  }
}
```

### What happened

```.json
{
  "data": {},
  "errors": [
    {
      "message": "Variable `creatorCount` not defined (line 5, column 41 (offset: 132))\n\"    WHERE ($isAuthenticated = true AND (creatorCount <> 0 AND ($jwt.uid IS NOT NULL AND this2.id = $jwt.uid)))\"\n                                         ^",
...
```

### Expected behaviour

I should be able to run this query and get the member count. If I remove the @authorization directive from `Person`, the query works. This issue is not there in `@neo4j/graphql@4.1.3`.

### Version

"@neo4j/graphql": "^4.3.1"

### Database version

Aura Professional 5

### Relevant log output

```Shell
Cypher:
MATCH (this:Family)
CALL {
    WITH this
    MATCH (this)<-[this0:MEMBER_OF]-(this1:Person)
    WHERE ($isAuthenticated = true AND (creatorCount <> 0 AND ($jwt.uid IS NOT NULL AND this2.id = $jwt.uid)))
    RETURN count(this1) AS var3
}
RETURN this { .id, membersAggregate: { count: var3 } } AS this
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @v-makh! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by angrykoala** [comment]
Hi @v-makh Thanks for reporting
This is caused by some internal changes made to cypher generation in version 4.2

The fix should be available in the next release soon

**Comment by v-makh** [comment]
Thanks for the quick fix!
