### ISSUE TITLE
Cannot filter on JWT fields using equality or NOT operations

### ISSUE THREAD

**Issue by jbhurruth** [neo4j/graphql#4099]
**Describe the bug**
When attempting to filter matched nodes using a boolean value in a JWT payload, the comparison is incorrectly determined to have no operator

**Type definitions**
```
type JWT @jwt {
    isAdmin: Boolean!
}

type User @authorization(filter: [
    { operations: [READ], where: { jwt: { isAdmin: true } } },
]) {
    id: ID @id
}
```

**To Reproduce**
Pass jwt however you want as long as it has a `isAdmin: true` claim. I've confirmed that the payload is correctly injected into the context and appears in the generated cypher.
```
query {
  users {
    id
  }
}
```
Running the query produces the error message `Failed to find operator in filter: isAdmin`

**Expected behavior**
All users should be returned

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@4.3.1
* Node.js version: 18.14.0

**Additional context**
It looks like the line referenced below causes two issues. It prevents the undefined operator being coalesced to 'EQ' in the return statement and also prevents '_NOT' operators working as they also have an undefined operator, instead using the 'isNot' property on the object returned by `parseWhereField`. Commenting out this if statement fixes things locally.

https://github.com/neo4j/graphql/blame/30705488aab3f2dd6336426ce4c6de11597a40ff/packages/graphql/src/translate/queryAST/factory/AuthFilterFactory.ts#L95

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jbhurruth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @jbhurruth! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by darrellwarde** [comment]
Thanks @jbhurruth, you were on the nose with the fix as well - PR open. 🙂
