### ISSUE TITLE
Provide a way to use the where clause in combination with @cypher properties

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#410]
**Is your feature request related to a problem? Please describe.**

Parameters can already be passed in to provide some degree of filtering power, but what would be a more powerful and consistent API is the ability to apply the `where` parameter as if properties defined using `@cypher` were ordinary relationships.

e.g. Our graph model contains `Team-HAS_GITHUB_TEAM->GithubTeam-IS_CODEOWNER_FOR->Repository`. We define a `repositories` property on `Team`, using `@cypher` to traverse the two relationship in one step.

There is a lot of metadata on Repository records, and also relationships to other things, so I would like to do something like, e.g.

```
Team {
  repositories(where: {
     isArchived: false,
     codeForSystem: {
        lifecycleStage: Decommissioned
     }
  })
}
```

This finds all a team's repositories that should be decommissioned. There are numerous other examples in our graph where combining `where` with `@cypher` would be immensely powerful.

**Describe the solution you'd like**

Intuitively this feels possible to implement in the schema augmentation via something like including a placeholder obeying a naming convention in the query used in the `@cypher` directive (similar to how `this` already has special meaning within queries used by the directive)

e.g. `@cypher(statement: "(this)-[:HAS_GITHUB_TEAM]->()-[:IS_CODEOWNER_FOR]->(r:Repository) %WHERE% RETURN r")`

Some things that I can think of that would need resolving are
- Making sure the where clause uses the correct cypher variable name (possibly naming convention?)
- Making sure the `where` argument of the property knows to expect the correct input type (perhaps the directive could take a `whereTopLevelType` argument or similar... in the example above it would be `Repository`)

Doubtless there are more difficulties that I haven't picked up on

**Comment by darrellwarde** [comment]
We can see the value of the use case here, but we don't want to add complexity to the `@cypher` directive. We have intentions to look into ways of adding support for multi-hop relationships into the library.

**Comment by wheresrhys** [comment]
That's exciting about natively supported multi-hops 👍
