### ISSUE TITLE
Using map object RETURNed from the @cypher directive fails when calling MATCH

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#411]
**Describe the bug**
The @cypher directive allows returning of map/objects:
type Some {
    image : [ImageObject] @cypher(statement: "MATCH (this)<-[rel:SHOWS]-(media) RETURN {media: media,  rel: rel}")
}
and it can be used in the returned class ('ImageObject') like this:
type ImageObject {
    usage: String @cypher(statement:"RETURN this.rel.usage")
    url: String @cypher(statement:"RETURN this.meida.url")
}

What does not work to use a return value (this.meida) as MATCH input:
type ImageObject {
    usage: String @cypher(statement:"RETURN this.rel.usage")
    url: String @cypher(statement:"RETURN this.meida.url")
    nothing_works: String @cypher(statement:"MATCH (this.meida)-[SOMETHING]-(some) RETURN some")
}

**To Reproduce**

1. Create a class including a code similar to the one suppllied
2. Try to call it to retrieve the 'nothing_works' value

**Expected behavior**
It would be good to be able to use map values as first-class-citizens in the chainged @cypher

**Screenshots**
"stacktrace": [
            "Neo4jError: Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: org.neo4j.exceptions.SyntaxException: Invalid input 'this': expected \"(\", \"allShortestPaths\" or \"shortestPath\" (line 1, column 127 (offset: 126))",
            "\"cypher runtime=slotted  WITH  $`auth` as `auth` ,  $`this` as `this` ,  $`language` as `language` ,  $`type` as `type` MATCH (this.medi)<-[r:DESCRIPTION_FOR]-(description:Description) WHERE (r.language in $language OR isEmpty($language)) AND (r.usage = $type OR isEmpty($type)) RETURN CASE collect(description.name) WHEN [] THEN [this.media.name] ELSE collect(description.name) END\"",

**System (please complete the following information):**

-   OS: Windows
-   Version: @neo4j/graphql@2.0.0
-   Node.js version: 14.16.0

**Comment by acmeguy** [comment]
I realize that there may be a right way to do this but I feel is that this would be a good flow :)

**Comment by acmeguy** [comment]
Workaround:
WITH this.media as media MATCH (media)

**Comment by acmeguy** [comment]
This should be closed and - perhaps - raised as a Cypher issue

**Comment by darrellwarde** [comment]
Hey @acmeguy, this isn't what the `MATCH` clause is for in Cypher. Your example of `MATCH (this.media)-[SOMETHING]-(some)` would never work, because anything inside the brackets must resolve to a node, whilst `this.media` is a property on a node. Trying to then traverse over a "SOMETHING" relationship is just invalid, because you cannot traverse from a property.

**Comment by acmeguy** [comment]
@darrellwarde  - This is not correct.  The map returned contains properrty with a an node in it and the workaround does work:
WITH this.media as media MATCH (media)

**Comment by darrellwarde** [comment]
@acmeguy, in the example that you gave:

```graphql
type ImageObject {
  usage: String @cypher(statement:"RETURN this.rel.usage")
  url: String @cypher(statement:"RETURN this.meida.url")
  nothing_works: String @cypher(statement:"MATCH (this.meida)-[SOMETHING]-(some) RETURN some")
}
```

`this` in the context of _all_ of those Cypher queries is the variable for the current `ImageObject` node. So `this.media` would be the `media` property on that node.

**Comment by acmeguy** [comment]
it is the inability to use that value directly that is the issue - not the value type of the property.

as in; the value works as soon as the property has been renamed to something without the "." in it.
It seems to fail a syntax rule in Cypher, rather than a value-type rule.
