### ISSUE TITLE
WITH clause before MATCH in generated Cypher

### ISSUE THREAD

**Issue by jbhurruth** [neo4j/graphql#4110]
**Describe the bug**
I'm not really sure what specifically is triggering this yet. I assume its something to do with my authorisation filter rules referencing the same type as the type they're defined for. I have a rule on a Company type which matches through two intermediate nodes on the way to a different Company to check that Users in a each have a reason to access each other's details. I'll try to add a real repro later today

I see cypher of the form 
```
CALL {
    WITH this
    MATCH (this)<-[:RELATIONSHIP]-(this0:OtherType)
    CALL {
        . . .
    }
    WITH *
    WHERE var6 = true
    RETURN count(this0) > 0 AS var7
}
MATCH (this:Company)
. . .
```
where the CALL is before the MATCH that provides the `this` variable. I can rearrange it and run manually to get the expected response

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@4.3.1
* Node.js version: 18.14.0

**Additional context**
I think this might be related to @darrellwarde's question on a recent PR which changed the order of the `matchClause` and `authFilterSubqueries` in the generated cypher
https://github.com/neo4j/graphql/pull/4084/files/97f38c337a71fe48dec281ddc0e30cd8183eead2#r1350137193

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jbhurruth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jbhurruth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
> Hey @jbhurruth, there's nothing wrong with a `WITH` before `MATCH` in a subquery - [that's how you import variables](https://neo4j.com/docs/cypher-manual/current/subqueries/call-subquery/#call-importing-variables).
> 
> Or are you trying to report something else here?

Ah, I think I see what you mean now, red herring!! 

Please provide a reproduction and we'll take a look. 🙂

**Comment by jbhurruth** [comment]
Turns out it wasn't too tricky to reproduce 😅 Here you go...

Schema:
```
type Company @authorization(filter: [
    { operations: [READ], where: { node: { inBetween: { company: { id: "example" } } } }  },
]) {
    id: ID @id
    inBetween: InBetween @relationship(type: "CONNECT_TO", direction: OUT)
}
type InBetween {
    id: ID @id
    company: Company! @relationship(type: "CONNECT_TO", direction: IN)
}
```

Query:
```
query {
  companies {
    inBetween {
      company {
        id
      }
    }
  }
}
```

Generated Cypher:
```
CALL {
    WITH this
    MATCH (this)-[:CONNECT_TO]->(this0:InBetween)
    OPTIONAL MATCH (this0)<-[:CONNECT_TO]-(this1:Company)
    WITH *, count(this1) AS companyCount
    WITH *
    WHERE (companyCount <> 0 AND this1.id = $param0)
    RETURN count(this0) = 1 AS var2
}
MATCH (this:Company)
WITH *
WHERE ($isAuthenticated = true AND var2 = true)
CALL {
    WITH this
    MATCH (this)-[this3:CONNECT_TO]->(this4:InBetween)
    CALL {
        WITH this4
        CALL {
            WITH this5
            MATCH (this5)-[:CONNECT_TO]->(this6:InBetween)
            OPTIONAL MATCH (this6)<-[:CONNECT_TO]-(this7:Company)
            WITH *, count(this7) AS companyCount
            WITH *
            WHERE (companyCount <> 0 AND this7.id = $param2)
            RETURN count(this6) = 1 AS var8
        }
        MATCH (this4)<-[this9:CONNECT_TO]-(this5:Company)
        WHERE ($isAuthenticated = true AND var8 = true)
        WITH this5 { .id } AS this5
        RETURN head(collect(this5)) AS var10
    }
    WITH this4 { company: var10 } AS this4
    RETURN head(collect(this4)) AS var11
}
RETURN this { inBetween: var11 } AS this
Params:
{
  "param0": "example",
  "isAuthenticated": true,
  "param2": "example"
}
```

Error:
```
Neo4jError: Variable `this` not defined (line 2, column 10 (offset: 16))
"    WITH this"
```

**Comment by jbhurruth** [comment]
Oh, and I've confirmed that this works in v4.1.3

**Comment by darrellwarde** [comment]
Oh dear, I'll take a look, thank you! And thank you for your patience with these recent changes. Turns out completely changing the underlying architecture for translating GraphQL to Cypher is not so simple! 😅

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @jbhurruth! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment]
Hi @jbhurruth 

This is fixed and will be available in the next release
