### ISSUE TITLE
@jwtClaim doesn't seem to add the targeted field to the roles array

### ISSUE THREAD

**Issue by dz0l038** [neo4j/graphql#4112]
# Describe the bug
It seems that `@jwtClaim` is not adding the targeted roles in the roles array, and thus `@authentication` fails to find them. I tested several different setup, but even the one in the doc is failing.

## To Reproduce
All tokens has been generated with jwt.io with the key 123456 , inclued the "admin" role, and are valid for a year.

The server: a classic apollo server with the following
```
const neoSchema = new Neo4jGraphQL({
    typeDefs,
    driver,
    features: {
      authorization: {
        key: "123456", // key used for the test to simplify token generation
      },
    }
  })
```
and lauched with
```
const { url } = await startStandaloneServer(server, {
    listen: { port: 4001 },
    context: async ({ req }) => ({
      token: req.headers.authorization,
    }),
  })
```

the typeDefs is the following:
```
const typeDefs = `#graphql
  type JWT @jwt {
    roles: [String!]!
  }

type Category @authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" } ) {
    name: String! @unique
  }

```

I ran the following tests, every time in order to list the categories, and the expected result here is that it should be ok as the admin role is defined in the jwt:
### "roles" field at the root 
```
type JWT @jwt {
    roles: [String!]!
  }
```

```
@authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" }
```

token used: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTcxMTc2NzIsImV4cCI6MTcyODY1MzgyMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsInJvbGVzIjpbImFkbWluIl19.jv9vXPuPjsTBLkBcpsQL9wG--N_C898NcHJc0ReWpmI

**Result: OK**

**Map myApplication.roles to roles with jwtClaims (from the doc)**
```
type JWT @jwt {
    roles: [String!]! @jwtClaim(path: "myApplication.roles")
  }
```

```
@authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" }
```

token used: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTcxMTc2NzIsImV4cCI6MTcyODY1MzgyMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIm15QXBwbGljYXRpb24iOnsicm9sZXMiOlsiYWRtaW4iXX19.gJsmG0M0BMYWQ9610r6vEVjYBWiAOTGEJnIro-ZhVFQ

**_Result: KO !_**

### Map roles to groups with jwtClaims
That is actually the one I really want to solve, because cognito provide a token with the field `cognito:groups` for the groups at the root. As I cannot define `cognito:groups` as a graphql field, I have to map it.
```
type JWT @jwt {
    roles: [String!]! @jwtClaim(path: "groups")
  }
```

```
@authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" }
```

token used: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTcxMTc2NzIsImV4cCI6MTcyODY1MzgyMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsImdyb3VwcyI6WyJhZG1pbiJdfQ.UcZG2NsGBbz0_xDDQcY1T4zufWEAQRpSeLPJqaKbG9U

**_Result: KO !_**

## Conclusion
I ran a lot of other tests, but basically I never managed to have @jwtClaim working as I was expected. So maybe I understand this feature wrong or I am not using it the right way.

## Versions
```
"@apollo/server": "^4.9.4",
"@neo4j/graphql": "^4.3.1",
"apollo-server": "^3.12.1",
"graphql": "^16.8.1",
"neo4j-driver": "^5.13.0"
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @dz0l038. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @dz0l038. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @dz0l038! :pray: We will now prioritise the bug and address it appropriately.

**Comment by dz0l038** [comment]
Thanks
If someone is having the same issue, here is a workaround: you can decode/verify your token, and remap it by hand in a format that match neo4j/graphql expectation (for cognito here):

```
const { url } = await startStandaloneServer(server, {
    listen: { port: 4001 },
    context: async ({ req }) => {
      if (!req.headers.authorization) return ({})
      const verifier = CognitoJwtVerifier.create({
        userPoolId: "..",
        tokenUse: "access",
        clientId: "...",
      });
      try {
        const payload = await verifier.verify(
          req.headers.authorization
        );
        const newToken = { ...payload, roles: payload["cognito:groups"] }
        const newJwt = jwt.sign(newToken, LOCAL_JWT_KEY);
        return ({
          token: newJwt,
        })
      } catch {
        console.log("Token not valid!");
        return ({})
      }
    },
  })
```

**Comment by raajnadar** [comment]
@dz0l038 thanks for the quick workaround

@darrellwarde thanks for giving an update on the priority to fix the bug
