### ISSUE TITLE
Nested aggregate query with @authorization fails

### ISSUE THREAD

**Issue by v-makh** [neo4j/graphql#4116]
### Type definitions

```GraphQL
type User {
  id: ID! @unique
  roles: [String!]!
}

type Family {
  id: ID! @id @unique
  members: [Person!]! @relationship(type: "MEMBER_OF", direction: IN)
  creator: User! @relationship(type: "CREATOR_OF", direction: IN)
}

type Person @authorization(filter: [{ where: { node: { family: { creator: { roles_INCLUDES: "plan:paid" }}}}}]) {
  id: ID! @id @unique
  creator: User! @relationship(type: "CREATOR_OF", direction: IN, nestedOperations: [CONNECT])
  family: Family! @relationship(type: "MEMBER_OF", direction: OUT)
}

type JWT @jwt {
  roles: [String!]!
}

extend schema @authentication
```

### Steps to reproduce

```graphQL
query Family {
  families {
    id
    membersAggregate {
      count
    }
  }
}
```

### What happened

```json
{
  "data": {},
  "errors": [
    {
      "message": "Variable `creatorCount` not defined (line 8, column 63 (offset: 261))\n\"    WHERE ($isAuthenticated = true AND (familyCount <> 0 AND (creatorCount <> 0 AND $param1 IN this3.roles)))\"\n                                                               ^",
...
```

### Expected behaviour

Expect the query to execute.

### Version

4.3.2

### Database version

5.12.0

### Relevant log output

```Shell
Cypher:
MATCH (this:Family)
CALL {
    WITH this
    MATCH (this)<-[this0:MEMBER_OF]-(this1:Person)
    OPTIONAL MATCH (this1)-[:MEMBER_OF]->(this2:Family)
    WITH *, count(this2) AS familyCount
    WITH *
    WHERE ($isAuthenticated = true AND (familyCount <> 0 AND (creatorCount <> 0 AND $param1 IN this3.roles)))
    RETURN count(this1) AS var4
}
RETURN this { .id, membersAggregate: { count: var4 } } AS this
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @v-makh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @v-makh! :pray: We will now prioritise the bug and address it appropriately.
