### ISSUE TITLE
Neo4jError: Invalid input 'WHERE': expected

### ISSUE THREAD

**Issue by afreakk** [neo4j/graphql#4118]
**Describe the bug**
Its not easy to describe the bug, but it seems related to `@authentication` and Ive reproduced a minimal example  it in this repository:
https://github.com/afreakk/n4j-issue-invalid-input

The error message is:
```
+               "Neo4jError: Invalid input 'WHERE': expected",
+               "  \"CALL\"",
+               "  \"CREATE\"",
+               "  \"DELETE\"",
+               "  \"DETACH\"",
+               "  \"FOREACH\"",
+               "  \"IN\"",
+               "  \"LOAD\"",
+               "  \"MATCH\"",
+               "  \"MERGE\"",
+               "  \"OPTIONAL\"",
+               "  \"REMOVE\"",
+               "  \"RETURN\"",
+               "  \"SET\"",
+               "  \"UNION\"",
+               "  \"UNWIND\"",
+               "  \"USE\"",
+               "  \"WITH\"",
+               "  \"}\" (line 39, column 2 (offset: 2178))",
+               "\"     WHERE this0_openingDays_connect0_node.id = $this0_openingDays_connect0_node_param0 AND apoc.util.validatePredicate(NOT ($isAuthenticated = true AND authorization_var0 = true), \"@neo4j/graphql/FORBIDDEN\", [0])\"",
```

**To Reproduce**

1. `git clone https://github.com/afreakk/n4j-issue-invalid-input`
2. `yarn install`
3. `./test.sh watch-test`

**Expected behavior**
This error probably shouldnt  be there.

**System (please complete the following information):**

* OS: NixOs
* Version: @neo4j/graphql@4.3.2
* Node.js version: v18.17.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @afreakk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @afreakk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @afreakk! :pray: We will now prioritise the bug and address it appropriately.
