### ISSUE TITLE
Type mismatch when generating cypher queries with a one-word attribute name

### ISSUE THREAD

**Issue by Ste90x** [neo4j/graphql#412]
**Describe the bug**
In the following case the node of type "Architecture" is related to a "Series" 
![image](https://user-images.githubusercontent.com/23119952/128918212-6e5336cf-203c-4129-acbb-d4197985d9f8.png)

When trying to get the new pagination parameters on a connection the following error occurs:
![image](https://user-images.githubusercontent.com/23119952/128918706-e6efe85f-d96e-436f-b246-d556226b1916.png)

This is only the case when I try to get the connection information on a relation with a single word as a type name.
In the following case:
![image](https://user-images.githubusercontent.com/23119952/128918985-1905e00f-7e3e-4f96-8aa2-492eaff8267b.png)
Everything works as expected with the generated query being:
![image](https://user-images.githubusercontent.com/23119952/128919105-75b89090-4c0c-47cd-9eaa-435038e863f8.png)

In the second case, the generator splits the attribute name into two different casings for the relation and for the node.
This is not the case when the attribute only has a single word in its typename.

**Type definitions**
BusinessObject:
![image](https://user-images.githubusercontent.com/23119952/128920941-189c07d0-1950-49f4-8bbb-8b7ad4217cec.png)

Series:
![image](https://user-images.githubusercontent.com/23119952/128919528-5d1bd024-1c42-4fef-9d4c-0418e897cd33.png)

BusinessDivision:
![image](https://user-images.githubusercontent.com/23119952/128919591-f9dda910-50ac-43e6-aa74-1ef5858adb4f.png)

Architecture:
![image](https://user-images.githubusercontent.com/23119952/128919627-f6587f56-f581-4c81-9470-7cc9b0c38d4d.png)

**To Reproduce**

1. Run a server with the following code...
- Standard implementation with the @neo4j/graphql 2.0 version as shown in the docs and run the debug mode
- Database version is 4.3.2 but it also happened on 4.2.5
2. Execute the following Mutation...
- No mutation or actual data needed
3. Then run the following Query...
`
query {
  series {
    name
    architectureConnection {
      pageInfo {
        hasNextPage
      }
      edges {
        node {
          name
        }
      }
    }
  }
}
`
![image](https://user-images.githubusercontent.com/23119952/128920262-f8fbf009-980b-4933-bd16-4757ea70ed12.png)

**Expected behavior**
I'd expect the same behaviour as the queries where relations with a type with multiple words are being requested. As shown in the pictures in the description.

**System:**

-   OS: [Windows]
-   Version: [@neo4j/graphql@2.0.0]
-   Node.js version: [14.16.0]

**Comment by dmoree** [comment]
It looks as if this has more to do with the names of the node and relation differing only in case. You have a node with a label `Architecture` and a relation `ARCHITECTURE`. In the translation the parameters are being assigned the same name. I could be wrong, but maybe changing the relationship to `HAS_ARCHITECTURE` would fix things.

**Comment by Ste90x** [comment]
@dmoree You are right. Thank you! 
I didn't think of that. I tried it right now and it works. 
So this error is not bound to the type name consisting of only one word but it is bound to the relation having the same name as the type. 
I don't know if it still counts as a bug though, seen as it can cause the cypher generator to generate invalid queries.

If not, please feel free to close this thread.

**Comment by dmoree** [comment]
I'm glad it works. I really don't think this is a bug. This is just a product of how this library translates graphql queries into cypher. By using the same name (albeit different case) you'll run into an error when the translation puts everything into lowercase. There isn't much the library can do, especially with something that calls for a simple workaround.

I don't have any control of closing the issue, but since I don't think it is a bug I think you should.

**Comment by darrellwarde** [comment]
Thanks for the bug report! It definitely is a bug - we thought we had caught all instances where a naming collision might happen but apparently one slipped through the net! Will take a look today. 🙂

**Comment by dmoree** [comment]
It makes sense to see this as a bug in order to remain agnostic about the naming style of any particular graph. Hopefully, at a minimum the workaround will work. @Ste90x perhaps changing the title to more accurately reflect the bug would be helpful.
