### ISSUE TITLE
Feature request: Allow sorting of relationships with union types

### ISSUE THREAD

**Issue by Mohammer5** [neo4j/graphql#414]
**Is your feature request related to a problem? Please describe.**
Thanks to the newly released version (2.0.0) we can now add properties to relationships and sort by properties on the relationships. Unfortunately this does not work when the field's type is a union of multiple types, like this:

```gql
query {
  columns {
    contentsConnection(sort: {
      edge: { position: ASC }
    }) {
      edges {
        node {
          ... on Note { id }
          ... on Card { id }
        }
      }
    }
  }
}
```

I've created a repository to reproduce both the currently working way as well as the way it does not work, the README contains more details:
https://github.com/Mohammer5/Feature-request-Union-relationship-sorting

**Describe the solution you'd like**
It would be nice to be nice to be able to sort when the field's type is a union type

**Describe alternatives you've considered**
Haven't really found an alternative way

**Additional context**
Please take a look at the repo provided above

**Comment by darrellwarde** [comment]
100% should be in, I'll note it down! 🙂
