### ISSUE TITLE
Support CONTAINS operator on numbers

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#4148]
Imagine having a filter on top of a table column. If this column is numeric, intuitively we want to be to match a sequence of digits. This is currently not possible at all. It would be nice to have a filter for this, possibly one that could be configured optionally in the neo4j schema configuration.

**Comment by jroith** [comment]
Let's say I have a field "test" of type Int! and it has the value 123 in the database.

Now I would like a filter test_CONTAINS: "2" that matches this number, because the digit is contained in there.

```graphql

interface Foo {
  test: Int!
}

foos(where: { test_CONTAINS: "2" }) {
  test
}

```

**Comment by angrykoala** [comment]
Hi @jroith 
Thanks for the example, we've been discussing this and we don't feel this operator is appropriate for numbers.

First, this operation is not supported by Neo4j (`CONTAINS` only works for numbers)

Secondly, this operation implies that the number is being treated as a string, to perform a string operation, this is not really fitting in a strongly typed language such as GraphQL, as it is an implicit conversion. 

thirdly, Even with an implicit conversion, this operation assumes base 10 on the conversion to string, making it a non-obvious behaviour in some scenarios (for instance when using HEX).

If you really need to perform an operation like this over a number in the database, consider converting it to a string with a custom resolver or using `@cypher`

**Comment by jroith** [comment]
I would love to use @cypher but it's not supported in filters.

**Comment by angrykoala** [comment]
@jroith 

I meant that you could create a custom Cypher directive, in which instead of a number, you cast it to a string, and then the operation `CONTAINS` should be available

Sorry, didn't explain myself :sweat_smile:

**Comment by jroith** [comment]
@angrykoala Oh, you mean a directive that works similar to @cypher but that I define myself? Is this possible? Or you mean I define an extra field with @cypher on it? I think so far all of the @cypher fields cannot be filtered at all, so _CONTAINS is not available there. Or has this feature been added since?

**Comment by angrykoala** [comment]
Nope, sorry, a filter on a custom cypher does not support that, my bad, you may consider a customResolver for this or updating your model to use a string instead of an int

**Comment by jroith** [comment]
Or maybe you consider supporting filtering @cypher in the future. It would solve many problems and while it is very powerful, most other systems, ORMs etc have mechanisms like that.
