### ISSUE TITLE
The `@relayId` fields cannot be aliased when queried using the Connection API.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4158]
The `@relayId` fields cannot be aliased when queried using the Connection API. 

Given the following typeDefs:
```graphql
type Movie {
    dbId: ID! @id @unique @relayId
    title: String!
    genre: Genre! @relationship(type: "HAS_GENRE", direction: OUT)
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: OUT)
}

type Genre {
    dbId: ID! @id @unique @relayId
    name: String!
}

type Actor {
    dbId: ID! @id @unique @relayId
    name: String!
}
```
And the following query:
```graphql
query {
    movies {
        testAliasID: id
        testAliasDBID: dbId
        title
        genre {
            testAliasID: id
            testAliasDBID: dbId
            name
        }
        actors {
            testAliasID: id
            testAliasDBID: dbId
            name
        }       
    }
}
```

It's possible to obtain both the `id` and `dbId` fields with their respective  GraphQL alias.

However when queried using the Connection API:
```graphql
query {
    moviesConnection {
        totalCount
        edges {
            node {
                testAliasID: id
                testAliasDBID: dbId
                title
                genre {
                    testAliasID: id
                    testAliasDBID: dbId
                    name
                }
                actors {
                    testAliasID: id
                    testAliasDBID: dbId
                    name
                }
            }
        }
    }
}
```

The following error appears: `GraphQLError: Cannot read properties of undefined (reading 'toString')`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
