### ISSUE TITLE
Incorrect Sorting when querying multiple nested nodes and some of the child nodes do not exist

### ISSUE THREAD

**Issue by pjaydev** [neo4j/graphql#4196]
### Type definitions

```GraphQL
type Foo {
    name: String
    bars: [Bar!]! @relationship(type: "relatesTo", direction: OUT)
}

type Bar {
    name: String
    foobars: [FooBar!]! @relationship(type: "relatesTo", direction: OUT)
}

type FooBar {
    name: String
    bars: [FooBar!]! @relationship(type: "relatesTo", direction: IN)
}
```

### Test data

```Shell
MERGE (:Foo {name: "A"})-[:relatesTo]->(b1:Bar {name: "bar1"})
MERGE (:Foo {name: "B"})
MERGE (:Foo {name: "C"})-[:relatesTo]->(b3:Bar {name: "bar3"})
MERGE (b1)-[:relatesTo]->(:FooBar {name: "a"})
MERGE (b3)-[:relatesTo]->(:FooBar {name: "b"})
```

### Steps to reproduce

1. Start a server using the type definitions above
2. For later comparison, first execute following query:

```graphql
query {
  foos (options: {sort: {name: ASC}}) {
    name
  }
}
```

3. You will receive the expected result - a list of nodes sorted by their names:

```json
{
  "data": {
    "foos": [
      {
        "name": "A"
      },
      {
        "name": "B"
      },
      {
        "name": "C"
      }
    ]
  }
}
```

4. Now execute a query, which  includes a double nested node in the selection subset:

```graphql
query {
  foos (options: {sort: {name: ASC}}) {
    name
    bars {
      foobars {
        name
      }
    }
  }
}
```

### What happened

You will receive the following result:

```json
{
  "data": {
    "foos": [
      {
        "name": "B",
        "bars": []
      },
      {
        "name": "A",
        "bars": [
          {
            "foobars": [
              {
                "name": "a"
              }
            ]
          }
        ]
      },
      {
        "name": "C",
        "bars": [
          {
            "foobars": [
              {
                "name": "b"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

As you see, the nodes, which do not have related nodes are listed first and the result set is no longer properly ordered by `Foo.name`. 

Changing the sorting from ASC to DESC does change the order of the nodes, which have children, but the childless nodes would still be listed first.

FYI: I also tried using a custom cypher for querying the nodes (via the `@cypher` directive) instead of the auto-generated `foos` resolver, but got the same problem. When I execute the same cypher statement in neo4j Browser, I receive the nodes in the correct order, but in Apollo Sandbox  the nodes without child nodes are **always** listed first.

### Expected behaviour

I would expected the resulting node list to be sorted by `Foo.name` as queried:

```json
{
  "data": {
    "foos": [
      {
        "name": "A",
        "bars": [
          {
            "foobars": [
              {
                "name": "a"
              }
            ]
          }
        ]
      }, 
      {
        "name": "B",
        "bars": []
      },
      {
        "name": "C",
        "bars": [
          {
            "foobars": [
              {
                "name": "b"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

### Version

tested with v3.24.1 and 4.3.4

### Database version

4.4.12 enterprise

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @pjaydev. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @pjaydev. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Confirmed bug report for DB version 4.4.12, but not an issue on 4.4.26 (latest 4.4 patch version at this time).

@pjaydev are you able to upgrade your database?

This is not an issue on DB version 5.2.0

**Comment by mjfwebb** [comment]
> @mjfwebb Thank you for your response! Interesting.
> 
> DB migration to v5 is on our roadmap, but I should be able to update to the latest patch version soon. But I definitely won't make it before next Wednesday (1.11.23). If you'd like to leave the issue open until then, I will let you know if it fixed it for us as well.

Just to clarify, from my testing, it seems that patch upgrading your DB to 4.4.26 (instead of the major migration to v5) would be sufficient.

**Comment by mjfwebb** [comment]
@pjaydev I'll close this now, but do let us know if you are still encountering this issue after upgrading your database :slightly_smiling_face:

**Comment by pjaydev** [comment]
@mjfwebb 
I decided to skip the Neo4j v4 update and today I directly migrated to Neo4j v5.13.0 on my test system. I can confirm that the issue is fixed with this setup.

Thanks a lot for your help and your good work!
