### ISSUE TITLE
Unknown function `apoc.util.validatePredicate` for nested create mutations

### ISSUE THREAD

**Issue by olivermack** [neo4j/graphql#4220]
**Describe the bug**
I'm just fiddling around with neo4j and its graphql support. While doing so I'm facing ongoing issues whenever I try to create a document which has a nested 1:1 dependency (I'm not yet very familiar with the graph/neo4j lingo).

In my setup I'm essentially just having a `Person` type and I wanted to _embed_ a map of links. For this, I've extracted the sub-document to a dedicate type `NamedLinks`.

Execution a mutation with the nested creation fails with the following error:

```json
"Unknown function 'apoc.util.validatePredicate' (line 22, column 16 (offset: 842))\n\"        \tWHERE apoc.util.validatePredicate(NOT (c <= 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDNamedLinks.person must be less than or equal to one', [0])\"\n                ^"
```

As I'm a newbie it's a bit hard to assess where the error originates - but it seems as there is an attempt to validate the creation of the nested document which fails due to a wrong function pointer.

The same happened also for other document relations which I stripped from the sample because the behavior seems identical.

**Type definitions**

```gql
type NamedLinks {
  youtube: String
  website: String
  x: String
  patreon: String
  facebook: String
  person: NamedLinks @relationship(type: "LINKS_OF", direction: OUT)
}

type Person @fulltext(indexes: [{ indexName: "PersonName", fields: ["name"] }]) {
  id: ID! @id
  name: String! @unique(constraintName: "unique_person_:name")
  nativeLanguage: String
  residentIn: String
  birthDate: DateTime
  deathDate: DateTime
  links: NamedLinks @relationship(type: "HAS_LINKS", direction: IN)
}
```

**To Reproduce**

1. Spin up some neo4j + Graphql Playground
2. Run the following mutation

```gql
mutation {
  createPeople(
    input: [
      {
        name: "John Doe"
        links: {
          create: {
            node: {
              website: "https://example.com/"
            }
          }
        }
      }
    ]
  ) {
    people {
      id
      name
      links {
        website
      }
    }
  }
}
```

**Expected behavior**
The mutation should succeed - essentially creating the `NamedLinks` node and the `Person` node alltogether.

**System (please complete the following information):**

* OS: macOS
* Version: `@neo4j/graphql@4.4.0`
* Neo4j Version: `5.13` (Docker)
* Node.js version: `20.0.0` - tested also on `18.18.1` which behaves identically

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @olivermack. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Liam-Doodson** [comment]
Hi @olivermack! This kind of error is normally caused by you not having the APOC plugin installed in your database. Can you try installing it by following the guide here: https://neo4j.com/docs/apoc/current/installation/
