### ISSUE TITLE
Error message "Directive @relationship cannot be used in combination with @cypher" under certain circumstances

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#4232]
**Describe the bug**
After upgrading from 3.x.x to >4, I got the following error message with our schema:
````
GraphQLError: Invalid directive usage: Directive @relationship cannot be used in combination with @cypher
````

We have in our schema the case where one implementation of an interface annotates a field with a "relationship" directive and another implementation of the same interface annotates the same field with "cypher"

For this bugticket I then reproduced this case in a test application... But there I didn't get this error anymore.

After a long search I found out that it depends on the order of the type/interface declaration 

**Type definitions**
That works:
````graphql
type Person {
  name: String!
}

interface IProduct {
  editorsInCharge: [Person!]!
}

type Episode implements IProduct {
  editorsInCharge: [Person!]! @relationship(type: "EDITORS_IN_CHARGE", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
  partOf: Series @relationship(type: "HAS_PART", direction: IN, nestedOperations: [CONNECT, DISCONNECT])
}

type Series implements IProduct {
  editorsInCharge: [Person!]!
    @cypher(
      statement: """
      MATCH (this)-[:HAS_PART]->()-[:EDITORS_IN_CHARGE]->(n)
      RETURN distinct(n) as editorsInCharge
      """,
      columnName: "editorsInCharge"
    )
  parts: [Episode!]! @relationship(type: "HAS_PART", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
}
````

This, on the other hand, does not work:
````graphql
type Person {
  name: String!
}

type Episode implements IProduct {
  editorsInCharge: [Person!]! @relationship(type: "EDITORS_IN_CHARGE", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
  partOf: Series @relationship(type: "HAS_PART", direction: IN, nestedOperations: [CONNECT, DISCONNECT])
}

type Series implements IProduct {
  editorsInCharge: [Person!]!
    @cypher(
      statement: """
      MATCH (this)-[:HAS_PART]->()-[:EDITORS_IN_CHARGE]->(n)
      RETURN distinct(n) as editorsInCharge
      """,
      columnName: "editorsInCharge"
    )
  parts: [Episode!]! @relationship(type: "HAS_PART", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
}

interface IProduct {
  editorsInCharge: [Person!]!
}
````

**Expected behavior**
Regardless of the order of type/interface declaration the application should work

**System (please complete the following information):**
* Version: 4.4.0

**Additional context**
In our project, the schema is so large that we put each type and interface into its own file.
At a certain point the typeDefs of all files are collected and then passed to the Neo4jGraphQLConstructor.

While collecting the typeDefs it happened that the interface was included after its implementation (e.g. because of alphabetical sorting).

For now we have changed the order manually.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.
