### ISSUE TITLE
Authorization produces a predicate not supported by the `apoc.util.validatePredicate`

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4239]
**Describe the bug**
Authorization produces a predicate not supported by the `apoc.util.validatePredicate` when the predicate it's against related nodes.

**Type definitions**
```graphql
type Movie
    @authorization(
        validate: [
            { when: [BEFORE], where: { node: { directorConnection: { node: { id: "$jwt.sub" } } } } }
        ]
    ) {
    title: String
    director: [Person!]! @relationship(type: "DIRECTED", direction: IN)
}

type Person {
    id: ID
}
```

**To Reproduce**
The following query: 

```graphql
query {
  movies {
    title
  }
}
```
generate the following error:
`Neo4jError: EXISTS is only valid in a WHERE clause as a standalone predicate or as part of a boolean expression (AND / OR / XOR / NOT) (line 3, column 68 (offset: 93))
"WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND EXISTS {"`

**Expected behavior**
Should return the right movies or the correct error in case the jwt.sub does not match the director.

**System (please complete the following information):**

* OS: [macOS]
* Version: ["4.4.0"]
* Node.js version: [v16.16.0]
* Neo4j [4.4.26]

**Additional context**

**Debug info**
```
  @neo4j/graphql:graphql received graphql query +0ms
  @neo4j/graphql:graphql {
  @neo4j/graphql:graphql   movies {
  @neo4j/graphql:graphql     title
  @neo4j/graphql:graphql   }
  @neo4j/graphql:graphql } +1ms
  @neo4j/graphql:graphql variable values: 'variable values:' {} +0ms
  @neo4j/graphql:graphql incoming context: { token: undefined, cypherParams: { tenant: 'test' } } +2ms
  @neo4j/graphql:auth request not authenticated +0ms
  @neo4j/graphql:execution executing cypher +0ms
  @neo4j/graphql:execution CALL dbms.components() YIELD versions, edition UNWIND versions AS version RETURN version, edition +0ms
  @neo4j/graphql:execution cypher params: { tenant: 'test' } +0ms
  @neo4j/graphql:translate ReadOperation
  @neo4j/graphql:translate |──── AuthorizationFilters
  @neo4j/graphql:translate |     |──── AuthorizationRuleFilter
  @neo4j/graphql:translate |         |──── ConnectionFilter [director] <SOME>
  @neo4j/graphql:translate |             |──── ParamPropertyFilter [id] <EQ>
  @neo4j/graphql:translate |──── AttributeField <title> +0ms
  @neo4j/graphql:execution executing cypher +47ms
  @neo4j/graphql:execution MATCH (this:Movie)
  @neo4j/graphql:execution WITH *
  @neo4j/graphql:execution WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND EXISTS {
  @neo4j/graphql:execution     MATCH (this)<-[this0:DIRECTED]-(this1:Person)
  @neo4j/graphql:execution     WHERE ($jwt.sub IS NOT NULL AND this1.id = $jwt.sub)
  @neo4j/graphql:execution }), "@neo4j/graphql/FORBIDDEN", [0])
  @neo4j/graphql:execution RETURN this { .title } AS this +1ms
  @neo4j/graphql:execution cypher params: { isAuthenticated: false, jwt: {}, tenant: 'test' } +0ms
  @neo4j/graphql:execution Neo4jError: EXISTS is only valid in a WHERE clause as a standalone predicate or as part of a boolean expression (AND / OR / XOR / NOT) (line 3, column 68 (offset: 93))
"WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND EXISTS {"
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
