### ISSUE TITLE
Generated Endpoints get translated during generic generation (or: are asserted to be english)

### ISSUE THREAD

**Issue by SimplyComple0x78** [neo4j/graphql#424]
**Describe the bug**
Some model e.g. named
```
type Person {
  name: String
}
```
results in generically translated Endpoints using `new Neo4jGraphQL({ typeDefs, driver: drv })`.
In my case, "Person" is the german word for "person". In German, the plural is "Personen", it's generated as "people" (only being correct in english through):
```
    CreatePeopleMutationResponse: CreatePeopleMutationResponse,
    UpdatePeopleMutationResponse: UpdatePeopleMutationResponse,
```
Furthermore, I can't see any option to add comments or add parameters to determine how the generation _should_ work instead ([the docs don't help](https://neo4j.com/docs/graphql-manual/2.0/) with that).

**Type definitions**
My GraphQL-schema is the following:
```
type Person {
  name: String
}
```

**To Reproduce**
Run a Node.js-Server using tsc with the following code:
```
import { Neo4jGraphQL } from "@neo4j/graphql";
import { gql } from "apollo-server";
import { driver, auth } from "neo4j-driver";

const typeDefs = gql`
  type Person {
    name: String
  }
`;

const drv = driver("neo4j://localhost", auth.basic("neo4j", "test"));

const neoSchema = new Neo4jGraphQL({ typeDefs, driver: drv });
console.log(neoSchema.schema); // This is already broken
```

**Expected behavior**
I expected some generic pluralization like
```
CreatePersonsMutationResponse: CreatePersonsMutationResponse,
UpdatePersonsMutationResponse: UpdatePersonsMutationResponse
```
Another option would be to give in a mapping to define which are the correct plural forms (or how the naming should be overall).

**Screenshots**
E.g., using the [Apollo-Explorer](https://studio.apollographql.com/sandbox/explorer), I get non-german (i.e. english) endpoints this way although my initial input was completely in german:

![Bildschirmfoto von 2021-08-14 17-24-10 2](https://user-images.githubusercontent.com/876742/129451287-b344d4c8-0b5f-4f38-bf92-36c5c6b93b5e.png)

**System (please complete the following information):**
-   OS: Linux (Ubuntu, Bionic Beaver)
-   Version: @2.0.0
-   Node.js version: 12.14.0

**Additional Information**
The issue is about your usage of the `pluralize`-package since I don't always want to pluralize this way.

**Comment by darrellwarde** [comment]
I feel your frustration, but the use of the `pluralize` package saves us having to implement pluralization ourselves - I don't think there's such thing as "generic pluralization" as you've described because it is crazy complex even just for one language, let alone trying to account for many.

I guess you could say we're an "English-first" library, and following discussions in the team that is unlikely to ever change, and as such I'm going to close this issue as a "won't do". Apologies, but I hope you understand!

**Comment by SimplyComple0x78** [comment]
@darrellwarde Sure, I understand the issue and thanks for the reply.
Could you please tell me what could be the right direction to hack around this? If i traverse through your `neoSchema` (referencing the above example) and replace all your names with ones that suit my needs, would that work or do I miss something with that idea?
I'd just implement that, but your structure is rather complex so maybe you can stop my thoughts before the effort.

**Comment by darrellwarde** [comment]
Sure thing, as a workaround, you could look into schema wrapping using `@graphql-tools/wrap`. A bit complex, but essentially can be used to wrap our schema, renaming types and fields as you need. Find the docs here: https://www.graphql-tools.com/docs/schema-wrapping 🙂
