### ISSUE TITLE
Support @populatedBy or similar for relationships

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#4240]
I am currently storing the user id of the use who created certain objects in a not-selectable property createdByUserName using @populatedBy and have a @cypher-backed field createdBy for reading the User object back out later.

This works, but the drawback is that it is not possible to properly filter users. To do so, I would either need something like @populatedBy for relationships to automatically connect a node during creation.

(Alternatively supporting filtering on @cypher fields would also help - although it would be quite inefficient in this case.)

**Comment by darrellwarde** [comment]
At some point, we would like to add "Cypher hooks" (#2265).

We also intend to allow filtering by Cypher fields (#554).
