### ISSUE TITLE
Logical operators do not work correctly inside Authorization rules 

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4268]
**Describe the bug**
Logical operators do not work correctly inside Authorization rules.

**Type definitions**
```graphql
type JWT @jwt {
    id: ID!
    email: String!
    roles: [String!]!
}

type Movie @authorization(validate: [
        {
             when: [BEFORE]
             where: { jwt: { OR: [{ roles: "admin" }, { roles: "super-admin" }] } }
        } 
    ]) {
    title: String
    director: [Person!]! @relationship(type: "DIRECTED", direction: IN)
}

type Person {
    id: ID
}
```

**To Reproduce**
Run the following query, with a JWT that contains an "admin" or "super-admin" role:
```graphql
query {
  movies {
    title
  }
}
```

The Cypher produced is:

```cypher
MATCH (this:Movie)
WITH *
WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND ($jwt.OR IS NOT NULL AND $jwt.OR = $param2)), "@neo4j/graphql/FORBIDDEN", [0])
RETURN this { .title } AS this
```

As it's visible the Cypher produced does not generate correctly the logical filter for the `OR`.

**Expected behavior**
It should not raise an error if the JWT contains "admin" or "super-admin" in the `roles` claim.

**System (please complete the following information):**

* OS: [macOS]
* Version: [@neo4j/graphql@4.4.1]
* Node.js version: [16.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
