### ISSUE TITLE
Interface relationship connection where logical operators does not filter the results in Cypher

### ISSUE THREAD

**Issue by a-alle** [neo4j/graphql#4287]
**Describe the bug**
When using the logical operators on the relationship connection where filter when the relationship is to an Interface type, the generated Cypher does not contain the filters specified inside the logical operators.

**Type definitions**
```graphql
type Actor {
    name: String
    actedIn: [Production!]! @relationship(type: "ACTED_IN", properties: "actedIn", direction: OUT)
}
interface actedIn @relationshipProperties {
    role: String
}
interface Production {
    title: String
}
type Movie implements Production{
    title: String
    runtime: Int
}
type Series implements Production{
    title: String
    episodes: Int
}
```

**To Reproduce**
1. Execute the following Query:
```graphql
query {
    actors {
        actedInConnection(where:  {
          OR: [
            {
              node: {
                title: "something"
              },
            }
            {
              node: {
                title: "whatever"
              }
            }
          ]  
        }) {
          edges {
            node {
              __typename
              title
            }
          }
        } 
    }
}
```

2. Notice how the generated Cypher does not filter the results in any way (there is no `WHERE`):
```sql
MATCH (this:Actor)
CALL {
    WITH this
    CALL {
        WITH this
        MATCH (this)-[this0:ACTED_IN]->(this1:Movie)
        WITH { node: { __resolveType: "Movie", __id: id(this1), title: this1.title } } AS edge
        RETURN edge
        UNION
        WITH this
        MATCH (this)-[this2:ACTED_IN]->(this3:Series)
        WITH { node: { __resolveType: "Series", __id: id(this3), title: this3.title } } AS edge
        RETURN edge
    }
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    RETURN { edges: edges, totalCount: totalCount } AS var4
}
RETURN this { actedInConnection: var4 } AS this
```

**Expected behavior**
The results should have title either "something" or "whatever".
This is a regression from 4.0, when the translation looked like this:
```sql
MATCH (this:Actor)
CALL {
    WITH this
    CALL {
        WITH this
        MATCH (this)-[this0:ACTED_IN]->(this1:Movie)
        WHERE (this1.title = "something" OR this1.title = "whatever")
        WITH { node: { __resolveType: "Movie", __id: id(this1), title: this1.title } } AS edge
        RETURN edge
        UNION
        WITH this
        MATCH (this)-[this2:ACTED_IN]->(this3:Series)
        WHERE (this3.title = "something" OR this3.title = "whatever")
        WITH { node: { __resolveType: "Series", __id: id(this3), title: this3.title } } AS edge
        RETURN edge
    }
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    RETURN { edges: edges, totalCount: totalCount } AS var4
}
RETURN this { actedInConnection: var4 } AS this
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @a-alle. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @a-alle! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
