### ISSUE TITLE
Interface relationship connection where logical operators throws an unexpected error

### ISSUE THREAD

**Issue by a-alle** [neo4j/graphql#4288]
**Describe the bug**
When using the logical operators on the relationship connection where filter when the relationship is to an Interface type, if there are 2 conditions both only checking a subset of the implementing concrete types, an error is thrown: `_on is used as the only argument and node is not present within.`
Notice in the below example how the implementing concrete types are Movie and Series, and the filters only check for one of them at a time (one filter _on Movie + another filter _on Series).

**Type definitions**
```graphql
type Actor {
    name: String
    actedIn: [Production!]! @relationship(type: "ACTED_IN", properties: "actedIn", direction: OUT)
}
interface actedIn @relationshipProperties {
    role: String
}
interface Production {
    title: String
}
type Movie implements Production{
    title: String
    runtime: Int
}
type Series implements Production{
    title: String
    episodes: Int
}
```

**To Reproduce**
1. Execute the following Mutation:
```graphql
mutation {
  updateActors {
    actors {
      actedInConnection(where: {
          OR: [
            {
              node: {
                _on: {
                  Movie: {
                    runtime: 100
                  }
                }
              }
            }
            {
              node: {
                _on: {
                  Series: {
                    episodes: 20
                  }
                }
              }
            }
          ]  
        }) {
        edges {
          node { 
            title
          }
        }
      }
    }
  }
}
```

2. Notice the error:
`_on is used as the only argument and node is not present within.`

**Expected behavior**
No error should be thrown, the filters should both be applied to each individual Union subquery, similar to this:
```sql
MATCH (this:Actor)
CALL {
    WITH this
    CALL {
        WITH this
        MATCH (this)-[this0:ACTED_IN]->(this1:Movie)
        WHERE this1.runtime = 100
        WITH { node: { __resolveType: "Movie", __id: id(this1), title: this1.title } } AS edge
        RETURN edge
        UNION
        WITH this
        MATCH (this)-[this2:ACTED_IN]->(this3:Series)
        WHERE this3.episodes = 20
        WITH { node: { __resolveType: "Series", __id: id(this3), title: this3.title } } AS edge
        RETURN edge
    }
    WITH collect(edge) AS edges
    WITH edges, size(edges) AS totalCount
    RETURN { edges: edges, totalCount: totalCount } AS var4
}
RETURN this { actedInConnection: var4 } AS this
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @a-alle. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @a-alle! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
`_on` is being removed in version 5.0.0 of the library, so this will not be fixed.
