### ISSUE TITLE
Pass both the Edge and the Out-Vertex into relations types for the @relations directive

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#429]
Hi,

Please consider passing a map of botht he Edge and the Out-Vertex into the Relations type when generating the code for the automatic @relations handling.

This would provide full context. 

With 'this' as a relation then having the ability to call out(this) and in(this) is better. I have not been able to find that ability and inquireing about the existance of such methods has not worked) :)

**Comment by acmeguy** [comment]
intended for the 2.0.0 (before any such changes become problematic)

**Comment by darrellwarde** [comment]
I'm not sure I fully understand what you're suggesting here, could you possibly give an example of where this would be used and how it would be beneficial?

**Comment by acmeguy** [comment]
sure Darell.

usually the only thing that a type gets is the parent object as 'this'.
When working with Edges/Relations the Edge is passed as 'this' but it would be very beneficial to get both the relation and the our-tart Vertex. Returning a masp with {ret:relations and out:vertex} would provide an easy access to both the relation and the destination vertex. {this.rel and this.out/this.in}

Regards,
 - Stefán

**Comment by darrellwarde** [comment]
So you're talking in the context of custom Cypher fields I'm assuming? For now, we've disabled the addition of custom Cypher fields to relationship properties interfaces, whilst we make decisions on exactly the kind of things you've described here. 🙂

**Comment by acmeguy** [comment]
ok.  Easy access is important - or at lease extreamly convenient - when creating composite Edge representations that include information from source/dstination vertices. If they are done at this stage in the process then the overhead should be minimal and the complete cypher should be less complex, compared to having to featch it again inside sub-cypher matches.

**Comment by danstarns** [comment]
Closing this due to no concrete examples of what the schema would look like, how you would interact with the schema and what the generated cypher would be. Please re-comment if you have more information.
