### ISSUE TITLE
Empty where condition in nodeConnection parameters causes malformed cypher

### ISSUE THREAD

**Issue by jbhurruth** [neo4j/graphql#433]
```graphql
query {
  nodes {
    otherNodeConnection(where: {}) {
      edges {
        node {
          property
        }
      }
    }
  }
}
```
A query like this will cause an error as is executes the resultant cypher since the generated cypher has a line in the statement which just reads "WHERE" without a following condition. It only happens with the "nodeConnection" form

**Comment by darrellwarde** [comment]
@jbhurruth, what result would you expect here? How have you ended up with the `where` argument as an empty object?
