### ISSUE TITLE
Bumping the @graphql-tools to the latest major release

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#434]
Hi hi,

Why is the 2.0.0. using the 7x version of @graphql-tools ?
Is it possible to bump these to latest stable release?

- Stefán

**Comment by darrellwarde** [comment]
It's on our books - we would have done it with the 2.0.0 release but it's HUGELY breaking and there was already enough changes in this release.

**Comment by acmeguy** [comment]
OK, were those bugs or deprecated things that required refactoring?

I ask because we want to use graphql-tools as a backbone for what we are doing - now that the playtime is over - and I'd like to know if we should stick with the 7x version.

**Comment by darrellwarde** [comment]
Mostly deprecated things which require refactoring - upgrading is going to mean a lot of changes for us, and it will be a major version bump of this library when we decide to do it. It won't be for a while yet - we want to focus on important features over dependency upgrades.

**Comment by darrellwarde** [comment]
We're finally going to be getting around to this after Christmas!
