### ISSUE TITLE
Authorization does not work with array-based filters.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4405]
**Describe the bug**
The param coming from the filter `title_IN: ["Matrix"]`  is evaluated as `[ { "0": "M", "1": "a", "2": "t", "3": "r", "4": "i", "5": "x" } ]` rather than: `["Matrix"]` if used inside an authorization rule.

**Type definitions**
```graphql
type Movie {
    title: String
}

type Actor
    @authorization(
        validate: [
            {
                when: [BEFORE]
                operations: [READ]
                where: { node: { actedInConnection_SOME: { node: { title_IN: ["Matrix"] } } } }
            }
        ]
    ) {
    name: String!
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

interface ActedIn @relationshipProperties {
    screenTime: Int!
}
```

**To Reproduce**
Run the following query:

```graphql
query actors {
  actors {
    name
  }
}
```

**Cypher**
```cypher
  MATCH (this:Actor)
  WITH *
  WHERE apoc.util.validatePredicate(NOT ($isAuthenticated = true AND size([(this)-[this1:ACTED_IN]->(this0:Movie) WHERE ($param1 IS NOT NULL AND this0.title IN $param1) | 1]) > 0), "@neo4j/graphql/FORBIDDEN", [0])
  RETURN this { .name } AS this
```
**Params**
```json
{
    "isAuthenticated": false,
    "param1": [ { "0": "M", "1": "a", "2": "t", "3": "r", "4": "i", "5": "x" } ],
 }
```

**Expected behavior**
The `Cypher.Param` should be evaluated correctly.

**System (please complete the following information):**

* OS: [macOS]
* Version: [e.g. @neo4j/graphql@4.4.4]
* Node.js version: [14.16.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
