### ISSUE TITLE
Can't disable authentication for OGM but keep it enabled on API

### ISSUE THREAD

**Issue by kozak-codes** [neo4j/graphql#4419]
**Describe the bug**

This is my schema type def:
extend schema @authentication

When I use the same type defs in OGM that I do for my apollo gateway,  with "features.authentication" set to undefined, and make a call to find something, I get an "Unauthenticated" error. Is this intended, can I disable it somehow? Or should I extract the directives from my typedefs for my OGM call? I also get a message in the logs that say I need to enable it in the features

This is my temporary workaround:
```
        ogmTypeDefs = ogmTypeDefs
            .replace(/@authentication((.?))/g, '')
            .replace(/@authorization((.?))/g, '')
            .replace(/extend schema/g, '')
```

Don't have a ton of time to fully flesh this issue out but figured I'd raise it!

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...
3. Then run the following Query...

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: [e.g. @neo4j/graphql@1.0.0]
* Node.js version: [e.g. 14.16.0]

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @kozak-codes. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
@kozak-codes do you have any example code we can use to reproduce this? Thank you!

**Comment by angrykoala** [comment]
Closing this as it is unreproducible for a while, @kozak-codes feel free to comment here if there is more information that may help us reproduce the issue
