### ISSUE TITLE
Cannot use autogenerated types in schema for custom resolvers

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/graphql#442]
**Describe the bug**

Schema:
```graphql
type Post {
 id: Int!
 text: String!
}
extend Mutation{
   create_Post(text: String!): CreatePostsMutationResponse!
}
```

Now CreatePostsMutationResponse is inaccessible, along with UpdatePostsMutationResponse, SortDirection etc.
It writes now:
Error: Unknown type "CreatePostsMutationResponse".
    at assertValidSDLExtension
    at Object.extendSchema
    at Object.validateDocument 
    at Object.makeAugmentedSchema 
    at new Neo4jGraphQL 
    at Object.<anonymous>

It was broken between alpha.4 and rc.1

**Comment by Kubera2017** [comment]
My subspection it was broken by https://github.com/neo4j/graphql/pull/356

**Comment by darrellwarde** [comment]
This is actually to do with the enhanced validation of type definitions we added in 2.0.0. You can actually fully work around it (https://neo4j.com/docs/graphql-manual/current/guides/v2-migration/miscellaneous/#_schema_validation), and I've noted down that we need to allow MutationResponse types through. 🙂

**Comment by killmenot** [comment]
@darrellwarde Hi

After migration my project from 2.x to 3.11.1 I faced with the same problem during the validation
```
Error: Unknown type "SortDirection". Did you mean "__Directive"?
```

Here is a working example:
https://github.com/killmenot/neo4j-custom-resolver-problem

Only passing
```js
config: {
   skipValidateTypeDefs: true,
},
```
to both OGM and Neo4jGraphQL helped me but probably it's just a temporary hack
<img width="1044" alt="Screenshot 2022-10-28 at 14 15 34" src="https://user-images.githubusercontent.com/119337/198574718-4f03de72-30bf-43bf-8e81-8df068f16ae6.png">
