### ISSUE TITLE
Add ability to subscribe to events via the OGM

### ISSUE THREAD

**Issue by kozak-codes** [neo4j/graphql#4420]
**Is your feature request related to a problem? Please describe.**

eg:

```
const Message = ogm.model('Message');
Message.on('created', {
  where: {},
}, (result) => {
  // do something with your new message
})

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbhurruth** [comment]
You can achieve this by writing a custom subscription plugin and then routing the events to your handlers. I've found the only issue is that the execution context doesn't make it through to plugin unless you make some minor patches to the library. This doesn't matter if you don't have about your event handlers and the mutations thats caused them being scoped to the same transaction.

**Comment by darrellwarde** [comment]
With the current OGM being moved to LTS status, this is a feature that we will not be adding.
