### ISSUE TITLE
The connection to a to-1 union does not check whether only one node is actually connected.

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#4424]
**Describe the bug**
With a To-1 relationship to a union, the library does not check whether only one node is actually connected. 

**Type definitions**
````graphql
type Movie {
  name: String!
  publicationEvent: [PublicationEvent!]! @relationship(type: "HAS_PUBLICATION_EVENT", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
}

type Episode {
  name: String!
  publicationEvent: [PublicationEvent!]! @relationship(type: "HAS_PUBLICATION_EVENT", direction: OUT, nestedOperations: [CONNECT, DISCONNECT])
}

union MovieOrEpisode = Movie | Episode

type PublicationEvent {
  name: String!
  product: MovieOrEpisode! @relationship(type: "HAS_PUBLICATION_EVENT", direction: IN, nestedOperations: [CONNECT, DISCONNECT])
}
````

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...
(1) Create movies and episodes
````graphql
mutation CreateMoviesAndEpisodes {
  createMovies(input: [
    {
      name: "TestMovie1"
    },
    {
      name: "TestMovie2"
    }
  ]) {
    movies {
      name
    }
  }

  createEpisodes(input: [
    {
      name: "TestEpisode1"
    },
    {
      name: "TestEpisode2"
    }
  ]){
    episodes {
      name
    }
  }
}
````

(2) Create PublicationEvent-Object
No filter is specified here for the connection (it has been forgotten). The mutation works anyway. **Both movie nodes are connected.**
````graphql
mutation CreatePublicationEvent {
  createPublicationEvents(input: {
    name: "TestPubEvent1",
    product: {
      Movie: {
        connect: {
          where: {
            node: {}
          }
        }
      }
    }
  }){
    publicationEvents {
      name
    }
  }
}
````
3. Then run the following Query...
However, only one movie node is returned. It appears undeterministic.
````graphql
query GetPublicationEvents {
  publicationEvents {
    name
    product {
      ... on Movie {
        name
      }
      ... on Episode {
        name
      }
    }
  }
}
````
````json
{
  "data": {
    "publicationEvents": [
      {
        "name": "TestPubEvent1",
        "product": {
          "name": "TestMovie2"
        }
      }
    ]
  }
}
````

**Expected behavior**
When executing the second mutation, the following error message should be returned: PublicationEvent.product required exactly once

**Screenshots**
![image](https://github.com/neo4j/graphql/assets/49721200/acd7a030-2875-47ab-9a7c-143d0d43e99c)

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: @neo4j/graphql@4.4.1
* Node.js version: [e.g. 14.16.0]

**Additional context**

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
Hey @AccsoSG, I'm honestly unsure whether we ever implemented cardinality checks for union relationships, it's something we need to go away and look at. But this could be a feature request as opposed to a bug in that sense. Thanks, happy holidays!

**Comment by darrellwarde** [comment]
We will be removing support for 1:1 and 1:* relationships in Version 7 of the library for these exact reasons. We need to stop supporting things which are not natively supported by the database! We won't be adding this into Version 5 LTS.
