### ISSUE TITLE
Since 4.2.0, filtering through a connection to a many-to-1 relationship on the other side doesn't work anymore

### ISSUE THREAD

**Issue by MichaelCDormann** [neo4j/graphql#4450]
**Describe the regression**
Filtering through a connection to a many-to-1 relationship on the other side doesn't work anymore. The example below is maybe a little contrived, but I have queries doing this sort of filtering running in production. 

**Last working version**

Worked up to version: @neo4j/graphql@4.1.3

Stopped working in version: @neo4j/graphql@4.2.0

**Type definitions**
```
type Actor {
    name: String
    scene: [Scene!]! @relationship(type: "IN_SCENE", properties: "ActorScene", direction: OUT)
}

type Scene {
    number: Int
    actors: [Actor!]! @relationship(type: "IN_SCENE", properties: "ActorScene", direction: IN)
    location: Location! @relationship(type: "AT_LOCATION", direction: OUT)
}

type Location {
    city: String
    scenes: [Scene!]! @relationship(type: "AT_LOCATION", direction: IN)
}

interface ActorScene @relationshipProperties {
    cut: Boolean
}
```

**To Reproduce**

1. With the above type definitions run the following query:
```
query ExampleQuery($where: ActorWhere) {
  actors(where: $where) {
    name
  }
}
```
with variables:
```
{
  "where": {
    "sceneConnection_SOME": {
      "edge": {
        "cut": true
      },
      "node": {
        "location": {
          "city": "test"
        }
      }
    }
  }
}
```
2. See the below error
```
Variable `locationCount` not defined (line 4, column 37 (offset: 119))\n\"    WHERE (this0.cut = $param0 AND (locationCount <> 0 AND this2.city = $param1))
```

**Expected behavior**
It should not error, and I should get back [] or actors who are in scenes that they have been cut from at the location specified.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MichaelCDormann. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MichaelCDormann! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
