### ISSUE TITLE
Nested aggregate filtering not working after updating neo4j-graphql from V3 to V4

### ISSUE THREAD

**Issue by simon-heka** [neo4j/graphql#4477]
I believe this is bug introduced between v3 and v4.

Given the following type defs:

```
  type Brand {
      services: [Service!]! @relationship(type: "HAS_SERVICE", direction: OUT)
  }

  type Collection {
      services: [Service!]! @relationship(type: "HAS_SERVICE", direction: OUT)
  }

  type Service {
      collection: Collection @relationship(type: "HAS_SERVICE", direction: IN)
  }
```

If I run a query as follows (to find Services that aren't in a Collection):
```
query ExampleQuery {
  brands {
    services(where: { collectionAggregate: { count: 0 } }) {
      collectionAggregate {
        count
      }
    }
  }
}
```
In V3 I got the following result (as expected):
```
{
  data: {
    "brands": [
      {
        "services": [
          {
            "collectionAggregate": {
              "count": 0
            }
          }
        ]
      }
    ]
  }
}
```
But now, in V4, I get this result: 
```
{
  data: {
    "brands": [
      {
        "services": [
          {
            "collectionAggregate": {
              "count": 0
            }
          },
          {
            "collectionAggregate": {
              "count": 1
            }
          }
        ]
      }
    ]
  }
}
```
So, in V4, the aggregate filter is not being respected. However, if I query with Services at the top level (as opposed to Brands), the aggregate filter works correctly, leading me to believe that the issue is only effecting aggregate filters when nested.

i.e. the following query, in V4, with the Services at top level, returns only Services that are not related to a Collection (as expected):
```
query ExampleQuery {
    services(where: { collectionAggregate: { count: 0 } }) {
      collectionAggregate {
        count
      }
    }
}
```

Thanks.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @simon-heka. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Thanks for moving this over here @simon-heka, we will firstly confirm this issue and then decide on a plan of action next week. 🙂

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @simon-heka! :pray: We will now prioritise the bug and address it appropriately.
