### ISSUE TITLE
Spelling error in documentation 

### ISSUE THREAD

**Issue by dryhurst** [neo4j/graphql#448]
**Describe the bug**
Spelling error/typo.

**To Reproduce**
1.browse to page: https://neo4j.com/docs/graphql-manual/current/ogm/ 
2. read

**Expected behavior**
Should say Neo4j not Neo4h

**Screenshots**
![image](https://user-images.githubusercontent.com/1443017/130285728-f57e6f7d-9e6a-4c36-9aa0-ca8f651a0022.png)

**Comment by darrellwarde** [comment]
Thanks, fixed in #450! 🙂
