### ISSUE TITLE
Inconsistent behaviour for subscription `EventPayload` when using interfaces

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#4511]
**Describe the bug**

Given a schema [like in the tests:](https://github.com/neo4j/graphql/blob/551c0cc4389f23eebd06928be7f50d12e9f48c0f/packages/graphql/tests/schema/experimental-schema/subscriptions.test.ts#L5688-L5714) 

```graphql
type Movie implements Production @subscription(events: []) {
    title: String!
    id: ID @unique
    director: Creature!
}
type Series implements Production {
    title: String!
    episode: Int!
    id: ID @unique
    director: Creature!
}
interface Production {
    id: ID
    director: Creature! @relationship(type: "DIRECTED", direction: IN)
}
type Person implements Creature {
    movies: Production!
}
interface Creature {
    movies: Production! @relationship(type: "DIRECTED", direction: OUT)
}
```

The following type is generated:

```graphql
interface ProductionEventPayload {
  id: ID
}

type SeriesEventPayload implements ProductionEventPayload {
  director: Creature!
  directorConnection: ProductionDirectorConnection!
  episode: Int!
  id: ID
  title: String!
}

...
```

I would not expect the fields `director` and `directorConnection` on `SeriesEventPayload` since they are no scalar- / enum- / spatial- fields ([isEventPayloadField](https://github.com/neo4j/graphql/blob/2bb8f8b628c52c102c2db988685fc54f08521488/packages/graphql/src/schema-model/attribute/model-adapters/AttributeAdapter.ts#L142))

When removing the interface `Production` from the `Series` object type, these fields are not present on the `SeriesEventPayload`

**Current analysis:**

The place where this happens is in [buildRelationshipDestinationInterfaceNodeType](https://github.com/neo4j/graphql/blob/3ded9dace92c9e83278480f982148c01b2d2637b/packages/graphql/src/schema/subscriptions/generate-subscription-connection-types.ts#L77-L80)

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
