### ISSUE TITLE
Inconsistent augmentation of relational fields of interfaces

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#4514]
**Describe the bug**

Currently interfaces get augmented differently depending if they are used  as target of a relations or not.

Example

https://github.com/neo4j/graphql/blob/7342feda553c018f869a0cef4a070409155766d2/packages/graphql/tests/schema/directives/settable.test.ts#L7126-L7147

generates

https://github.com/neo4j/graphql/blob/7342feda553c018f869a0cef4a070409155766d2/packages/graphql/tests/schema/directives/settable.test.ts#L7553-L7558

but 

https://github.com/neo4j/graphql/blob/387e455bb9aebb94663b05baed6c8694ec304e80/packages/graphql/tests/schema/experimental-schema/interfaces.test.ts#L28-L46

generates

https://github.com/neo4j/graphql/blob/387e455bb9aebb94663b05baed6c8694ec304e80/packages/graphql/tests/schema/experimental-schema/interfaces.test.ts#L520-L525

where the arguments on the augmented relational fields of the interface `MovieNode` are missing.

**Expected behavior**

All augmented interfaces have arguments on their relational fields

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
