### ISSUE TITLE
Authorization validate argument should also handle a single (non-array) entry

### ISSUE THREAD

**Issue by mjfwebb** [neo4j/graphql#4534]
The library is throwing an error if the validate argument is not an array.

We should be able to handle both an array of arguments and a single non-array argument:
```graphql
validate: { where: { jwt: { roles_INCLUDES: "admin" } } }
``` 
```graphql
validate: [{ where: { jwt: { roles_INCLUDES: "admin" } } }]
```

Currently, it only accepts the latter where the argument is an array. With the former, the following error is thrown by the library:

```ts
    TypeError: validate?.map is not a function

      35 |     };
      36 |     const filterRules = filter?.map((rule) => new AuthorizationFilterRule(rule as AuthorizationFilterRuleConstructor));
    > 37 |     const validateRules = validate?.map(
         |                                     ^
      38 |         (rule) => new AuthorizationValidateRule(rule as AuthorizationValidateRuleConstructor)
      39 |     );
      40 |

      at parseAuthorizationAnnotation (packages/graphql/src/schema-model/parser/annotations-parser/authorization-annotation.ts:37:37) 
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mjfwebb. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mjfwebb! :pray: We will now prioritise the bug and address it appropriately.
