### ISSUE TITLE
Inconsistent behavior between field-level authorization and entity-level authorization on Update.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4536]
**Describe the bug**

Authorization on update has different behavior depending on whether the directive is applied at the field level or the entity level.

**Type definitions**
```graphql
type User {
    id: ID
    name: String
}

extend type User {
    name: String @authorization(validate: [ { operations: [READ], when: BEFORE, where: { node: { name "$jwt.sub" } } }])
}
```

**To Reproduce**

Run the following mutation:

```graphql
mutation {
    updateUsers(where: {id: "user-id"}, update: {id: "new-id"}) {
        users {
            id
	    name
        }
    }
}
```

With an invalid JWT,  a Forbidden error is returned.

However by changing the above typeDefs to:

```graphql
type User {
    id: ID
    name: String
}

extend type User @authorization(validate: [ { operations: [READ], when: BEFORE, where: { node: { name "$jwt.sub" } } }])
```

The Forbidden error disappears.

**Expected behavior**
A consistent behavior between field-level authorization and entity-level authorization.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by jbhurruth** [comment]
Wait, when was property level authorization added? Was it always there? Just want to point out that the only mention of this feature in the docs is the ambiguously worded 
`They use predicates to evaluate the data accessed by the Cypher generated from a GraphQL query, thus allowing or disallowing execution within the context of nodes and their properties.`
and is almost contradicted by 
`@authorization Specifies authorization rules for queries and mutations on the type.`

Sometimes I get the feeling that there's a whole other set of docs that everyone knows about except me 🥲

**Comment by MacondoExpress** [comment]
It was always there, it was an already existing behavior of the previous `@auth` directive, and the same concept exists as well within the new `@authorizatiton` directives, although it seems is no longer specifically described in the new documentation. You can raise it directly in the documentation https://github.com/neo4j/docs-graphql repository to improve the next reader's experience!
