### ISSUE TITLE
@id and @timestamp directives not applied to edge properties.

### ISSUE THREAD

**Issue by maxwellprioritynetworks** [neo4j/graphql#456]
**Describe the bug**

**Type definitions**
`
interface ServiceVehicleRegistrationDetails{
        id: ID @id
        startDT: DateTime @timestamp(operations: [CREATE])
        endDT: DateTime
        truck_id: String
        active: Boolean
    }

    type ServiceVehicle {
        id: ID! @id
        customer: Customer @relationship(type: "OWNED_BY", properties:"ServiceVehicleRegistrationDetails", direction: OUT)
        customerRented: Customer @relationship(type: "RENTED_BY", properties: "ServiceVehicleRegistrationDetails", direction:OUT)
        license_plate: String!
    }
`
**To Reproduce**
Apply a create or update to any edge property that should be autogenerated. It does not create the expected cypher. 

**Expected behavior**
ID or datetime values should be applied.

**Screenshots**
**Additional context**

It looks like there is a noop in two places: 
1) packages/graphql/src/translate/create-set-relationship-properties-and-params.ts: line 49 and line 58
2) packages/graphql/src/translate/create-set-relationship-properties.ts: line 49 and line 58

For example there will never be a member of Object.entries(properties) with autogenerate=true as the API would exclude this field from the mutation type.

My fix:

```ts
import { Relationship } from "../classes";
/*
    TODO - lets reuse this function for setting either node or rel properties.
           This was not reused due to the large differences between node fields
           - and relationship fields.
*/
function createSetRelationshipPropertiesAndParams({
    properties,
    varName,
    relationship,
    operation,
}: {
    properties: Record<string, unknown>;
    varName: string;
    relationship: Relationship;
    operation: "CREATE" | "UPDATE";
}): [string, any] {
    const strs: string[] = [];
    const params = {};

    // iterate through all autogenerate fields.
    relationship.primitiveFields.forEach((primitiveField)=>{
        if (primitiveField?.autogenerate) {
            if (operation==='CREATE'){
                strs.push(`SET ${varName}.${primitiveField.fieldName} = randomUUID()`);
            }
        }
    });

    relationship.dateTimeFields.forEach((dateTimeField)=>{
        if (dateTimeField?.timestamps?.includes(operation)){
            strs.push(`SET ${varName}.${dateTimeField.fieldName} = datetime()`);
        }
    });

    Object.entries(properties).forEach(([key, value]) => {
        const paramName = `${varName}_${key}`;

        // const dateTimeField = relationship.dateTimeFields.find((x) => x.fieldName === key);
        // if (dateTimeField && dateTimeField.timestamps?.length) {
        //     (dateTimeField.timestamps || []).forEach((ts) => {
        //         if (ts.includes(operation)) {
        //             strs.push(`SET ${varName}.${key} = datetime()`);
        //         }
        //     });
        //
        //     return;
        // }
        //
        // const primitiveField = relationship.primitiveFields.find((x) => x.fieldName === key);
        // if (primitiveField?.autogenerate) {
        //     strs.push(`SET ${varName}.${key} = randomUUID()`);
        //
        //     return;
        // }

        const pointField = relationship.pointFields.find((x) => x.fieldName === key);
        if (pointField) {
            if (pointField.typeMeta.array) {
                strs.push(`SET ${varName}.${key} = [p in $${paramName} | point(p)]`);
            } else {
                strs.push(`SET ${varName}.${key} = point($${paramName})`);
            }

            params[paramName] = value;

            return;
        }

        strs.push(`SET ${varName}.${key} = $${paramName}`);
        params[paramName] = value;
    });

    return [strs.join("\n"), params];
}

export default createSetRelationshipPropertiesAndParams;
```

**Comment by darrellwarde** [comment]
Hey @maxwellprioritynetworks - thanks for pointing this out and offering a solution! We will take a look, obviously we're going to need to add a bunch of tests as well as the solution, so give us a bit of a time to look into it.

**Comment by maxwellprioritynetworks** [comment]
Hey Darrel, you are welcome. I've sort of been sitting on this bug fix for a while though never got around to writing the tests needed for a PR. Same goes for my implementation of @index and @unique field directives into an apoc.schema.assert call. If interested I could share a patch file with this feature.
