### ISSUE TITLE
"$input" context in authorization rules

### ISSUE THREAD

**Issue by jbhurruth** [neo4j/graphql#4560]
I've recently come across a scenario where I'd like to ensure that users cannot create two nodes that represent intervals and overlap each other. I've been looking to achieve this via an authorization `validate` rule and initially hoped that either `$node` or `$this` would be supported in same the way `$jwt` is inside strings. At this point I'm guessing that full schema traversal would be difficult but for my use case a way to compare against properties of an `$input` object would be useful.

**Describe the solution you'd like**
I'm imagining the following schema
```graphql
type Interval @authorization(validate: [
    { operations: [CREATE, UPDATE], when: BEFORE, where: {
        node: { 
            other: {
                intervals_NONE: {
                    OR: [
                        { start_LT: "$input.end", start_GTE: "$input.start" },
                        { end_LTE: "$input.end", end_GT: "$input.start" }
                    ],
                }
            }
         }
    }  },
]) {
    id: ID @id
    start: DateTime!
    end: DateTime!
    other: Other! @relationship(type: "HAS_INTERVAL", direction: IN)
}
type Other {
    id: ID @id
    intervals: [Interval!]! @relationship(type: "HAS_INTERVAL", direction: OUT)
}
```
The `$input` object would have to unroll to be compared against the respective nodes if executing a mutation with multiple inputs. In this specific scenario each input object would be compared against all existing nodes, and ideally in addition to any previous inputs that have already been handled. As I write this I realise that this aspect is both awkward and vulnerable to attempts to defeat such a check.

**Describe alternatives you've considered**
Alternatively this could be solved by a custom validation hook that gets passed the transaction context and relevant data. This is definitely more flexible and potentially less complex. I have a feeling this may have been requested before but can't find it

There's probably a better way to achieve something like this that hasn't occurred to me yet. What are your thoughts?

**Comment by darrellwarde** [comment]
With the side effects you mention such as unrolling, this is not something we will implement.

Really, I would say this is validation that should be done before the database, so maybe some kind of custom resolver?

Alternatively, if these are nested operations, allowing them to take place, and validating the result. 

Closing because I don't think there's anything for us to implement here.
