### ISSUE TITLE
Mandatory missing relationships are not during insertion/update if the relationship type is an interface type.

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#4565]
**Describe the bug**

Mandatory missing relationships are not during insertion/update if the relationship type is an interface type. They will fail only during querying later. But if the type of the mandatory field is a type and not an interface it works as expected.

To reproduce, run the example blow once as it is and observe no error occurs and once by changing the line following the instruction "# An error will occur if and only if "I!" is changed to "B!" and observe the expected error.

```javascript
/*
package.json

{
  "name": "test-case-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@neo4j/graphql": "^4.4.5",
    "graphql": "^16.6.0",
    "graphql-tag": "^2.12.6",
    "neo4j-driver": "^5.5.0"
  }
}

*/
const gql = require("graphql-tag");
const { Neo4jGraphQL } = require("@neo4j/graphql");
const neo4j = require("neo4j-driver");
const { execute, validate } = require("graphql");

const typeDefs = gql`
  interface I {
    name: String
  }
  type A implements I {
    name: String
  }
  type B implements I {
    name: String
  }

  type Foo {
    whatever: String
    # An error will occur if and only if "I!" is changed to "B!".
    bar: I! @relationship(type: "MANDATORY", direction: OUT)
  }
`;

const driver = neo4j.driver(
  "bolt://localhost:7687/neo4j",
  neo4j.auth.basic("neo4j", "test")
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

neoSchema.getSchema().then(async (schema) => {
  const document = gql(`mutation Test {
      createFoos(input: {
        whatever: "test"
        bar: {
          connect: {
            where: {
              node: { name: "missing" }
            }
          }
        }
      }) {
        foos { whatever }
      }
    }`);
  const validationErrors = validate(schema, document);
  if (validationErrors.length > 0) {
    throw new Error(validationErrors);
  }

  const res = await execute({
    schema,
    document,
    contextValue: {},
  });
  console.log(JSON.stringify(res, null, 2));
});

```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hello @jroith, this is a known missing feature. We don't currently have any intention to change this in the library.

**Comment by jroith** [comment]
Is this particularly difficult to implement? It certainly looks like a bug to me, because it makes it easy to insert invalid data (in fact data that does not conform to the schema) and that data will cause queries to crash later.

**Comment by mjfwebb** [comment]
Unfortunately, it's not a simple one.

We would need to add a lot of extra reads after every write operation because a write operation won’t necessarily impact all possible interface implementations.

**Comment by jroith** [comment]
Would it not be sufficient to check through a cypher predicate if the edge with that name exists exactly once? In that case I don't see how it depends on what's going on in the interfaces that are being connected to. Obviously I must be missing something.

**Comment by jroith** [comment]
I have noticed that this also is true the other way around and so I can insert as many nodes on a n:1 or 1:1 connection as I want. All connections then exist in the database and on the GraphQL layer a random one (or the last one) appears. This is even worse.

**Comment by darrellwarde** [comment]
Let's take a look at some simple example type definitions.

```graphql
type Foo {
  foo: String!
  bar: Bar! @relationship(type: "HAS_BAR", direction: OUT)
}

interface Bar {
  bar: String!
}

type A implements Bar {
  bar: String!
}

type B implements Bar {
  bar: String!
}

type C implements Bar {
  bar: String!
}
```

If we were to use a nested create operation as the simplest example, for instance:

```graphql
mutation {
  updateFoos(
    where: { foo: "Foo!" }
    create: { bar: { node: { A: { bar: "Bar!" } } } }
  ) {
    foos {
      foo
    }
  }
}
```

In the above example, we have created a new `A` node from `Foo` nodes with `foo` equal to "Foo!". This mutation has absolutely zero context of the currently connected `B` nodes or `C` nodes. So in order to add cardinality checks for these situations, we would have to query every single relationship to all of the implementing types from the `Foo` nodes. The Cypher complexity would be very large, with potential performance impacts.

I hope this simple worked example helps highlight the complexities a little? It honestly might be easier for us to just say "given Neo4j does not natively support relationship cardinality enforcement, we only allow list relationships in the GraphQL Library".

**Comment by jroith** [comment]
Since the problem only occurs with interfaces it would be possible to throw if a schema contains a non-list relationship of an interface type. While not great it would at least avoid strange surprises.

Regarding your example, and without having looked at the generated cypher, I don't really understand why the code could not match against the existence of (x:Foo)-[:MANDATORY]->(y) and why the type or label on y would matter in this case.

**Comment by jroith** [comment]
I have tested this again, once with a type and once with an interface. When I use a type I get a piece of Cypher like:

```cypher
CALL {
 	WITH this0
 	MATCH (this0)-[edge_unique:MANDATORY]->(:B)
 	WITH count(edge_unique) as c
 	WHERE apoc.util.validatePredicate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDFoo.bar required exactly once', [0])
 	RETURN c AS create_this1_bar_B_unique_ignored
}
```

Now it seems possible to also insert the same check for the interface case:

```cypher 

CALL {
    CREATE (this0:Foo)
    SET this0.whatever = "foo"

    WITH *
    CREATE (this0_barB0_node:B)
    SET this0_barB0_node.name = "bar"
    MERGE (this0)-[:MANDATORY]->(this0_barB0_node)
    RETURN this0
}
CALL {
 	WITH this0
 	MATCH (this0)-[edge_unique:MANDATORY]->(:A|B|C|...)
 	WITH count(edge_unique) as c
 	WHERE apoc.util.validatePredicate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIREDFoo.bar required exactly once', [0])
 	RETURN c AS create_this1_bar_B_unique_ignored
}
CALL {
    WITH this0
    RETURN this0 { .whatever } AS create_var0
}
RETURN [create_var0] AS data

```

where either A|B|C enumerates the concrete types if the MANDATORY edge by itself is not the only possible edge:

```cypher 
 	MATCH (this0)-[edge_unique:MANDATORY]->(:(A|B|C|...))
```

or the constraint could simply be:

```cypher 
 	MATCH (this0)-[edge_unique:MANDATORY]->()
```

if the edge name by itself is unique. In this case the name of the interfaces doesn't seem to matter.

Would this not be a possible solution?

**Comment by darrellwarde** [comment]
As per some of my other comments you may have seen today, we aim to only support database native cardinality enforcement, which currently doesn't support this.
