### ISSUE TITLE
Missing takeover of custom directives for interfaces

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#4566]
**Describe the bug**

Custom directives for interfaces are not take over to augmented interface

**Type definitions**

Given the following schema (from the tests):

https://github.com/neo4j/graphql/blob/9b372bdc65752bcd6a4bf8ea2eb261ac0ddee948/packages/graphql/tests/schema/inheritance.test.ts#L27-L47

The following graphql is augmented:

```graphql
interface Person {
  friends(directed: Boolean = true, options: PersonOptions, where: PersonWhere): [Person!]! @customDirectiveField
  friendsConnection(after: String, directed: Boolean = true, first: Int, sort: [PersonFriendsConnectionSort!], where: PersonFriendsConnectionWhere): PersonFriendsConnection!
  name: String @customDirectiveField
}
```

But i would expect the  `Person` interface to have the directive `@customDirectiveInter` taken over from the source schema

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
