### ISSUE TITLE
plugins missing in Neo4jGraphqlConstructor

### ISSUE THREAD

**Issue by coupster74** [neo4j/graphql#4575]
**Describe the bug**
Much of the official documentation discusses plugins as a mechanism for adding capability, as shown here (https://neo4j.com/docs/graphql/current/migration/authorization/, or https://www.npmjs.com/package/@neo4j/graphql-plugin-auth) or below. I don't know if I missed it, but this doesn't seem to be the approach anymore, and I can't find any documentation which addresses this change and identifies the alternative approach. 

```javascript
import { Neo4jGraphQL } from "@neo4j/graphql";
import { Neo4jGraphQLAuthJWTPlugin } from "@neo4j/graphql-plugin-auth";

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    plugins: {
        auth: new Neo4jGraphQLAuthJWTPlugin({
            secret: "super-secret",
        }),
    },
});
```

I'm using: 
    "@neo4j/graphql": "^4.4.5",

Any guidance on where this is and where it's going would be appreciated. Not sure if this is an oversight?

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @coupster74. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @coupster74, actually on that first page you linked it documents the changes necessary to move from `plugins` to `features`

So if you had this before:

```ts
new Neo4jGraphQL({
    typeDefs,
    plugins: {
        auth: new Neo4jGraphQLAuthJWTPlugin({
            secret: "secret",
        }),
    }
})
```

You'd use this now:

```ts
new Neo4jGraphQL({
    typeDefs,
    features: {
        authorization: {
            key: "secret",
        }
    }
})
```
