### ISSUE TITLE
Error when using the typename filter with mutations

### ISSUE THREAD

**Issue by a-alle** [neo4j/graphql#4583]
**Describe the bug**
Unexpected error is thrown because typename is treated as a field.

**Type definitions**
```graphql
 interface Production {
                title: String!
                actors: [Actor!]! @declareRelationship
            }

            type Movie implements Production {
                title: String!
                runtime: Int!
                actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
            }

            type Series implements Production {
                title: String!
                episodeCount: Int!
                actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "StarredIn")
            }

            type ActedIn @relationshipProperties {
                screenTime: Int!
            }


            type StarredIn @relationshipProperties {
                episodeNr: Int!
            }

            type Actor {
                name: String!
                actedIn: [Production!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
            }
```

**To Reproduce**
1. Run mutation
```graphql
 mutation CreateActors {
        createActors(
              input: {
                name: "My Actor"
                actedIn: {
                  connect: {
                    edge: { screenTime: 10 }
                    where: { node: { title: "some movie", typename_IN: [Movie] } }
                  }
                }
              }
            ) {
              actors {
                name
              }
            }
          }
```
2. Notice error

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: [e.g. @neo4j/graphql@1.0.0]
* Node.js version: [e.g. 14.16.0]

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @a-alle. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @a-alle! :pray: We will now prioritise the bug and address it appropriately.
