### ISSUE TITLE
Authorization rules are not applied in nested Cypher fields

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4617]
**Describe the bug**
In the issue https://github.com/neo4j/graphql/issues/326 there was described a bug where the authorization was not applied for custom Cypher fields. For the top-level Cypher field, the User authorization is applied correctly, but if you query the User from another entity then the authorization is no longer applied.

**Type definitions**
```graphql
type Post {
    title: String
    likedBy: [User!]!
        @cypher(
            statement: """
            MATCH (user:User)
            RETURN user
            """
            columnName: "user"
        )
}

type User {
    id: ID
    email: String!
        @authorization(validate: [{ when: [BEFORE], operations: [READ], where: { node: { id: "$jwt.sub" } } }])
}
```

**To Reproduce**
Execute the following query:

```graphql
{
    posts {
        likedBy {
            email
        }
    }
}
```

**Expected behavior**
I should receive a Forbidden error with an Invalid JWT and the correct results with a valid one.
Authorization rules should be applied consistently between top-level and nested.

**System (please complete the following information):**

* OS: [macOS]
* Version: [4.4.5]
* Node.js version: [20.11.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
