### ISSUE TITLE
Filtering for non existing relationships does not work

### ISSUE THREAD

**Issue by megatrond** [neo4j/graphql#4667]
**Describe the bug**
When querying for items that have a relationship set to null, all the items are returned

**Type definitions**
```graphql
type MyThing {
    id: ID! @id
    stuff: MyStuff @relationship(type: "THE_STUFF", direction: OUT)
}

type MyStuff {
    id: ID! @id
    thing: MyThing @relationship(type: "THE_STUFF", direction: IN)
}
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Run a server 
2. Execute the following Mutation:
```graphql
mutation {
  createMyThings(input: [{}, {}, {}]) {
    myThings {
      id
      stuff {
        id
      }
    }
  }
  createMyStuffs(input: [{}, {}, {}]) {
    myStuffs {
      id
      thing {
        id
      }
    }
  }
}
```
3. Then run connect one of the things to one of the stuff:
```graphql
mutation {
  updateMyThings(
    where: { id: "THING_ID" }
    update: { stuff: { connect: { where: { node: { id: "STUFF_ID" } } } } }
  ) {
    myThings {
      id
      stuff {
        id
      }
    }
  }
}
```
4. Run this query:
```graphql
query {
  myThings(where: { stuff: null }) {
    id
    stuff {
      id
    }
  }
}
```
5. This returns all of the things, even the one that is connected to a stuff

**Expected behavior**
The thing with the stuff should not be returned

**System (please complete the following information):**

* OS: macOs
* Version: @neo4j/graphql@4.4.5
* Node.js version: v18.12.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @megatrond. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by megatrond** [comment]
Workaround for now:

- Activate aggregates on the relevant relationships
- Filter on `stuffAggregate: {count: 0}` instead

**Comment by darrellwarde** [comment]
Glad that there's some workarounds, but yes, it appears we completely omit the necessary filter in the Cypher when a `null` argument is specified! This is definition a regression, perhaps when we moved over to the new translation layer @MacondoExpress?

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @megatrond! :pray: We will now prioritise the bug and address it appropriately.

**Comment by MacondoExpress** [comment]
Confirmed and it is a regression, likely when we migrated to the new translation layer.  For a better context, the bug is related to the 1 to 1 relationship.
