### ISSUE TITLE
Incorrect Logical Operators used by relationship filters.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4704]
**Describe the bug**
The query:
```graphql
{
    actors(
        where: {
            actedInConnection_ALL: { node: { actorsConnection_ALL: { node: { name: "Keanu Reeves" } } } }
        }
    ) {
        actedIn {
            title
        }
    }
}
```
Produce the wrong results when `actedInConnection_ALL` is targeting an interface. 

**Type definitions**
```graphql

interface Show {
    title: String!
    actors: [Actor!]! @declareRelationship
}

type Movie implements Show {
    title: String!
    cost: Float
    runtime: Int
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

type Series implements Show {
    title: String!
    episodes: Int
    actors: [Actor!]! @relationship(type: "STARRED_IN", direction: IN, properties: "StarredIn")
}

type Actor {
    name: String!
    actedIn: [Show!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

type ActedIn @relationshipProperties {
    screenTime: Int
}

type StarredIn @relationshipProperties {
    episodes: Int
}
```

**To Reproduce**

Run the following query:
```graphql
{
    actors(
        where: {
            actedInConnection_ALL: { node: { actorsConnection_ALL: { node: { name: "Keanu Reeves" } } } }
        }
    ) {
        actedIn {
            title
        }
    }
}
```
The Cypher produced is:
```graphql
MATCH (this:Actor)
WHERE ((EXISTS {
    MATCH (this)-[this0:ACTED_IN]->(this1:Movie)
    WHERE (EXISTS {
        MATCH (this1)<-[this2:ACTED_IN]-(this3:Actor)
        WHERE this3.name = $param0
    } AND NOT (EXISTS {
        MATCH (this1)<-[this2:ACTED_IN]-(this3:Actor)
        WHERE NOT (this3.name = $param0)
    }))
} AND NOT (EXISTS {
    MATCH (this)-[this0:ACTED_IN]->(this1:Movie)
    WHERE NOT (EXISTS {
        MATCH (this1)<-[this2:ACTED_IN]-(this3:Actor)
        WHERE this3.name = $param0
    } AND NOT (EXISTS {
        MATCH (this1)<-[this2:ACTED_IN]-(this3:Actor)
        WHERE NOT (this3.name = $param0)
    }))
})) OR (EXISTS {
    MATCH (this)-[this4:ACTED_IN]->(this5:Series)
    WHERE (EXISTS {
        MATCH (this5)<-[this6:STARRED_IN]-(this7:Actor)
        WHERE this7.name = $param1
    } AND NOT (EXISTS {
        MATCH (this5)<-[this6:STARRED_IN]-(this7:Actor)
        WHERE NOT (this7.name = $param1)
    }))
} AND NOT (EXISTS {
    MATCH (this)-[this4:ACTED_IN]->(this5:Series)
    WHERE NOT (EXISTS {
        MATCH (this5)<-[this6:STARRED_IN]-(this7:Actor)
        WHERE this7.name = $param1
    } AND NOT (EXISTS {
        MATCH (this5)<-[this6:STARRED_IN]-(this7:Actor)
        WHERE NOT (this7.name = $param1)
    }))
})))
CALL {
    WITH this
    CALL {
        WITH *
        MATCH (this)-[this8:ACTED_IN]->(this9:Movie)
        WITH this9 { .title, __resolveType: \\"Movie\\", __id: id(this9) } AS this9
        RETURN this9 AS var10
        UNION
        WITH *
        MATCH (this)-[this11:ACTED_IN]->(this12:Series)
        WITH this12 { .title, __resolveType: \\"Series\\", __id: id(this12) } AS this12
        RETURN this12 AS var10
    }
    WITH var10
    RETURN collect(var10) AS var10
}
RETURN this { actedIn: var10 } AS this
```
As shown above, the approach used by the library is to generate every concrete entity an `EXISTS` subquery for each concrete entity implemented by the interface "Show". However, the logical operator used under the hood remains independent from the filter used.
This will produce incorrect data, as for the `_SOME` operator it will make sense that at least one implementation fulfills the predicate, and therefore seems correct to use the Logical Operator `OR`, but for the operator `_ALL` the expected behavior is that the predicate should be fulfilled by each concrete entity.

**Expected behavior**
The logical operator used should reflect the operation used:
- `ALL` ->  should be true across all the concrete entities
- `SOME` -> should be true for some concrete entites
- `SINGLE` ->  should be true exactly once
- `NONE` -> should be true across all the concrete entites

**System (please complete the following information):**

* OS: [e.g. macOS]
* Version: [@neo4j/graphql@4.5]
* Node.js version: [18.0.0]

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
