### ISSUE TITLE
Empty input types generated

### ISSUE THREAD

**Issue by process0** [neo4j/graphql#471]
**Describe the bug**

If a type has only list fields (? see additional context), then the generated type for `<C/U/D>Input` will be empty

**Type definitions**

```graphql
type Person  {
  pets: [Pet]
}

type Pet {
  name: String!
}
```

**To Reproduce**

Pass typedefs to `Neo4jGraphQL` and print the schema generated.  

```graphql
...

input PersonCreateInput

input PersonOptions {
  limit: Int
  offset: Int
}

input PersonUpdateInput

...
```

If you try to pass this schema to `ApolloServer` and error will occur:

```
Error: Input Object type PersonCreateInput must define one or more fields.

Input Object type PersonUpdateInput must define one or more fields.
```

**Expected behavior**
Input types should be generated

**Screenshots**

**System (please complete the following information):**

-   OS: [e.g. macOS, Windows]
-   Version: 2.0.1
-   Node.js version: 14.16.0

**Additional context**

I came across this while looking into https://github.com/neo4j/graphql/issues/221.  If I print the output of `buildSchema` with unused types left, then its clear that more input types that are empty exist, but are removed since they are unused.

```graphql

input PersonCreateInput

input PersonUpdateInput

input PersonDeleteInput

...

input PetDeleteInput
```

If this only applied to types that only have lists then its unclear why this happens to `PetDeleteInput`

**Comment by danstarns** [comment]
Hey, this is related to #269. From my view you should add a relationship directive onto `pets: [Pet]` like so: 

```
pets: [Pet] @relationship(type: "HAS_PET", direction: OUT)
```

**Comment by process0** [comment]
When I do this, there still is an empty type created.  I guess my question is given #221 and `composer.toSDL()` removing unused types,  is this an intentional choice and behavior or is this a bug that isn't known because `compose.toSDL` is removing the unused type?

**Comment by darrellwarde** [comment]
Hey @process0, I just tested this with the following type definitions:

```graphql
type Person {
    pets: [Pet] @relationship(type: "HAS_PET", direction: OUT)
}

type Pet {
    name: String!
}
```

And it worked as expected, producing the following `PersonCreateInput`:

```graphql
input PersonCreateInput {
    pets: PersonPetsFieldInput
}
```

Without the `@relationship` directive, we can't produce an input type, because each object type needs at least one scalar field or one relationship field. This is not a bug, more just a behaviour of the library.

**Comment by process0** [comment]
@darrellwarde, the example schema does work as expected.  When examining #221 to see if it was possible to keep unused types, I noticed empty input types generated that were automatically removed due to `composer.toSDL` removing unused types.  In the example schema you used, `input PetDeleteInput` is an empty input type generated but automatically removed in the generated schema.

```gql
input PetCreateInput {
  name: String!
}

input PetUpdateInput {
  name: String
}

input PetDeleteInput
```

> Without the `@relationship` directive, we can't produce an input type, because each object type needs at least one scalar field or one relationship field. This is not a bug, more just a behaviour of the library.

This clears it up, thanks!
