### ISSUE TITLE
Unknown function 'apoc.date.convertFormat' [Solved]

### ISSUE THREAD

**Issue by turbothinh** [neo4j/graphql#472]
**Describe the bug**
I follow [this course](https://neo4j.com/graphacademy/training-graphql-apis/02-graphql-apis-overview-of-neo4j-graphql/) 
and connect to my Neo4j Desktop DB version 4.2.1. When I run `createReviews` mutation, it returns
```
"message": "Unknown function 'apoc.date.convertFormat' (line 20, column 36 (offset: 480))\n\"    RETURN count(*) AS `count(*)`\"\n                       ^"
```
If I switch to the Sandbox one, the operation works. The `@neo4j/graphql` version in the tutorial is `1.0.0`, it is the same behavior if I update to the latest `2.1.0`. This behavior occur also when I tried the example `neo-push` and connecting to the desktop DB.

**To Reproduce**

1. Run a server with the [this code](https://codesandbox.io/s/github/johnymontana/training-v3/tree/master/modules/graphql-apis/supplemental/code/02-graphql-apis-overview-of-neo4j-graphql/begin?file=/.env)
2. Connect to your Neo4j desktop DB 4.2.1
3. Then run the following Query
```
mutation {
  createBooks(
    input: {
      isbn: "1492047686"
      title: "Graph Algorithms"
      price: 37.48
      description: "Practical Examples in Apache Spark and Neo4j"
    }
  ) {
    books {
      isbn
      title
      price
      description
      __typename
    }
  }
}

mutation {
  createReviews(
    input: {
      rating: 5
      text: "Best overview of graph data science!"
      book: { connect: { where: { title: "Graph Algorithms" } } }
    }
  ) {
    reviews {
      rating
      text
      createdAt
      book {
        title
      }
    }
  }
}
```

**Expected behavior**
Mutation succeed

**System (please complete the following information):**

-   OS: macOS
-   Version: @neo4j/graphql@1.0.0, @neo4j/graphql@2.1.0
-   Node.js version: 14.17.1

**Comment by turbothinh** [comment]
Updated the DBMS to 4.3.3 and still same error

**Comment by turbothinh** [comment]
Now solved by installing ** APOC** plugin. Would be great if we can add this to the tutorial/docs. Maybe we should consider adding this plugin to the core DB engine, given that the official tools are using these extensively?

Feel free to close this PR :)

**Comment by darrellwarde** [comment]
It is actually in the requirements section of the docs: https://neo4j.com/docs/graphql-manual/current/introduction/#_requirements

Regarding moving things like this to the core DB engine, that is a much _much_ longer play, but indeed something which would be great!
