### ISSUE TITLE
Connecting a node multiple times to another node doesn't work when creating

### ISSUE THREAD

**Issue by megatrond** [neo4j/graphql#4739]
**Describe the bug**
When trying to connect a node to a different node multiple times, we get an error.

**Type definitions**
```graphql
type MyThing {
    id: ID! @id
    stuff: [MyStuff!]! @relationship(type: "THE_STUFF", direction: OUT)
}

type MyStuff {
    id: ID! @id
    thing: [MyThing!]! @relationship(type: "THE_STUFF", direction: IN)
}
```

**To Reproduce**

1. Create a `MyStuff` with the following mutation:
```graphql
mutation {
  createMyStuffs(input: {}) {
    myStuffs {
      id
    }
  }
}
```
2. Then try to create a thing, while connecting it to the stuff (using the id from the previous mutation) twice:
```graphql
mutation {
  createMyThings(
    input: {
      stuff: {
        connect: [
          {
            where: { node: { id: "4e8baf75-3313-4b18-9e97-54635df89bb7" } }
            overwrite: false
          }
          {
            where: { node: { id: "4e8baf75-3313-4b18-9e97-54635df89bb7" } }
            overwrite: false
          }
        ]
      }
    }
  ) {
    myThings {
      id
      stuff {
        id
      }
    }
  }
}
```
4. The api returns the following error:
```
{
  "errors": [
    {
      "message": "MyThing.stuff required exactly once for a specific MyStuff",
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ],
      "path": [
        "createMyThings"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Neo4jGraphQLRelationshipValidationError: MyThing.stuff required exactly once for a specific MyStuff",
          "    at Executor.formatError (/Users/user/projects/n4j-issue/node_modules/@neo4j/graphql/dist/classes/Executor.js:86:24)",
          "    at Executor.execute (/Users/user/projects/n4j-issue/node_modules/@neo4j/graphql/dist/classes/Executor.js:73:24)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async execute (/Users/user/projects/n4j-issue/node_modules/@neo4j/graphql/dist/utils/execute.js:28:20)",
          "    at async Object.resolve [as createMyThings] (/Users/user/projects/n4j-issue/node_modules/@neo4j/graphql/dist/schema/resolvers/mutation/create.js:35:31)"
        ]
      }
    }
  ],
  "data": null
}
```
**Expected behavior**
We expected this to add two relationships from the thing to the stuff

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@4.4.5
* Node.js version: 18.12.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @megatrond. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by megatrond** [comment]
I also tried this with the following typedefs:

```graphql
type MyThing {
    id: ID! @id
    stuff: [MyStuff!]! @relationship(type: "THE_STUFF", direction: OUT, properties: "MyStuffDetails")
}

type MyStuff {
    id: ID! @id
    thing: [MyThing!]! @relationship(type: "THE_STUFF", direction: IN, properties: "MyStuffDetails")
}
interface MyStuffDetails @relationshipProperties {
    seconds: Int!
}
```

and this mutation:

```graphql
mutation {
  createMyThings(
    input: {
      stuff: {
        connect: [
          {
            where: { node: { id: "732e5c95-6852-485b-a72b-705965df11ed" } }
            edge: {seconds: 2}
            overwrite: false
          }
          {
            where: { node: { id: "732e5c95-6852-485b-a72b-705965df11ed" } }
            edge: {seconds: 4}
            overwrite: false
          }
        ]
      }
    }
  ) {
    myThings {
      id
      stuff {
        id
      }
    }
  }
}
```

with identical results (error)

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @megatrond! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment]
This is the intended behaviour, as multiple relationships of the same type between 2 nodes is not support. However, the error message could be improved to make it clear this behaviour

**Comment by megatrond** [comment]
> This is the intended behaviour, as multiple relationships of the same type between 2 nodes is not support. However, the error message could be improved to make it clear this behaviour

Hi @angrykoala 

Then we have definitely been confused - I was under the impression that the purpose of the required `overwrite` boolean was to support multiple relationships of this sort. If not - what is the purpose of this property on the connection mutations?

This also seems to be implied in this comment on a different issue: https://github.com/neo4j/graphql/issues/610#issuecomment-1460533192 but maybe I'm misunderstanding something?

**Comment by angrykoala** [comment]
The purpose is to either throw an error or rewrite existing connection

The confusion is understandable, we need to update our documentation on that matter
