### ISSUE TITLE
Support `Order By` for cypherFields

### ISSUE THREAD

**Issue by rcbevans** [neo4j/graphql#474]
There are many situations where it is desirable to be able to sort results based on the result of a traversal, for example, sort posts by most comments/most recently commented, or authors by most upvoted post, or most recent post.

Currently, the GraphQL library does not generate `<Type>Sort` inputs which include cypherFields.  Cypher is a very natural way for developers to implement arbitrary traversals to grab descendant fields, count edges, etc and it would therefore make a great deal of sense to be able to sort on the result of these fields.

It is possible to hack around the problem by denormalizing data into properties on the node you wish to filter on, but if the data itself is dynamic and changes often, keeping the de-normalized data up to date could be a problem.

**What I'd like**
Cypher Fields which return **primitive** types should appear in the augmented schema allowing callers to .sort based on that value

**Describe alternatives you've considered**
I tried working around the problem by denormalizing, but this requires all mutations go through a custom mutation to ensure the denormalized field is kept up to data as data changes.  Alternatively, custom queries need to be written just to implement the sorting.  This then requires re-implementing all of the auth checks, or where filters manually and is really a last resort.

**Additional context**
Locally I was able to get sorting on cypher fields working by making the following changes:

- Update [make-augmented-schema.ts](https://github.com/neo4j/graphql/blob/master/packages/graphql/src/schema/make-augmented-schema.ts#L473) to include `...node.cypherFields` in `sortFields` on L473
- Update [translate-read.ts](https://github.com/neo4j/graphql/blob/master/packages/graphql/src/translate/translate-read.ts#L148) to return the `sortStr` *after* `RETURN`, and remove `WITH ${varName}` since `this` is included in `sortStr` already, and the cypherField is resolved within a result named `this` already.

I haven't made the change in the full repo and run all of the integration tests (I'm sure many will fail due to the lines being reordered, even if functionally it would be the same; but I don't know for sure if reordering the query in this way (particularly removing the WITH) is likely to cause any actual issues.

@danstarns @darrellwarde Would love if we could sync up on this; it's another blocking feature I really need so am more than willing to contribute the code change myself to get it done ASAP.

**Comment by dmoree** [comment]
@rcbevans I was also interested in sorting by cypher fields although it is not a blocking feature for me, but I went ahead and implemented the changes you suggested here: https://github.com/neo4j/graphql/compare/master...dmoree:feature/sort-by-cypher-field

One problem is that if you do not have the cypher field in your selection set then it does not get projected. The sort will still be there and will fail silently.

**Comment by rcbevans** [comment]
@dmoree that's awesome, did you notice any issues in the integration tests with the change?

I noticed that the filter field needs to be in the projection, whilst ideally it should work either way, at least to me, the value add of being able to sort on the field outweighs the burden of meeting to remember to return it in the orojection.

One possibility could be moving the projection, including all cypher fields earier on the query, filtering/ordering, then returning a final projection.

It would be great as a next step if it was also possible to apply where filters to cypher fields, but based on my quick look at the code it didn't seem as obvious how to do it (in an unintrustive way).

**Comment by rcbevans** [comment]
@dmoree I checked out your branch and it looks great!

I've included the change in a forked package I'm publishing, if you wanted to try it out: https://www.npmjs.com/package/@pandaai/graphql-fork.  I've just pulled in the package and am giving it a try.

**Comment by dmoree** [comment]
The integration tests were fine only the obvious TCK test change.

I'm not sure what you mean about moving the projection. Could you elaborate on this? Perhaps there is some way to add the field using `fieldsByTypename`. Either way it should probably look through the `resolveTree.args.options` and pick out all fields that are `@cypher` fields and add them (somehow) to the selection set before translation.

There is a mention of this limitation in [Cusom Resolvers](https://neo4j.com/docs/graphql-manual/current/custom-resolvers/)

> Due to the nature of the Cypher generation in this library, you must query any fields used in a custom resolver. For example, in the first example below calculating fullName, firstName and lastName must be included in the selection set when querying fullName. Without this being the case, firstName and lastName will be undefined in the custom resolver.

A similar note on sorting may suffice; it would save the trouble.

**Comment by dmoree** [comment]
@rcbevans That's great. You could see if it has any major limitations, but maybe more people could benefit from its own PR. @danstarns @darrellwarde should probably speak more to that.

**Comment by rcbevans** [comment]
Hmmm, have been trying to test the latest package I published, but something seems to have broken auth;   I don't see what could have caused the issue in your change, but I see the commits from the neo4j repo were added to my previous ANY/ALL branch, so having to look into those...

**Comment by rcbevans** [comment]
@darrellwarde were there any changes in commits 365a41f725cf4f5808db2a4163ea08fc4810264f, a0b7d413826c512227f04f36ee47fa99a5885f17, or 4d8a4666b6316381b768805a1f4d968c5b2f0dc3 relating to auth rules/validation.  Since updating the package today every request is giving me an `Neo.ClientError.Security.Unauthorized` error.

I added a new simple query:

```
type Query {
    myRoles: [String!] @cypher(statement: "RETURN $auth.roles") @auth(rules: [{allowUnauthenticated: true}])
}
```

And even this query is returning unauthorized.

I haven't changed anything in the middlewares in terms of how claims are being passed to the context:

```
    context: (opts) => {
      const { req, res } = opts;

      // Fetch/Create a Neo4j driver for the database using the right creds
      const driver = getDriver(res.locals.orgId as string);

      return {
        req,
        driver,
        database: NEO4J_DB_NAME,
        // Pass the decoded JWT claims through for
        // GraphQL library to use in auth checking
        jwt: res.locals.claims,
      };
    },
```

**Comment by dmoree** [comment]
Looks like they upgraded the driver in https://github.com/neo4j/graphql/commit/a0b7d413826c512227f04f36ee47fa99a5885f17. Did you install this and open up the right neo4j instance? I’m not seeing any errors if that helps.

**Comment by rcbevans** [comment]
> Did you install this and open up the right neo4j instance

I need to go for a walk... Just spent 1.5 hours trying to figure out what the hell was going on.

... I still had my graphql library dev instance running, so the creds for the db were wrong, hence, forbidden.

![image](https://user-images.githubusercontent.com/2041260/132409944-31af09f5-ee7e-4e96-a48d-9726a0a24d14.png)

**Comment by rcbevans** [comment]
Anyway, back to your previous question, 

> I'm not sure what you mean about moving the projection.

The generated query for a type looks something like:

```
MATCH (this:Type)
WHERE <where filters> AND <auth where>
CALL apoc.util.validate(<auth roles>)
RETURN this { <projections> } as this
ORDER BY <order by clauses>
```

To support filtering on cypher fields, the projection which resolves the cypher fields needs to be done not in the RETURN statement, but earlier in a WITH such that it can then have a WHERE filter attached.

I think that would look something like adding a 

```
WITH this { <projection> } as this
WHERE <cypher field filter>
RETURN this
ORDER BY ...
```

or whatever the valid cypher syntax would be for it.  This might require splitting where statements based on if they're cypher fields or not, and doing non-cypher fields first, as is currently done, then, for any cypher field filters, inserting the additional `WITH WHERE`.

It seems like a bit more of an involved change.  The existing filter generation is pretty flexible and so it's not something that I think is a blocking issue, but it could be nice to have.

For example, given a blog post with text content, if you have a full text index on the content, you could have a cypher field that returns a boolean where a particular key phrase matches, and filter the resulting posts based on that.  (I don't know if the existing filter for `text_CONTAINS` will hit full text indices to find matches?

**Comment by rcbevans** [comment]
@dmoree I've been using your fix for ordering by custom cypher and it's working great.  I didn't see a PR up with the change to get it mainlined, did you plan on doing that?

**Comment by dmoree** [comment]
I can create a PR for this.

**Comment by darrellwarde** [comment]
Sorry for the radio silence on this one - if you have a solution to contribute then we will of course happily accept following review! 😃

**Comment by cramatt** [comment]
@darrellwarde I'm looking for a similar impl with `where` filter on `@cypher` Fields - I searched but didn't find a ticket... do you know of a ticket covering this? Or should I create a new issue? (Or perhaps this is available in 2.x library - we have not yet upgraded).

**Comment by cramatt** [comment]
Example

```graphql
type Animal {
  id: ID!
  eye_count: Int
  is_multi_eye: Boolean @cypher(statement: "MATCH (this) RETURN this.eye_count > 1")
```

```graphql
query test {
  animals(where: {is_multi_eye_EQ: true}) {
    id
  }
}
```
