### ISSUE TITLE
Named aggregate property always returns null 

### ISSUE THREAD

**Issue by mabalik** [neo4j/graphql#4759]
**Describe the bug**
If you want to name an aggregate field in a query, null is always returned

**Type definitions**
```graphql
type Node2 {
    uuid: ID! @id
    name: String!
    active: Boolean!
    node: Node1 @relationship(type: "HAS_NODE", direction: OUT)
}

type Node1 {
    uuid: ID! @id
    name: String!
    nodes: [Node2!]! @relationship(type: "HAS_NODE", direction: IN)
}
```
**To Reproduce**
Add activeNodes:  as name to nodesAggregate 

**Example**
```graphql
query Node1 {
  node1 {
    uuid
    name
    activeNodes: nodesAggregate(where: {active: true}) {
      count
    }
  }
}
```

activeNodes is always null

```graphql
query Node1 {
  node1 {
    uuid
    name
    nodesAggregate(where: {active: true}) {
      count
    }
  }
}
```

nodesAggregate.count = correct count of nodes

**Expected behavior**
activeNodes return the correct count

* OS: [e.g. macOS, Windows]
* Version: @neo4j/graphql: 4.4.5
* Node.js version: ^20

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mabalik. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @mabalik 
I haven't been able to reproduce the problem. I have tried both on version `4.4.5` and on 5.0.0 of the library, as well as Neo4j 4 and 5

I opened the PR #4780 validating this use case, which is currently passing. I'll be closing this issue once the PR is merged, please, let me know if I missed something in that test or there may be something else I may try
