### ISSUE TITLE
Error: SortDirection values must be an object with value names as keys

### ISSUE THREAD

**Issue by TheMaximeBatandeoExperience** [neo4j/graphql#4774]
**Describe the bug**
Error: SortDirection values must be an object with value names as keys. This line `await schema.getSchema()` triggers the error whatever the typeDefs I define 

**Type definitions**
```ts
type Movie {
    title: String
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}

type Actor {
    name: String
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

**To Reproduce**
```ts
const driver = neo4j.driver(NEO4J_URI, neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD));

const schema = new Neo4jGraphQL({
  typeDefs,
  driver
});

const yogaSchema = await schema.getSchema();
```

then you see the error Error: SortDirection values must be an object with value names as keys so the schema is undefined

**Expected behavior**
I should have a schema

**System (please complete the following information):**

* OS: Github codespace
* Version: @neo4j/graphql": "^5.0.0",
* Node.js version: v20.11.0

**Additional context**
I try with the version 4 or 3 and I have the same issue
"graphql": "^16.8.1",
"graphql-yoga": "^5.1.1",
"neo4j-driver": "^5.17.0",

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @TheMaximeBatandeoExperience. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @TheMaximeBatandeoExperience, I can't reproduce this issue locally. Are you able to provide a full code-example which reproduces this issue?

**Comment by TheMaximeBatandeoExperience** [comment]
Yes, thank you for your quick answer

```ts
import {getNeo4JSession} from "./neo4j";
import {Neo4jGraphQL} from "@neo4j/graphql";

export const neoSchema = async () => {
  try {
    const {driver} = await getNeo4JSession();
    const schema = new Neo4jGraphQL({
      typeDefs: `#graphql
    type Movie {
        title: String
        actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
    }

    type Actor {
        name: String
        movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
    }
`,
      driver
    });
    const yogaSchema = await schema.getSchema();
    return yogaSchema;
  } catch (error) {
    console.error("Error initializing schema", error);
  }
};
```

I use it a nextJs 14 AppRouter. So i created a route api/graph/route.ts where my yoga server lives using the implementation in the yoga documentation 

```ts
import { createSchema, createYoga } from 'graphql-yoga'
 
const { handleRequest } = createYoga({
  schema: await neoSchema()
    }
  }),
 
  // While using Next.js file convention for routing, we need to configure Yoga to use the correct endpoint
  graphqlEndpoint: '/api/graphql',
 
  // Yoga needs to know how to create a valid Next response
  fetchAPI: { Response }
})
 
export { handleRequest as GET, handleRequest as POST, handleRequest as OPTIONS } 
```

Also I tried with apollo server and same trouble. 
I am not sure that it is relevant but from the beginning I always had a Typescript error with the schema provided by Neo4jGraphQl (with Apollo or Yoga)
Unable to assign 'GraphQLSchema | undefined' au type 'YogaSchemaDefinition<{}, {}> | undefined Missing isPossibleType

**Comment by angrykoala** [comment]
Hi @TheMaximeBatandeoExperience 
Sorry, but the code you provided doesn't seem correct as it is invalid javascript  (maybe a copy paste problem?).

Please refer to [this example](https://github.com/neo4j/graphql/blob/d660be856a302fc229a147312d86b41128e7f2f1/examples/subscriptions/yoga_sse/server.js#L47) on how to set up a yoga server with Neo4j GraphQL (you can ignore the typedefs and the subscription on that example), I just checked that example and the js code should work.

For how to integrate yoga with NextJS you'll need to refer to either one of those projects.

**Comment by TheMaximeBatandeoExperience** [comment]
I finally found the reason of the bug. I am using a monorepo and there were conflicts between versions of GraphQl (16.8 and 15.8). In graphQl-tools, there was a deprecation with the field isPossibleType which led to an invalid schema. The fix was to upgrade graphql at the root of the monorepo and it worked
