### ISSUE TITLE
The `empyInput` flag is ignored during creation.

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#4838]
**Describe the bug**

As my title, if you try to create a node with the emptyInput set a true, the `emptyInput` flag is ignored and instead is written the database.

**Type definitions**

```graphql
type Test {
  test(value: Boolean): Boolean! @cypher(statement: "RETURN $value as value", columnName: "value")
}
```

**To Reproduce**
With the above typeDefs run the below:
```graphql
mutation Mutation {
  createTests(input: { _emptyInput: true }) {
    tests {
      test
    }
  }
}
```

**Expected behavior**
`emptyInput` should not be stored in the `Test` node.

**System (please complete the following information):**

* OS:  macOS
* Version: @neo4j/graphql@5.1.0
* Node.js version: 20.11.0

**Additional context**
Here the Debug log:
**Normal Create**
```cypher
CALL {
WITH [] AS meta
CREATE (this0:Test)
SET this0._emptyInput = $this0__emptyInput
WITH *, meta + { event: "create", id: id(this0), properties: { old: null, new: this0 { .* } }, timestamp: timestamp(), typename: "Test" } AS meta
RETURN this0, meta AS this0_meta
}
WITH this0, this0_meta AS meta
CALL {
    WITH this0
    CALL {
        WITH this0
        CALL {
            WITH this0
            WITH this0 AS this
            RETURN NULL as value
        }
        WITH value AS create_this0
        RETURN create_this0 AS create_var1
    }
    RETURN this0 { test: create_var1 } AS create_var2
}
RETURN [create_var2] AS data, meta
```
**Unwind Create**

```cypher
UNWIND $create_param0 AS create_var0
CALL {
    WITH create_var0
    CREATE (create_this1:Test)
    SET
        create_this1._emptyInput = create_var0._emptyInput
    
    RETURN create_this1
}
CALL {
    WITH create_this1
    CALL {
        WITH create_this1
        WITH create_this1 AS this
        RETURN NULL as value
    }
    WITH value AS create_this2
    RETURN create_this2 AS create_var3
}
RETURN collect(create_this1 { test: create_var3 }) AS data
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
