### ISSUE TITLE
Objects fully defined by custom queries should not throw warnings about unresolved fields. 

### ISSUE THREAD

**Issue by dumitru-marian-barbu** [neo4j/graphql#4843]
### Type definitions

```GraphQL
extend schema @mutation(operations: []) @subscription(events: [])

type Movie @query(read:false) {
    actors: [Actor!]!
}

type Actor {
   name: String
}

type Query {
   getMovies():[Movie!]!
}
```

### Steps to reproduce

1. Generate schema or use OGM for type generation
2. Warning "Object types need a way to be resolved for field:  actors" is received 

### What happened

Consider we have a type of object that is fully returned by a custom query. Let's say that object is the Movie we have above. Our getMovies is implemented by a custom query that fully returns the object:

```ts
module.exports = {
  Query: {
      getMovies: getMoviesImplementationFunction,
   }
}
```

When upgrading from 4.4.5 to 5.1.0 for neo4j/graphql and neo4j/graphql-ogm, we get a warning when building schema or generating types using OGM that the actors field does not have a way to be resolved.  

We are using `@query(read:false)` to avoid having the query autogenerated and thus have full control over it's implementation.  We're also not generating any mutations. Thus,  we would expect not to have that warning thrown in this scenario. 

### Expected behaviour

No warning thrown, as it behaved in 4.4.5

### Version

5.1.0

### Database version

4.4

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @dumitru-marian-barbu. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
Hi @dumitru-marian-barbu ,
Thank you for the report, we confirmed that the warning is thrown we put it as low priority as it's not blocking and no workaround is required for this case.

**Comment by jdzak** [comment]
@dumitru-marian-barbu Have you figured out any ways to work around this issue? I'm experiencing this and the warnings are making our tests very verbose and it's hard sorting though the noise to find the issue.

**Comment by dumitru-marian-barbu** [comment]
No, I have not figured out any work arounds. The logs are getting longer as our data model expands and indeed add a lot of noise. I'm hoping for a fix or some way to disable them soon.

**Comment by to-kn** [comment]
@angrykoala any info on this, since we have the same problem as the others above - making tests and logs unnecessaryly long and verbose :)
Thanks a lot for the great work and effort put in this library!

**Comment by angrykoala** [comment]
Hi @to-kn 
Sorry, still no news. @MacondoExpress and I will discuss this today to see how to improve this. Thanks for your patience :pray:

**Comment by angrykoala** [comment]
After a discussion, we decided to put the validation warnings under the `DEBUG=@neo4j/graphql:graphql` environment variable. This means that it will not appear by default

Note that this is a workaround to avoid this verbosity at the moment, and we may change this behaviour when we do a more through work on error and warning handling

**Comment by to-kn** [comment]
thanks a lot @angrykoala  - but your commit was reverted?

**Comment by Liam-Doodson** [comment]
> thanks a lot @angrykoala - but your commit was reverted?

No it's not been reverted. That was just a miss click by me
