### ISSUE TITLE
Fields relational/cypher fields are not resolved for custom queries/mutations returning Interfaces or Unions

### ISSUE THREAD

**Issue by rcbevans** [neo4j/graphql#487]
**Describe the bug**
Related nodes, cypher fields are not resolved on interface/union types returned by custom cypher fields/mutations.  Queries/Mutations returning concrete types *do* correctly have requested fields and edges traversed for use in the response.

**Type definitions**
Given a simple schema:

```

type Author {
    name: String!  @relationship(type: "WROTE", direction: OUT)
}

type Director {
    name: String! @relationship(type: "DIRECTED", direction: OUT)
}

interface ThingWithTitleInterface {
    title: String!
}

type Book implements ThingWithTitleInterface {
   title: String!

    author: Author! @relationship(type: "WROTE", direction: IN)
    numberOfPages: Int!
}

type Movie implements ThingWithTitleInterface {
    title: String!

    director: Director! @relationship(type: "DIRECTED", direction: IN)
    runtime: Int!
}

union ThingWithTitle: Book | Movie

type Query {
    getByTitle(title: String!): [ThingWithTitle!] @cypher(statement: "<cypher query>")
    
    **** OR ****

    getByTitle(title: String!): [ThingWithTitleInterface!] @cypher(statement: "<cypher query>")
}
```

I should be able to call with a query like:

```
getByTitle(title: "Jurassic Park") {
    title
    ... on Book {
        author {
           name
       }
        numberOfPages
    }
    ... on Movie {
        director {
           name
       }
        runtime
    }
}
```

however, the call throws an error:

`Cannot return null for non-nullable field Movie.director`

Looking at the cypher being generated:

```
WITH apoc.cypher.runFirstColumn("<cypher query>", {auth: $auth, input: $input}, false) as x
                UNWIND x as this
                WITH this


RETURN this  AS this
```
It is clear that no attempt is being made to resolve connected edges, either director, or author, whichever concrete type is returned by `getByTitle`.

Fields and relationships *are* correctly evaluated *IFF* a concrete type is returned by the custom query or mutations, for example a custom query returning a specific Book or Movie.

**Expected behavior**
The GraphQL Library should correctly resolve and return data as requested by the caller.

GraphQL library is correctly populating the types, for example, Apollo GraphQL Sandbox correctly provides auto completion for fields provided by an interface, when the return type of the query is an interface.  If a custom query or mutation returns an interface or union type, the child fields should be correctly resolved *even if* that means a second call to Neo4j needs to be made based on the runtime resolved type.

At the very least, *interface* fields, including relationships, should be resolved correctly if an interface type is returned.

**Comment by rcbevans** [comment]
Looking into the code, the entry point for a top level cypher field/mutation is [cypher.ts](https://github.com/neo4j/graphql/blob/master/packages/graphql/src/schema/resolvers/cypher.ts#L64) and I can see that on line 63/64, the code is checking if the type being returned by the field is a concrete type as declared in the schema.

IFF the type is concrete, createProjectionAndParams is called to generate the appropriate projections to continue resolving child connections or cypher queries.

If not a concrete type, but instead a union, or interface, this code is skipped, no projection is used, and the GraphQL call will fail.

**Comment by oskarhane** [comment]
Do you think https://github.com/neo4j/graphql/pull/376 would fix this issue @rcbevans ?

**Comment by rcbevans** [comment]
@oskarhane looks like it.

I'll take a better look at the PR later and can see about pulling it into my test package to verify.

It does seem that this PR misses continuing to resolve fields on unions returned by cypher fields on types.  There is similar logic checking the node reference type in translate-read when generating the projection for cypher fields.  Can also double check that later.

**Comment by rcbevans** [comment]
As I suspected, #376 misses the resolution of cypher fields within a projection.  Exactly the same `NodeReference` check is done in [create-projection-and-params](https://github.com/neo4j/graphql/blob/master/packages/graphql/src/translate/create-projection-and-params.ts#L184)

The same change to check for a union should be reusable here to also resolve cypher fields returning unions *on* types correctly.

**Comment by AccsoSG** [comment]
@rcbevans Has the problem been solved for interfaces as well? In the related issues and merge requests, only unions are mentioned, not interfaces.

**Comment by rcbevans** [comment]
I'm still on a forked version of the library from a few months ago where I made some specific fixes to issues I was running into, so I'm not sure of the level of support for interfaces in the latest code.

I do recall seeing PRs for resolving fields on interfaces, though don't know if that's in all situations where an interface could be returned, or only specific scenarios.

**Comment by AccsoSG** [comment]
@danstarns I think this ticket isn't ready yet because cypher support for interfaces hasn't been implemented yet. The related PR #495 applies only to unions. I tried to solve the problem myself in my fork (see: https://github.com/AccsoSG/graphql/commits/dev). The implementation is similar to that for unions. It generally works, but I don't know enough about the code to safely submit a pull request. Should I create a new feature request for this topic first to discuss it?

**Comment by danstarns** [comment]
> @danstarns I think this ticket isn't ready yet because cypher support for interfaces hasn't been implemented yet. The related PR #495 applies only to unions. I tried to solve the problem myself in my fork (see: https://github.com/AccsoSG/graphql/commits/dev). The implementation is similar to that for unions. It generally works, but I don't know enough about the code to safely submit a pull request. Should I create a new feature request for this topic first to discuss it?

Hey, @AccsoSG go. Firstly Thank you. Then please do make a pull request, it will make it easier for the team to see your changes and work with you to get it mergeable.
