### ISSUE TITLE
`@populatedBy` does not work in conjunction with `DateTime` data type: callback function is not called

### ISSUE THREAD

**Issue by andreloeffelmann** [neo4j/graphql#4886]
**Describe the bug**
The `@populatedBy` directive does not work if the field the directive is declared for has the `DateTime` datatype. The callback function never gets called.

**Type definitions**
````graphql
type Request {
  status: Status!
  approvedAt: DateTime @populatedBy(callback: "setApprovedAtTimestampCallback", operations: [UPDATE])
}

enum Status {
  REQUESTED,
  APPROVED
}
````

**To Reproduce**

1. Declare the callback function:
````javascript
const setApprovedAtTimestampCallback: async (root, _parent, _args, context) => {
        return root.status === 'APPROVED' ? new Date().toISOString() : null;
},
````
2. Execute the following Mutation...
````graphql
mutation {
updateRequests(update: { status: APPROVED }){ info { nodesCreated } }
}
````
3. See error: the callback function is never called

**Expected behavior**
The callback function should be called and invoked as described in the docs.

**System:**
* Version: @neo4j/graphql@5.2.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @andreloeffelmann. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
Hi @andreloeffelmann , 
You're right DateTime is not supported by the populatedBy, populatedBy is supported only on primitive fields.
We'll update the documentation to reflect this as it's currently not clear that the `@populatedBy` directive can be used only on primitive fields.
I'll put the label `feature request` so that we can discuss and prioritize the development.

**Comment by andreloeffelmann** [comment]
Hi @MacondoExpress , thanks for the clarification.
I can understand that `populatedBy` is intended for primitive fields only. However, from the API's consumer point of view, a `DateTime` is just a `String` when passing it via GraphQL input fields. 
It would be nice if this was supported :-)

**Comment by MacondoExpress** [comment]
I see and I agree it should not be hard to actually support `@populatedBy` for complex types, we will have to coerce the callback returned value or instruct the users to return the driver wrapper in case of temporal types and spatial types.

**Comment by andreloeffelmann** [comment]
Thanks guys for solving this 👍🏻
