### ISSUE TITLE
Subscriptions do not reliably return strings or numbers for ids

### ISSUE THREAD

**Issue by angrykoala** [neo4j/graphql#4890]
**Describe the bug**

When running the test `integration/subscriptions/create-relationship/create.int.test.ts` in Aura, some expectations fail as a string is returned instead of a number for ids. This may be caused by the ID being a BigInt (e.g. `1152963286048703328`) instead  of the usual increment in the tests (e.g. `62`).

Subscriptions parsing seem to return number or string to the plugin

Note: The test mentioned has been changed to use `expect.anything()` instead of `expect.any(Number)` to avoid flakyness in Aura.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @angrykoala. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @angrykoala! :pray: We will now prioritise the bug and address it appropriately.
