### ISSUE TITLE
Custom query names 

### ISSUE THREAD

**Issue by dumitru-marian-barbu** [neo4j/graphql#4924]
When migrating from neo4j-graphql-js to neo4j/graphql, query names have been changed from first letter upper case type name (for example Movie) to lower case and plural (for example movies). This creates a lot of load because all clients need to be updated to cover these changes. Even more, generated typescript  type names for query parameters also change, so we get different types that have the same fields and thus those also need to be updated. 

Our request is a way to specify a custom name for the generated query (so we can specify the names we used to have). One way this could be done is by adding a new optional field to the @query annotation that allows us to specify the name.

**Comment by darrellwarde** [comment]
Hey @dumitru-marian-barbu, sorry if it's not what you want to hear, but we don't have an appetite for this. Whilst it is a "migration", these are two completely different libraries and not just different versions. There are open source tools which can be used to rename GraphQL fields, and I would recommend looking into them. For example, https://the-guild.dev/graphql/tools/docs/api/modules/wrap_src
