### ISSUE TITLE
Field with populatedBy directive should appears in UpdateInput or CreateInput when not defined in the operations 

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#4991]
**Describe the bug**
Since the update to version >5, a field is created in UpdateInput for a field with a timestamp directive if the operation is only set to "Create". I am not sure if this is a desired behavior. If so, how can I switch it off?

**Type definitions**
````graphql
interface INode {
  dateCreated: DateTime!
  #etc.
}
type Person implements INode {
  dateCreated: DateTime!
      @timestamp(operations: [CREATE])
      @selectable(onRead: true, onAggregate: true)
      @filterable(byValue: true, byAggregate: true)
  #etc.
}
````

**Expected behavior**
A field with a timestamp directive must not appear in the UpdateInput input types. Alternatively, it must be possible to deactivate it.

**Screenshots**
![image](https://github.com/neo4j/graphql/assets/49721200/89c7939d-e816-4480-a046-a5fdd55dd5f3)

**System (please complete the following information):**
* Version: @neo4j/graphql@5.3.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @AccsoSG 
I think this is desired behaviour.
You should be able to disable it with the [`@settable`](https://neo4j.com/docs/graphql/current/schema-configuration/field-configuration/#_settable) directive

**Comment by AccsoSG** [comment]
Hi @angrykoala 
Ok I see, thanks for the quick answer.
But then you should think about implementing the same behavior for the populatedBy directive. Basically, the timestamp directive is nothing else.

**Comment by angrykoala** [comment]
Could you elaborate regarding the `@populatedBy`?

**Comment by AccsoSG** [comment]
I have a similar field "createdBy" with the populatedBy directive. The name of the person is written there when the node is created.

It looks like this:

````graphql
    createdBy: String!
      @populatedBy(operations: [CREATE], callback: "createdBy") 
      @selectable(onRead: true, onAggregate: false)
      @filterable(byValue: true, byAggregate: false)
````

No field for createdBy is created in the UpdateInput here. This only happens for the field with the timestamp directive. But basically, however, I would say that the timestamp directive is to be understood as a special predefined populatedBy directive.

**Comment by angrykoala** [comment]
Thanks for the example. That is a good point, I'll take a look at this and come back to you

**Comment by angrykoala** [comment]
After discussing this a bit, indeed the `@populatedBy` should behave in the same way as `@timestamp`.

This means that the field will be available on all the operations that are not defined in the `operations` argument

I will rename this issue

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.
