### ISSUE TITLE
Cannot deactivate the top-level queries for unions

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#4995]
**Describe the bug**
Cannot switch off the top-level queries for unions. An error message is thrown when the query directive is attached to a union.

**Type definitions**
````graphql
type A {
  a: String
}

type B {
  b: String
}

union AorB = A | B
extend union AorB
  @query(read: false, aggregate: false)
````

**To Reproduce**

1. Run a server with the following code...
2. See error
````
Invalid directive usage: Directive @query can only be used in one location: either schema or type
````

**Expected behavior**
It should be possible to deactivate the top level queries for Unions

**System (please complete the following information):**
* Version: @neo4j/graphql@5.3.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by a-alle** [comment]
Hi @AccsoSG I have tried to reproduce your issue but I do not get any errors. Could it be that in your code this line `extend schema @query(..)` is being appended to the type definitions you sent?

**Comment by AccsoSG** [comment]
Hi @a-alle, thanks for your reply.
That is strange.

So my code does not contain such a query directive directly on the schema. I actually built a minimal example and get this error.

**Comment by AccsoSG** [comment]
@a-alle I found out that this error occurs when initializing the ogm.

````typescript
//...
const neo4jGraphQLConstructor: Neo4jGraphQLConstructor = {
  typeDefs,
  driver,
}

const neoSchema = new Neo4jGraphQL(neo4jGraphQLConstructor);

const ogm = new OGM(neo4jGraphQLConstructor);
await ogm.init(); //<------------ the error occurs here

const schema = await neoSchema.getSchema();

await neoSchema.assertIndexesAndConstraints({ options: { create: true } });
//...
````

**Comment by MacondoExpress** [comment]
Hi, the Schema configuration directives do not apply to the union type https://neo4j.com/docs/graphql/current/schema-configuration/type-configuration/#_query but only at the Type, Field, and Schema level. In this case you have to apply the `@query` directive in both `A` or `B` or directly at the Schema Level https://neo4j.com/docs/graphql/current/schema-configuration/global-configuration/, hope it helps!

**Comment by AccsoSG** [comment]
@MacondoExpress Thanks for your answer. I think the documentation is a bit outdated here.

In fact, the query directive also works on union types. The problem only occurs when I use the ogm at the same time. If I do not use the OGM, the schema generation works as expected. With query(read: false) no top level query is generated for the union. With query(read:true) a top level query is generated for the union.

Here it also looks like this: https://github.com/neo4j/graphql/blob/e34016aa6a162579099c0fb2a7924faa67e983e7/packages/graphql/src/graphql/directives/query.ts#L41

**Comment by MacondoExpress** [comment]
You're right @AccsoSG , I completely ignored that the support for the union was added at some point, let me check again this issue!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.

**Comment by MacondoExpress** [comment]
I was able to reproduce it, although, just to let you know, Schema Configuration directives are not supported on OGM, see https://neo4j.com/docs/graphql/current/ogm/directives/#_excluded_directives. The bug in this case is that OGM throws when the behavior expected instead is to ignore the Schema Configuration directives. We will discuss the prioritization of this bug soon!

**Comment by AccsoSG** [comment]
Yes, it makes sense that this directive is not considered in the OGM. I.e. the directive must simply be ignored during the initialization of the OGM.

Thank you.
