### ISSUE TITLE
Wrong cypher generated for nodes with multiple labels

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#5013]
given the following schema (from the tests):

https://github.com/neo4j/graphql/blob/1b52f8372bbaa54048c56badc99420e4ae3f31fd/packages/graphql/tests/tck/aggregations/where/node/string.test.ts#L724-L742

The following query is generated:

https://github.com/Andy2003/neo4j-graphql-js/blob/1b52f8372bbaa54048c56badc99420e4ae3f31fd/packages/graphql/tests/tck/aggregations/where/node/string.test.ts#L762-L771

```cypher
MATCH (this:Post)
CALL {
    WITH this
    MATCH (this)<-[this0:LIKES]-(this1)
    WHERE (this1:\`User:Employee\` OR this1:Person)
    RETURN any(var2 IN collect(this1.name) WHERE var2 = $param0) AS var3
}
WITH *
WHERE var3 = true
RETURN this { .content } AS this
```

The WHERE clause is querying a label named `User:Employee` but not the labels `User` and ` Employee`

The correct query would look like:

```cypher
MATCH (this:Post)
CALL {
    WITH this
    MATCH (this)<-[this0:LIKES]-(this1)
    WHERE (this1:User:Employee OR this1:Person)
    RETURN any(var2 IN collect(this1.name) WHERE var2 = $param0) AS var3
}
WITH *
WHERE var3 = true
RETURN this { .content } AS this
```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
