### ISSUE TITLE
Argument "phrase" is blocked for custom cypher queries since Neo4j-GraphQL >5

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#5030]
**Describe the bug**
We have a custom cypher query at top level. There we have an argument "phrase". Since the upgrade to Neo4j-GraphQL >5, this custom cypher query no longer works because there is a check for the phrase argument in the Neo4j-GraphQL code.

The server starts normally. The problem only occurs when the query is used. The error message:
````
Failed to get context fulltext
````

See: https://github.com/neo4j/graphql/blob/e34016aa6a162579099c0fb2a7924faa67e983e7/packages/graphql/src/translate/queryAST/factory/OperationFactory.ts#L107

**Type definitions**
````graphql
extend type Query {
  customCypher(
    phrase: String!
  ): [Result!]!
    @cypher(
      statement: """
        // No matter what the cypher looks like.
      """
    )
}
````
**System (please complete the following information):**

* Version: @neo4j/graphql@5.3.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @AccsoSG. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @AccsoSG! :pray: We will now prioritise the bug and address it appropriately.
