### ISSUE TITLE
Generated Cypher invalid, includes empty auth statements where specified field is missing

### ISSUE THREAD

**Issue by rcbevans** [neo4j/graphql#504]
**Describe the bug**
When adding an auth rule to a type and a typo is made, e.g authId rather than authID

```
type Person {
    id: ID
    name: String
    authID: String!
}

extend type Person @auth(rules: [
    {
        operations: [READ],
        where: { 
            OR: [
                { authId: "$jwt.sub" },
                { name: "John Smith" }
            ]
        }
    }
])
```

the authId property cannot be resolved to a field in the schema, and the returned auth rule is an empty string.  This results in invalid cypher being generated such as:

```
MATCH (this:Person)
WHERE (  OR  this.name IS NOT NULL AND this.name = $this_where0_OR_name )
RETURN this
```

If a field in an auth rule cannot be resolved, this is undoubtedly a developer error and so I would expect an exception to be thrown ideally during schema generation, or worst case, during query generation.

**System (please complete the following information):**

-   Version: @neo4j/graphql@2.1.0

Ideally auth rules should be validated against the schema when the augmented schema is being generated at server startup, or at the very least, create-auth-and-params should throw an error at generation time when a query is being built.

**Comment by danstarns** [comment]
This was fixed in #342
