### ISSUE TITLE
Auth rules are broken for relationships to union types

### ISSUE THREAD

**Issue by rcbevans** [neo4j/graphql#508]
**Describe the bug**
create-auth-and-params throws an error when an auth rule has a relationship to a union type caused by unsafe access of `refNode.labels` at https://github.com/neo4j/graphql/blob/master/packages/graphql/src/translate/create-auth-and-params.ts#L133.  This is due to an assumption that the type of a relationship field will be a concrete type.

> Cannot read property 'labelString' of undefined

```ts
const relationField = node.relationFields.find((x) => key === x.fieldName);
  if (relationField) {
    // UNSAFE CAST DUE TO BAD ASSUMPTION
    const refNode = context.neoSchema.nodes.find((x) => x.name === relationField.typeMeta.name) as Node;
     // ...
     // ERROR
    const labels = refNode.labelString;
```

**Type definitions**
```gql
type User {
    id: ID!
    t1s: [T1] @relationship(type: "HAS_T1", direction: OUT)
    t2s: [T2] @relationship(type: "HAS_T2", direction: OUT)
}

type T1 {
    id: ID!
    child: Child @relationship(type: "HAS_PARENT", direction: IN)
    user: User! @relationship(type: "HAS_T1", direction: IN)
}

type T2 {
    id: ID!
    child: Child @relationship(type: "HAS_PARENT", direction: IN)
    user: User! @relationship(type: "HAS_T1", direction: IN)
}

union T = T1 | T2

type Child {
    id: ID!
    parent: T @relationship(type: "HAS_PARENT", direction: OUT)
}

extend type Child @auth(rules: [
    { parent: { user: { id: "$jwt.sub" } } }
])
```

**To Reproduce**

- Create a schema like above
- Seed some data, a single user, with a T1 or T2, and a child
- Execute query

```gql
query Children {
    children {
        id
    }
}
```

Observe error is thrown.

**Expected behavior**
`create-auth-and-params` should correctly generate auth code to check that the parent node has a user with id matching jwt sub.

At the very least, the code shouldn't crash.

**System (please complete the following information):**

-   Version: @neo4j/graphql@2.2.0

**Additional context**
`create-auth-and-params` currently makes no effort to identify relationships with union types meaning that it is not currently possible to have allow/where/bind rules that traverse union relationships and runtime errors will occur.

**Comment by angrykoala** [comment]
This issue can be currently reproduced with an empty database and the following typedefs (slight changes over the original typedefs due to compatibility issues with next release):
```gql
    type User {
        id: ID!
        t1s: [T1!]! @relationship(type: "HAS_T1", direction: OUT)
        t2s: [T2!]! @relationship(type: "HAS_T2", direction: OUT)
    }

    type T1 {
        id: ID!
        child: Child @relationship(type: "HAS_PARENT", direction: IN)
        user: User! @relationship(type: "HAS_T1", direction: IN)
    }

    type T2 {
        id: ID!
        child: Child @relationship(type: "HAS_PARENT", direction: IN)
        user: User! @relationship(type: "HAS_T1", direction: IN)
    }

    union T = T1 | T2

    type Child {
        id: ID!
        parent: T @relationship(type: "HAS_PARENT", direction: OUT)
    }

    extend type Child @auth(rules: [{ where: { parent: { user: { id: "$jwt.sub" } } } }])
```

And the same query as above:
```gql
query Children {
    children {
        id
    }
}
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @rcbevans! :pray: We will now prioritise the bug and address it appropriately.

**Comment by angrykoala** [comment]
Hi @rcbevans
