### ISSUE TITLE
Neo4jError: Variable `<propertyName>Count` not defined 

### ISSUE THREAD

**Issue by afreakk** [neo4j/graphql#5080]
**Describe the bug**
When trying to mutate a type with @authorization through a `@cypher` like:
```
type Mutation {
    deleteCar(input: DeleteCarInput!): DeletedCar!
        @cypher(
            statement: """
            MATCH(s:Car)
            WHERE (s.id = $input.carId)
            REMOVE s:Car
            SET s:DeletedCar
            SET s.reason = $input.reason
            RETURN s AS s
            """
            columnName: "s"
        )
}
```
I get error like: 
```
"Neo4jError: Variable \`ownerCount\` not defined (line 11, column 69 (offset: 240))"
```

**Type definitions**
```
type JWT @jwt {
    id: String
}
type User @authorization(filter: [{ where: { node: { userId: "$jwt.id" } } }]) {
    userId: String! @unique
    adminAccess: [Tenant!]!
        @relationship(type: "ADMIN_IN", direction: OUT, aggregate: false)
}

type Tenant
    @authorization(
        validate: [{ where: { node: { admins: { userId: "$jwt.id" } } } }]
    ) {
    id: ID! @id
    admins: [User!]!
        @relationship(type: "ADMIN_IN", direction: IN, aggregate: false)
    deletedCars: [DeletedCar!]!
        @relationship(type: "OWNED_BY", direction: IN, aggregate: false)
    cars: [Car!]!
        @relationship(type: "OWNED_BY", direction: IN, aggregate: false)
}

input DeleteCarInput {
    carId: ID!
    reason: String!
}
type Mutation {
    deleteCar(input: DeleteCarInput!): DeletedCar!
        @cypher(
            statement: """
            MATCH(s:Car)
            WHERE (s.id = $input.carId)
            REMOVE s:Car
            SET s:DeletedCar
            SET s.reason = $input.reason
            RETURN s AS s
            """
            columnName: "s"
        )
}

type Car
    @mutation(operations: [UPDATE])
    @authorization(
        validate: [
            { where: { node: { owner: { admins: { userId: "$jwt.id" } } } } }
        ]
    ) {
    id: ID! @id
    owner: Tenant!
        @relationship(type: "OWNED_BY", direction: OUT, aggregate: false)
    name: String!
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    updatedBy: String
        @populatedBy(
            callback: "getUserIDFromContext"
            operations: [CREATE, UPDATE]
        )
}

type DeletedCar
    @mutation(operations: [UPDATE])
    @authorization(
        validate: [
            { where: { node: { owner: { admins: { userId: "$jwt.id" } } } } }
        ]
    ) {
    id: ID! @id
    owner: Tenant!
        @relationship(type: "OWNED_BY", direction: OUT, aggregate: false)
    name: String!
    reason: String!
    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])
    updatedBy: String
        @populatedBy(
            callback: "getUserIDFromContext"
            operations: [CREATE, UPDATE]
        )
}

extend schema @authentication @query(read: true, aggregate: false)
```

**To Reproduce**

1. `git clone https://github.com/afreakk/n4j-issue.git`
2. `cd n4j-issue/`
3. `git checkout cypher-issue`
4. `yarn`
5. `./test.sh watch-test`
6. see error

**Expected behavior**
No error

**System (please complete the following information):**

* OS: linux
* Version: @neo4j/graphql@5.3.2
* Node.js version: 20.11.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @afreakk. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @afreakk 
A similar bug was fixed in version 5.3.5, would you mind confirming if this is still happening with the latest `@neo4j/graphql` version?

**Comment by angrykoala** [comment]
Hi @afreakk
This bug looks similar to the one fixed in 5.3.5. Would you mind checking if the bug still happens in the latest version of `@neo4j/graphql`?

**Comment by afreakk** [comment]
> Hi @afreakk This bug looks similar to the one fixed in 5.3.5. Would you mind checking if the bug still happens in the latest version of `@neo4j/graphql`?

https://github.com/afreakk/n4j-issue/commit/c73381774acd8ac5b11a4e9decfa1ca51ce43cf5
I just tested here, but no, still the same error

**Comment by angrykoala** [comment]
Thanks @afreakk 
I'll take a look at this

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @afreakk! :pray: We will now prioritise the bug and address it appropriately.
