### ISSUE TITLE
Error "Cannot return null for non-nullable field" when limit exceeds result count in queries with non-nullable fields

### ISSUE THREAD

**Issue by Wenzel** [neo4j/graphql#5089]
**Describe the bug**
When executing a GraphQL query that includes a non-nullable field (e.g., director in a Movie type), the query fails with an error if the limit parameter provided exceeds the number of actual results that meet the query's criteria.

This issue occurs even if the existing data correctly adheres to the schema definitions, suggesting a potential issue with how pagination and non-nullable fields are handled.

**Type definitions**
```graphql
type DirectedDate @relationshipProperties {
    date: Date!
}

type Person {
    name: String!
    directedMovies: [Movie!]! @relationship(type: "DIRECTED", direction: OUT, properties: "DirectedDate")
}

type Movie {
    title: String!
    director: Person! @relationship(type: "DIRECTED", direction: IN, properties: "DirectedDate")
}
```

**To Reproduce**

1. Insert the following data

```cypher
// Create Person nodes
CREATE (p1:Person {name: "Alice"})
CREATE (p2:Person {name: "Bob"})

// Create Movie nodes
CREATE (m1:Movie {title: "First Movie"})
CREATE (m2:Movie {title: "Second Movie"})
CREATE (m3:Movie {title: "Third Movie"})

// Create relationships with properties
CREATE (p1)-[:DIRECTED {date: date("2022-01-01")}]->(m1)
CREATE (p1)-[:DIRECTED {date: date("2022-02-01")}]->(m2)
CREATE (p2)-[:DIRECTED {date: date("2022-03-01")}]->(m3)
```

2. Run the following query to get all Movies directed by "Alice":

```graphql
query ListMovies($options: MovieOptions, $where: PersonWhere) {
  movies(options: $options) {
    title
    director(where: $where) {
      name
    }
  }
}
```
parameters:
```json
{
  "options": {
    "limit": 1
  },
  "where": {
    "name": "Alice"
  }
}
```
Observe that it works:
```json
{
  "data": {
    "movies": [
      {
        "title": "First Movie",
        "director": {
          "name": "Alice"
        }
      }
    ]
  }
}
```

3. Change the parameters to set the `limit` to a high number
parameters
```JSON
{
  "options": {
    "limit": 100
  },
  "where": {
    "name": "Alice"
  }
}
```

Observe that it fails now:

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Movie.director.",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "movies",
        2,
        "director"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot return null for non-nullable field Movie.director.",
          "    at completeValue (/app/node_modules/graphql/execution/execute.js:605:13)",
          "    at executeField (/app/node_modules/graphql/execution/execute.js:500:19)",
          "    at executeFields (/app/node_modules/graphql/execution/execute.js:414:22)",
          "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:925:10)",
          "    at completeValue (/app/node_modules/graphql/execution/execute.js:646:12)",
          "    at completeValue (/app/node_modules/graphql/execution/execute.js:595:23)",
          "    at /app/node_modules/graphql/execution/execute.js:707:25",
          "    at Function.from (<anonymous>)",
          "    at completeListValue (/app/node_modules/graphql/execution/execute.js:687:34)",
          "    at completeValue (/app/node_modules/graphql/execution/execute.js:618:12)"
        ]
      }
    }
  ],
  "data": null
}
```

**Expected behavior**
The query should return movies directed by "Alice", handling cases where the number of results is less than the limit without error.

**System (please complete the following information):**

* OS: Ubuntu 22.04
* Version: `5.3.5`
* Node.js version: `5.15.0`

Thanks !

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Wenzel. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by Liam-Doodson** [comment]
Hi @Wenzel! This is the intended behaviour and that error comes from graphql itself.

Because you are filtering on the director itself, you end up returning data that is null. Because the director of the "Third movie" is not "alice" the filter means that no director can be returned for the "Third movie".

Maybe a query such as this is what you are looking for?

```gql
query ListMovies {
  movies(where: {director: {name: "Alice"}}) {
    title
    director {
      name
    }
  }
}
```

This would result in only returning movies where the director is called alice
