### ISSUE TITLE
Options (sorting and paging) are not auto-injected into custom Cypher

### ISSUE THREAD

**Issue by magaton** [neo4j/graphql#512]
**Describe the bug**
Options (sorting and paging) are auto-injected

**Type definitions**

```
type Client {
   id: String!
   login: String!
   name: String!
   sponsor: [Client] @relationship(type: "HAS_SPONSOR", direction: OUT)
   type: String!
   level: Int
   typeLevel: String
}
```
and the custom query type:

```
   upline(where: ClientWhere, options: ClientOptions): [Client!] @cypher(statement: """
        MATCH (me:Client) WHERE me.login=$where.login
        WITH me
        MATCH path=((client:Client)<-[hs:HAS_SPONSOR*0..2]-(me))
        WITH NODES(path) AS nodes, path, me, LENGTH(path) AS level, client, (LENGTH(path) + client.type) AS typeLevel, CASE WHEN LENGTH(path)>=1 THEN 1 ELSE 0 END AS sponsorIndex
        WITH client, nodes[sponsorIndex] AS sponsor, level, typeLevel
        RETURN client{.*, level:level, typeLevel: typeLevel, sponsor: sponsor{.*}} AS this
    """)
```

**To Reproduce**
Fire the following query:
```
    {
      upline(where: {login: "c4"}, options: {sort:[{name: ASC}]}) {
         id
         name
         type
         level
         login
      }
    }

```
The sorting by name will be ignored.

**Expected behavior**
That ordering and pagination is supported on library level (for custom query types) like it was in old `neo4j-graphql-js`.

**System (please complete the following information):**

-   Version: [e.g. @neo4j/graphql@2.2.0]

**Additional context**
The current workaround is to explicitly return with ORDER BY and LIMIT in cypher and populate them with $options.

**Comment by danstarns** [comment]
Thank you for your request. We can't provide a way to do this, Because you're using custom Cypher you are responsible for the where and sorting that happens inside your custom logic.
