### ISSUE TITLE
Null options in custom query type and incorrect 'limit' type resolution

### ISSUE THREAD

**Issue by magaton** [neo4j/graphql#513]
**Describe the bug**
As a workaround for currently not supported auto-injection of options in custom query types (see https://github.com/neo4j/graphql/issues/512) one needs to specify ORDER BY and LIMIT in embedded cypher.

The 1st problem is that in case options are not specified, they are not passed as null, so the query breaks.
The workaround is that the client code specifies `options: null` which is a bit ugly and hard to request.
The second problem is that with:

```
  {
      upline(where: {login: "c25"}, options: {limit:2}) {
         id
         name
         type
         level
         login
      }
    }
```

limit is passed as 2.0 instead of 2, hence breaking LIMIT in cypher (that expects Integer value)

**Type definitions**
Query type:
```
 upline(where: ClientWhere, options: ClientOptions): [Client!] @cypher(statement: """
        MATCH (me:Client) WHERE me.login=$where.login
        WITH me
        MATCH path=((client:Client)<-[hs:HAS_SPONSOR*0..2]-(me))
        WITH NODES(path) AS nodes, path, me, LENGTH(path) AS level, client, (LENGTH(path) + client.type) AS typeLevel, CASE WHEN LENGTH(path)>=1 THEN 1 ELSE 0 END AS sponsorIndex
        WITH client, nodes[sponsorIndex] AS sponsor, level, typeLevel
        RETURN client{.*, level:level, typeLevel: typeLevel, sponsor: sponsor{.*}} AS this ORDER BY COALESCE($options.sort, level) LIMIT COALESCE(TOINTEGER($options.limit), 10000)
    """)
```

**Expected behavior**
Options are passed as null by default and handled in cypher with COALESCE.
Value for limit is treated as Integer

**System (please complete the following information):**

-   Version: [e.g. @neo4j/graphql@2.2.0]

**Comment by darrellwarde** [comment]
For your problem of "limit is passed as 2.0 instead of 2, hence breaking LIMIT in cypher (that expects Integer value)", I saw your comment in https://github.com/magaton/ce/blob/master/src/queries.graphql:

```graphql
// this works now. In 2.2.0 it was not. LIMIT is now correctly passed as integer

    {
        downline(where: {login: "c4"}, options: {limit: 10}) {
            id
            name
            typeLevel
            sponsor {
               id
               name
            }
        }
    }
```

Can you can confirm that this is no longer an issue?
