### ISSUE TITLE
Map projection as result in custom query type does not allow to request relationship fields

### ISSUE THREAD

**Issue by magaton** [neo4j/graphql#514]
**Describe the bug**
When the custom query type returns map projection instead of the node itself, it is not possible to specify relationship fields in the GRAPHQL request.

**Type definitions**
```gql
type Client {
   id: String!
   login: String!
   name: String!
   level: Int
   typeLevel: String
}
```

and query type:

```gql
query {
 downline(where: ClientWhere, options: ClientOptions): [Client] @cypher(statement: """
      MATCH (me:Client) WHERE me.login=$where.login
      WITH me
      MATCH path=((client:Client)-[hs:HAS_SPONSOR*0..2]->(me))
      WITH NODES(path) AS nodes, path, me, LENGTH(path) AS level, client, (LENGTH(path) + client.type) AS typeLevel, CASE WHEN LENGTH(path)>=1 THEN 1 ELSE 0 END AS sponsorIndex
      WITH client, nodes[sponsorIndex] AS sponsor, level, typeLevel
      RETURN client{.*, typeLevel: typeLevel, level: level} AS this ORDER BY COALESCE($options.sort, level) LIMIT COALESCE(TOINTEGER($options.limit), 10000)
   """)
}
```

**To Reproduce**
Fire the following query:
```gql
  {
        downline(where: {login: "c4"}, options: null) {
            id
            name
            typeLevel
            sponsor {
              id
              name
            }
        }
    }
```
It will blow with: `"Expected to find a node at '  this@504' but found Map"`

**Expected behavior**
That map projection is correctly mapped to a return type and that the relationship fields can be requested in Graphql request

**System (please complete the following information):**

-   Version: [e.g. @neo4j/graphql@2.2.0]

**Additional context**
The self contained project with working and non-working queries is available at:
https://github.com/magaton/ce

**Comment by darrellwarde** [comment]
@magaton, we don't have enough information to reproduce here because we don't have your `Sponsor` type. Also, do we need some test data in the database for this to work?

We don't like to make assumptions whilst reproducing bugs because we might do things slightly differently.

**Comment by magaton** [comment]
@darrellwarde No worries, I understand.
I have posted a sample project in the initial issue description.

The self-contained project with working and non-working queries is available here :
https://github.com/magaton/ce

There is no `Sponsor` type.

It is `(Client)-[:HAS_SPONSOR]->(Client)`
but you will see that in schema.graphql.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @magaton! :pray: We will now prioritise the bug and address it appropriately.

**Comment by magaton** [comment]
Hello, may I ask about the status of this bug?

**Comment by darrellwarde** [comment]
Still in our backlog - we can't prioritise anything to do with custom Cypher as high priority because frankly it's just a Pandora's Box, in that there are so many various ways in which user input can affect behaviour. Additionally, there tends to always be a workaround for bugs with custom Cypher, given the freedom that Cypher offers. In this case, you may be able to use something like Virtual Nodes (https://neo4j.com/labs/apoc/4.1/virtual/) to achieve this.

**Comment by darrellwarde** [comment]
I think there's nothing we can do here - if the return value in a custom Cypher is not of a node type, we can't do relationship traversals from it.
