### ISSUE TITLE
Filtering issue in `@authorization` directive

### ISSUE THREAD

**Issue by mathix420** [neo4j/graphql#5143]
**Describe the bug**
Can't filter on basic relationship, was previously working on `v4.3.4`.

**Type definitions**
```graphql
type User {
  id: ID! @id
}

type Video {
  id: ID! @id
  publisher: User! @relationship(type: "PUBLISHER", direction: IN)
}
extend type Video
  @authorization(
    filter: [
      { where: { node: { publisher: { id: "$jwt.sub" } } } }
    ]
  )
  
type Query {
  getAllVids: [Video]!
    @cypher(
      statement: """
      MATCH (video:Video)
      RETURN video
      LIMIT 1
      """
      columnName: "video"
    )
}
```

**To Reproduce**

1. Run a server with the given type defs
2. Run this query
```graphql
query videos {
  getAllVids {
    id
  }
}
```

**Expected behavior**
Should return a video.

```
Variable `publisherCount` not defined (line 8, column 37 (offset: 125))
"WHERE ($isAuthenticated = true AND (publisherCount <> 0 AND ($jwt.sub IS NOT NULL AND this1.id = $jwt.sub)))"
                                     ^
```

**System (please complete the following information):**

* OS: [e.g. macOS, Windows] linux
* Version: [e.g. @neo4j/graphql@1.0.0]  "5.3.6"
* Node.js version: [e.g. 14.16.0] 18

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mathix420. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mathix420! :pray: We will now prioritise the bug and address it appropriately.
