### ISSUE TITLE
Unable to use relational fields in @auth directive "where" argument

### ISSUE THREAD

**Issue by inf3rnus** [neo4j/graphql#518]
**Describe the bug**
I may be doing something wrong, but I've read the docs and experimented with this for about a day, and it appears that if the properties of edges are used in the "where" argument of the @auth directive, a non functional query is produced leading to neo4j throwing a syntax error.

Based off of the docs, this _seems_ like it should be supported.

**Some extra info**

In an attempt to get a grasp on all the potential issues of migrating to this package, this problem sprang up, and unfortunately, edge properties are something that are crucial to my team's current model for managing auth.

To expand on the basics, the idea is that we want to have different permission levels for a set of users, and those users will be part of "Room" nodes. Their "User" nodes' edges contain a property called "role" and that role determines what sorts of operations a user should be allowed to perform on a room. e.g. the prop's value could be "OWNER", "ADMIN", "MEMBER", etc. With each role defining a different set of allowed operations.

While the "where" argument does just fine in allowing operations to go through to see if a property is on a matching node, it will crash if you feed it a relational field.

Please see the repro below for more details.

**Type definitions**
```
type Person {
  name: String!
  rooms: [Room]
    @relationship(type: "MEMBER_OF", properties: "Permission", direction: OUT)
}

interface Permission @relationshipProperties {
  role: String
}

type Room {
  roomName: String!
  members: [Person]
    @relationship(type: "MEMBER_OF", properties: "Permission", direction: IN)
  # @auth(rules: [{ operations: [CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], roles: ["admin"] }])
}

extend type Room
  @auth(
    rules: [
      {
        operations: [CONNECT]
        where: {
          members: {
            # If you change this, as expected, John will not be connected to the room "Kewl Room"
            name: "John"

            ##### --------> UNCOMMENT THE LINE TO CRASH THE LIBRARY ###### <--------
            # roomsConnection: { edge: { role: "$context.test" } }
          }
        }
      }
    ]
  )


```

**To Reproduce**

1. Run a server with the following code, adjust accordingly to hook it up to your db instance
```
/* eslint-disable max-len */
const { Neo4jGraphQL } = require('@neo4j/graphql');
const { ApolloServer } = require('apollo-server');
const neo4j = require('neo4j-driver');
const typeDefs = require('fs').readFileSync(`${__dirname}/schema.gql`, 'utf8');
// NOTE the jwt functionality of auth is not being used right now, this is simply here to allow the @auth directive to work
// which was needed to keep things simple
const secret = require('fs').readFileSync('./authPublicKey.key');

const AURA_ENDPOINT = 'neo4j://localhost:7687';

const USERNAME = 'neo4j';
const PASSWORD = '1234';

// Create Neo4j driver instance
const driver = neo4j.driver(
  AURA_ENDPOINT,
  neo4j.auth.basic(USERNAME, PASSWORD)
);

// Create instance that contains executable GraphQL schema from GraphQL type definitions
const neoSchema = new Neo4jGraphQL({
  typeDefs,
  driver,
  config: {
    jwt: {
      secret
    }
  }
});

// Create ApolloServer instance to serve GraphQL schema
const server = new ApolloServer({
  schema: neoSchema.schema,
  // takes the request and from it constructs a context
  // which is injected into graphql resolvers
  context: obj => {
    const { req } = obj;
    return { req, test: 'John' };
  }
});

// Start ApolloServer
server.listen().then(({ url }) => {
  console.log(`GraphQL server ready at ${url}`);
});
```

2. Run the following queries (in order, from top to bottom):

```
mutation {
  createPeople(input: [
    {name: "John"},
    {name: "Paul"}
  ]){
    people {
      name
    }
  }

}

mutation {
  createRooms(input: [
    {roomName: "Kewl Room"}
  ]){
    rooms {
      members {
        name
      }
    }
  }
}

mutation {
  updateRooms(where: {
    roomName: "Kewl Room"
  }
  connect: {
    members: {
      edge: {
        role: "testingggg"
      }
      where: {
        node: {
          name: "John"
        }
      }
    }
  }
  
  ) {
    rooms {
      members {
        name
      }
    }
  }
}
```

**Expected behavior**
The software does not crash and one is able to use edge properties to manage operations on resources within the @auth directive

**Screenshots**

![image](https://user-images.githubusercontent.com/5959983/135182317-02aeaa77-862b-42e8-aa9b-9a748405fd5e.png)

**System (please complete the following information):**

-   OS: Ubuntu 18.04 LTS
-   Version: @neo4j/graphql 2.2.0
-   Node.js version: 14.17.5

**Additional context**

**Comment by darrellwarde** [comment]
We're thinking about our long-term roadmap and want to consolidate our backlog so that we can accurately plan moving forward. As such, this is being closed in favour of #1871 where we will capture all requirements in relation to filtering in the `@auth` directive.
