### ISSUE TITLE
Creating distinct relationships on interface field no longer possible since v5 if the interface does not include common identifier

### ISSUE THREAD

**Issue by pjaydev** [neo4j/graphql#5213]
Assuming we have the following **Type definitions**:

```graphql
interface ICountable {
    count: Int
}

type DataGroup implements ICountable {
    groupId: ID! @id
    name: String!
    count: Int
}

type DataSet implements ICountable {
    setId: ID! @id
    count: Int
}

type DataCollection {
    id: ID! @id
    name: String!
    countables: [ICountable!]! @relationship(type: "hasCountable", direction: OUT)
}
```

Up to v4, to create one or more relationships between a `DataCollection` node and a other types, which implement the interface `ICountable`, I could execute the following mutation: 

```graphql
mutation {
  updateDataCollections(
    where: { id: "e8375b92-be1f-414a-954f-30e25a96d578" }
    update: {
      countables: {
        connect: {
          where: {
            node: {
              _on: {
                DataGroup: { groupId: "7fc6bdf6-931b-4ed2-b1cd-0c82ae81dff0" }
                DataSet: { setId: "0c03f926-b990-48d9-8776-84c7b3bf4142" }
              }
            }
          }
        }
      }
    }
  ) {
    info {
      relationshipsCreated
    }
  }
}
```

But unfortunatelly this is no longer possible in v5, since the `_on` field was removed with this [PR](https://github.com/neo4j/graphql/pull/4568).

This report is similar to [this issue](https://github.com/neo4j/graphql/issues/4825), which rather focusses on filtering unions, whereas in my case of the concrete need of creating distinct relationships to existing nodes, I can not figure out any suitable workaround. Is it just **no longer possible** to create relationships on an interface field to existing nodes since v5, if the interface does not include a common identifier field, which is used for all implementing types? Or am I missing something?

Thanks in advance!

**Comment by MacondoExpress** [comment]
Hi @pjaydev,
Yes, this is the intended behavior, as for the other issue we have chosen to remove the `_on` as it was leading to unclear outputs. 
In your case, I would suggest to use a shared identifier, for instance:
```graphql
interface ICountable {
    count: Int
    id: ID!
}

type DataGroup implements ICountable {
    id: ID! @id
    name: String!
    count: Int
}

type DataSet implements ICountable {
    id: ID! @id
    count: Int
}

type DataCollection {
    id: ID! @id
    name: String!
    countables: [ICountable!]! @relationship(type: "hasCountable", direction: OUT)
}
```

then:
```graphql
mutation {
  updateDataCollections(
    where: { id: "e8375b92-be1f-414a-954f-30e25a96d578" }
    update: {
      countables: {
        connect: {
          where: {
            node: {
              OR: [
                {
                  id: "7fc6bdf6-931b-4ed2-b1cd-0c82ae81dff0"
                  typename_IN: [DataGroup]
                }
                {
                  id: "0c03f926-b990-48d9-8776-84c7b3bf4142"
                  typename_IN: [DataSet]
                }
              ]
            }
          }
        }
      }
    }
  ) {
    info {
      relationshipsCreated
    }
  }
}
```

**Comment by pjaydev** [comment]
Thanks a lot @MacondoExpress for your quick response. Your suggested workaround is exactly what I tried to express in the title with "..if the interface does not implement common identifier" (i actually meant to say "include" instead of "implement", my bad).

To be honest, suggesting to modify the schema to comply with the technology appears very unsatisfying to me. The basic idea of GraphQL is to "Think in Graphs" and to "model your business domain as a graph" [(Source)](https://graphql.org/learn/thinking-in-graphs/). In my understanding, this means, the GraphQL schema should primarily represent a semantic representation of the domain model and only should only have to adapt to the technical requirements in very exceptional cases. 

I cannot see a semantic justification to introduce an "id" field to an interface like "ICountables", whose only purpose should be to emphasize that implementing types are countable. 

Migrating by implementing this workaround would not only mean to add identifier fields to all interfaces, but also the requirement of renaming some fields, in case of types, which implement one interface and have different names for their identifier fields (as shown in my example). Renaming fields in turn means to break the schema causing incompatibilities with all clients, that use the API, and not to mention the required data migration.

Neo4j will certainly have good reasons for this decision to remove the `_on` field. But in this process removing a core functionality such as creating distinct relationships on interface properties is a little bit hard to comprehend for me.

**Comment by MacondoExpress** [comment]
Hi @pjaydev ,  
My suggestion for changing the `ICountable` in the example was to showcase the new filter capabilities as the filter: `typename_IN` introduced that solved that particular case, it was not intended to be a suggestion on the modeling. The reason why we have chosen to remove the `_on` was that it caused too much ambiguity and unspecified behavior, some of the behaviors expressed under the `_on` filters were:
- type filtering, expressed  as `_on: { Movie: {} }`.
- override filter mechanism, expressed as ` { title: "the Matrix" , _on: { Series: "Lost" } }`.

When mixing these behaviors with other functionalities like `Boolean operators` it was no longer clear the output produced.

**Comment by pjaydev** [comment]
Thanks for the explanation on why you decided to remove `_on`, @MacondoExpress. 

I'm afraid I still cannot understand how `typename_IN ` should solve the problem of the requirement to change the model (by adding `id`s to each interface).

Can you please provide one last example on how to create a distinct relationship to a node on a interface relationship field, where the interface does **not** have to include an `id` (or any other unique) field?

Thank you.

**Comment by MacondoExpress** [comment]
I'm afraid that the requirement to not change the model cannot be satisfied.
