### ISSUE TITLE
Spatial type projection fails if the `srid` is included in the SelectionSet

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/graphql#5223]
**Describe the bug**
As by the title, the GraphQL query fails when the `srid` is explicitly defined in a Spatial Type SelectionSet.

**Type definitions**
```graphql
type Location  {
  id: String
  value: CartesianPoint!
}
```

**To Reproduce**
```graphql
mutation MyMutation {
  createLocations(input: {value: {x: 1.5, y: 1.5}, id: "1"}) {
    locations {
       id
       value {
          x
          y 
          crs
          srid
       }
    }
  }
}
```

**Expected behavior**
It should create a valid Location with a valid CartesianPoint and it should be able to project the Cartesian field `srid`.

**System (please complete the following information):**
* Version: [e.g. @neo4j/graphql/5.4.2]

**Additional context**
```json
{
  "errors": [
    {
      "message": "Int cannot represent non-integer value: 7203",
      "locations": [{ "line": 11, "column": 11 }],
      "path": [
        "createLocations",
        "locations",
        0,
        "value",
        "srid"
      ]
    }
  ],
  "data": null
}

```

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @MacondoExpress. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @MacondoExpress! :pray: We will now prioritise the bug and address it appropriately.
