### ISSUE TITLE
Int Argument on Custom Query Converted to Float

### ISSUE THREAD

**Issue by inf3rnus** [neo4j/graphql#526]
**Describe the bug**
I'm unable to use Int's as arguments when using custom cypher queries with the @cypher directive.

Simply including it and passing the paramater to the LIMIT clause of a cypher query will trigger the following error:

```"Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: org.neo4j.exceptions.InvalidArgumentException: LIMIT: Invalid input. '25.0' is not a valid value. Must be a non-negative integer."```

![image](https://user-images.githubusercontent.com/5959983/135925277-540094bb-ed73-4258-82eb-674e478dfa35.png)

**Type definitions**
```
type Movie {
  title: String
  tags: [Tag] @relationship(type: "HAS", direction: OUT)
}

type Tag {
  id: String!
  name: String!
  papers: [Movie] @relationship(type: "HAS", direction: IN)
}

type Query {
  movie_tags(tagName: String = "", limit: Int): [Movie]
    @cypher(
      statement: """
      MATCH (tag:Tag{type: 'task'})<-[:HAS]-(movie:Movie)
      WHERE tag.name = $tagName
      RETURN movie
      LIMIT $limit
      """
    )
}
```

**To Reproduce**

1. Run a server and simply feed those typeDefs to it
2. Execute the query:
```
{
  movie_tags(tagName: "test", limit: 25) {
    title
    tags {
      name
    }
  }
}
```
4. Error should arise

**Expected behavior**
The Int type is able to be used as an argument for custom queries that use the @cypher directive

**System (please complete the following information):**

-   OS: Ubuntu 18.04 LTS
-   Version: @neo4j/graphql 2.2.0
-   Node.js version: v14.17.5

**Extra Info**
Could be useful to know, I am using neo4j 4.3.2

**Comment by oskarhane** [comment]
Thanks for reporting this, sure looks like a bug. We'll get on it.

**Comment by oskarhane** [comment]
As a workaround, you can use the `BigInt` type rather than `Int` - it'll be transformed correctly @inf3rnus
