### ISSUE TITLE
Authorization filter causing undefined error

### ISSUE THREAD

**Issue by 0xbmart** [neo4j/graphql#5270]
**Describe the bug**

When trying to query the user associated to the passed JWT using a cypher directive while there are authorization filters to filter out blocking user, i am receiving an error stating a variable is undefined in the resulting cypher query 

**Type definitions**

```
  type User @node(labels: ["User"]) @authorization(
		filter: [
			{ where: { node: { NOT: { blockedUsers_SOME: { to: { id: "$jwt.sub" } } } } } },
			#{ where: { node: { blockedUsers_NONE: { to: { id: "$jwt.sub" } } } } },
		]
	) {
		id: ID! @unique @id

    blockedUsers: [UserBlockedUser!]! @relationship(type: "HAS_BLOCKED", direction: OUT)
  }

  type UserBlockedUser @node(labels: ["UserBlockedUser"]) @authorization(
		filter: [
			{ where: { node: { from: { id: "$jwt.sub" } } } }
		]
	) {
		id: ID! @id @unique

		from: User! @relationship(type: "HAS_BLOCKED", direction: IN) @settable(onCreate: true, onUpdate: false)
		to: User! @relationship(type: "IS_BLOCKING", direction: OUT) @settable(onCreate: true, onUpdate: false)
	}

  type Query {
    getMe: User @cypher(statement: "OPTIONAL MATCH (u:User {id: $jwt.sub}) RETURN u", columnName: "u")
  }
```

**To Reproduce**

1. Pull [this repo](https://github.com/bmart7/neo4j-auth-issue)
2. `npm run up-build` to start the server
3. Then run the following Query with the following `Authorization` header:
- Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YzFiMDE4NC1kODU3LTRkOWQtOGUxMy1mYmFiNGJkYWVkMmUiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.Vf_ydofF9cKOJmMmtxXVozpt6Lux9HErskAzi6izNuw"

```
query GetMe {
  getMe {
    id
    __typename
  }
}
```

5. See error
```
WITH u AS this0
MATCH (this0)-[:HAS_BLOCKED]->(this1:UserBlockedUser)
OPTIONAL MATCH (this1)-[:IS_BLOCKING]->(this2:User)
WITH *, count(this2) AS toCount
WITH *
WHERE (toCount <> 0 AND ($jwt.sub IS NOT NULL AND this2.id = $jwt.sub))
RETURN count(this1) > 0 AS var3
WITH *
WHERE ($isAuthenticated = true AND NOT (var3 = true))
WITH this0 { .id } AS this0
RETURN this0 AS this
2024-06-25T02:36:03.571Z @neo4j/graphql:execution cypher params: {
  jwt: {
    sub: '8c1b0184-d857-4d9d-8e13-fbab4bdaed2e',
    name: 'John Doe',
    iat: 1516239022
  },
  isAuthenticated: true
}
2024-06-25T02:36:03.623Z @neo4j/graphql:execution Neo4jError: Variable `this0` not defined (line 13, column 6 (offset: 392))
"WITH this0 { .id } AS this0"
      ^

    at captureStacktrace (/app/node_modules/neo4j-driver-core/lib/result.js:620:17)
    at new Result (/app/node_modules/neo4j-driver-core/lib/result.js:112:23)
    at newCompletedResult (/app/node_modules/neo4j-driver-core/lib/transaction.js:528:12)
    at Object.run (/app/node_modules/neo4j-driver-core/lib/transaction.js:360:20)
    at Transaction.run (/app/node_modules/neo4j-driver-core/lib/transaction.js:181:34)
    at ManagedTransaction.run (/app/node_modules/neo4j-driver-core/lib/transaction-managed.js:54:21)
    at Executor.transactionRun (/app/node_modules/@neo4j/graphql/src/classes/Executor.ts:297:28)
    at <anonymous> (/app/node_modules/@neo4j/graphql/src/classes/Executor.ts:269:33)
    at TransactionExecutor._safeExecuteTransactionWork (/app/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:211:26)
    at TransactionExecutor.<anonymous> (/app/node_modules/neo4j-driver-core/lib/internal/transaction-executor.js:198:46) {
  constructor: [Function],
  code: 'Neo.ClientError.Statement.SyntaxError',
  retriable: false
}
```

**Expected behavior**
if the JWT is valid and associated id exists within the db, the user node should be returned. Otherwise it should return `null`

**Screenshots**

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: [e.g. @neo4j/graphql@1.0.0]
* Node.js version: [e.g. 14.16.0]

**Additional context**

Additionally, I noticed that when each of the following filters are applied to the User node the results seem to differ although logically I believe they should be the same result:
- `{ where: { node: { NOT: { blockedUsers_SOME: { to: { id: "$jwt.sub" } } } } } }`
- `{ where: { node: { blockedUsers_NONE: { to: { id: "$jwt.sub" } } } } }`

They are included in the repo as well if you would like to flip the commented line and test them out or let me know if you would like me to open a separate issue

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @bmart7. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @bmart7! :pray: We will now prioritise the bug and address it appropriately.
