### ISSUE TITLE
graphql-ogm with aggregations and full text searches

### ISSUE THREAD

**Issue by nicecatch** [neo4j/graphql#5345]
**Describe the bug**
I cannot seem to be able to count results when a fulltext search is made against an aggregation query

**Type definitions**
```
const typeDefs = gql`
  type Person
    @fulltext(
      indexes: [
        {
          name: "personFullTextIndex"
          fields: ["firstName", "lastName", "nickname", "title", "companyName"]
        }
      ]
    ) {
    id: ID! @id

    firstName: String
    lastName: String
    nickname: String

    title: String
    companyName: String

    region: String
}
`
```

**To Reproduce**
```
    const where: PersonWhere = {
      region_IN: ["North America"],
    };

    const fulltext = {
      personFullTextIndex: {
        phrase: "test",
      },
    };

    const total = await Person.aggregate({
      where,
      aggregate: {
        count: true,
      },
    });

    const totalAggregate = await Person.aggregate({
      where,
      fulltext,
      aggregate: {
        count: true,
      },
    });

    console.log("total", total);
    console.log("totalAggregate", totalAggregate);
```
They both returns the same total 

**Expected behavior**
I should get different values

**Screenshots**
These are the 2 queries generated by the libraries
<img width="1282" alt="image" src="https://github.com/neo4j/graphql/assets/12105333/0761e7e5-06fa-4e69-a2e2-5fa0f967829e">
---
<img width="1315" alt="image" src="https://github.com/neo4j/graphql/assets/12105333/c6e8761f-2332-4f30-a23c-e08c9a085ece">
The second query has the $fulltext param but the variable is not passed

**System (please complete the following information):**

```
  "dependencies": {
    "@neo4j/graphql-ogm": "^5.4.5",
    "graphql": "^16.9.0",
    "graphql-tag": "^2.12.6",
    "neo4j-driver": "^5.22.0",
  },
```

**Additional context**
Running a `Person.find` applies where and fulltext correctly to the query

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @nicecatch. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:
