### ISSUE TITLE
`{type}Connection` queries return results irrespective of the fulltext search phrase.

### ISSUE THREAD

**Issue by willhl** [neo4j/graphql#5378]
**Describe the bug**
Using a fulltext search phrase with a `{type}Connection` query returns results irrespective of the search phrase.

**Type definitions**
```
type Space
  @fulltext(
    indexes: [
      {
        indexName: "fulltext_index_space_name_number"
        fields: ["Name", "Number"]
      }
    ]
  ) {
  Id: ID! @id @unique
  Number: String
  Name: String!
}
```

**To Reproduce**

1. Start an instance using `neo4j/graphql@5.5.1` using above schema
2. Create some sample spaces with following mutation:
```
mutation CreateSpaces($input: [SpaceCreateInput!]!) {
  createSpaces(input: $input) {
    spaces {
      Id
    }
  }
}
```

Variables
```
{
  "input": [
    {
      "Number": "B1",
      "Name": "Bedroom 1"
    },
    {
      "Number": "B2",
      "Name": "Bedroom 2"
    },
    {
      "Number": "K3",
      "Name": "Kitchen"
    }  
  ]
}
```
4. Then run the following Query:
```
query SpacesSearchConnection($fulltext: SpaceFulltext) {
  spacesConnection(
    fulltext: $fulltext
  ) {
    totalCount
    edges {
      node {
        Name
        Number
      }
    }
  }
  spacesAggregate(
    fulltext: $fulltext
  ) {
    count
  }
}
```
Variables:
```
{
  "fulltext": {
    "fulltext_index_space_name_number": {
      "phrase": "Bedroom"
    }
  }
}
```

6. See the number of spaces returned for `spacesConnection` and for `spacesAggregate` differs.
```
{
  "data": {
    "spacesConnection": {
      "totalCount": 3,
      "edges": [
        {
          "node": {
            "Name": "Bedroom 1",
            "Number": "B1"
          }
        },
        {
          "node": {
            "Name": "Bedroom 2",
            "Number": "B2"
          }
        },
        {
          "node": {
            "Name": "Kitchen",
            "Number": "K3"
          }
        }
      ]
    },
    "spacesAggregate": {
      "count": 2
    }
  }
}
```

**Expected behavior**
-  Queries with `{type}Connection` should return only nodes which match the given fulltext search phrase.

**Screenshots**
![image](https://github.com/user-attachments/assets/29e109e9-1002-4461-8e4e-27be5d70b66e)

**System:**

* Linux (base image `node:20-alpine`)
* @neo4j/graphql@5.5.1
* Node.js 20

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @willhl. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @willhl! :pray: We will now prioritise the bug and address it appropriately.

**Comment by willhl** [comment]
Thank you @angrykoala for getting to this looked into, fixed and released so swiftly, it is much appreciated!
