### ISSUE TITLE
@plural directive is ignored

### ISSUE THREAD

**Issue by mobsean** [neo4j/graphql#5428]
**Describe the bug**
Coming from Version `3.24.3` I´m trying to update to current Version `5.5.2` and experienced different behavior for the @plural directive.

[docs](https://neo4j.com/docs/graphql/current/directives/schema-configuration/type-configuration/#type-definitions-plural) say: 
_This directive redefines how to compose the plural of the type for the generated operations. This is particularly useful for types that are not correctly pluralized or are **non-English** words._

This is exactly what I need. 

`V5.5.2` keeps adding an `s` in the end of every query and mutation.

**Type definitions**

```gql
    type Test @plural(value:"Test") {
        Name: String
    }
```

**To Reproduce**
 index.js 

```javascript
import { ApolloServer } from '@apollo/server';
import { startStandaloneServer } from '@apollo/server/standalone';
import { Neo4jGraphQL } from "@neo4j/graphql";
import neo4j from "neo4j-driver";

const typeDefs = `#graphql
    type Test @plural(value:"Test") {
        Name: String
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7474",
    neo4j.auth.basic("user", "password")
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

const server = new ApolloServer({
    schema: await neoSchema.getSchema(),
});

const { url } = await startStandaloneServer(server, {
    context: async ({ req }) => ({ req }),
    listen: { port: 4000 },
});

console.log(`🚀 Server ready at ${url}`);
```

**Expected behavior**

Use the plural as stated in docs and do not add an `s` in everthing (query, mutations, etc.) like in Version 3 of this lib.

**Screenshots**

from apollo interface: 

![image](https://github.com/user-attachments/assets/a59a8f3a-18b7-4736-a106-929a219fc4b2)

**System (please complete the following information):**

* OS: Windows
* Version: @neo4j/graphql@5.5.2
* Node.js version: 20

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mobsean. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mobsean! :pray: We will now prioritise the bug and address it appropriately.
