### ISSUE TITLE
Authorization examples in documentation don't work

### ISSUE THREAD

**Issue by avendiart** [neo4j/graphql#5435]
### Type definitions

```GraphQL
type User {
  id: ID! @id
}

type Post
  @authorization(
    validate: [{ where: { node: { author: { id: "$jwt.sub" } } } }]
  ) {
  title: String!
  content: String!
  author: User! @relationship(type: "AUTHORED", direction: IN)
}
```

### Steps to reproduce

Start server, observe crash

### What happened

```
GraphQLError: Invalid argument: validate, error: Field "author" is not defined by type.
```

### Version

5.5.2

### Database version

5.21.2

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @avendiart. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @avendiart, we don't seem to be able to reproduce this! Could you possibly provide more detailed instructions, or a repository with a reproduction in it?

**Comment by avendiart** [comment]
Here is the repo: https://github.com/avendiart/neo4j-graphql-authorization, run `pnpm install` followed by `pnpm start` and observe the crash. I assume it fails because `PostWhere` indeed has no `author` field (taken from a schema generated before adding `@authorization`)

```gql
input PostWhere {
  title: String
  title_IN: [String!]
  title_CONTAINS: String
  title_STARTS_WITH: String
  title_ENDS_WITH: String
  content: String
  content_IN: [String!]
  content_CONTAINS: String
  content_STARTS_WITH: String
  content_ENDS_WITH: String
  OR: [PostWhere!]
  AND: [PostWhere!]
  NOT: PostWhere
  authorAggregate: PostAuthorAggregateInput
}
```

If that is of any help, tests have been performed using node 22.5.1 and latest neo4j docker image (as defined in `docker-compose.yml`)

**Comment by avendiart** [comment]
I can get it to start by removing `arrayFilters: true` from `features.excludeDeprecatedFields`, but then I wonder why authorization would require deprecated fields to work correctly. Hope that information helps!

**Comment by darrellwarde** [comment]
> I can get it to start by removing `arrayFilters: true` from `features.excludeDeprecatedFields`, but then I wonder why authorization would require deprecated fields to work correctly. Hope that information helps!

This is very helpful - just spotted a small bug around the generation of filters which I will take a look at now. Thanks!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @avendiart! :pray: We will now prioritise the bug and address it appropriately.
