### ISSUE TITLE
Apollo Studio intellisense is misleading for this edge case

### ISSUE THREAD

**Issue by DanielAtCosmicDNA** [neo4j/graphql#5456]
**Describe the bug**
The bug is associated with https://github.com/neo4j/graphql/issues/5451
I understand there is currently a limitation in the subscriptions functionality as stated by [@darrellwarde](https://github.com/darrellwarde). But Apollo Studio Sandbox on localhost should not hint or even accept unavailable queries within subscriptions.

The problem is evidenced by the following screenshot:
![image](https://github.com/user-attachments/assets/d0a2fb93-60ba-4fe1-8e94-91486afdf88c)

When you type Ctrl + space, just after the conversation block, Apollo Studio Sandbox presents as if querying `seen` and `sender` was valid.

**Type definitions**
```GraphQL
type User {
  id: ID! @id @unique
  name: String
  conversations: [Conversation!]!
    @relationship(type: "CONVERSATIONS_USERS", direction: IN)
  seenMessages: [Message!]!
    @relationship(type: "SEEN_MESSAGES_USERS", direction: IN)

  messages: [Message!]! @relationship(type: "MESSAGES_SENDER", direction: OUT)
}

type Conversation {
  id: ID! @id @unique
  name: String

  messages: [Message!]!
    @relationship(type: "CONVERSATION_MESSAGES", direction: IN)
  users: [User!]! @relationship(type: "CONVERSATIONS_USERS", direction: OUT)
}

type Message {
  id: ID! @id @unique
  body: String

  seen: [User!]! @relationship(type: "SEEN_MESSAGES_USERS", direction: OUT)
  conversation: Conversation
    @relationship(type: "CONVERSATION_MESSAGES", direction: OUT)

  sender: User @relationship(type: "MESSAGES_SENDER", direction: IN)
}

type Subscription {
  messageCreated(conversationId: ID!): Message
}
```

**To Reproduce**
Steps to reproduce the behaviour:

Follow https://github.com/neo4j/graphql/issues/5451 then open Apollo Studio Sandbox on localhost and type Ctrl + space right after conversation block as shown in picture above.

**Expected behavior**
Seen and sender should not be populated there. And the subscription should be invalid as it does not follow the underlying database rules.

**Screenshots**
![image](https://github.com/user-attachments/assets/d0a2fb93-60ba-4fe1-8e94-91486afdf88c)

**System (please complete the following information):**

* OS: Windows version: 10.0.22624.1391
* Version: [e.g. @neo4j/graphql@1.0.0] ^5.5.2
* Node.js version: [e.g. 14.16.0] v20.14.0

**Additional context**

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @DanielAtCosmicDNA. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
You have applied filtering so that only a single event matching the single conversation title you have specified will ever be returned.

Without the filter applied, it would be perfectly valid to have `seen` and `sender` in the selection set, and they would be populated when relationships matching those fields are created.

It is not possible to dynamically change GraphQL type definitions based on inputs, this is not something we can do anything about. Sorry!
