### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by jbhurruth** [neo4j/graphql#5492]
Sorry to raise this here but I feel like I'm going crazy. Is there another set of documentation other than [neo4j.com/docs/graphql-manual/current/](https://neo4j.com/docs/graphql-manual/current/)? The number of features that I'm actively using or I see mentioned in bug reports that are not described in the aforementioned docs has convinced me that I cannot be looking in the right place. 

On a previous ticket I was asked to raise a bug again the docs repo but I honestly don't know where to start. Authorisation is the big one for me, as every new piece of information I find kinda blows my mind, e.g. the recent addition of a warning for lack of @subscriptionsAuthorization rules. Without writing super exhaustive tests to test the library itself I don't know how a dev would come across the need to implement these rules until some sensitive piece of data turns up in the wrong event handler.

I've gleaned 90% of my understanding of how the library should work from reading bug reports and more recently getting an LLM to search and summarise across the history of issues which, as you can imagine, is not ideal due to the amount of change has been made version to version.

At this point I'm quite nervous that my team has invested a lot of time building a complex system on top of this and at any moment we might discover some undocumented detail that undermines our design, especially around auth.

Could you guys point me in a direction to work through this uncertainty? I honestly love what you're doing with this and neo4j, and it has so much potential, but for a soon to be v6 library it doesn't always feel supportable

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jbhurruth. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by mjfwebb** [comment]
Hi @jbhurruth,

Thanks for this feedback. You're correct that the documentation is lacking details in some areas, and this is something we are actively working on improving. We are aware of the limited documentation on Authorization and will work on improving this area.

We're addressing the lack of `@subscriptionsAuthorization` documentation in [this PR](https://github.com/neo4j/docs-graphql/pull/165), and any feedback on these changes are very welcome.

If you have specific points that you notice are missing, please either comment here and I'll create an issue for them in the [docs repository](https://github.com/neo4j/docs-graphql/), or if you would like to you could create the issues yourself.

**Comment by mjfwebb** [comment]
I'm closing this issue but please do let us know if there are any specific parts of the documentation you think are lacking.

**Comment by fridaystreet** [comment]
It's pretty shocking tbh. All the links to previous documentation don't work.if some has posted a link in SO, it loads you see the document, then the neo4j site decides it no longer exists and redirects.

It's really not good enough fir a company and product of this magnitude. Where is the doco about @auth. I feel like I'm going mad. I've seen. So many references to it in bugs abd examples, but cannot find single image on neo4j site about it.

**Comment by mjfwebb** [comment]
@fridaystreet Depending on which the version of the library you are using, the auth related directives can be found here:


V5: https://neo4j.com/docs/graphql/current/security/
V4: https://neo4j.com/docs/graphql/4/authentication-and-authorization/
V3: https://neo4j.com/docs/graphql/3/auth/

From each of these pages I am able to select the version in the top-left of the page to switch between them. Is that not working for you?

**Comment by jbhurruth** [comment]
Missed the previous notification on this but got the recent emails. In case it's still relevant in this thread, here are a few big ones:

- There's nothing about the `when: BEFORE | AFTER` behaviour. Additionally, the associativity between combinations of `operations` and `when` for matching rules isn't covered.
- The possibility/limitations of using the authorisation directive on fields isn't mentioned, nor how this might interact with node-level rules.
- Subscription rules are described as more limited than other rules but then there is not detail about how they're limited. Considering that they can't consider connected nodes and I'd say that "more limitations" is an understatement and its more of a "minimal functionality" case in the context of a graph database.

**Comment by mjfwebb** [comment]
@jbhurruth Thanks for the valuable feedback!
