### ISSUE TITLE
Unable to add new relationship

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#555]
Hi I'm in a migration from neo4j-graphql-js. 

Here was my setup:

this is the abridged/relevant parts of the definition:

```
type Playlist {
    id: ID!,
    name: String!,
    things: [Thing] @relationship(type: "HAS_THING", direction: OUT),
}
```

```
mutation ADD_THING_TO_PLAYLIST($playlistId: ID!, $thingId: ID!){
  AddPlaylistThings(from: { id: $playlistId }, to: {id: $thingId}){
    to{
      id
    }
  }
}
```

And this is what I have now. It returns the proper playlist but things remains empty. `relationshipsCreated` returns 0.

```

mutation ADD_THING_TO_PLAYLIST($playlistId: ID!, $thingId: ID!){
  updatePlaylists(
    where: { id: $playlistId },
    connect: { things: { where: { node: { id:$thingId } }}}
  ){
    playlists {
      id
      things {
         id
       }
    }
    info {
      relationshipsCreated
    }
  }
}
```

Any idea what may be going wrong? It appears correct based on the documentation and lack of errors being spit out at me. Thank you in advance!

**Comment by keanugrieves** [comment]
I could be way off base and my server is down at the moment so I can't check GraphQL Playground, but IIRC, your connect argument should include an array somewhere along that chain.

**Comment by danielfein** [comment]
I don't think so, if you refer to the docs: https://neo4j.com/docs/graphql-manual/current/guides/migration-guide/mutations/#_connecting

You shouldn't need an array? I'm just trying to connect one Thing to one Playlist.

**Comment by keanugrieves** [comment]
Even though I haven't brought my server back up (in the middle of a big refactoring), here's my working update operation to connect any elements  — even a single element — from one type User to UserGroups, each of which has a many-to-many relationship with the other...

```
mutation {
  updateUserGroups(
    where: {
      id: "1635629294475"
    }
    update: {
      users: {
        connect: [
          {
            where: {
              node: {
                id: "1635629373327"
              }
            }
          }
        ]
      }
    }
  ) {
    userGroups {
      id
    }
  }
}
```
...and after writing that out, I just realized you're using the connect operation, which maybe has a different syntax.

But the update operation will connect nodes using an array argument.

Anyway, I hope this helps. Hopefully someone else can chime in!

**Comment by danielfein** [comment]
Hi Appreciate the help - unfortunately I'm not trying to get it working with Javascript yet. Starting with the GraphiQL interface as I'm trying to iterate until I find the mutation that works. The example structure you gave that works for your connect didn't work for me.

I still receive:

```
"info": {
        "relationshipsCreated": 0
      },
```

Thank you again. Maybe somebody else has an idea that might be able to help!

**Comment by danielfein** [comment]
Hi Does anybody know if this is an issue with the package or perhaps my queries are off in some way? They appear to be inline with the documentation.

**Comment by dmoree** [comment]
@danielfein Your query seems fine to me. I have reproduced this with `@neo4j/graphql@2.3.0`:

#### Type definitions
```graphql
  type Playlist {
    id: ID!
    name: String!
    things: [Thing] @relationship(type: "HAS_THING", direction: OUT)
  }

  type Thing {
    id: ID!
    title: String!
  }
```
#### To Reproduce
1. Clone
```
git clone git@github.com:dmoree/neo4j-graphql-playlist-thing.git
```
2. Seed and start server
```
cd neo4j-graphql-playlist-thing && yarn install && yarn seed && yarn start
```
3. Run the query in GraphiQL at `http://localhost:4000/graphql` (or as defined in `.env`)
###### Query
```graphql
mutation ADD_THING_TO_PLAYLIST($playlistId: ID!, $thingId: ID!) {
  updatePlaylists(
    where: { id: $playlistId }
    connect: { things: { where: { node: { id: $thingId } } } }
  ) {
    playlists {
      id
      name
      things {
        id
        title
      }
    }
    info {
      relationshipsCreated
    }
  }
}
```
###### Variables
```json
{
  "playlistId": "playlist1",
  "thingId": "thing2"
}
```

###### Response
```
{
  "data": {
    "updatePlaylists": {
      "playlists": [
        {
          "id": "playlist1",
          "name": "repudiandae",
          "things": [
            {
              "id": "thing2",
              "title": "sequi"
            }
          ]
        }
      ],
      "info": {
        "relationshipsCreated": 1
      }
    }
  }
}
```

My only thought is that perhaps the ids that are being passed are incorrect.

**Comment by danielfein** [comment]
Hi @dmoree - thank you for taking a look. Strangely, I cloned your repo and got the same results. I confirmed the playlist and thing IDs were returning the correct results.

```
query get_playlist($playlistId: ID!){
  playlists(where: { id: $playlistId}){
    id
    name
    things{
      id
      title
    }
  }
}```


```query get_thing($thingId: ID!){
  things(where: { id: $thingId}){
    id
  }
}```

These both return the nodes I expected them to.

Could it be an error with my database itself? Does that need updating in some way? I would share my package.json but I just used your entire codebase with the same result so I don't think it will help.

What would you do from here? Thanks again!

**Comment by dmoree** [comment]
It could perhaps be an error in your database. What database version are you using? That example was using a locally run instance of `4.3.2`. Also what is the debug output after cloning the repo and running it there?

**Comment by danielfein** [comment]
Legend @dmoree! That was it. I had to upgrade from 4.1.x to 4.3.x! That should probably be included in the migration docs, but thank you so much! I really appreciate your time
