### ISSUE TITLE
GraphQLError: Input Object type ArticleCreateInput must define one or more fields.

### ISSUE THREAD

**Issue by KleptoKat** [neo4j/graphql#556]
**Describe the bug**
When you create a type which only has _only_ auto generated and/or relationship fields on it and then attempt to run the generated schema through the "validateSchema" function in graphql (used by Apollo and the like) you will get multiple errors: GraphQLError: Input Object type ArticleCreateInput must define one or more fields; GraphQLError: Input Object type ArticleUpdateInput must define one or more fields. There is no way to disable this functionality in the graphql validateSchema function.

**Type definitions**
```graphql
type Journalist {
    articles: [Article]! @relationship(type: "HAS_ARTICLE", direction: OUT, properties: "HasArticle" )
}

interface HasArticle @relationshipProperties {
    createdAt: DateTime! @timestamp
}

type Article {
    id: ID! @id
}
```

**To Reproduce**
Run an apollo server with the above types:
```typescript

    const apolloServer = new ApolloServer({
        schema: neoSchema.schema,
        context: ({ request }) => ({ request }),
    });
```

Alternatively, run the schema through validateSchema:

```typescript
import { validateSchema } from "graphql";
const errors = validateSchema(neoSchema.schema);
expect(errors).toEqual([]);
```

errors should be an empty array.

**Expected behavior**
Empty inputs should be either:
a) Removed from the schema. Would break create and update functionality.
b) Have a placeholder field placed on them. Introduces possibility of frontend regressions if a client uses the placeholder field
c) Replaced with a scalar. Scalars can be empty objects.

**Additional context**
I am running on the latest master branch.

This should also take interfaces into account.

**Comment by angrykoala** [comment]
As discussed in #557, This should be properly documented with the workaround of adding a field so users can apply it themselves without adding unexpected fields in the final schema

**Comment by KleptoKat** [comment]
Hey @angrykoala @danstarns apologies for the delay in response, been doing some travelling.

My issue with simply documenting this issue is twofold:

 1. There are many cases where users have nodes that have no manually provided properties on them, just relationships and/or autogenerated properties. The error that Apollo Graphql gives the user is not verbose enough and would require the user to google the error to find that specific piece of documentation if they haven't thoroughly read the documentation. Then, they have to implement a workaround which, in my opinion, doesn't seem very professional because...
 2. Providing an extra property manually then allows for that property to be set in the database. Where _emptyInput did _not_ set the property on the node, providing your own _empty: String on the type definition could, potentially, allow a malicious actor to set things in the database that a user is not expecting, such as a really long string that could DOS the database by making it really huge.
 
So if adding this extra property is not an option, in addition to the documentation updates, I propose that we consider either a) removing the input from the system if it is empty which will require quite a bit of overhead or b) adding a console log/warning to the user that they have empty inputs and so the schema will not compile, with a link to the documentation/fix, and with a flag which can be passed to neo4j graphql to turn off the warning.

**Comment by angrykoala** [comment]
Good points @KleptoKat 
We re-discussed that and it totally makes sense. I'll reopen your PR.
