### ISSUE TITLE
Error: Cannot read property 'args' of undefined in subscriptions with args

### ISSUE THREAD

**Issue by Dajust** [neo4j/graphql#559]
**Describe the bug**
When you publish a subscription that accepts arguments, the above error is thrown.

**Type definitions**
```
type Query {
  greet: String
}
type Subscription {
  newMessage(to: String!): String
}
```

**Resolver function**

```
{
   Subscription: {
    newMessage: {
      subscribe: () => pubsub.asyncIterator('newMessage'),
    },
}
```
**To Reproduce**

1. Run a server with the above Subscription type definition
2. Subscribe for `newMessage` event ( on Apollo Studio/Playground )
3. Make the server Publish a `newMessage` event.
5. Remove the arguments from the Subscription type definition
6. Repeat step 3
7. See there is NO error

**Expected behavior**
Neo4jGraphQL should be able to publish a Subscription that accepts arguments on its type definition. But instead of doing so, it currently throws the `Error: Cannot read property 'args' of undefined`

**System (please complete the following information):**

-   OS: macOS
-   Version: "@graphql-tools/schema": "^8.3.1",
    "@neo4j/graphql": "^2.3.0",
    "subscriptions-transport-ws": "^0.9.19",
    "apollo-server-core": "^3.4.0",
    "apollo-server-express": "^3.4.0",
-   Node.js version: "16.6.0"

**Additional context**
It might also help to know that everything works well when you replace Neo4jGraphQL schema with `makeExecutableSchema`.

```js
const neoSchema = new Neo4jGraphQL({
  driver,
  typeDefs,
  resolvers,
});
const schema = neoSchema.schema;
// Everything works if we swtich back to  `makeExecutableSchema`, but that's old school 🤧🥴
// const schema = makeExecutableSchema({ typeDefs, resolvers })
```

**Comment by KleptoKat** [comment]
Have you got a sample of your newMessage resolver?

**Comment by Dajust** [comment]
Thanks, @KleptoKat, updated with the resolver function now.

**Comment by danstarns** [comment]
I wrote an int test for this in `/packages/graphql/tests/integration/issues/` and it works before and after, am I missing something or does this not fix the associated issue? 

```ts
import { Driver } from "neo4j-driver";
import { createSourceEventStream, parse } from "graphql";
import { gql } from "apollo-server";
import { generate } from "randomstring";
import neo4j from "../neo4j";
import { Neo4jGraphQL } from "../../../src/classes";
import { PubSub } from "graphql-subscriptions";

describe("https://github.com/neo4j/graphql/issues/559", () => {
    let driver: Driver;

    beforeAll(async () => {
        driver = await neo4j();
    });

    afterAll(async () => {
        await driver.close();
    });

    test("should not throw when subscription is subscribed to", async () => {
        const pubsub = new PubSub();

        const to = generate({
            charset: "alphabetic",
        });

        const typeDefs = gql`
            type Query {
                greet: String
            }

            type Subscription {
                newMessage(to: String!): String
            }
        `;

        const neoSchema = new Neo4jGraphQL({
            typeDefs,
            resolvers: {
                Subscription: {
                    newMessage: {
                        subscribe: () => pubsub.asyncIterator("newMessage"),
                    },
                },
            },
        });

        const query = `
            subscription {
                newMessage(to: "${to}")
            }
        `;

        const gqlResult = await createSourceEventStream(neoSchema.schema, parse(query), null, { driver });

        setTimeout(() => {
            pubsub.publish("newMessage", to);
        }, 1000);

        // @ts-ignore
        const next = await gqlResult.next();
        expect(next.value).toEqual(to);
    });
});
```
