### ISSUE TITLE
@customResolver over fetches fileds not stored in the database

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#5595]
**Describe the bug**

Given the existing test

https://github.com/neo4j/graphql/blob/7ad1e91e1247e72998cb40403f3ed4ef0faa045c/packages/graphql/tests/tck/directives/customResolver.test.ts#L151-L169

And [the documentation](https://neo4j.com/docs/graphql/current/directives/custom-logic/#_customresolver)

> Specifying the `@customResolver` directive on the field definition keeps `fullName` from being included in any query or mutation fields and hence as a property on the `:User` node in the database. 

The generated Cypher 

```cypher
MATCH (this:User) RETURN this { .firstName, .fullName } AS this
```
is wrong, since it includes the filed annotated with `@customResolver`

Expected cypher should be:

```cypher
MATCH (this:User) RETURN this { .firstName } AS this
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.
