### ISSUE TITLE
Module '"@graphql-tools/utils"' has no exported member 'SchemaDirectiveVisitor'

### ISSUE THREAD

**Issue by phucle225** [neo4j/graphql#561]
**Questions/Help**
I use @neo4j/graphql-ogm : 2.3.0, i see error in node_module , when build tsc (typescript:4.3.5), can you help me 
![image](https://user-images.githubusercontent.com/31835504/139919494-c38a42c5-3760-48a5-ad04-8b16bbd21b8d.png)

**Comment by phucle225** [comment]
tsconfig.json
![image](https://user-images.githubusercontent.com/31835504/139919869-2e163d4d-0757-405a-bc32-f3c72333a6d5.png)

**Comment by nagaky4** [comment]
i got the same issue, have any solution?

**Comment by danstarns** [comment]
Hi, @phucle225 & @nagaky4 thanks for reporting. Can you both share your package.json file please ?

**Comment by phucle225** [comment]
@danstar, sorry github don't support upload file json, i convert to txt
[package.txt](https://github.com/neo4j/graphql/files/7476249/package.txt)
ns

**Comment by danstarns** [comment]
> @danstar, sorry github don't support upload file json, i convert to txt [package.txt](https://github.com/neo4j/graphql/files/7476249/package.txt)

`@neo4j/graphql` supports versions `^7.10.0` of `@graphql-tools/utils` [here](https://github.com/neo4j/graphql/blob/master/packages/graphql/package.json#L66), in your package.json you are using version 8+. I think there could be a conflict here, try lowering your versions to be compatible with ours.

**Comment by phucle225** [comment]
@danstarns , i change version "@graphql-tools/utils": "^7.10.0", version about 6 month ago, but npm graphql-file-loader,load, schema dependencies @graphql-tools/utils, i change version all npm above range [3-6] month ago, more error :(
![image](https://user-images.githubusercontent.com/31835504/140380816-ee9a92f8-5e63-4782-bc08-b2504c88fee6.png)

**Comment by phucle225** [comment]
@danstarns Can you give me compatible versions?, graphql-file-loader,load, schema dependencies @graphql-tools/utils : ^7.10.0

**Comment by phucle225** [comment]
magic , i remove node_module, reinstall, keep graph-utils : 8.5.1, it work :)), thanks all.
