### ISSUE TITLE
What features to avoid for potential v6 migration

### ISSUE THREAD

**Issue by lkysow** [neo4j/graphql#5666]
I saw this comment

> In version 6.0.0 of the Neo4j GraphQL Library we're going to be making some drastic changes, including removing the ability to model 1:1 relationships as in this bug report - all relationships will have to be modelled as lists. Fundamentally, we've been battling the database for the past 3 years, and it's time to have the library only support features which the database itself natively supports. Until the database supports full schema including relationship cardinality, this will not be supported in the library, to avoid these kinds of issues.

in https://github.com/neo4j/graphql/issues/5250#issuecomment-2211092414 by @darrellwarde

And I was wondering if there might be a list of features or patterns we should potentially avoid right now to make an eventual migration to 6.0.0 easier?

**Comment by mjfwebb** [comment]
Hi @lkysow thanks for raising the question!

We're going to release some more details about this soon and we'll reply to this thread when we do.

**Comment by darrellwarde** [comment]
Hey @lkysow, we've written a short blog outlining the roadmap for the library: https://neo4j.com/developer-blog/neo4j-graphql-library-roadmap/

Additionally, we have the guide for migrating to Version 6: https://neo4j.com/docs/graphql/current/migration/
