### ISSUE TITLE
Combining PUSH and POP in update mutations

### ISSUE THREAD

**Issue by rsill-neo4j** [neo4j/graphql#5671]
While reading the docs about combining PUSH and POP in update mutations (https://neo4j.com/docs/graphql/5/mutations/update/#_combined_methods), the question arose if it's possible to combine a POP and a PUSH on the same array in a single mutation, for example to update an array ['a', 'b', 'c'] to ['a', 'b', 'd'] (tags array, see below) in a single mutation:

```
mutation {
    updateMovies (update: { tags_POP: 1, tags_PUSH: "d" }) {
        movies {
            title
            tags
        }
    }
}
```

the order is essential, since a PUSH followed by a POP would leave the array unchanged.
however, apparently no matter the order of the POP and PUSH operations inside "update", that is exactly what happens - the array doesn't change.

does PUSH take precedence? are the operations in "update" unordered?

is this a potential bug?

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @rsill-neo4j! :pray: We will now prioritise the bug and address it appropriately.
