### ISSUE TITLE
Unexpected behaviour when trying to connect two nodes with multiple connections of same type but different connection properties

### ISSUE THREAD

**Issue by a4GevatterTod** [neo4j/graphql#5677]
### Type definitions

```GraphQL
type City @mutation (operations: [CREATE, UPDATE, DELETE]) {
  id: ID! @id
  name: String!
  founded: Date!
  connectedTo: [City!]! @relationship(type: "CITY_CONNECTION", properties: "CityConnectionProperties", direction: OUT, queryDirection: DEFAULT_DIRECTED)
}

type CityConnectionProperties @relationshipProperties {
  transportationType: TransportationType! 
  distance: Int! 
}

enum TransportationType {
  Car
  Train
}
```

### Test data

```Shell
mutation CreateCities($input: [CityCreateInput!]!) {
  createCities(input: $input) {
    cities {
      id
      name
    }
  }
}


{
  "input": [
    {
      "name": "Hamburg"
    },
    {
      "name": "Bremen"
    }
  ]
}


mutation UpdateCities($where: CityWhere, $update: CityUpdateInput) {
  updateCities(where: $where, update: $update) {
    cities {
      id
      name
    }
    info {
      nodesCreated
      nodesDeleted
      relationshipsCreated
      relationshipsDeleted
    }
  }
}

{
  "update": {
    "connectedTo": [
      {
        "connect": [
          {
            "where": {
              "node": {
                "id": "Change me to id of Bremen"
              }
            },
            "edge": {
              "distance": 180,
              "transportationType": "Train"
            },
            "overwrite": false
          }
        ]
      }
    ]
  },
  "where": {
    "id": "Change me to id of Hamburg"
  }
}
```

### Steps to reproduce

1. Start Server
2. Execute query: `mutation UpdateCities($where: CityWhere, $update: CityUpdateInput) {
  updateCities(where: $where, update: $update) {
    cities {
      id
      name
    }
    info {
      nodesCreated
      nodesDeleted
      relationshipsCreated
      relationshipsDeleted
    }
  }
}
`
with this input: 
`{
  "update": {
    "connectedTo": [
      {
        "connect": [
          {
            "where": {
              "node": {
                "id": "Change me to id of Bremen"
              }
            },
            "edge": {
              "distance": 200,
              "transportationType": "Car"
            },
            "overwrite": false
          }
        ]
      }
    ]
  },
  "where": {
    "id": "Change me to id of Hamburg"
  }
}`

### What happened

I receive the following error:
```
{
  "errors": [
    {
      "message": "City.connectedTo required exactly once for a specific City",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateCities"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Neo4jGraphQLRelationshipValidationError: City.connectedTo required exactly once for a specific City",
          ....
        ]
      }
    }
  ],
  "data": null
}
```

### Expected behaviour

2 Nodes are creates. Those 2 nodes should have 2 connections. One connection of type "train" and distance of 180, and another of type "car" and distance of 200.

### Version

 "@apollo/server": "^4.11.0",     "@neo4j/graphql": "^5.9.0",

### Database version

4.4.26-community

**Comment by darrellwarde** [comment]
Hey @a4GevatterTod, not great news for you I'm afraid, this is actually just a limitation of the library in its current state - you cannot have multiple relationships between the same two nodes. Apologies I didn't understand the issue sooner.

This is something we're planning to look at down the line (in future major versions), but for now is something that will not be supported, so going to close this. Apologies again!

**Comment by a4GevatterTod** [comment]
Hi @darrellwarde, no problem here on my side, no apologies needed. It was just an experiment. 
One could always implement the mutation manually (which is what we already did). 
I just want to point out, that this is something which should be documented as a current limitation of the lib. If you are familiar with neo4j and cypher, one would expect this to work, as it's the way one would model this situation purely with cypher (in my mind). Here is a model from which i derived this city usecase: 

<img width="956" alt="Bildschirmfoto 2024-10-24 um 09 38 56" src="https://github.com/user-attachments/assets/8af2f71f-3623-4bdd-ba3c-ee122201420a">

As you can see, we have materials which are connected to suppliers. A material can be connected to one ore more suppliers, but this might be different for each plant. 



Thanks again!
