### ISSUE TITLE
graphql-ogm generate output contains missing types and therefore TypeScript errors

### ISSUE THREAD

**Issue by mscottreed** [neo4j/graphql#5679]
**Describe the bug**
graphql-ogm generate output contains missing types and therefore TypeScript errors

**Type definitions**
-- in the graphql file
```gql
type AssessmentCumulativeCost {
  opportunity: Opportunity
  idea: Idea
  costs: [Int!]!
}

type Query {
  assessmentCumulativeCosts(opportunityId: ID!): [AssessmentCumulativeCost!]!
}
```

-- output of the generate
```ts
export declare class AssessmentCumulativeCostModel {
  public find(args?: {
    where?: AssessmentCumulativeCostWhere;
    options?: AssessmentCumulativeCostOptions;
    selectionSet?: string | DocumentNode | SelectionSetNode;
    args?: any;
    context?: any;
    rootValue?: any;
  }): Promise<AssessmentCumulativeCost[]>;
```

---
however, the type for AssessmentCumulativeCostOptions, is not generated.

**To Reproduce**
Unfortunately when I separated out the type into its own graphql file, and did not include the 300 other types, the problem no longer reproduces.  So I am not sure how to give you a repro without giving you the whole codebase.

**Expected behavior**
I am not sure why the AssessmentCumulativeCostModel is generated at all, because we do not store the object in neo4j, it is a generated type only used for output in the graphql.

**Screenshots**
ERROR in ./apps/api/src/app/graphql/ogm-types.ts:126765:15
TS2552: Cannot find name 'AssessmentCumulativeCostOptions'. Did you mean 'AssessmentCumulativeCost'?
    126763 |     where?: AssessmentCumulativeCostWhere;
    126764 |
  > 126765 |     options?: AssessmentCumulativeCostOptions;
           |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    126766 |     selectionSet?: string | DocumentNode | SelectionSetNode;
    126767 |     args?: any;
    126768 |     context?: any;

**System (please complete the following information):**
* OS: macOS
* Version: @neo4j/graphql@5.9.0, @neo4j/graphql-ogm@5.9.0
* Node.js version: "node": ">=20.16.0"

**Additional context**

**Comment by mscottreed** [comment]
If you send me an upload link I think I can directly send you the ~45 graphql files.

**Comment by darrellwarde** [comment]
> If you send me an upload link I think I can directly send you the ~45 graphql files.

We've identified the problem on this one @mscottreed - working on a fix! Thanks for the offer!

**Comment by darrellwarde** [comment]
Hey @mscottreed, we've just been looking into this, and I'm afraid this is a case where the OGM falls short of the GraphQL Library. Custom queries and types which don't map to nodes do not have a clean way of mapping in the OGM.

The upcoming Version 6 and Version 7 releases of the library will make the use of `@node` mandatory for types mapping to nodes, but until this point, this is a hard problem to solve. 

As you can maybe imagine, adding this functionality into the OGM would be quite the endeavour. As we are about to cease active development on the OGM, I'm going to close this issue as a "won't do". However, if you wish to look into this yourself, we would be happy to engage in pull request reviews if you figure out a way to do this. 

Apologies for the bad news!

**Comment by mscottreed** [comment]
@darrellwarde - Is there an estimated timeframe for the release of 6?  I know that it will depend on testing, but I was just wondering if there is a rough guess (week, weeks, month, months)?

**Comment by darrellwarde** [comment]
> @darrellwarde - Is there an estimated timeframe for the release of 6? I know that it will depend on testing, but I was just wondering if there is a rough guess (week, weeks, month, months)?

Apologies, I have not explained myself well here. The OGM will _not_ be moving into Version 6 and Version 7 - it is a product that we need to go back to the drawing board with, and we want to be able to fully focus on the library through this period of quite intense development. We will be looking back into the OGM probably around mid next year.
