### ISSUE TITLE
Add `values`/`distinctValues` to TypeAggregateSelection

### ISSUE THREAD

**Issue by rcbevans** [neo4j/graphql#569]
I need to be able to query (distinct) type field values with filters applied to the type match for the purposes of populating field filter dropdowns in the front-end.

Given a type

```gql
type Book {
   id: ID!
   title: String!
   year: Int!
}
```

I'd like to get a list of the `year` field values for books with "Neo4j" in the name.

This seems like a natural extension of the neo4j graphql `Aggregate` queries which are generated and already have nice support for `BookWhere` filtering.

I'd like to see the `TypeAggregateSelection`, e.g `IntAggregateSelection` include a `values` or `distinctValues` field which will use the `collect` aggregate function to return a list of field values based on the matched nodes.

For example:

```gql
query bookYears($where: BookWhere!) {
 booksAggregate(where: $where) {
    year {
      distinctValues
    }
  }
}
```

with parameters:

```json
{
  where: {
    title_MATCHES: "(?i).*?neo4j.*?"
  },
}
```

should return a `[Int!]` containing the distinct publish years of books with a title including "neo4j".

Given that there could be a lot of matches resulting in a long array of values,  depending on the dataset, it would be nice if `distinctValues` field could take a `where`/`options` arg to filter/offset/limit/sort the results.

I could implement a query doing this myself, but I have been unable to figure out a nice way of utilizing the cypher translation capabilities of the neo4j-graphql library to allow me to reuse the existing `TypeAggregate`/`TypeWhere` functionality provided by the library, meaning I'd have to reimplement support from scratch, or hand-roll/maintain support in a custom resolver.

I tied to use `mergeSchemas` from graphql tools to extend the `TypeAggregateSelection` type with a custom cypher field which does what I want to collect the values, but the Neo4jGraphQL type doesn't then seem to see/generate the appropriate `apoc.do.it` for the added cypher field.

I tried to add a `collect` field on the TypeAggregateSelection hoping that the neo4j translate-aggregation would use collect as the operation as it does for min, max, but it also doesn't seem to see the field selection to emit the cypher into the executed query.

**Comment by rcbevans** [comment]
Updating `make-augmented-schema.ts` to add a `values` field returning a corresponding type array, and adding a check for `operator == "values"`, in which case operator is replaced with `collect`, in `translate-aggregate.ts` seems to work for types other than datetime.

the `field.typeMeta` for datetime fields is the primitive non-array type and so `createDateTimeElement` in `create-daetime-element.ts` is not outputting the necessary list comprehension, other types including strings, floats and ints seem to be resolving correctly.  Passing `[DateTime]` typeMeta to `createDateTimeElement` will probably do the trick, I'm not sure what the best way to get that is though.

**Comment by rcbevans** [comment]
The `numerical` and `id` resolvers do not currently handle resolving arrays of Ints,  adding 

```
    if (Array.isArray(value)) {
        return value.map((v) => {
            if (isInt(v)) {
                return (v as Integer).toNumber();
            }

            return v;
        });
    }
```

to the resolver allows [Int!] to be resolved correctly.

```
function numerical(source, args, context, info) {
    const value = defaultFieldResolver(source, args, context, info);

    if (Array.isArray(value)) {
        return value.map((v) => {
            if (isInt(v)) {
                return (v as Integer).toNumber();
            }

            return v;
        });
    }

    // @ts-ignore: outputValue is unknown
    if (isInt(value)) {
        return (value as Integer).toNumber();
    }

    return value;
}
```

**Comment by rcbevans** [comment]
It's also possible to collect distinct values from array fields with something like

```
MATCH (n:Node)
RETURN {things: apoc.coll.toSet(REDUCE(out = [], r IN collect(n.things) | out + r))}
```

**Comment by danstarns** [comment]
Thanks for your feature request we have tracked this internally and should get to it soon :)

**Comment by darrellwarde** [comment]
We can see the value of adding an argument for getting distinct values from a query (#779), but we don't have appetite for adding these fields into our aggregation results.
