### ISSUE TITLE
Add labels based on the properties of the node

### ISSUE THREAD

**Issue by magaton** [neo4j/graphql#574]
**Is your feature request related to a problem? Please describe.**
Having:
``` 
type Client {
   id: String!
   login: String!
   name: String!
   type: String!
}
```
I would like to add a dynamic label equal to `client.type` in mutation.

**Additional context**
It would be great if besides `$jwt` and `$context`, $this also becomes available in the `@node` directive

**Comment by danstarns** [comment]
Thank you for this, we have added this to our board internally and shall shape and discuss if it's something to add.

**Comment by Kubera2017** [comment]
Similar idea https://github.com/neo4j-graphql/neo4j-graphql-js/issues/567

**Comment by angrykoala** [comment]
Hi @magaton 
After some discussion, we decided that this kind of use case seems an anti-pattern within a graph database, as any filtering based on labels can be done with properties. This also may lead to an ambiguous schema.

If you have an example use case that we may have not considered, feel free to comment here.
