### ISSUE TITLE
Sorting vector search results by score without score in selection set results in error

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#5759]
### Type definitions

```GraphQL
type Movie
  @vector(
    indexes: [
      {
        indexName: "MovieIndex"
        embeddingProperty: "embedding"
        queryName: "searchMovies"
      }
    ]
  )
  @node {
  title: String!
  released: Int!
}
```

### Steps to reproduce

The execution of a query such as the following will result in a Cypher syntax error:

```gql
query($vector: [Float!]) {
  searchMovies(vector: $vector, sort: { score: DESC } ) {
    edges {
      node {
        title
      }
    }
  }
}
```

### What happened

Error: ```Variable `var1` not defined (line 10, column 14 (offset: 308))```

### Version

latest

### Database version

5.24

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.
