### ISSUE TITLE
Ordering of sorting criteria not honoured in vector search query

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#5760]
### Type definitions

```GraphQL
type Movie
  @vector(
    indexes: [
      {
        indexName: "MovieIndex"
        embeddingProperty: "embedding"
        queryName: "searchMovies"
      }
    ]
  )
  @node {
  title: String!
  released: Int!
}
```

### Steps to reproduce

The generated Cypher of the following query sorts by score first, as indicated by the array index in the `sort` argument.

```gql
query ($vector: [Float!]) {
  searchMovies(
    vector: $vector
    sort: [{ score: ASC }, { node: { title: DESC } }]
  ) {
    edges {
      score
      node {
        title
      }
    }
  }
}
```

This query _should_ sort by title first, but it does not - the generated Cypher is identical to above and the results are identical:

```gql
query ($vector: [Float!]) {
  searchMovies(
    vector: $vector
    sort: [{ node: { title: DESC } }, { score: ASC }]
  ) {
    edges {
      score
      node {
        title
      }
    }
  }
}
```

### Version

latest

### Database version

5.24.1

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.
