### ISSUE TITLE
Aggregation filtering missing from schema for relationships to a union

### ISSUE THREAD

**Issue by solter** [neo4j/graphql#577]
**Describe the bug**
When I define a relationship that points at a union, the aggregation filtering is missing from the schema.

**Type definitions**
(pulled from [Unions - Neo4j GraphQL Library docs](https://neo4j.com/docs/graphql-manual/current/type-definitions/unions/))
```graphql
union Content = Blog | Post

type Blog {
    title: String
    posts: [Post] @relationship(type: "HAS_POST", direction: OUT)
}

type Post {
    content: String
}

type User {
    name: String
    content: [Content] @relationship(type: "HAS_CONTENT", direction: OUT)
}
```

The following query is not supported after the schema has been generated:
```graphql
query findUsersWithMultiplePosts{
  users( where: { contentAggregate: { count_GT: 1 } }) {
    name
  }
}
```

**To Reproduce**

1. Run a basic server built using the same steps as on the [Getting Started Page](https://neo4j.com/docs/graphql-manual/current/getting-started/)
   - optional: populating database with some data
2. Open the Apollo sandbox
3. Try running the query
```graphql
query findUsersWithMultiplePosts{
  users( where: { contentAggregate: { count_GT: 1 } }) {
    name
  }
}
```

**Expected behavior**
The query should've returned all users with more than 1 content entry. Instead it errors out because the where clause only supports `contentConnections`, but not a `contentAggregate` filter. 

**Screenshots**

**System (please complete the following information):**

-   OS: Windows
-   Version: @neo4j/graphql@2.4.0
-   Node.js version: 14.17.4

**Additional context**

**Comment by danstarns** [comment]
> @danstarns, was this left out of scope, or just a gap in the feature set?

It was left out of scope, it was proved to be difficult when doing nested projections.

**Comment by darrellwarde** [comment]
> > @danstarns, was this left out of scope, or just a gap in the feature set?
> 
> It was left out of scope, it proved to be difficult when doing nested projections.

Thanks for the info, will re-label this as a feature request and track in Trello.

**Comment by darrellwarde** [comment]
Although slightly newer, this is covered by #810 which also covers a couple of other missing input fields as well.
