### ISSUE TITLE
Add dotenv config to jest.config.base.js to configure environment variables for tests

### ISSUE THREAD

**Issue by KleptoKat** [neo4j/graphql#580]
**Is your feature request related to a problem? Please describe.**

It's frustrating to add environment variables via command line every time you want to run a test.

**Describe the solution you'd like**

Add the following to `jest.config.base.js:

```js
require('dotenv').config();
````

This will then allow you to create a .env file and place your docker-compose.yaml variables in it:

```
NEO_USER=neo4j
NEO_PASSWORD=test
NEO_URL=neo4j://localhost:7687
```

Additionally, this allows you to run and debug tests from vscode.

**Comment by darrellwarde** [comment]
Seems like a good idea! This is generally the kind of thing we address during "cool-down" between our development phases, or feel free to add this in yourself. 🙂
