### ISSUE TITLE
Cannot resolve properties from common interface with new interface

### ISSUE THREAD

**Issue by KleptoKat** [neo4j/graphql#583]
**Describe the bug**

When you add a separate interface to a type it is resolved with inline fragments but its properties are not projected. See below:

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

```graphql
interface Show {
  title: String
}

interface Awardable {
  awardsGiven: Int!
}

type Actor implements Awardable {
  name: String
  awardsGiven: Int!
  actedIn: [ Show! ] @relationship(type: "ACTED_IN", direction: OUT)
}

type Movie implements Show & Awardable {
  title: String
  awardsGiven: Int!
}

type Series implements Show & Awardable {
  title: String
  awardsGiven: Int!
}

type ShortFilm implements Show {
  title: String
}
```

**To Reproduce**

1. Run a server with the above type definitions
2. Run the following neo4j query:

```
CREATE (a:Actor { name:  "aaa", awardsGiven: 0 })
CREATE (a)-[:ACTED_IN]->(:Series { title: 'stranger who', awardsGiven: 2 })
CREATE (a)-[:ACTED_IN]->(:Movie { title: 'doctor things', awardsGiven: 42 })
CREATE (a)-[:ACTED_IN]->(:ShortFilm { title: 'all too well' })
```

3. Run the following graphql query:
```graphql

query shows {
  actors {
    name
    __typename
 	  actedIn {
      title
      ...on Awardable {
        awardsGiven
      }
    }  
  }
}


```

4. See error: `Cannot return null for non-nullable field Movie.awardsGiven.`

**Expected behavior**

Because awardsGiven is set for both the series and the movie, we would expect it to return but it doesn't so we get an error. When we debug the cypher query, it looks something like this:

```
MATCH (this:Actor)
WITH this
CALL {
WITH this
MATCH (this)-[:ACTED_IN]->(this_Movie:Movie)
RETURN  { __resolveType: "Movie", title: this_Movie.title } AS actedIn
UNION
WITH this
MATCH (this)-[:ACTED_IN]->(this_Series:Series)
RETURN  { __resolveType: "Series", title: this_Series.title } AS actedIn
UNION
WITH this
MATCH (this)-[:ACTED_IN]->(this_ShortFilm:ShortFilm)
RETURN  { __resolveType: "ShortFilm", title: this_ShortFilm.title } AS actedIn
}
RETURN this { .name, actedIn: collect(actedIn) } AS this
```

As you can see, awardsGiven is never projected in neither Series nor Movie. We should detect if Series or Movie implements the desired interface and add those properties to the projection, if required. In this case, ShortFilm does not implement awardsGiven so it should not have awardsGiven projected.

**System (please complete the following information):**

-   OS: linux
-   Version: master
-   Node.js version: 14

**Comment by amitozalvo** [comment]
Also experiencing this bug, any workarounds?

**Comment by dmoree** [comment]
@amitozalvo I'm not sure if there is a workaround for the use case described in the issue as there may be a bug that removes these fields in the projection (see proposed fix https://github.com/neo4j/graphql/pull/590/commits/b7c157f478c3d6ec0bdac4877a1c0eab28455212).
