### ISSUE TITLE
Neo4j Introspector misses some relationships

### ISSUE THREAD

**Issue by tfunken** [neo4j/graphql#5884]
**Describe the bug**
We use neo4j introspector to generate our graphql structure. We have a relationship called "Value" that is reused between several pairs of different node types (7 in total). However, in the generated graphql schema, there are only two relationships, because there is a limit clause when reading connected node types [to internal struct](https://github.com/neo4j/graphql/blob/dev/packages/introspector/src/to-internal-struct.ts#L117):

```
const relationshipsRes = await conSession.readTransaction((tx) =>
    tx.run(`
      MATCH (n)-[r:${escapedType}]->(m)
      WITH n, r, m LIMIT 100
      WITH DISTINCT labels(n) AS from, labels(m) AS to
      WITH from, to WHERE SIZE(from) > 0 AND SIZE(to) > 0
      RETURN from, to, "${relType.replace(/"/g, '\\"')}" AS relType`)
); 
```
Therefore, only node pairs within the first 100 results are considered for the generated graphql schema.

**To Reproduce**
Create a schema with a relationship between multiple pairs of node types and create more than 100 instances of the relationship per node pair. Then use introspector to create the graphql schema for the database.

**Expected behavior**
Generate relationships for all node pairs in the graph that use that relationship type.

**System (please complete the following information):**

* OS: Ubuntu 22 LTS
* Version: @neo4j/introspector: 4.0.0
* Node.js version: 22.11.0

**Comment by angrykoala** [comment]
Hi @trislanger 

I've added your proposed change to the introspector. This change will be available from version 5 of the graphql library and introspector onwards
