### ISSUE TITLE
Filter on interfaces is not working

### ISSUE THREAD

**Issue by Masadow** [neo4j/graphql#5887]
**Describe the bug**
Filter on interface doesn't behave as expected

**Type definitions**
```gql
type Base {
  id: ID!
}

type A implements Base {
  id: ID!
}

type B implements Base {
  id: ID!
}

type Test {
  base: Base! @relationship(type: "HAS", direction: OUT)
}
```

**To Reproduce**

Use the following query

```gql
query q1 {
  tests(where: { base: { id: "some_valid_id" } }) {
    base {
      id
    }
  }
}

query q2 {
  tests {
    base {
      id
    }
  }
}
```
**Expected behavior**

q1 should results in Test visible in q2

Actually, q1 doesn't return if it's a A but returns if it's a B

**System (please complete the following information):**

* OS: macOS
* Version: 5.11.1
* Node.js version: not relevant

**Additional context**

I found out that the generated query produces something like : 

```
MATCH (this:Test)
CALL {
    WITH this
    OPTIONAL MATCH (this)<-[:HAS]-(this1:A)
    WITH *, count(this1) AS baseCount
    OPTIONAL MATCH (this)<-[:HAS]-(this2:B)
    WITH *, count(this2) AS baseCount
    WITH *
    WHERE ((baseCount <> 0 AND this1.id = $param0) OR (baseCount <> 0 AND this2.id = $param1))
    RETURN count(this) = 1 AS var3
}
WITH *
... rest of query
```

The issue is that `baseCount` is overriden in the following query, it should be renamed to `baseCount1` and `baseCount2` respectively

Looks like an easy fix but I can't install the library locally on branch lts (which should be similar to 5.11.1), weird errors in graphql package appears when I start my project that I can't troubleshoot like :

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
GraphQLError: Enum "SubscriptionEvent" cannot represent value: "RELATIONSHIP_CREATED"
```

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Masadow! :pray: We will now prioritise the bug and address it appropriately.
