### ISSUE TITLE
Missing optional arguments on cypherFields are not passed to cypher query causing runtime error

### ISSUE THREAD

**Issue by rcbevans** [neo4j/graphql#595]
Given the following simple schema:

```gql
type Account {
    id: ID!
    name: String!
}

input ListAccountOptions {
    offset: Int
    limit: Int
}

type Query {
    listAccounts(options: ListAccountOptions): [Account!]!
        @cypher(
            statement: "MATCH (accounts:Account) RETURN accounts SKIP coalesce($options.offset, 0) LIMIT coalesce($options.limit, 30)"
        )
}
```

Executing the GraphQL query

```gql
query MyListAccounts {
    listAccounts {
        id
        name
    }
}
```

The library does not pass an `options` parameter as part of the query execution, causing the execution to throw a runtime error: 

>Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: org.neo4j.exceptions.ParameterNotFoundException: Expected parameter(s): options

Unfortunately, it doesn't seem to be possible to coalesce non-existent parameters to a value either, so starting the statement with

```
WITH coalesce($options, NULL) AS options
```

still throws the same error.

As a consequence, it doesn't seem possible to have cypher fields with optional arguments.

**Comment by maieulChevalier** [comment]
As a workaround, I think you can provide `null` to the optional arguments. It seems to work for simple arguments at least.

For example, given the following type defs:

``` graphql
type Post {
  title: String!
  text: String
}

type Mutation {
  createPost(title:String!, text:String): Post!
        @cypher(
            statement: "CREATE (p:Post{title:$title, text:$text) RETURN p"
        )
}
```
Executing following mutation

```graphql
mutation {
  createPost(title:"neo4j/graphql is cool") {
    title
  }
}
```
throws a **similar** error (It's not `apoc.cypher.runFirstColumn` but `apoc.cypher.doIt`)

> Failed to invoke procedure `apoc.cypher.doIt`: Caused by: org.neo4j.exceptions.ParameterNotFoundException: Expected parameter(s): text

But if you add `text:null`

```graphql
mutation {
  createPost(title:"neo4j/graphql is cool", text:null) {
    title
  }
}
```

The mutation works. Though having to add `null` to all optional arguments doesn't result in a good developer experience. 

Right now I rely on multiple almost identical queries and mutations with the `@cypher directive` to achieve unsupported features, where I could have only a few queries and mutations with the `@cypher directive` if we could use optional arguments/parameters.

**Comment by dmoree** [comment]
@rcbevans The `@cypher` directive, I believe, passes default values for the argument, so if you write the type definitions as:

```graphql
type Account {
    id: ID!
    name: String!
}

input ListAccountOptions {
    offset: Int
    limit: Int
}

type Query {
    listAccounts(options: ListAccountOptions = {}): [Account!]!  # <-- NOTE: Default argument, {}
        @cypher(
            statement: "MATCH (accounts:Account) RETURN accounts SKIP coalesce($options.offset, 0) LIMIT coalesce($options.limit, 30)"
        )
}
```

This should pass `$options` as a parameter which would make the cypher statement work as intended.
