### ISSUE TITLE
Support for soft deletion

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#608]
In some cases I want to prevent certain nodes from being hard deleted. In such cases it would be nice to be able to mark nodes as deleted. A soft deleted node shouldn't be mutable until it is restored.

**Comment by darrellwarde** [comment]
Hey @AccsoSG, it's unlikely we'll implement soft deletion as we see this more of a user implementation. However, I can give you a bit of a dirty hack using the `@auth` directive that might work for you!

Let's say you have an object type with a field `deleted`:

```graphql
type User {
  name: String!
  deleted: Boolean! @default(value: false)
}
```

You could extend that type with an `@auth` directive with a rule based on the `deleted` field to throw a forbidden error if it is `true`:

```graphql
extend Type User @auth(
    rules: [
        {
            operations: [CREATE, DELETE, UPDATE, CONNECT, DISCONNECT],
            allow: { deleted: false }
        }
    ]
)
```

A bit hacky, but it should prevent accidental mutation of soft-deleted nodes! Going to close this issue though, let me know if this worked for you. 🙂

**Comment by AccsoSG** [comment]
Hi @darrellwarde,

your solution works for me. Thanks very much! 
The only downside is that the error message isn't very helpful to the client. Do you have an idea to define a special error message for such a special case? The current error message for the client looks like this:
````json
{
  "errors": [
    {
      "message": "Forbidden",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateZdfApplications"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [...]
        }
      }
    }
  ],
  "data": null
}
````

**Comment by darrellwarde** [comment]
> Hi @darrellwarde,
> 
> your solution works for me. Thanks very much! The only downside is that the error message isn't very helpful to the client. Do you have an idea to define a special error message for such a special case? The current error message for the client looks like this:
> 
> ```json
> {
>   "errors": [
>     {
>       "message": "Forbidden",
>       "locations": [
>         {
>           "line": 2,
>           "column": 3
>         }
>       ],
>       "path": [
>         "updateNode"
>       ],
>       "extensions": {
>         "code": "INTERNAL_SERVER_ERROR",
>         "exception": {
>           "stacktrace": [...]
>         }
>       }
>     }
>   ],
>   "data": null
> }
> ```

That's great! Sadly no support for custom error messages yet, but it is something that we want to add support for in the near future. 🙂
