### ISSUE TITLE
Usage of OGM in custom directive

### ISSUE THREAD

**Issue by pmakowski23** [neo4j/graphql#612]
Hi, I have a problem with the usage of OGM in my nextJS app.
[project on github](https://github.com/pmakowski23/AJI/tree/master/Exercise_4)
I wanted to create a custom directive to implement business logic instead of creating a custom resolver for the model. And I need to check the value before updating and take the one from the update. Currently in `/api/graphql/checkStateDirective/index.ts` you have my implementation. I want to change `const currentState = states.indexOf(source.state)` as this is false (I get this way value from the update) with a query to DB with an id of the changing element to find its current value and compare it with the value from the update. 
My current implementation was that I created `export const ogm = new OGM({ typeDefs, driver })` in `graphql.ts` and then imported it in `/api/graphql/checkStateDirective/index.ts` and used it normally
```
const Parent = ogm.model(info.parentType.name);
const id = source.id
const currentState = states.indexOf(await Parent.find({ where: { id } }))
```
But I get an error `Expected undefined to be a GraphQL schema.` as the response :c 

I already wrote about this on discord and was asked to make it a GitHub issue

**Comment by jbhurruth** [comment]
What version of graphql are you using? I just had this issue while updating packages which included bumping graphql to v16.0.1
Downgrading to v15.7.2 solved this issue for me. It looks like this library doesn't support v16 yet
