### ISSUE TITLE
Generate function does not respect plural directive from schema

### ISSUE THREAD

**Issue by lennerd** [neo4j/graphql#626]
**Describe the bug**

When using `generate` on GraphQL types which have a `plural` directive, the return types for the models `create` and `update` methods are not generated correctly and therefore referencing a not existing type.

**To Reproduce**

Example for generating types (with the german word `Steckbrief` and the plural version `Steckbriefe`):

``` js
const graphQlOgm = require("@neo4j/graphql-ogm");
const path = require("path");
const invariant = require("tiny-invariant");

const typeDefs = `
  type Steckbrief @node(plural: "Steckbriefe") {
    id: ID
    titel: String
  }
`;

const ogm = new graphQlOgm.OGM({ typeDefs });

async function main() {
  const outFile = path.resolve(process.cwd(), process.argv.slice(2)[0]);

  await graphQlOgm.generate({
    ogm,
    outFile: "invalid-types.ts",
  });

  console.log("Types Generated");
}

main();
```

Excerpt from the generated file:

```ts
export declare class SteckbriefModel {
  // … other methods from the generate model
  public create(args: {
    input: SteckbriefCreateInput[];
    selectionSet?: string | DocumentNode | SelectionSetNode;
    args?: any;
    context?: any;
    rootValue?: any;
  }): Promise<CreateSteckbriefsMutationResponse>;
  public update(args: {
    where?: SteckbriefWhere;
    update?: SteckbriefUpdateInput;

    selectionSet?: string | DocumentNode | SelectionSetNode;
    args?: any;
    context?: any;
    rootValue?: any;
  }): Promise<UpdateSteckbriefsMutationResponse>;
}
```

**Expected behavior**
The types returned with a promise should be named `CreateSteckbriefeMutationResponse` and `UpdateSteckbriefsMutationResponse` (see `Steckbriefs` vs the expected `Steckbriefe`)

Hope this are all the information you need to reproduce this. Reach out to me if you have anymore questions.

**Comment by darrellwarde** [comment]
Hey @lennerd - I've just tested this on `master` (current release) and `dev` (next release). Whilst this is indeed broken on `master` and as such the current release, this will work as expected in the next release.

As such, I'm going to close this as fixed, and it will be released in 3.0.0 in a couple of weeks time. This will be a breaking release, although not as severe as 1.x->2.x was.
