### ISSUE TITLE
@auth directive does not work using _IN when checking user is member of security group at node level

### ISSUE THREAD

**Issue by GlenOFI** [neo4j/graphql#631]
**Describe the bug**
I want to implement node level security using security groups. So each node will have a property called "groups" which is a string or ideally an array of strings, which defines which security groups have permission to access the node. In the JWT is a claim called "groups" which is an array of strings which represent the Ids of the security groups that the user is a member of. 

In the documentation when using "where" I should be able to append "_IN" to the end of my parameter to search within an array: https://neo4j.com/docs/graphql-manual/current/filtering/#_array_comparison

However, when I run the code using this:
`extend type SavedVisualisation @auth(rules: [{ where: { groups_IN: "$context.groups" } }])`
The Cypher produced does not check the array of groups that the user is a member of, it ignores it and returns all nodes: 
`MATCH (this:SavedVisualisation)
RETURN this { .name, .data, .groups } as this`

If I remove the "_IN" suffix:
`extend type SavedVisualisation @auth(rules: [{ where: { groups: "$context.groups" } }])`
Then it processes it as a string to string comparison and returns no results. The Cypher produced is:
`MATCH (this:SavedVisualisation)
WHERE this.groups IS NOT NULL AND this.groups = $this_auth_where0_groups
RETURN this { .name, .data, .groups } as this
Params:
{
  "this_auth_where0_groups": [
    "ee397bba-15fc-4531-8e71-25c7906bd3d9",
    "bb4d4bd4-1fab-4c9e-aaa3-ed87b11fe9a6",
    "f01d348e-7311-4536-b46c-be391d1bf237",
    "2d06a778-73b8-4039-9070-f2dde33e1418",
    "09f7ad0f-9038-4253-83b3-e5ca3266d4d7",
    "075724dd-418b-4f48-9052-130a7487ea9c",
    "a6b51304-4257-4cf6-befe-c7add32f5ea9",
    "2614e71f-39cf-40c1-b565-4ca90b5acfca",
    "b0d1ef9b-104e-4496-a841-dd44aede759b",
    "15cb6599-58db-4623-b229-e4d17d300e35",
    "5f15b895-24eb-42f3-9771-f77007cffc1a",
    "3054d774-2693-43dc-8622-43128595df8f",
    "f7f0b4ae-19da-490b-91a1-17955fac1d89"
  ]
}`

**Type definitions**
`type SavedVisualisation {
	_id: ID! @cypher(statement: "RETURN ID(this)")
	data: String!
	name: String!
	groups: String
}`
// Returns all nodes
`extend type SavedVisualisation @auth(rules: [{ where: { groups_IN: "$context.groups" } }])`
// Returns no results:
//`extend type SavedVisualisation @auth(rules: [{ where: { groups: "$context.groups" } }])`

**To Reproduce**

1. Run a server with the following code...
2. `const groups = [
    'ee397bba-15fc-4531-8e71-25c7906bd3d9',
    'bb4d4bd4-1fab-4c9e-aaa3-ed87b11fe9a6',
    'f01d348e-7311-4536-b46c-be391d1bf237',
    '2d06a778-73b8-4039-9070-f2dde33e1418',
    '09f7ad0f-9038-4253-83b3-e5ca3266d4d7',
    '075724dd-418b-4f48-9052-130a7487ea9c',
    'a6b51304-4257-4cf6-befe-c7add32f5ea9',
    '2614e71f-39cf-40c1-b565-4ca90b5acfca',
    'b0d1ef9b-104e-4496-a841-dd44aede759b',
    '15cb6599-58db-4623-b229-e4d17d300e35',
    '5f15b895-24eb-42f3-9771-f77007cffc1a',
    '3054d774-2693-43dc-8622-43128595df8f',
    'f7f0b4ae-19da-490b-91a1-17955fac1d89',
];

const server = new ApolloServer({
    context: ({ req }) => ({
        groups: groups,
    }),
    schema: typeDefs,
})`

2. Run the following Mutations...
3. `mutation {
  createSavedVisualisations(input: [
    {
      name: "test1",
      data:""
      groups: "ee397bba-15fc-4531-8e71-25c7906bd3d9"
    },{
      name: "test2",
      data:""
      groups: "12345678-15fc-4531-8e71-25c7906bd3d9"
    }
  ]){
    savedVisualisations{
      name
      groups
    }
  }
}`
3. Run the following Query...
3. `query	{
  savedVisualisations{
    name
    data
    groups
  }
}`

**Expected behavior**
Only return nodes where the nodes group is in the user's list of groups (set in the context) ie node with name "test1.

**System (please complete the following information):**

-   OS: Windows 10
-   Version: @neo4j/graphql@2.4.0
-   Node.js version: 14.15.4

**Additional context**
Should this work using groups_IN? Is there another easier way of achieving node level security? Will it be possible for a node to define groups as an array of strings and compare it to an array of string in the JWT/context?

**Comment by rcbevans** [comment]
This is a known issue. I have had a PR up for a while to add support for modifiers such as `_IN` on auth rules, see https://github.com/neo4j/graphql/pull/500, but the core dev team have asked for changes which I haven't gotten around to working on yet.

If it's something you are willing/able to help with I'd happily take contributions into my branch to get the PR unblocked.

**Comment by darrellwarde** [comment]
We're thinking about our long-term roadmap and want to consolidate our backlog so that we can accurately plan moving forward. As such, this is being closed in favour of #1871 where we will capture all requirements in relation to filtering in the `@auth` directive.
