### ISSUE TITLE
Simple Bind Across Relationship Broken for CREATE

### ISSUE THREAD

**Issue by dvanmali** [neo4j/graphql#633]
**Describe the bug**
The following schema provided on the [bind documentation](https://neo4j.com/docs/graphql-manual/current/auth/authorization/bind/) no longer works on the CREATE operation.

### To Reproduce

**Type definitions**

```gql
type User {
    id: ID @id
    name: String
}

type Post @auth(rules: [
    { operations: [CREATE], bind: { creator: { id: "$jwt.sub" } } }
]) {
    content: String
    creator: User @relationship(type: "HAS_POST", direction: IN)
}
```

**GraphQL Request**
```gql
mutation CreatePostsTmp($createPost: [PostCreateInput!]!) {
  createPosts(input: $createPost) {
    posts {
      content
    }
  }
}
```
```
{
  "createPost": [
    {
      "content": "My content"
    }
  ]
}
```

**Generated Cypher**
```cypher
CALL {
    CREATE (this0:Post)
    SET this0.content = $this0_content
    WITH this0
    CALL apoc.util.validate(NOT(
        EXISTS((this0)<-[:HAS_POST]-(:User)) AND ALL(creator IN [(this0)<-[:HAS_POST]-(creator:User) | creator] 
        WHERE creator.id IS NOT NULL AND creator.id = $this0_auth_bind0_creator_id)), "@neo4j/graphql/FORBIDDEN", [0])
    RETURN this0
}
RETURN 
this0 { .content } AS this0
```

**Generated Forbidden Error**
```
{
  "errors": [
    {
      "message": "Forbidden",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPosts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Neo4jGraphQLForbiddenError: Forbidden",
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Expected behavior**
When a User created first, the above query should create and connect (create relationship) to an existing User. However, a forbidden error gets generated. Looking at the Cypher request, we easily notice that the request translates to an `EXISTS((this0)<-[:HAS_POST]-(:User)) ` request. However, the relationship searches for a relationship that does not yet exist. Instead, we need to perform a `MATCH` to an existing user and `MERGE` the property.

**Comment by darrellwarde** [comment]
> When a User created first, the above query should create and connect (create relationship) to an existing User. However, a forbidden error gets generated.

I'm looking at the variables for your GraphQL query and it doesn't look as if you are connecting to any existing users. Whilst you have:

```json
{
  "createPost": [
    {
      "content": "My content"
    }
  ]
}
```

You would need something like the following to achieve the `MERGE` behaviour that you describe and get rid of this issue:

```json
{
  "createPost": [
    {
      "content": "My content",
      "creator: {
        "connect": {
          "where": { "node": { "name": "some existing user" } }
        }
      }
    }
  ]
}
```

At the moment it is behaving as it should because that relationship doesn't exist.

**Comment by dvanmali** [comment]
Your recommendation @darrellwarde works. However, since we are utilizing a bind, I recommend that we shouldn't need to manually `connect` in the query itself. In the current case, we need to unwrap the JWT token every time we have a bind to obtain the user. Instead, the bind property (not the query) maintains the user location, which is `$jwt.sub`.

The issue is not a major problem so I will close the comment for now, but if in the long term y'all wish to create this feature, feel free to tag this issue :)
