### ISSUE TITLE
Allow use of @coalesce on enum fields

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#660]
**Is your feature request related to a problem? Please describe.**
I was one of the original requesters of `@coalesce` but I've just discovered it doesn't meet my use case as it is restricted to primitive types. The primary use case I have is that records to filter records that _do not_ have a particular value of an enum stored in them, including those that do not have a value defined.

**Describe the solution you'd like**
Allow `@coalesce` to be used on enum fields. The value passed in to `@coalesce` should be allowed to be any string (not restricted to the values of the enum) as its purpose in my use case is to avoid the sometimes unintuitive behaviour caused by querying against a field that is sometimes `null`

**Additional context**
https://github.com/neo4j/graphql/issues/157

**Comment by darrellwarde** [comment]
This sounds like a good idea!

> The value passed in to `@coalesce` should be allowed to be any string (not restricted to the values of the enum)

However, fairly sure this won't work because the GraphQL runtime would complain that the values aren't present in the enum.

**Comment by wheresrhys** [comment]
> However, fairly sure this won't work because the GraphQL runtime would complain that the values aren't present in the enum.

Although with coalesce, it's only use in the neo4j querying and no value is returned by the API IIUC... so would this be an issue? Although I can see that it would be impossible to query explicitly for records with a field that is unset as GraphQL would not allow the coalesced value to be passed in to the query. While I am not a fan of reimplementing `null`, perhaps a way forward for us is to add `NULL` or `UNDEFINED` as an option in all our enums, and coalesce to this

A follow up use case I've also just stumbled across is temporal types (and I think the same could be said for spatial types too). e.g. to facilitate a query such as 'Return all systems where the last release timestamp is before this year or has never been set' it would be useful to avoid having to write more complex GraphQL queries to deal with `null`. Coalescing to the UNIX epoch feels like it might be a good approach, but then also we basically lose the ability to intuitively query for records where the date is not set.

I guess there is a trade off between ease of querying "X or null" vs "null" which we'll have to work out the right approach for us

**Comment by darrellwarde** [comment]
> > However, fairly sure this won't work because the GraphQL runtime would complain that the values aren't present in the enum.
> 
> Although with coalesce, it's only use in the neo4j querying and no value is returned by the API IIUC... so would this be an issue? Although I can see that it would be impossible to query explicitly for records with a field that is unset as GraphQL would not allow the coalesced value to be passed in to the query. While I am not a fan of reimplementing `null`, perhaps a way forward for us is to add `NULL` or `UNDEFINED` as an option in all our enums, and coalesce to this
> 
> A follow up use case I've also just stumbled across is temporal types (and I think the same could be said for spatial types too). e.g. to facilitate a query such as 'Return all systems where the last release timestamp is before this year or has never been set' it would be useful to avoid having to write more complex GraphQL queries to deal with `null`. Coalescing to the UNIX epoch feels like it might be a good approach, but then also we basically lose the ability to intuitively query for records where the date is not set.
> 
> I guess there is a trade off between ease of querying "X or null" vs "null" which we'll have to work out the right approach for us

You're absolutely right; it's been so long since I looked at `@coalesce` that I forgot exactly what it does!

I'll certainly note down these requirements, they should be possible!

**Comment by wheresrhys** [comment]
I've found a few use cases for @coalesce and @default on booleans too if you're open to implementing that too?

**Comment by darrellwarde** [comment]
> I've found a few use cases for @COALESCE and @default on booleans too if you're open to implementing that too?

I'm almost 100% sure this should already work, and if it doesn't, then should probably be reported as a bug!!!

**Comment by darrellwarde** [comment]
> I've found a few use cases for @COALESCE and @default on booleans too if you're open to implementing that too?

Hey @wheresrhys, I've just tested `Boolean` values for both `@default` and `@coalesce` but both appear to work fine. If you're still having an issue with this, can you raise a separate bug report please? Thanks!

**Comment by darrellwarde** [comment]
I've validated this for Enum and `Boolean` values and both `@default` and `@coalesce` work as expected. I will close this for now, feel free to reopen if you encounter issues.
