### ISSUE TITLE
How to mock the resolver

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#663]
In neo4j-graphql-js I used the following to create a mock resolver:

```
jest.mock('neo4j-graphql-js', () => {
	const real = jest.requireActual('neo4j-graphql-js');
	real.neo4jgraphql = jest.fn();
	return real;
});
...
		neo4jGraphql.neo4jgraphql.mockResolvedValue({ name: 'name1' });
```

I'm struggling to figure out an equivalent in the new library (though I imagine it's probably possible if the resolver is not completely private)

FYI my use case is to write tests for custom resolvers we also have in our API as it avoids having to mess around with creating lots of neo4j test data

**Comment by wheresrhys** [comment]
@darrellwarde Is there any advice on this these days?

**Comment by chris-aeviator** [comment]
https://github.com/neo4j/graphql/issues/1160

**Comment by darrellwarde** [comment]
As @chris-aeviator alluded to, [this comment](https://github.com/neo4j/graphql/issues/1160#issuecomment-1423970732) may help on this one, and I will close this to clean our issues of general questions.
