### ISSUE TITLE
@unique directive not constraining values to uniqueness

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#673]
**Describe the bug**
I am currently trying to prevent new nodes from being created when there's a node with a matching field.

**Type definitions**
This is my `Tag` type definition:

```
type Tag {
    id: ID! @id(autogenerate: true),
    text: String! @unique,
    created_date: DateTime! @timestamp(operations: [CREATE]),
}
```

And my query looks like this:

```
mutation new_tag{
  createTags(input: [{ text: "text" }, { text: "text" }]){
  	tags{
      id
      text
      created_date
    }
  }
}
```

And here is a sample response:

```
{
  "data": {
    "createTags": {
      "tags": [
        {
          "id": "a29b6985-ca2d-4d82-aaf4-bc1d5000a605",
          "text": "text",
          "created_date": "2021-12-28T21:50:28.469Z"
        },
        {
          "id": "09a4c9ef-5e39-4a16-8319-6ccf1b18bf2b",
          "text": "text",
          "created_date": "2021-12-28T21:50:28.469Z"
        }
      ]
    }
  }
}
```

Note the same text field entry but two separate IDs, it didn't hold the constraint. The same applies when you break out the single mutation into two separate mutations that each create a tag one at a time

This is with Neo4j 2.5.4

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @danielfein. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @danielfein, have you executed `assertIndexesAndConstraints` before this? https://neo4j.com/docs/graphql-manual/current/type-definitions/indexes-and-constraints/#type-definitions-indexes-and-constraints-asserting

**Comment by danielfein** [comment]
Oh wow that was it, thanks a lot @darrellwarde!
