### ISSUE TITLE
Significantly slower augmentation process than neo4j-graphql-js

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#674]
**Describe the regression**
Based on a handful of samples neo4j-graphql-js takes ~1.5s to augment my 2162 line schema, whereas @neo4j/graphql takes ~7s. Samples taken on my local machine so probably more performant than many production servers

This is significantly slowing down our test suite as the schema is augmented for every spec file (sometimes multiple times per file). It also makes things a bit problematic for our API as we 'hot reload' our schema from a url (polling on an interval) and build a new graphql handler on the fly. Blocking the process for 1.5s we could just about get away with but ~7s (sometimes quite a bit longer - the distribution of the augmentation's running time seems quite wide) takes us to the point where we will have to engineer around it.

**Last working version**

neo4j-graphql-js

**To Reproduce**
Augment any reasonably big schema

**Expected behavior**
It'd be nice if the augmentation did not block the main thread for so long, perhaps implemented asynchronously in steps. Also, perhaps some performance tests in the test suite would avoid performance regressions in future too.

**Comment by wheresrhys** [comment]
To add to this, we'd like to use the OGM to add some custom resolvers. This means the augmentation process must happen twice - once for the OGM and once for the main executable schema, which makes the time blocking the main thread twice as bad. Is there some pattern I can use to avoid this double augmentation?

**Comment by darrellwarde** [comment]
This has already been improved, and we'll always aim for good performance here moving forwards.
