### ISSUE TITLE
@timestamp directive not triggered on 'connectOrCreate'

### ISSUE THREAD

**Issue by steffenkoenig** [neo4j/graphql#675]
I have some type fields with @timestamp directive. 
If the types are created directly. e.g. createPerson(), updatePerson() these fields are set as expected.

But created via a traversal through connectOrCreate the timestamps are not getting set.

For example see following schema:

**Schema**
```
type Company {
    id: ID! @id
    name: String! @unique

    employees: [Person] @relationship(type: "WORKS_FOR", properties: "WorksFor", direction: IN)

    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp
}

type Person {
    id: ID! @id 
    name: String! @unique

    email: String

    company: Company @relationship(type: "WORKS_FOR", properties: "WorksFor", direction: OUT)

    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp
}

interface WorksFor @relationshipProperties {
    role: String

    createdAt: DateTime! @timestamp(operations: [CREATE])
    updatedAt: DateTime! @timestamp
}
```

**Query**
```
mutation UpdateCompany($where: CompanyWhere, $connectOrCreate: CompanyConnectOrCreateInput) {
  updatePlatforms(where: $where, connectOrCreate: $connectOrCreate) {
    info {
      nodesCreated
      relationshipsCreated
    }
  }
}
```

**Variables**
```
{
  "where": {
    "name": "Apple"
  },
  "connectOrCreate": {
    "employee": [
      {
        "where": {
          "node": {
            "name": "Tim Cook"
          }
        },
        "onCreate": {
          "node": {
            "email": "info@apple.com"
          },
          "edge": {
            "role": "CEO"
          }
        }
      }
    ]
  }
}
```

Doing this creates the Node and Relationship with the fields specified in the variables. 
But the createdAt or updatedAt fields for the nodes and relationship are not set.

**Comment by danielfein** [comment]
Is this possibly related to the directives on createOrConnect for #671?

**Comment by dmoree** [comment]
@danielfein I believe that the two are related in that neither directives were being taken into account. I started #679 as a proposed fix for both.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @steffenkoenig! :pray: We will now prioritise the bug and address it appropriately.
