### ISSUE TITLE
'Property values can only be of primitive types or arrays thereof' error occurs onCreate of connectOrCreate

### ISSUE THREAD

**Issue by danielfein** [neo4j/graphql#680]
**Describe the bug**
When I run the below query it works fine for the first bit, when there's a connection, but breaks when it needs to go to onCreate and returns this error:

 "Property values can only be of primitive types or arrays thereof. Encountered: Map{connect -> Map{where -> Map{node -> Map{id -> String(\"this_is_the_user_id\")}}}}

This is a simplified version of the mutation (as the error still exists with this and is easier to read)

```
mutation NEW_POST {
  createPosts(input: { categories: {connectOrCreate: {where: { node: { name: "name"}}, onCreate: { node: { name: "name", creator: { connect: { where: {node:{id: "this_is_the_user_id"}}}}}}}}}){
  posts {
   id
    }
  }
}
```

The GraphQL explorer doesn't show any errors with syntax or format, and I've checked it a few times for that and it works onConnect.

This is on the latest Neo4j version.

Thank you!

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @danielfein. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @danielfein, can you please provide some type definitions so that we can easily reproduce this? Thanks!

**Comment by darrellwarde** [comment]
@danielfein, I'm going to close this as we are lacking the necessary information. However, we have recently realised that nested Mutation operations should not be available under `onCreate` and these fields will be removed in the next release (#872). Apologies for any confusion here.
