### ISSUE TITLE
openCypher compatibility?

### ISSUE THREAD

**Issue by redbar0n** [neo4j/graphql#741]
Could this library and the OGM be made compatible with the [openCypher](http://opencypher.org/) standard?

**Comment by darrellwarde** [comment]
Hey @redbar0n! Just as one example, this library requires APOC which is not compatible with openCypher. Beyond this, there are probably other compatibility issues, but there is little value in us diving into the details of this at the moment. Going to close this for now, as probably a _long_ way down the road.
