### ISSUE TITLE
UNWIND not working as expected using @cypher directive

### ISSUE THREAD

**Issue by SimoGh** [neo4j/graphql#762]
**Describe the bug**
UNWIND not working as expected using @cypher directive

**Type definitions**
```
const typeDefs = gql`
	type Query{
		unwind : [Int]
	 		@cypher(statement:"""
				UNWIND range(0,5) as x 
				RETURN x
				"""
			)		
	}
`;
```

**To Reproduce**

1. Using the following dependencies:
```
  "dependencies": {
    "@neo4j/graphql": "^2.5.5",
    "apollo-server": "^2.25.3",
    "graphql-type-json": "^0.3.2",
    "neo4j-driver": "^4.4.1"
  }
```
2. Using the following schema (resolvers is empty)
```
const neoSchema = new Neo4jGraphQL({
	typeDefs,
	resolvers,
	driver,
});
```
3. Using the following Apollo server instance
```
const server = new ApolloServer({
  context: ({req})=> ({ req }),
  schema: neoSchema.schema,
  introspection: true,
  playground: true
});
```
4. Then run the following Query
```
query {
        unwind
}
```
5. See error
```
{
    "data": {
        "unwind": [
            0
        ]
    }
}
```

**Expected behavior**
The expected result:
```
{
    "data": {
        "unwind": [
            0,
            1,
            2,
            3,
            4,
            5
        ]
    }
}
```

**System (please complete the following information):**

-   OS: Windows
-   Version: @neo4j/graphql@2.5.5
-   Node.js version: v16.13.1

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @SimoGh. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @SimoGh, thanks for the detailed bug report! 🙇 

You actually need to slightly tweak your type definitions to get this working:

```graphql
type Query {
    unwind: [Int]
        @cypher(
            statement: """
            UNWIND range(0,5) as x
            RETURN collect(x)
            """
        )
}
```

Notice the `collect` before the `RETURN`. Without the `collect`, the values are returned as individual records from the database, but they need to be returned as an array within a single record. I hope that helps!
