### ISSUE TITLE
Augmented schema is missing description for relationship fields 

### ISSUE THREAD

**Issue by Roei-Levi** [neo4j/graphql#764]
**Describe the bug**
Every field in a GraphQL schema can have a description associated with it. However, the augmented schema doesn't seem to include the description on fields with the "relationship" directive specified to them. 

**Type definitions**
```graphql
type Application {
	"Application ID"
	id: ID

	**"Related Object Description"
	object: [Service] @relationship(type: "has_object", direction: OUT)**
}
type Service{
	"Service ID"
	id: ID
}
```

**To Reproduce**
Run the server with a GraphQL schema similar to the one above. The description property is missing from the "object" field. 

**Expected behavior**
The description "Related Object Description" should be shown in the graphQL documentation of the "object" field. 

**Additional context**
I presume that the description is dropped when the function createRelationshipFields() is executed to create relationship fields.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Roei-Levi. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Roei-Levi! :pray: We will now prioritise the bug and address it appropriately.
