### ISSUE TITLE
`assertIndexesAndConstraints` with `create` option throws an error if fulltext index already exists

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#841]
**Describe the bug**

We should check whether fulltext indexes already exist before trying to create them.

This is a side effect of having to use `db.index.fulltext.createNodeIndex` over `CREATE FULLTEXT INDEX` (to support DB 4.1).

Customer reported.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @darrellwarde. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.

**Comment by darrellwarde** [comment]
This can be reproduced by taking any type definitions with a `@fulltext` definition and then calling `assertIndexesAndConstraints` twice. The second time will throw an error. Partial example:

```ts
const typeDefs = gql`
    type Product @fulltext(indexes: [{ name: "ProductName", fields: ["name"] }]) {
        name: String!
    }
`;

const neoSchema = new Neo4jGraphQL({
    driver,
    typeDefs,
});

await neoSchema.assertIndexesAndConstraints({ options: { create: true } });
await neoSchema.assertIndexesAndConstraints({ options: { create: true } }); // throws
```

Assertions should be idempotent.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!

**Comment by mobsean** [comment]
Hi,
I´m also running into this problem.

I can see this merged to **neo4j:dev** branch,  when will it be merged to the master branch?
