### ISSUE TITLE
Querying Multiple Interface Relations generates Invalid Cypher Query

### ISSUE THREAD

**Issue by jnterry** [neo4j/graphql#847]
**Describe the bug**

When a `type` contains multiple `@relationship`s to an `interface`, querying both fields at once results in an invalid cypher query being generated. Querying each field individually works as expected.

**Type definitions**

**NOTE**: This is the same schema that generates another (I think unrelated) bug: https://github.com/neo4j/graphql/issues/832

```graphql
interface Entity {
    id: String!
}

type Person implements Entity {
    id   : String! @unique
    name : String!
}

type Place implements Entity {
    id       : String! @unique
    location : Point!
}

type Interaction  {
    id       : ID! @id
    kind     : String!
    subjects : [Entity!]! @relationship(type: "ACTED_IN", direction: IN )
    objects  : [Entity!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

**To Reproduce**

Seed the database with some data using the following mutation:

```graphql
mutation {
  createPeople(input: [
    { id: "adam", name: "Adam" },
    { id: "eve",  name: "Eve" },
    { id: "cain", name: "Cain"},
  ]) {
    people {
      id
    }
  }
  createInteractions(input: [{
    subjects : { connect: { where: { node: { id_IN: ["adam", "eve"] }}}},
    kind     : "PARENT_OF",
    objects  : { connect: { where: { node: { id_IN: ["cain"] }}}}
  }]) {
    info { nodesCreated }
    interactions { id }
  }
}
```

Now execute the following query:

```graphql
query {
  interactions {
    id
    subjects { id }
    objects { id }
  }
}
```

The following error is produced - suggesting that the generated Cypher code is invalid:

```json
{
  "message": "Variable `subjects` not defined (line 22, column 38 (offset: 598))\n\"RETURN this { .id, subjects: collect(subjects), objects: collect(objects) } as this\"\n                                      ^",
  "locations": [{ "line": 2, "column": 3}],
  "path": ["interactions"]
}
```

Note that querying just `subjects { id }` or just `objects { id }` one at a time works as expected. The bug is only observed when querying both fields at once.

**Expected behavior**

Query should execute successfully.

**System (please complete the following information):**

OS: Linux (Debian 10)
Version: @neo4j/graphql@2.5.5, graphql@16.2.0, apollo-server@3.6.2
Node.js version: v14.15.0
Neo4j DB Version: 4.4.0

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jnterry. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by dmoree** [comment]
This is an interesting bug. I reproduced this here: https://github.com/dmoree/neo4j-graphql-issue-multiple-interface-relationships.git

But the generated output from above was:
<details><summary>Generated Output</summary>
<p>

```
MATCH (this:Interaction)
WITH this
CALL {
WITH this
MATCH (this)<-[:ACTED_IN]-(this_Person:Person)
RETURN { __resolveType: "Person", id: this_Person.id } AS subjects
UNION
WITH this
MATCH (this)<-[:ACTED_IN]-(this_Place:Place)
RETURN { __resolveType: "Place", id: this_Place.id } AS subjects
}
WITH this
CALL {
WITH this
MATCH (this)-[:ACTED_IN]->(this_Person:Person)
RETURN { __resolveType: "Person", id: this_Person.id } AS objects
UNION
WITH this
MATCH (this)-[:ACTED_IN]->(this_Place:Place)
RETURN { __resolveType: "Place", id: this_Place.id } AS objects
}
RETURN this { .id, .kind, subjects: collect(subjects), objects: collect(objects) } as this
```
</p>
</details>

Each interfaceField generates a subquery, but the only variable before the subquery is `this`. It should carry over each variable defined prior (here `subjects`) in order to be defined in the final `RETURN` statement. Furthermore, there can be a mismatch in row so it should `collect(DISTINCT)` when returned.

<details><summary>Proposed Cypher</summary>
<p>

```
MATCH (this:Interaction)
WITH this
CALL {
WITH this
MATCH (this)<-[:ACTED_IN]-(this_Person:Person)
RETURN { __resolveType: "Person", id: this_Person.id } AS subjects
UNION
WITH this
MATCH (this)<-[:ACTED_IN]-(this_Place:Place)
RETURN { __resolveType: "Place", id: this_Place.id } AS subjects
}
WITH this, subjects <----- subjects must be added here
CALL {
WITH this
MATCH (this)-[:ACTED_IN]->(this_Person:Person)
RETURN { __resolveType: "Person", id: this_Person.id } AS objects
UNION
WITH this
MATCH (this)-[:ACTED_IN]->(this_Place:Place)
RETURN { __resolveType: "Place", id: this_Place.id } AS objects
}
RETURN this { .id, .kind, subjects: collect(DISTINCT subjects), objects: collect(DISTINCT objects) } as this
                                                ^--------------DISTINCT------------^            
```
</p>
</details>

I implemented these changes here: https://github.com/neo4j/graphql/compare/dev...dmoree:fix/multiple-interface-relationships

The tests pass of course, but I'm not confident of any downstream effects by changing this perhaps @danstarns or @darrellwarde  could comment on this.

**Comment by darrellwarde** [comment]
As @dmoree has highlighted, this is going to be pretty important for us to fix but we want to make sure we do it right. So we're going to plan out the fix for this as we would a feature - it could get pretty complex pretty quickly.
