### ISSUE TITLE
Allow @exclude-Directive on relation fields

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#850]
Currently there is no way to exclude some operations on relation fields.

I would suggest allowing the use of the `@exclude` directive at the field level for relations as well, so that you can configure the following:

```graphql
type Actor @exclude(operations: [CONNECT]) {
  name: String
}

type Movie {
  title: String
  actors: [Actor] @relationship(type: "ACTED_IN", direction: IN) @exclude(operations: [DELETE, DISCONNECT])
}
```

With the example above, no `connect`, `delete` and `disconnect` operations are allowed for the `Movie::actors` field

The available operations for `@exclude` would be extended by `CONNECT` and `DISCONNECT`

**Comment by darrellwarde** [comment]
Taking a slightly different approach, we have added new arguments to the `@relationship` directive which allows this configuration, such as `nestedOperations` and `aggregate`. 🙂
