### ISSUE TITLE
Top Level Connections

### ISSUE THREAD

**Issue by litewarp** [neo4j/graphql#851]
I would like the ability to add top-level connections, or to fetch relationships using connections even if no relationship properties are defined.

Currently, if I want to do pagination client-side, I have to handle two different types of pagination requests -- those using the connections model, and those without. Pagination is not a trivial task, and there is a high potential for confusion (as evidenced by all the discord and issues) when users have to switch between offsets and cursors.

For example, I have a relay-nextjs app I am putting together to where the user can select multiple companies. Since those companies are not yet associated with a node, I have to query them using the default top-level findMany resolver, i.e.
 
```graphql

## currently

type Query {
  companies(where: CompanyWhere, options: CompanyOptions): [Company!]!
}

## proposed

type Query {
  companiesConnection(first: Int, after: String, where: CompanyWhere, sort: [CompanySort]): CompanyConnection!
}
```

Since this general findMany query is not relay-compliant, I can't take advantage of all the built-in goodness that `react-relay` offers, e.g., [usePaginationFragment](https://relay.dev/docs/guided-tour/list-data/rendering-connections/). So if I am querying a top-level "node", in order to paginate through the list, I now have to keep track of the offset, calculate the next page and send the request. I also have to manually include the aggregation query in the top-level selection set and then divide the total number by the page size to determine if there is a next page. This information should come from the server, which is why connections are often preferable to simple paginated lists. 

I know there has been some debate over whether relationship fields without properties should have connections generated for them. I don't know the specifics of that debate, but allowing users to query all types of relationships through connections would certainly make it easier to do pagination seamlessly. For other packages, it seems like the criteria is whether a list of nodes is being fetched rather than when properties are present. For example, [Postgraphile implements connections for any "large list"](https://www.graphile.org/postgraphile/connections/#gatsby-focus-wrapper), and [Hasura has top-level connections as well](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/relay-schema.html) (see the "users_connection" in the screenshot).

Currently, I use a [custom graphql-tools plugin I built](https://github.com/litewarp/graphql-utils/blob/main/packages/neo4j-helpers/src/plugins/top-level-connections.ts) which repurposes the findMany function into a connection field, but it is not the easiest to maintain and comes with other drawbacks since it hijacks the aggregation count field as well and there may be conflicting arguments sent. 

Alternatively, could you remove the prohibition on using the name "connections" on the top level query (and maybe mutation) field(s)? Then I can probably suffice by querying the ogm for both count and the findMany results and stitch the connection together.

**Comment by darrellwarde** [comment]
> I know there has been some debate over whether relationship fields without properties should have connections generated for them. I don't know the specifics of that debate, but allowing users to query all types of relationships through connections would certainly make it easier to do pagination seamlessly. For other packages, it seems like the criteria is whether a list of nodes is being fetched rather than when properties are present. For example, [Postgraphile implements connections for any "large list"](https://www.graphile.org/postgraphile/connections/#gatsby-focus-wrapper), and [Hasura has top-level connections as well](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/relay-schema.html) (see the "users_connection" in the screenshot).

I don't think there's a huge amount of debate on this - connection fields get added to relationships whether or not they have relationship properties. Root-level connection fields have been on our to-do list for some time, we've just not had time to implement them. We would love to see these added, and if you would like to implement these yourself then we would welcome that contribution with open arms.

> Alternatively, could you remove the prohibition on using the name "connections" on the top level query (and maybe mutation) field(s)? Then I can probably suffice by querying the ogm for both count and the findMany results and stitch the connection together.

There is currently no prohibition on defining fields ending "Connection" - it's actually the definition of new object types ending "Connection" because we implement the reserved types rules from the spec: https://relay.dev/graphql/connections.htm#sec-Reserved-Types

If this something you have time for and would be interested in implementing @litewarp, or is this a general feature request for us to take a look at it? 🙂

**Comment by litewarp** [comment]
Oh! I wasn't aware that connections were enabled for non-relationship-property fields. I've been creating dummy fields and interfaces in my schema. Good to know I can remove those now. 

And yes, I've got a PR coming 😁So far I've added top level connections to the schema and gotten all the schema level tests to pass. Just need to figure out the best way to run the query without creating a new translate-root-connection resolver, although I may just do that anyways.

**Comment by darrellwarde** [comment]
> And yes, I've got a PR coming 😁So far I've added top level connections to the schema and gotten all the schema level tests to pass. Just need to figure out the best way to run the query without creating a new translate-root-connection resolver, although I may just do that anyways.

Sounds great!! Feel free to add a new resolver and relevant translation. 🙂
