### ISSUE TITLE
Custom return type and OGM : ContainerCreateInput must define one or more fields

### ISSUE THREAD

**Issue by Wenzel** [neo4j/graphql#856]
**Describe the bug**
When defining a custom query with a complex custom return type and calling the OGM in the query resolver function, an error is raised if the type doesn't define an non array field.

Below, you can see that the `Container` type, excluded from the data model with `@exclude`, has only 1 field, which is an array of `Item`, also `@exclude`.

This doesn't play well with the OGM, for some reason.

**Type definitions**
Please use the following `bug.ts` to repro the issue:
~~~typescript
import { Neo4jGraphQL } from "@neo4j/graphql";
import { OGM } from "@neo4j/graphql-ogm";
import { ApolloServer, gql } from "apollo-server";
import neo4j from "neo4j-driver";

const NEO4J_URI = "neo4j+s://xxxxxxx.databases.neo4j.io";
const NEO4J_USER = "neo4j";
const NEO4J_PASSWORD = "xxxx";

// Neo4j driver instance
const driver = neo4j.driver(
    NEO4J_URI,
    neo4j.auth.basic(NEO4J_USER, NEO4J_PASSWORD)
);

const typeDefs = gql`
    type User {
        name: String!
    }
    # custom types not part of Data model
    type Container @exclude {
        items: [Item]!
    }

    type Item @exclude {
        fieldA: String!
    }
    # custom Queries
    type Query {
        custom_query: Container!
    }
`;

// OGM instance
const ogm = new OGM({ typeDefs, driver });

const resolvers = {
    Query: {
        async custom_query(_source) {
            // must use the OGM to query the bug
            const User = ogm.model("User");
            const selectionSet = `{
                name
            }`;
            // this will trigger a Input Object type ContainerCreateInput must define one or more fields.
            await User.find({
                selectionSet,
            });
            return {
                items: [],
            };
        },
    },
};

const neoSchema = new Neo4jGraphQL({ typeDefs, driver, resolvers });

const server = new ApolloServer({
    schema: neoSchema.schema,
});

server.listen().then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
});
~~~

**To Reproduce**

1. Run a server with the provided code: `DEBUG=@neo4j/graphql:* npx ts-node bug.ts`
2. Execute the following query:
~~~gql
query {
  custom_query {
    __typename
  }
}
~~~

**Expected behavior**
The following data should have been returned, according to the resolver
~~~gql
{
  "data": {
    "custom_query": {
      "__typename": "Container"
    }
  }
}
~~~

**Screenshots**
Actual error raised:
![Capture d’écran de 2022-01-23 18-05-37](https://user-images.githubusercontent.com/964610/150689569-bf0cc7d0-9e9d-4e1b-880b-61a1592c0de3.png)

**System (please complete the following information):**

-   OS: Ubuntu 20.04
-   Version: `@neo4j/graphql@2.5.4`
-   ts-node version: `10.4.0`

Thank you !

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Wenzel. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

Thanks again! :pray:

**Comment by angrykoala** [comment]
Hi @Wenzel 
Which `graphql` version are you running?
Currently, `graphql@16` is **not** supported in `@neo4j/graphql@2` due to some breaking changes, please, try your example using `graphql@15.5.1`

GraphQL 16 will soon be supported in the next `@neo4j/graphql` major release

**Comment by Wenzel** [comment]
Hi @angrykoala, thanks for your reply.

I'm actually using `graphql@15.5.1`, as indicated by my `package.json`:
~~~json
  "dependencies": {
    "@neo4j/graphql": "^2.5.0",
    "@neo4j/graphql-ogm": "^2.5.4",
    "apollo-server": "^3.5.0",
    "dotenv": "^10.0.0",
    "graphql": "^15.5.1",
    "neo4j-driver": "^4.4.1",
    "ts-node": "^10.4.0",
    "tsc": "^2.0.3"
  },
~~~

**Comment by angrykoala** [comment]
Thanks for the additional info @Wenzel I'll try to reproduce the problem with your package.json

**Comment by Wenzel** [comment]
@angrykoala I'm coming back to you after trying to replicate the bug this week-end on a clean package.json (no package-lock.json)

And the bug disappeared.
I tracked the issue to the `neo4j/graphql-ogm` package, which triggers the bug in `2.5.4` but not in `2.5.6` anymore.

I'll mark this as resolved then
But I didn't suspect that a minor release would fix this problem.

Thank you for your help !

**Comment by angrykoala** [comment]
Hi @Wenzel 
Glad to know that fixed it. We usually bundle bugfixes in patch releases
