### ISSUE TITLE
If all field of an interface are private an invalid schema is generated

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#870]
Given the following schema ([taken from the tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/directives/private.test.ts#L28-L36)):

```graphql
interface UserInterface {
  private: String @private
}

type User implements UserInterface {
  id: ID
  password: String @private
  private: String
}
```

[An empty interface is generated](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/directives/private.test.ts#L113):

```graphql
interface UserInterface
```

Which [is not allowed by the GrapQL spec](https://spec.graphql.org/June2018/#sec-Interfaces):

> An Interface type must define one or more fields.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
