### ISSUE TITLE
Harmonize names for connection-where of unions

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#871]
Given the following schema ([taken from the tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/schema/unions.test.ts#L28-L38)):

```graphql
union Search = Movie | Genre

type Genre {
  id: ID
}

type Movie {
  id: ID
  search: [Search!]! @relationship(type: "SEARCH", direction: OUT)
  searchNoDirective: Search
}
```

The following type is generated among others:

```graphql
input MovieSearchConnectionGenreWhere {
  AND: [MovieSearchConnectionGenreWhere!]
  OR: [MovieSearchConnectionGenreWhere!]
  node: GenreWhere
  node_NOT: GenreWhere
}
```

All other connection-where-types are named `${prefix}${node.name}ConnectionWhere` but for unions the name is `${prefix}Connection${node.name}Where`, we should harmonize them!

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
