### ISSUE TITLE
*ConnectOrCreateFieldInputOnCreate and  *CreateFieldInput are completely identical

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#872]
While harmonizing the logic for schema augmentation in java, I realized, that the types for `${prefix}ConnectOrCreateFieldInputOnCreate` and `${prefix}CreateFieldInput` are identical.

For example the following schema:

```graphql
type Movie {
  title: String!
  id: ID! @id
}

type Actor {
  name: String!
  movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

will generate the following types among others:

```graphql
input ActorMoviesConnectOrCreateFieldInputOnCreate {
  node: MovieCreateInput!
}

input ActorMoviesCreateFieldInput {
  node: MovieCreateInput!
}
```

And if there are relation properties like:

```graphql
type Movie {
  title: String!
  isan: String! @unique
}

type Actor {
  name: String!
  movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

interface ActedIn {
  screentime: Int!
  characterName: String
}
```

The following types are generated among others:

```graphql

input ActorMoviesConnectOrCreateFieldInputOnCreate {
  edge: ActedInCreateInput!
  node: MovieCreateInput!
}

input ActorMoviesCreateFieldInput {
  edge: ActedInCreateInput!
  node: MovieCreateInput!
}
```

**Comment by darrellwarde** [comment]
For `connectOrCreate.onCreate`, this can only have primitive values because nested operations do not work. So this is a bug and has been classified as so. 🙂

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @Andy2003! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
