### ISSUE TITLE
Provide option to disable mutations

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#878]
While moving to GraphQL mutations is an end goal for us, we currently have a REST API which has various validation steps and side-effects built into it. Users creating records via GraphQL will bypass these important features so I'd really like to disable mutations.

As a short-term hack I'm going to force the server to error on every mutation attempt, but would much rather exclude these from getting generated in the first place

**Comment by maieulChevalier** [comment]
I think you can use [`@exclude`](https://neo4j.com/docs/graphql-manual/current/type-definitions/access-control/#type-definitions-access-control-exclude):

```graphql
type User @exclude(operations: [CREATE]) {
    name: String
}
```

But I do agree that it would be nice if we could specify this for all the types at once.

**Comment by benjamin-rood** [comment]
This is actually a regression from `neo4j-graphql-js`, where you could globally disable autogeneration of Query and/or Mutation types by providing config object to `makeAugmentedSchema`:

```
config: { query: false, mutation: false } // query and mutation autogeneration disabled
```

So this should actually be tagged a regression.

What is need is an equivalent parameter(s) added to the `Neo4jGraphQLConstructor` interface.

**Comment by darrellwarde** [comment]
> This is actually a regression from `neo4j-graphql-js`, where you could globally disable autogeneration of Query and/or Mutation types by providing config object to `makeAugmentedSchema`:
> 
> 
> 
> ```
> 
> config: { query: false, mutation: false } // query and mutation autogeneration disabled
> 
> ```
> 
> 
> 
> So this should actually be tagged a regression.
> 
> 
> 
> What is need is an equivalent parameter(s) added to the `Neo4jGraphQLConstructor` interface.

We won't class this as a regression because there is a valid alternative with `@exclude`, but we do realise that this is a lot more boilerplate.

**Comment by wheresrhys** [comment]
Just some quick feedback on the docs that would've made it easier to discover this feature. In the directives section it says:

> The @exclude directive is used on object types to instruct them to be skipped during Query and Mutation generation.

The following would have piqued my curiosity enough to click through for more details

> The @exclude directive is used on object types to instruct them to be skipped during Query and/or Mutation generation.

@darrellwarde
