### ISSUE TITLE
SDL Import Tooling for multiple typedef files with Neo4j extended syntax

### ISSUE THREAD

**Issue by benjamin-rood** [neo4j/graphql#884]
**Is your feature request related to a problem? Please describe.**

When working with large projects, it's common to declare your type definitions across multiple SDL files.

All tooling which I am aware of (including those from `graphql-tools`) underneath uses `assertValidSDL` from the `graphql/js` library, and if your typedefs include any expanded Neo4j syntax—e.g. `@relationship`, `@cypher`, `DateTime`, etc—then that assertion will fail.

The reason this tooling is so useful is that it allows you to declare `Query` and `Mutation` types across multiple files next to the related types the queries and mutations will be acting on, and it automatically merges them together. In my organisation, we always define an explicit API with custom `Query` and `Mutation` types. This approach also allows you to use conditional logic to include/import certain SDL files or not, which is extremely useful in feature-flagging parts of your schema, for example.

Example error output:

```
Error: Unknown directive "@relationship".

Unknown directive "@cypher".

Unknown directive "@exclude".

Unknown directive "@id".

Unknown type "DateTime".

Unknown directive "@relationship".

Unknown directive "@relationship".

Unknown directive "@relationship".
    at assertValidSDL (<ProjectRoot>/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (<ProjectRoot>/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeExecutableSchema (<ProjectRoot>/node_modules/@graphql-tools/schema/index.js:497:26)
    at Object.mergeSchemas (<ProjectRoot>/node_modules/@graphql-tools/schema/index.js:534:12)
    at loadSchemaSync (<ProjectRoot>/node_modules/@graphql-tools/load/index.js:639:29)
    at getTypeDefs (<ProjectRoot>/src/schema.ts:12:49)
    at Object.<anonymous> (<ProjectRoot>/src/index.ts:10:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (<ProjectRoot>/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-3205297082206877.js:69:33)
[ERROR] 17:27:36 Error: Unknown directive "@relationship".

Unknown directive "@cypher".

Unknown directive "@exclude".

Unknown directive "@id".

Unknown type "DateTime".

Unknown directive "@relationship".

Unknown directive "@relationship".

Unknown directive "@relationship".
```

**To Reproduce**

I've posted a basic repo which sufficiently demonstrates the issue [here](https://github.com/benjamin-rood/neo4j-graphql-merge-schemas-demo), replicating the same `graphql-tools` libraries I am using and the logic. The repo demos how it breaks when attempting to import and merge SDL files (NOT WORKING), versus defining all the typedefs "inline" as a single `gql`-tagged string literal (WORKING AS EXPECTED).

Steps to reproduce the behaviour:

1. Run the server with the following code `npm run start`
2. See error
3. Run the server again, but this time use `TYPEDEFS=aio npm run start` to use the "inline" typedefs
4. Server starts correctly

**Describe the solution you'd like**

Unfortunately, I cannot see any way around this other than providing a wrapper function around the tools that the `graphql-tools` libraries provide (in the same way `makeAugmentedSchema` does), or, failing that, changing the `Neo4jGraphQL` constructor to optionally take a wildcard-supporting list of string paths.

**Describe alternatives you've considered**

In the past, the only way I have gotten around this is by either having one giant SDL file, manually importing the files using `fs` (bug-prone), or, running a simple server using `neo4j-graphql-js`/`@neo4j/graphql` and stealing the generated type definitions by introspection and manually adding them into my own SDL. The problem with this last hack is that you don't get any generation of filtering or sorting fields for your types, so you have to write these yourself, and that's both an extra burden and error-prone.

**Comment by dmoree** [comment]
@benjamin-rood Perhaps I don't fully understand your use case, but is there any reason why you couldn't use `loadFilesSync` from `@graphql-tools/load-files` to load in the `.graphql` files?

It worked after I loaded the typedefs with `loadFilesSync` and used `mergeTypeDefs` on which ones to use.

I tested it here: https://github.com/dmoree/neo4j-graphql-issue-merge-schemas

**Comment by benjamin-rood** [comment]
@dmoree That does seem sufficient, thank you!

Let me test it in a large real project to confirm.

**Comment by darrellwarde** [comment]
Sounds like this was previously resolved!

**Comment by benjamin-rood** [comment]
@darrellwarde Yes it is resolved. Sorry, I forgot to come back and close it
