### ISSUE TITLE
Incomplete Cypher query params creation

### ISSUE THREAD

**Issue by darrellwarde** [neo4j/graphql#901]
Neo4j Version: 4.4.x
neo4j-driver 4.4.1, neo4j/graphql 2.5.5
Reproduced locally: yes

Customer reported an issue with our neo4j/graphql js library, specifically it seems like the Cypher parameter creation based on the GraphQL variables does not function properly when a query needs to have a multi-filter based on relationships.

---

Steps to reproduce:

- Add the following query variables:

```json
{
  "where": {
    "current": true,
    "OR": [
      {
        "manufacturerConnection": {
          "edge": {
            "current": true
          },
          "node": {
            "name": "abc"
          }
        }
      },
      {
        "brandConnection": {
          "edge": {
            "current": true
          },
          "node": {
            "name": "smart"
          }
        }
      }
    ]
  }
}
```

- Execute the following GraphQL query:

```gql
# Query to receive filtered Series
query getSeriesWithRelationFilters($where: SeriesWhere = { current: true }) {
  series(where: $where) {
    name
    brand {
      name
    }
    manufacturer {
      name
    }
  }
}
```

At this point check the application logs, the parameters generated from the Query variables are the following:

```json
{
  "this_series": {
    "where": {
      "brandConnection": {
        "edge": {
          "current": true
        },
        "node": {
          "name": "smart"
        }
      }
    }
  },
  "this_current": true
}
```

As you can see, the filter on relationship "manufacturerConnection" is missing, the expectation from the customer is to have the following params:

```json
{
  "this_series": {
    "where": {
      "brandConnection": {
        "edge": {
          "current": true
        },
        "node": {
          "name": "smart"
        }
      },
      "manufacturerConnection": {
        "edge": {
          "current": true
        },
        "node": {
          "name": "abc"
        }
      }
    }
  },
  "this_current": true
}
```

Are we doing something wrong here?
Is this a known issue/missing functionality?

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @darrellwarde. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
@neo4j/graphql, this is a customer request and further details can be found in Trello.

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @darrellwarde! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
