### ISSUE TITLE
@unique directive does not apply to custom scalars

### ISSUE THREAD

**Issue by mobsean** [neo4j/graphql#915]
**Describe the bug**
Using @unique directive does not create constraints for custom scalars. For example UnsignedInt from 'graphql-scalars'

**Type definitions**
```
scalar UnsignedInt

type Order {
  OrderNo: UnsignedInt! @unique
  Name: String
}
```

**To Reproduce**

1. use typedef provided
2. run await assertIndexesAndConstaints() on server startup
3. Start Server
4. on Startup: this will **NOT** be generated: 
@neo4j/graphql:execute About to execute Cypher: 
CREATE CONSTRAINT Order_OrderNo IF NOT EXISTS ON (n:Order) ASSERT n.OrderNo IS UNIQUE +1ms 

**Expected behavior**
assertIndexesAndConstaints() should also generate Cypher for custom scalars.

@neo4j/graphql:execute About to execute Cypher: 
CREATE CONSTRAINT Order_OrderNo IF NOT EXISTS ON (n:Order) ASSERT n.OrderNo IS UNIQUE +1ms 

Also interesting: the old neo4j-graphql-js package was able to handle exactly this. I´m trying to get rid off it...

**System:**

* OS: Windows
* Version: @neo4j/graphql@2.5.6 and graphql-scalars 1.14.1
* Node.js version: 16

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @mobsean. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @mobsean! :pray: We will now prioritise the bug and address it appropriately.

**Comment by magnusart** [comment]
Just ran into this very same issue Is it possible to see when this planned to be included in a specific release?

**Comment by magnusart** [comment]
For anyone looking for a manual workaround here is a suggestion: 

Create a session and transaction during server startup and run all hardcoded statements (ie. `CREATE CONSTRAINT X_y IF NOT EXISTS ON(n: X) ASSERT n.y IS UNIQUE`) the library should have generated.

Not a lot of fun to maintain separate Cypher statements and manually keep up with the schema, but it gets you there in the mean time.

**Comment by magnusart** [comment]
Right now the GraphQL schema no longer represents the truth: declaring `@unique` fails silently for `scalar` fields. 

If supporting `@unique` for custom `scalar` fields is a feature, then `@unique` failing silently to create the constraints for custom `scalar` fields _surely_ must be a bug?

Maybe I'm splitting hairs but can this be tagged as both a `feature` and a `bug` at the same time to help prioritization? 

I'm worried this will be put on the back burner when it's only tagged as a `feature request` and a `workaround available` tag! 

Raising an error for these fields would be a good first step if supporting this as a feature has low priority.
