### ISSUE TITLE
Extension of the @readonly directive to also prevent creation

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#916]
**Is your feature request related to a problem? Please describe.**
Certain data should not be created via the GraphQL API, but only read out. Because of this, it would be great to extend the existing @readonly directive with the ability to also prevent node creation.

**Describe the solution you'd like**
Something like this: @readonly(enableCreation: false)

**Describe alternatives you've considered**
There is an option to do this using a custom cypher query. But I suppose this is not efficient since "apoc.cypher.runFirstColumn" is used for custom cypher queries.

**Comment by darrellwarde** [comment]
Superseded by #1034.
