### ISSUE TITLE
@readonly support for relationships with the @relationship directive

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#917]
**Is your feature request related to a problem? Please describe.**
In some cases you want to create a relationship that cannot be changed afterwards. For example, I have the following use case:

````graphql
type Product {
    id: ID
    name: String
    createdBy: Application! @relationship(type: "CREATED_BY", direction: OUT) @readonly
}

type Application {
    name: String
}
````

When a product is created, an application should also be linked as the creator. When the product is created, the link to the application should be immutable
However, this currently leads to this error message: "Error: Directive @relationship cannot be used in combination with @readonly"

**Comment by darrellwarde** [comment]
3.20.0 marks the release of the `nestedOperations` in the `@relationship` directive, and this allows you to configure which nested operations you would like to have available for a given relationship. Setting this to perhaps just `[CREATE]` should provide you with the functionality you're looking for here!
