### ISSUE TITLE
Guaranteeing the order in which a sort is applied

### ISSUE THREAD

**Issue by AccsoSG** [neo4j/graphql#918]
**Is your feature request related to a problem? Please describe.**
I want to be able to use multiple sorting criteria where order is respected. Currently, the order of the sort criteria is ignored.

Example: I want the results to be sorted by name first and then by id.
````graphql
query {
  products(options: { sort: { name: ASC, id: ASC }}) {
    id
    name
  }
}
````

**Comment by dmoree** [comment]
@AccsoSG I think that the sort order will be respected if you rewrite your query with `sort` as an array as in:
```graphql
query {
  products(options: { sort: [{ name: ASC }, { id: ASC }]}) {
    id
    name
  }
}
```

**Comment by AccsoSG** [comment]
@dmoree You're absolutely right, that was my mistake. I misunderstood the description for the generated ProductSort type.
````text
Fields to sort Products by. The order in which sorts are applied is not guaranteed when specifying many fields in one ProductSort object.
````
With that I close the ticket. Thank you very much =)
