### ISSUE TITLE
Multiple Fragment spreads on multiple Level break query Resolution

### ISSUE THREAD

**Issue by reckter** [neo4j/graphql#920]
**Describe the bug**
If using multiple Fragment spreads, on multiple levels a query can crash, when it shouldn't.

```graphql
            query Actors($name: String) {
                actors(where: { name: $name }) {
                    actedIn {
                        ...FragmentA
                    }
                    ...FragmentB
                }
            }

            fragment FragmentA on Production {
                title
            }

            fragment FragmentB on InterfaceA {
                actedIn {
                    runtime
                }
            }
```

I managed to build a reproducible test here: https://github.com/opencreek/graphql/blob/154ee81346842c9a66a16f6b003ecc916adbcb23/packages/graphql/tests/integration/multiple-fragment-spreads.test.ts#L97

The test currently fails with `Received: [[GraphQLError: Cannot return null for non-nullable field Movie.title.]]`, eventhough the title definitely is there.

My (uneducated) guess is that somewhere when merging these fragments an error happens and not all information is correctly merged.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @reckter. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @reckter! :pray: We will now prioritise the bug and address it appropriately.
