### ISSUE TITLE
False checking for existence for negated connection where

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#925]
Given the following example ([taken from the tests](https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/tck/tck-test-files/advanced-filtering.test.ts#L661-L694)):

```graphql
type Movie {
  _id: ID
  id: ID
  title: String
  actorCount: Int
  budget: BigInt
  genres: [Genre!]! @relationship(type: "IN_GENRE", direction: OUT)
}

type Genre {
  name: String
  movies: [Movie!]! @relationship(type: "IN_GENRE", direction: IN)
}
```

and the request:

```graphql
{
  movies(where: {genresConnection_NOT: {node: {name: "some genre"}}}) {
    actorCount
  }
}
```

the following cypher is generated:

```cypher
MATCH (this:Movie)
    WHERE EXISTS((this)-[:IN_GENRE]->(:Genre)) AND NONE(this_genresConnection_NOT_Genre_map IN [(this)-[this_genresConnection_NOT_Genre_MovieGenresRelationship:IN_GENRE]->(this_genresConnection_NOT_Genre:Genre)  | { node: this_genresConnection_NOT_Genre, relationship: this_genresConnection_NOT_Genre_MovieGenresRelationship } ] WHERE this_genresConnection_NOT_Genre_map.node.name = $this_movies.where.genresConnection_NOT.node.name)
    RETURN this { .actorCount } as this
```

This cypher will only return `movies` with an existing `genres` connection, b/c there is the check:

>  `EXISTS((this)-[:IN_GENRE]->(:Genre))`

With the given GraphQL query, I would expect movies to be returned that have no genres assigned to them as well.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @Andy2003. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by dmoree** [comment]
For `n..m` relationships `{field}Connection_NOT` is going to be [deprecated](https://github.com/neo4j/graphql/pull/796/commits/7a8bf4e362b5cb68abb9220d2b3908db4d670551#diff-c959164e0520019a32e358e5f3015ef72e35d106f4dbc41f73a33bc0ed8a0266) in favor of `{field}Connection_NONE` (by your suggestion in #144 interestingly enough) which will make it more clear what is actually being queried.

I think you may have to use an `OR` to capture `null` values.

Relevant code for translation:
https://github.com/neo4j/graphql/blob/d5c34423532caadfa5278a374186a67b204c6345/packages/graphql/src/translate/where/create-node-where-and-params.ts#L165-L231

Specifically,
https://github.com/neo4j/graphql/blob/d5c34423532caadfa5278a374186a67b204c6345/packages/graphql/src/translate/where/create-node-where-and-params.ts#L193-L196

Your query will probably have to be
```graphql
{
  movies(where: {OR: [{genresConnection_NOT: {node: {name: "some genre"}}}, {genresConnection: null}]}) {
    actorCount
  }
}
```

**Comment by darrellwarde** [comment]
> Your query will probably have to be
> 
> ```graphql
> {
>   movies(where: {OR: [{genresConnection_NOT: {node: {name: "some genre"}}}, {genresConnection: null}]}) {
>     actorCount
>   }
> }
> ```

I agree with @dmoree on this one - this is behaving as expected and is not a bug. If we started including `null` results here, then I believe it would become difficult or impossible to achieve filters as they currently behave.

**Comment by Andy2003** [comment]
The issue in this ticket is the expectation of what should be returned with the query.

I think the check for existence should be handled as follow (also valid for #144):

- n..m
  - `any`, `single`, `all`: here we don't need to check for existence since the predicate implies the existence of the relation
  - `none`: here I expect to not check for the existence at all, since I just want the nodes where none of the relations exists
- n..1
  - `eq`: here we should check for existence
  - `not` here we should check for not existence

**Comment by Andy2003** [comment]
> I believe it would become difficult or impossible to achieve filters as they currently behave.

So if your concern is about compatibility, I would suggest to use #144 to enable a smooth migration. The old (deprecated) fields can behave the old way, the new fields should behave as described above.

**Comment by dmoree** [comment]
It also reads to me that `none` implies the existence of the relation as well.

It's a little more verbose but: `none` have `name` `some_genre` `OR` `all` are `null` seems to be more explicit.

**Comment by Andy2003** [comment]
> It also reads to me that `none` implies the existence of the relation as well.

So from natural language: "Give me a movie where none of the genres is 'fantasy'" I would also expect to get movies returned with no genres assigned at all.

**Comment by dmoree** [comment]
I definitely agree that this would be a correct interpretation, but in terms of being explicit about what is being sought for I think `null` and `undefined` should be handled explicitly.

**Comment by Andy2003** [comment]
If we go this path I would suggest to add this to the documentation of the generated where-fields. 

Should we make this behavior configurable for `none`-filters? 

What about the other cases (`any`, `single`, `all`) do we need to check for existence there? I don't think so.
