### ISSUE TITLE
Issues with aliases on connectOrCreate

### ISSUE THREAD

**Issue by tbwiss** [neo4j/graphql#976]
**Describe the bug**
Customer reported a unusual behaviour of aliases and we'd like to understand wether this is an actual bug/limitation of the GrapQL library or an expected behaviour.

**Type definitions**
```graphql
type BibliographicReference @node(additionalLabels: ["Resource"]){
    iri: ID! @unique @alias(property: "uri")
    prefLabel: [String]
    isInPublication: [Concept!]! @relationship(type: "isInPublication", direction: OUT)
}

type Concept @node(additionalLabels: ["Resource"]){
    iri: ID! @unique @alias(property: "uri")
    prefLabel: [String]!
}
```

**To Reproduce**
1. Execute the following mutation:

```gql
mutation {
  createBibliographicReferences(
    input: {
      iri: "urn:myiri2"
      prefLabel: "Initial label"
      isInPublication: {
        create: { node: { iri: "new-e", prefLabel: "stuff" } }
      }
    }
  ) {
    bibliographicReferences {
      iri
      prefLabel
      isInPublication {
        iri
        prefLabel
      }
    }
  }
}
```
2. Execute the following mutation:
```gql
mutation {
  deleteConcepts(where: { iri: "new-e" }) {
    nodesDeleted
  }

  updateBibliographicReferences(
    where: { iri: "urn:myiri2" }
    update: {
      prefLabel: "Updated Label"
      isInPublication: [
        {
          connectOrCreate: {
            where: { node: { iri: "new-g" } }
            onCreate: { node: { iri: "new-g", prefLabel: "pub" } }
          }
        }
        {
          connectOrCreate: {
            where: { node: { iri: "new-f" } }
            onCreate: { node: { iri: "new-f", prefLabel: "pub" } }
          }
        }
      ]
    }
  ) {
    bibliographicReferences {
      iri
      prefLabel
      isInPublication(where: { iri_IN: ["new-f", "new-e"] }) {
        iri
        prefLabel
      }
    }
  }
}
```

Customer at this point reports two issues:
1. Execute `MATCH (n:Resource{iri:'new-f'}) return n` ~> the node has `iri` property (should be `uri` based on the model).
2. The second mutation does not retrieves any `isInPublication`, customer believes that this is due to the fact that the alias is applied upon retrieval while it is not applied upon update.

**System (please complete the following information):**

* Neo4j Version: 4.4.x
* neo4j/graphql 2.5.8
* Reproduced locally: yes

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @tbwiss! :pray: We will now prioritise the bug and address it appropriately.
