### ISSUE TITLE
Incomplete Cypher query params creation - v2

### ISSUE THREAD

**Issue by tbwiss** [neo4j/graphql#988]
**Describe the bug**
Neo4j Version: 4.4.x
neo4j-driver 4.4.1
neo4j/graphql 2.5.8
Reproduced locally: yes

Customer reported another issue related to incomplete Cypher params creation after the fix provided with graphQL 2.5.8 (see Issue https://github.com/neo4j/graphql/issues/901).
Apparently the library does not handle more than 1 parameter value on inner conditions

**Type definitions**
```graphql
type Series {
    name: String
    current: Boolean!
    manufacturer: [Manufacturer!]!
        @relationship(type: "MANUFACTURER", properties: "RelationProps", direction: OUT)
    brand: [Brand!]! @relationship(type: "BRAND", properties: "RelationProps", direction: OUT)
}

type Brand {
    name: String
    current: Boolean!
}

type Manufacturer {
    name: String
    current: Boolean!
}

interface RelationProps {
    current: Boolean!
}
```

**To Reproduce**

- Add the following query variables (as you can see we have 2 different values for `manufacturerConnection`):
```json
{
  "where": {
    "current": true,
    "AND": [
      {
        "OR": [
          {
            "manufacturerConnection": {
              "edge": {
                "current": true
              },
              "node": {
                "name": "C"
              }
            }
          },
          {
            "manufacturerConnection": {
              "edge": {
                "current": false
              },
              "node": {
                "name": "AM"
              }
            }
          }
        ]
      },
      {
        "OR": [
          {
            "brandConnection": {
              "edge": {
                "current": true
              },
              "node": {
                "name": "smart"
              }
            }
          }
        ]
      }
    ]
  }
}
```

- Execute the following GraphQL query:
```gql
# Query to receive filtered Series
query getSeriesWithRelationFilters($where: SeriesWhere = { current: true }) {
  series(where: $where) {
    name
    current
    manufacturerConnection {
      edges {
        current
        node {
          name
        }
      }
    }
    brandConnection {
      edges {
        current
        node {
          name
        }
      }
    }
  }
}
```

- At this point check the application logs, the parameters generated from the Query variables are the following:
```json
{
  "this_series": {
    "where": {
      "manufacturerConnection": {
        "edge": {
          "current": false
        },
        "node": {
          "name": "AM"
        }
      },
      "brandConnection": {
        "edge": {
          "current": true
        },
        "node": {
          "name": "smart"
        }
      }
    }
  },
  "this_current": true
}
```

**Expected behavior**
As you can see, only 1 value for the inner OR condition of `manufacturerConnection` is considered, the "C" value is missing.

**Additional context**
This is a customer request and further details can be found in Trello.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @tbwiss. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by neo4j-team-graphql** [comment]
We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @tbwiss! :pray: We will now prioritise the bug and address it appropriately.

**Comment by neo4j-team-graphql** [comment]
This bug report has been assigned high priority to fix. If you wish to contribute a fix, please branch from `master` and submit your PR with the base set to `master`. Thanks!
